### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0

### ISSUE THREAD

**Issue by faceoffers28** [microsoft/ApplicationInsights-aspnetcore#1008]
I created a new Asp.Net Core 2.1 app back in August of this year. I uploaded the app to Azure, added Application Insights using the Portal and everything was working fine. I was working on the client-side of the app and doing extensive testing on October 14th. On October 15th, I started work on the client-side app again and noticed an issue. During my investigation, I found an error in the Azure Event Logs for the ASP.Net Core app. After several hours of research, the fix was to disable Application Insights using the Portal. Once I did this, the app service rebooted and is now working just fine.

Here is the error.

Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

   at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.ApplicationInsightsWebHostBuilderExtensions.<>c.<UseApplicationInsights>b__0_0(IServiceCollection collection)

   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)

   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()

   at APPNAME.Program.Main(String[] args) in C:\Users\MYUSERNAME\Source\Repos\APPNAME\APPNAME\Program.cs:line 17
 

## Repro Steps

See above.

##  Actual Behavior

The app was giving a fatal error.

## Expected Behavior

The app should have worked.

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : Not sure, perhaps the error message gives an indication. This was all setup using the Azure Portal. 
.NET Core Version (TargetFramework in your .csproj file) : 2.1	 						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : I installed Application Insights using the Azure Portal.
OS : Azure App Service
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) : Azure App Service, worked find running locally, which helped me resolve the issue

**Comment by cijothomas** [comment]
Can you follow troubleshooting here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps#troubleshooting? 
And the results of running this page: 
https://yoursitename.scm.azurewebsites.net/ApplicationInsights

This may be an issue with AppService extension, so we need to know the version of it to investigate.

**Comment by faceoffers28** [comment]
@cijothomas I had to install Application Insights again in order to get the Kudu result. I have no idea if this is the new extension or the one I was using.

Pre-Installed Site Extension, version 2.8.23.1379, is running.

I assume this is a new version based on fact that I got a "new version warning" when I uninstalled the extension.

The good news is that Application Insights is now working again and the app is working too.

**Comment by cijothomas** [comment]
Good to know things are working now. I am wondering how did you enable/disable application insights? Because the "new version warning" should be a thing of the past. With the new model, extension is **always** the latest.

**Comment by faceoffers28** [comment]
I just clicked Disable in the Azure Portal.

**Comment by cijothomas** [comment]
Okay. The current UI talks about new update actually.
Anyway closing this as no further action needed.
