### ISSUE TITLE
Consider using taghelper to inject JavaScript into the page

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#107]
See this for example: https://github.com/Glimpse/Glimpse.Prototype/blob/5cdf0fee8b3f66757746459e9751fbaa03523ef8/src/Glimpse.Web.Common/ScriptInjector.cs

**Comment by dnduffy** [comment]
I believe this has now been done in a separate library by @Eilon's team.
The SDK still supports explicit injection via ```@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet``` in _ViewImports.cshtml and ```@Html.Raw(JavaScriptSnippet.FullScript)``` in _Layout.cshtml.
