### ISSUE TITLE
Ability to save the data offline and send it when online

### ISSUE THREAD

**Issue by ujwalr** [Microsoft/ApplicationInsights-aspnetcore#117]
Scenarios like ASPNET apps selfhosted can be used offline and when they are online the data needs to be synced.

We will need a telemetry channel that can keep the data offline and sync when online. Also would be useful to have retry logic for data sync instead of fire and forget

**Comment by abaranch** [comment]
It is related to #74

**Comment by kartang** [comment]
Resolved it in full framework by adding windows server telemetry channel, and created a new task that groups multiple items associated with core framework. https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/167
