### ISSUE TITLE
Allow Option to Include JavaScript from a Seperate File

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/ApplicationInsights-aspnetcore#120]
For those using the Content-Security-Policy (CSP) HTTP header, including inline JavaScript is not allowed. Would it be possible for Microsoft to create and use a CDN which returns the client side JavaScript? The instrumentation key could be included in the query string portion of the URL. So something like this:

```
<script src="https://application-insights.com?key=[INSTRUMENTATION KEY]"></script>
```

**Comment by SergeyKanzhelev** [comment]
You can host it in your own domain as mentioned in [this blog post](https://azure.microsoft.com/en-us/blog/case-study-adding-application-insights-to-a-website/). Hosting it on CDN wouldn't work as desired - see explanation of  it [here](http://apmtips.com/blog/2015/03/18/javascript-snippet-explained/): Specifically this

>... this script is working in application domain so it can subscribe on onerror callback and get a full error stack. Due to security restrictions browser will not give you the full error stack if you subscribe on onerror callback from the script downloaded from the different domain. It also takes cookies from application domain so they can be used for user/session tracking.

**Comment by RehanSaeed** [comment]
So you can have a separate file, as long as it's in the same domain. I suppose you could also use the script hash or nonce to get inline scripts working with CSP securely. Either way is not great but worth it to get app insights working.

**Comment by SergeyKanzhelev** [comment]
In aspnet5 it's very easy to implement. Something like pseudocode:

```
app.Use((reaquest, next) => { request.Response.Write(new httpclient.DownloadStringAsync("from "//az416426.vo.msecnd.net/scripts/a/ai.0.js"");})
```

**Comment by SergeyKanzhelev** [comment]
BTW, thanks for reporting the issue and using Application Insights!

**Comment by RehanSaeed** [comment]
Even better you can read the instrumentation key from config.json in your gulpfile.js file, then use gulp-replace to inject the key into the app insights JavaScript file.

I intend to add an app insights feature implemented as above to [ASP.Net MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) this weekend.

**Comment by SergeyKanzhelev** [comment]
Cool. Send me a link

BTW, in my example pseudo code I should have been using class ```JavaScriptSnippet``` instead of downloading script from CDN =)

**Comment by RehanSaeed** [comment]
Will do. The basic idea is:

```
var replace = require("gulp-replace"),    // String replace (https://www.npmjs.com/package/gulp-replace/)
var config = require("./config.json");    // Read the config.json file into the config variable.

gulp.task('insert-application-insights-key', function(){
  gulp.src(['scripts/application-insights.js'])
    .pipe(replace('[ApplicationInsightsInstrumentationKey]', config.ApplicationInsights.InstrumentationKey))
    .pipe(gulp.dest('wwwroot/js/application-insights.js'));
});
```

The application-insights.js file under the scripts folder should look like this:

```
var appInsights=window.appInsights||function(config){
    function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
}({
    instrumentationKey:"[ApplicationInsightsInstrumentationKey]"
});

window.appInsights=appInsights;
appInsights.trackPageView();
```

**Comment by SergeyKanzhelev** [comment]
Consider using [this package](https://www.nuget.org/packages/Microsoft.ApplicationInsights.JavaScript) to get snippet from if possible.
```
nuget install Microsoft.ApplicationInsights.JavaScript -Pre -OutputDirectory "c:\temp\nugets"
cd c:\temp\nugets
cd .\Microsoft.ApplicationInsights.JavaScript.0.15.0-build58334\tools\
cat .\prefix.html
```

**Comment by RehanSaeed** [comment]
That package has a prefix.html file with the script snippet in it. Is that what you mean? If so, being a .html file, it's not very easy to consume from Gulp. I would have to strip out the `<script>` tags.

It would be nice to have a NuGet package that I can take the .js from, rather than having to keep it up to date myself. Could this package be updated to include this?

**Comment by SergeyKanzhelev** [comment]
Feel free to send PR for our NuGet. NuGet definition is here: https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/NuGet.JavaScript/Package.nuspec

**Comment by RehanSaeed** [comment]
The snippet.html file does not seem to be checked-in, although it is referred to in the [NuGet.JavaScript.csproj](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/NuGet.JavaScript/NuGet.JavaScript.csproj) project as `..\JavaScriptSDK\min\snippet_vsix.html`. The same can be said for the ai.js and ai.min.js files. Am I missing something?

**Comment by RehanSaeed** [comment]
I don't mind raising a PR. Comments added to your new issue.

**Comment by RehanSaeed** [comment]
@SergeyKanzhelev I've updated the [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) project template. You can now create a new project and enable Application Insights by selecting the feature below:

![applicationinsights](https://cloud.githubusercontent.com/assets/2270364/11168294/800d9278-8b81-11e5-9091-6bdfbdf654e4.png)

It uses the gulp-replace method I explained above, so you can now try it out.

**Comment by RehanSaeed** [comment]
FYI, I spotted an applicationinsights-js bower package with the snippet.js file in it. You can now use that file in ASP.NET Core.

**Comment by RehanSaeed** [comment]
@SergeyKanzhelev In your early message you mentioned that hosting the app insights snippet on a CDN would not work but if I add the `crossorigin` attribute to enable reporting of errors from third party scripts (See https://raygun.com/blog/2015/05/fixing-script-errors/), then would this not work?

**Comment by SergeyKanzhelev** [comment]
@RehanSaeed I think this would work. However we still want Application Insights API to work before scripts loaded. Like "appInsights.trackTrace()". So you can report that something happened during the loading time. So we still want a snippet to be part of a page and it's easier to include `onerror` handler there. However I believe you the solution you proposing is a nice one for the certain customers who needs speed and knows what they are doing in terms of telemetry reporting. If you will manage it to work - I think it can make a nice blog post or documentation page.

**Comment by RehanSaeed** [comment]
Talking of a blog post, I wrote '[Making Application Insights Fast and Secure](http://rehansaeed.com/making-application-insights-fast-and-secure/)'.
