### ISSUE TITLE
Change package name, rename repo and update readme to use new name

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#125]
We need to rename repository and all documentation to use the new name

https://github.com/aspnet/Announcements/issues/144

Also we need to consider changing package name for consistency.

@Eilon - would the right name for Application Insights package be `Microsoft.ApplicationInsights.AspNetCore` instead of `Microsoft.ApplicationInsights.AspNet`?

**Comment by Eilon** [comment]
@SergeyKanzhelev yep that would be the recommended name.

**Comment by kartang** [comment]
Fixed it as a part of updates to RC2 and CLI in https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/142

**Comment by kartang** [comment]
Will close it as soon as the PR is good!

**Comment by kartang** [comment]
Closing it for now. Will open a new task when we plan to update the package, soon!
