### ISSUE TITLE
Application Insights Logging Adapters are broken in ASPNET5

### ISSUE THREAD

**Issue by ericc1103** [Microsoft/ApplicationInsights-aspnetcore#127]
All Application Insights Logging Adapters are broken in ASPNET5. Here are how to repro:
1. Install the latest ASP.NET 5 RC.
2. Create new ASP.NET 5 project.
3. Install log4net(or nlog).
4. Install Application Insights log4net (or nlog) adapter.
5. Build the solution. You will get the following error(s)
**The dependency log4net 2.0.3 in project WebApplication182 does not support framework DNXCore,Version=v5.0.**

Feel free to contact me @ echong@microsoft.com for any question.
Thanks,
Eric Chong

**Comment by SergeyKanzhelev** [comment]
There may be two issues - missing target's for DNXCore and the fact that ASP.NET Core is using Dependency injection when logging adaptors were designed for the use of singleton object. I also not sure whether log4net supports ASP.NET 5 at all.

I marked it as enhancements. We will need to have a separate issue at https://github.com/Microsoft/ApplicationInsights-dotnet-logging if we will decide that existing logging adaptor's design needs to be changed for ASP.NET Core support.

**Comment by gzepeda** [comment]
Thank you for the additional information. We will take a look and let you know our findings.

**Comment by gzepeda** [comment]
Hello Sergey, we are currently working on this issue. Can you assign it to me please?

**Comment by fidmor89** [comment]
- I successfully replicated the issue with adapters for NLog, Log4Net and SLAB.  
- NLog and Log4Net are not generating exceptions when adding the nugget package but the using directive is. I'm working to find a workaround before making any changes to the logging design.

**Comment by gzepeda** [comment]
Hello @SergeyKanzhelev, please assign this to @fidmor89

**Comment by SergeyKanzhelev** [comment]
Thanks for looking into this issue. I can only assign it to the people from the organization so I'm taking it on myself and remember you are looking at it.

**Comment by gzepeda** [comment]
Sounds good.

Sent from Outlook Mobile




On Tue, Feb 9, 2016 at 2:28 PM -0800, "Sergey Kanzhelev" <notifications@github.com> wrote:





Thanks for looking into this issue. I can only assign it to the people from the organization so I'm taking it on myself and remember you are looking at it.

---

**Comment by MedAnd** [comment]
+1

**Comment by kartang** [comment]
@gzepeda @fidmor89 : Please let us know if there is an update with this issue. Thanks!

**Comment by fidmor89** [comment]
@gzepeda @SergeyKanzhelev @kartang I was thinking we could modify semantic logging (previously known as SLAB) so it supports dependency injection, not sure if it can be done but might be worth to try as this could be a work arround for using logging adapters in ASP.NET5.

**Comment by gzepeda** [comment]
I see that in the latest versions of the project, EventSource was added to log useful errors or unwanted situations. Is this the replacement for the logging adapters that are referenced in this issue as broken?

**Comment by dnduffy** [comment]
The EventSource is for internal errors that the SDK reports against itself which is quite different from logging adapters for end users.

**Comment by georgiosd** [comment]
Guys, how does one redirect logging output from the aspnetcore ILogger to AppInsights?

**Comment by SergeyKanzhelev** [comment]
@georgiosd if you need ILogger adaptor - it is as easy as this sample:

``` csharp
  .UseLoggerFactory(new AppInsightsLoggingFactory())
```

``` csharp
public class AppInsightsLoggingFactory : ILoggerFactory
{
  public void AddProvider(ILoggerProvider provider)
  {
  }

  public ILogger CreateLogger(string categoryName)
  {
    return new AppInsightsLogger();
  }

  public void Dispose()
  {
  }
}

public class AppInsightsLogger : ILogger
{
  private TelemetryClient client = new TelemetryClient();

  public IDisposable BeginScope<TState>(TState state)
  {
    return new AppInsightsScope();
  }

  public bool IsEnabled(LogLevel logLevel)
  {
    return true;
  }

  public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
  {
    //if (logLevel != LogLevel.Debug)
    {
      client.TrackTrace(formatter(state, exception));
    }
  }
}

public class AppInsightsScope : IDisposable
{
  public void Dispose()
  {
  }
}
```

**Comment by cijothomas** [comment]
ILogger support is available for SDK and is documented.
Closing this issue now.
