### ISSUE TITLE
Configuring two middlewares generated two identical requests

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#137]
Requests tracking middleware should use a singleton to prevent sending of the two similar request data documents

**Comment by kartang** [comment]
Alternatively, we can also investigate if we can control the requests by checking if it already exists in the context (which also explains that the request middleware is already in place). 

@abaranch, @dnduffy: Please let me know if there could be any edge cases with respect to checking the request telemetry in context and controlling the middlewares.

**Comment by dnduffy** [comment]
Request tracking is now done differently since the rewrite for 2.0.0 to use diagnostic source listener instead of middleware so this issue is resolved.
