### ISSUE TITLE
Application Insight Instrumentation Key is empty in AspNet 5 via DI

### ISSUE THREAD

**Issue by jittuu** [Microsoft/ApplicationInsights-aspnetcore#141]
hi all,
i notice that the instrumentationKey is empty in my asp.net 5 project (1.0.0-rc1-update1)

## Steps to reproduce

create file with name config.json and populate the file with appInisight informations:
  ```
{
  "ApplicationInsights": {
     "InstrumentationKey": ""
   }
}
  ```

read and build configuration:
```
public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
{
  Configuration = new ConfigurationBuilder()
    .SetBasePath(appEnv.ApplicationBasePath)
    .AddJsonFile("config.json")
    .Build();
}
  ```

insert the following line in method ConfigureServices in startup.cs:
  ```
services.AddApplicationInsightsTelemetry(Configuration);
  ```

insert the following lines in method Configure:
  ```
app.UseApplicationInsightsRequestTelemetry();
app.UseApplicationInsightsExceptionTelemetry();
  ```

Now when I try to retrieve the `TelemetryClient` from myController(via Dependency Injection), I notice that the `InstrumentationKey` is Empty.

regards,
luca

**note**: I also faced the same issue and as per [the issue](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/171), I moved it to here.

**Comment by AlexBulankou** [comment]
Thanks for reporting @jittuu! We'll have an update soon on this.

**Comment by dnduffy** [comment]
TelemetryClient.InstrumentationKey should be empty unless you explicitly set it there as an override of what is in configuration.
If you inspect a DI provided client instance in the debugger the value in the .Context will also be empty but the value in the .configuration should be set (unlike if you try to manually create a new instance using the constructor).
In DI provided instances the key has always been set in the .configuration variable in my tests with new ASP.NET 5 web projects (DNX 4.5.1).
I've tested this with Microsoft.ApplicationInsights.AspNet version 1.0.0-rc1 and version 1.0.0-rc1-update2 with dependency on Microsoft.ApplicationInsights version 1.1.1-beta and version 2.0.0-beta4 respectively (i.e. with and without NuGet updates).

**Comment by dnduffy** [comment]
Closing because DI is working as expected and a backwards compatibility has been committed which allows manually created TelemetryClient instances to also work in ASP.NET 5.
