### ISSUE TITLE
Expose user configurable settings in a friendly extensible way.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#159]
Currently the call to wire up Application Insights is a nice one liner when you want the defaults:
    services.AddApplicationInsightsTelemetry(Configuration);

But if you want to use a custom setup and change which initializers, modules, channels, or processors get used it is somewhat hidden behind layers of helper methods and requires undoing the defaults after the fact.

I propose that it might be preferable to expose an additional mechanism for selectively wiring up the initial configuration of desired initializers etc. such that users who want a custom configuration do not have to first use the defaults and then undo the parts they don't want.  We could then leverage the same system as the backing for the simple default configuration one liner call and preserve that simplicity for average users.

**Comment by ctolkien** [comment]
I'd also flag that most (all?) other services use an `Action<TOptions>` to configure registering options.

**Comment by joechiu-msft** [comment]
We are using service fabric and stateless web api, so we have to rip out AzureWebAppRoleEnvironmentTelemetryInitializer, WebUserTelemetryInitializer, SyntheticTelemetryInitializer and WebSessionTelemetryInitializer via their type name (because they are internal types), not ideal, would be nice to be able to configure it.

**Comment by cijothomas** [comment]
We have to see if it makes sense to mark certain classes as public, to enable easy 'removal' as needed.

**Comment by cijothomas** [comment]
@joechiu-msft We have made telemetryinitializers public (https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/611)
It should be easy to remove them now.
