### ISSUE TITLE
AuthenticatedUserIdTelemetryInitializer missing?

### ISSUE THREAD

**Issue by mejje** [Microsoft/ApplicationInsights-aspnetcore#169]
Will there be an AuthenticatedUserIdTelemetryInitializer as in ApplicationInsights-dotnet-server?

**Comment by kartang** [comment]
We do not have AuthenticatedUserIdTelemetryInitializer in the current version of Aspnet5 sdk. We have it in our backlog, and will be added in the next iteration. Thank you for reporting.

**Comment by mejje** [comment]
No news on this?

**Comment by dnduffy** [comment]
We're working on higher priority stabilization fixes in the regular .NET SDK's and haven't been able to spend time on new features for the .NET Core SDK.
We would however be happy to accept a pull request if you have time to contribute one.
