### ISSUE TITLE
AppInsights tracktrace logging with ILogger interface

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-aspnetcore#180]
Hello,
I'd like to send all my app logs through AI's tracktrace method. I know I can access it by getting a TelemetryClient using DI in a controller, but I'd like to manage logging through ASP NET Core's ILogger interface. This would allow me to switch from VS's debug output to AI depending on configuration and without changing the controller.
Is there a provider for the ASP NET Core's Logger system and AI? Is there any other suggested way of using AI as a logger but retaining the flexibility to switch to another logger without rewriting the code? Thanks!

**Comment by dnduffy** [comment]
We talked about this but don't currently have it on our roadmap.
You have a couple options:
1) Write an ILogger to AI bridge, this is what I recommend.  See here for an example of an ILogger bridge to EventSource: https://github.com/aspnet/Logging/issues/328
2) Write your own Module for AI that does whatever you want

If you do write an ILogger to AI bridge I would love to see the pull request. :)

**Comment by bragma** [comment]
Thanks! I'll give it a look and if I find some time I'll submit a PR.

**Comment by francischeung** [comment]
The Microsoft.ApplicationInsights.AspNetCore assembly has ApplicationInsightsLoggerFactoryExtensions that seem to provide this functionality. I pass in app.ApplicationServices as the IServiceProvider. Works great for me. Are there any issues with doing this?

**Comment by cijothomas** [comment]
@francischeung No issues, thats the recommended way.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging
