### ISSUE TITLE
Major enhancements

### ISSUE THREAD

**Issue by kartang** [Microsoft/ApplicationInsights-aspnetcore#188]
- [ ] Updating telemetry initializers: 
-  Change operation id telemetry initializer to operation correlation telemetry initializer: Use parentcontext, rootOperationId and parentId
- Update SessionId telemetry initializer: Include IsFirst details
- Add AuthUser telemetry initializer
- Add AccountId telemetry initializer
- We have UserAgent telemetry initializer, DomainName Role instance initializer and componentversion telemetry initializer in addition

- [ ] Create a new ```netstandard``` project besides ```PCL```, that would be used for aspnetcore applications:

- Current implementation requires an additional import statement with either "dnxcore50" or "dotnet5.4" or "dotnet5.6". 

- [x] Update the build definition for signing:

- I have created a sample build definition(**AspNetCore_Signed**), however, we need an agent pool (that has a support for CLI as well as signing) to sign the dlls.

- [ ] Enable StyleCop and clean up the code base 

- Cleaning up the code (especially tests) to remove unwanted commands, code, comments etc, and enable stylecop.

**Comment by Zoltu** [comment]
It would be nice if these were broken up into separate issues so I could vote on them independently.  As a user, I would really like to see the `netstandard` one, while the others I don't care much about.

**Comment by dnduffy** [comment]
- https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/238
- https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/239
- https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/240
