### ISSUE TITLE
Namespace of ApplicationInsightsJavaScriptExtensions.cs

### ISSUE THREAD

**Issue by LeandroPT** [Microsoft/ApplicationInsights-aspnetcore#190]
The namespace of ApplicationInsightsJavaScriptExtensions.cs is still Microsoft.AspNet.Mvc.Rendering

Shouldn't it be Microsoft.**AspNetCore**.Mvc.Rendering?

**Comment by kartang** [comment]
Hello,

We didn't merge the aspnetcore changes to master yet. Please pull the develop branch to get the CLI updates. 

Thanks
