### ISSUE TITLE
Change success status to failed in case there's exception caught in RequestTrackingMiddleware.cs and response code is 200

### ISSUE THREAD

**Issue by kartang** [Microsoft/ApplicationInsights-aspnetcore#192]

**Comment by kartang** [comment]
Set the default status code in Exception Middleware, so that we make sure that status code is never <401 in case of exception, as we do in web.

**Comment by Dmitry-Matveev** [comment]
If response to the client is 200 and the client is not affected, SDK would need to set request status to success and code to 200 just like ASP.NET core does. We should have exception telemetry item collected so that exception would not go unnoticed.

**Comment by gzepeda** [comment]
Hi, 

We were looking for the file RequestTrackingMiddleware.cs to do the change but we are not able to find it. 

Is the context of the bug still valid or the file just got renamed? thanks!

**Comment by dnduffy** [comment]
The AI SDK for .NET Core was rewritten a couple months ago to use listeners instead of middleware.
See HostingDiagnosticListener.cs.

**Comment by gzepeda** [comment]
Thanks. We will check it out.

**Comment by dnduffy** [comment]
I apologize, after looking at the pull request I believe this issue no longer existed after the rewrite and we just failed to close it.  The PR would actually create a bug where all status codes != 200 would suddenly report success which is not correct.
