### ISSUE TITLE
[Tooling] Tooling will not display the link to reenter credentials

### ISSUE THREAD

**Issue by javiercn** [Microsoft/ApplicationInsights-aspnetcore#196]
* File -> New Project
* Given the credentials are expired
![image](https://cloud.githubusercontent.com/assets/6995051/15198602/3a0c6a86-178d-11e6-96d0-ac6247739998.png)
(I cleared the email with Paint)
* The link to reenter credential doesn't appear.
* If I switch accounts and go back to the original account
![image](https://cloud.githubusercontent.com/assets/6995051/15198652/8d652fd8-178d-11e6-8b4d-b5c0d96bad39.png)

**Comment by kartang** [comment]
Redirecting to dev tools team.
