### ISSUE TITLE
[Tooling] Tooling could default to a new resource group with the project name.

### ISSUE THREAD

**Issue by javiercn** [Microsoft/ApplicationInsights-aspnetcore#197]
Currently it defaults to the following
![image](https://cloud.githubusercontent.com/assets/6995051/15198712/0181d2cc-178e-11e6-8c4b-3eee6e21bc64.png)
As can be seen in
![image](https://cloud.githubusercontent.com/assets/6995051/15198733/29b913ae-178e-11e6-9234-cd52de8843d3.png)
The default resource group doesn't exist, so if a new resource group is create it would be better to just default to the project name.

**Comment by kartang** [comment]
Redirecting to devtools team.
