### ISSUE TITLE
[Tooling] Tooling doesn't remember choices between the Application Insights dialog and the Azure Website dialog

### ISSUE THREAD

**Issue by javiercn** [Microsoft/ApplicationInsights-aspnetcore#198]
It will be nice that choices flow from the Application Insights dialog into the new website dialog. For example resource group and subscription.

After selecting a resource group and a subscription in application insights, when I'm in the Create App Service dialog, the subscription and resource group I chose are not being respected.

While this might work, it's error prone as I might end up, for example, misspelling the resource group and creating resources into two different resource groups, which is then annoying to clean up.

**Comment by kartang** [comment]
Redirecting to devtools team.
