### ISSUE TITLE
Make options visible only in full framework, as they are not primarily used in core

### ISSUE THREAD

**Issue by kartang** [Microsoft/ApplicationInsights-aspnetcore#201]

**Comment by kartang** [comment]
It might be confusing to see options like "EnableAdaptiveSampling" visible in core framework, without any use.

**Comment by dnduffy** [comment]
Eventually they should be supported though so I'm not sure if we should try to hide that now or not.

**Comment by kartang** [comment]
Enabling server telemetry channel and telemetry processors in core framework is a huge task by itself, and might take a while (I think). We don't want to expose these two options in core framework until that point. I believe it shouldn't take too long to get this worked, and with the trade off of the current time to implement vs the time we keep these exposed, i think its fair to remove them for now.

**Comment by cijothomas** [comment]
Server Channel is now enabled for both full framework and core. Closing this as irrelevant now.
