### ISSUE TITLE
Redirection to custom error page not happening on server box

### ISSUE THREAD

**Issue by MahehsChewale** [Microsoft/ApplicationInsights-aspnetcore#212]
<httpErrors errorMode="Custom" existingResponse="Replace">
      <clear />
      <remove statusCode="404" subStatusCode="-1" />
      <remove statusCode="403" subStatusCode="-1" />
      <error statusCode="403" responseMode="ExecuteURL" path="/Error/Apology" />
      <error statusCode="404" responseMode="ExecuteURL" path="/Error/Apology" />
    </httpErrors>

Added above line of code in web.config to redirect to Error controller apology action when 404 or 403 error occurred which is working locally but not on server box. 

Please help me with solution ASAP.

Thanks in advance

**Comment by kartang** [comment]
Hello, 

We are having trouble to find the line of code above. Can you please provide more details on where you are actually using this, and by not working, are you referring to Application Insights not capturing the handled exception?

Thanks

**Comment by MahehsChewale** [comment]
<httpErrors errorMode="Custom" existingResponse="Replace">
      <clear />
      <remove statusCode="404" subStatusCode="-1" />
      <remove statusCode="403" subStatusCode="-1" />
      <error statusCode="403" responseMode="ExecuteURL" path="/Error/Apology" />
      <error statusCode="404" responseMode="ExecuteURL" path="/Error/Apology" />
    </httpErrors>

**Comment by MahehsChewale** [comment]
```
<httpErrors errorMode="Custom" existingResponse="Replace">
      <clear />
      <remove statusCode="404" subStatusCode="-1" />
      <remove statusCode="403" subStatusCode="-1" />
      <error statusCode="403" responseMode="ExecuteURL" path="/Error/Apology" />
      <error statusCode="404" responseMode="ExecuteURL" path="/Error/Apology" />
    </httpErrors>
```

**Comment by abaranch** [comment]
@MahehsChewale, could you please explain how it is related to ApplicationInsights?

**Comment by kartang** [comment]
Closing this for now as there is clear description of the issue. 
@MahehsChewale Please open a thread in this repository if you continue to experience any issues with using Application Insights with AspNet Core. Thank you!
