### ISSUE TITLE
Add support for Live Stream in Core Framework

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/ApplicationInsights-aspnetcore#216]
I have a ASPNET Core application deployed and being monitored by Application Insights but when I try to view the Live Stream feature it says:

> Not available: your app is offline or using an older SDK
> Live Stream shows you key metrics within seconds. Monitor your app through deployments or critical periods. It's available if you install version 2.1.0-beta2 (or later) of the Application Insights SDK for ASP.NET in your app.

I would like to be able to use this feature with my ASPNET Core application running on CoreCLR (linux host).

**Comment by kartang** [comment]
@Zoltu Helllo. Thank you for reporting the issue. Currently, live stream uses telemetry processors, which are enabled only in full framework. Therefore, core framework as of today, does not enable live stream collection. Please visit https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream for more details on telemetry processors and live stream for aspnet core applications.

**Comment by Zoltu** [comment]
The instructions are a bit confusing for me, they say
> Metrics Stream feature is not enabled by default in ASP.NET Core applications. In order to enable the feature, `QuickPulseTelemetryProcessor`, as well as `QuickPulseTelemetryModule` should be registered with the telemetry configuration.

which makes it sound like I can simply register those two things and everything will work.  Unfortunately, there aren't any instructions on how to do this and as far as I can tell that processor and module are not available in the ASP.NET Core version of Application Insights.

Are these available but just not-enabled-by-default in ASP.NET Core or are the actually unavailable?  If it is the latter, I would recommend updating the Wiki to reflect that since right now it suggests that they are available for ASP.NET Core but disabled.

**Comment by kartang** [comment]
@Zoltu Sorry about the confusion. To clarify it again, metrics stream is not supported in .NET Core. For .NET Framework, metrics stream is enabled by default. I have updated the documentation to make it explicit. Thank you!

**Comment by SergeyKanzhelev** [comment]
Just a small note here - in order to implement live metrics in .NET Core the biggest thing that needs to be implemented it the new target framework implementation in this project: https://github.com/Microsoft/ApplicationInsights-dotnet-server/tree/master/Src/PerformanceCollector

**Comment by georgiosd** [comment]
How about adding them to a dotnetcore project that uses the full framework? 😕

**Comment by SergeyKanzhelev** [comment]
@georgiosd as @kartang mentioned it is already supported when running in full framework. Here is the initialization code: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L211-L222 Let us know if it is not working for you

**Comment by chrisaut** [comment]
Are there plans to enable this when running under .net core in the foreseeable future?

**Comment by dnduffy** [comment]
@chrisaut I presume you mean .NET core only and not .NET Core with full framework which is currently supported.  We plan to enable this functionality for pure .NET Core use as soon as we make some changes to build the Web SDK to be compatible with .NET Core without the full .NET framework.  Note however that there may not be 100% parity of the available data because performance counters are not a cross platform feature in .NET Core but we will be able to provide request and exception metrics as well as the data which Azure exposes if your app is hosted there.

**Comment by kieronlanning** [comment]
@dnduffy Is there any news on this? Cheers.

**Comment by lcyhjx** [comment]
Is there any plan when to support .Net Core, I mean the target framework is .Net Core.

**Comment by SergeyKanzhelev** [comment]
@lcyhjx - @netgh0st is working on PR: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/651

**Comment by lcyhjx** [comment]
@SergeyKanzhelev good to know. Thanks!

**Comment by lcyhjx** [comment]
@SergeyKanzhelev Do you know, is there any plan to release this feature?

**Comment by SergeyKanzhelev** [comment]
we do not have specific date for the next version of SDK. But we definitely working on releasing it

**Comment by lcyhjx** [comment]
@SergeyKanzhelev Thanks so much! We are looking forward the release.

**Comment by snickler** [comment]
This is good to know. I'm sitting here thinking that I'm doing everything wrong, but didn't realize that it wasn't supported in ASP.NET Core yet. Thanks for the update on this

**Comment by ctolkien** [comment]
#518 seems to have entirely stagnated.... is this issue still alive?

**Comment by SergeyKanzhelev** [comment]
2.5.-beta1 should support live metrics. Closing the issue

**Comment by isaac2004** [comment]
@SergeyKanzhelev I may be doing something wrong, but I have a 2.0.3 Web App that has 2.5.-beta1 added as well. I still get the "Not Available" Screen on Live Metrics. Do you need to add anything in Program or Startup to force the app what SDK to use?

**Comment by cijothomas** [comment]
@isaac2004 Have you upgraded your asp.net core application to use the 2.2.0-beta1? This is required for live metrics, as this is the version which depends on 2.5.0-beta1 of web sdk.

To upgrade your asp.net core app to 2.2.0-beta1, add the following to .csproj.
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.0-beta1" />


https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.2.0-beta1

**Comment by isaac2004** [comment]
@cijothomas wasn't aware the 2.2.0-beta1 dep.... That resolved it!

**Comment by LarsKemmann** [comment]
@SergeyKanzhelev Will it be possible with the new release to get Live Metrics Stream data from a non-Web .NET app, e.g. a Windows Service-hosted microservice? Happy to open a separate issue but figured I would ask here first. Thanks!

**Comment by SergeyKanzhelev** [comment]
@LarsKemmann yes, this post explains how: http://apmtips.com/blog/2017/02/13/enable-application-insights-live-metrics-from-code/

**Comment by kbdavis07** [comment]
I have Microsoft.ApplicationInsights.AspNetCore 2.5.1 Installed and still not working on Azure.

 `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.5.1" />`

![image](https://user-images.githubusercontent.com/5434970/48118409-2c0f9780-e23a-11e8-96b2-7ca2564cf513.png)

**Comment by cijothomas** [comment]
@kbdavis07 Please open a new issue describing the issue. LiveMetrics support for asp.net core is enabled in 2.2 onwards, so 2.5.1 should work for you. Please open a new issue with full description.
