### ISSUE TITLE
appInsights.setAuthenticatedUserContext is not a function - how to get authenticated user context on automatic telemetry?

### ISSUE THREAD

**Issue by bojingo** [Microsoft/ApplicationInsights-aspnetcore#218]
I am getting error "appInsights.setAuthenticatedUserContext is not a function" when using `"Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final"` in project.json.  Is there a new way of doing this?  Note that appInsights is definitely initialized.  It is the reference that is written out when doing `@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)`, which seems to work fine.  

I am getting telemetry on AJAX calls, but can't seem to find a way to get them to recognized the authenticated user.

**Comment by bojingo** [comment]
I should add, I'm using this JavaScript to try to get the telemetry to contain the authenticated user.  I pulled this JavaScript from various guides on using App Insights:

```
        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
        @if (User.Identity.IsAuthenticated)
        {
        <script>
            var appInsightsUserName = '@User.Identity.Name.Replace("\\", "\\\\")';
            appInsights.setAuthenticatedUserContext(appInsightsUserName.replace(/[,;=| ]+/g, "_"));
        </script>
        }
```

**Comment by dnduffy** [comment]
Some obvious first questions:
Is the script snippet being output on your page?
Do you have a value for User.Identity.Name that you can see in your variable appInsightsUserName if you debug in the browser?
Assuming you do have the variable set as expected, just to be thorough, is the output of the regular expression replace call still what you expect?

**Comment by bojingo** [comment]
> Is the script snippet being output on your page?

Yes, below is the full script that is output in the rendered page's head tag (with instrumentation key removed):

```
        <script type="text/javascript">
  var appInsights = window.appInsights || function(config){
  function s(config){
    t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})}
  }
  var t = { config:config }, r = document, f = window, e = "script", o = r.createElement(e), i, u; for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config, r, f, e, o) { var s = u && u(config, r, f, e, o); return s !== !0 && t["_" + i](config, r, f, e, o),s}),t 
  }({
  instrumentationKey: '--------------------------------------------------------'
}); 
  window.appInsights = appInsights;
  appInsights.trackPageView();
</script> 
        <script>
            var appInsightsUserName = 'test@user.com';
            appInsights.setAuthenticatedUserContext(appInsightsUserName.replace(/[,;=| ]+/g, "_"));
        </script>
```

> Do you have a value for User.Identity.Name that you can see in your variable appInsightsUserName if you debug in the browser?

Yes, it contains a correct user name value, as you can see above.

> Assuming you do have the variable set as expected, just to be thorough, is the output of the regular expression replace call still what you expect?

The Javascript regex never has a chance to execute because of the error "appInsights.setAuthenticatedUserContext is not a function".

**Comment by bojingo** [comment]
![image](https://cloud.githubusercontent.com/assets/671018/16116764/b5f6ccc4-339c-11e6-81fa-a7b4ff732c9c.png)

That shows what is on the appInsights reference, which proves that it was initialized.  The "setAuthenticatedUserContext" which is documented all over the place (such as here: https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#authenticated-users) is simply missing.

**Comment by dnduffy** [comment]
We've investigated and discovered that the JavaScript snippet output by the line "@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)" is out of date.
I will update that code and publish the fix in the next release.
Until then you can get an updated JavaScript snippet to use by going to the portal and copying it from there (see here: [https://azure.microsoft.com/en-us/documentation/articles/app-insights-javascript/](https://azure.microsoft.com/en-us/documentation/articles/app-insights-javascript/)).

**Comment by bojingo** [comment]
@dnduffy, that workaround resolved my issue - thanks!  For the benefit of others who come across this issue, here is the complete code at the end of my head tag:

```
        @*@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)*@
        <script type="text/javascript">
            // TODO: This entire script tag replaces the above line due to a bug (https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/218)
            //       With the next release of the Application Insights package, try to remove this script tag and uncomment the above line.
            var appInsights = window.appInsights || function (config) {
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
            }({
                instrumentationKey:"@TelemetryConfiguration.InstrumentationKey"
            });
            window.appInsights=appInsights;
            appInsights.trackPageView();
        </script>
        @if (User.Identity.IsAuthenticated)
        {
        <script>
            var appInsightsUserName = '@User.Identity.Name.Replace("\\", "\\\\")';
            appInsights.setAuthenticatedUserContext(appInsightsUserName.replace(/[,;=| ]+/g, "_"));
        </script>
        }
```

Note the TODO for when the true fix for this issue gets released.  I'll be watching this issue.

**Comment by dnduffy** [comment]
We should have a release with the fix in it soon, just coordinating with the release of ASP.NET Core 1.0.0.

**Comment by bojingo** [comment]
Issue seems to be fixed as of release - thanks!

**Comment by guybartal** [comment]
after installing Microsoft.ApplicationInsights.AspNetCore 1.0.1 or 1.02 on asp.net core application i get this error on restoring nuget packages:

Package Microsoft.ApplicationInsights 2.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0)

![image](https://cloud.githubusercontent.com/assets/3179107/19743089/72de8a0c-9bd0-11e6-9723-b8f731292d24.png)
