### ISSUE TITLE
Update telemetry initializers

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#239]
- [ ] Updating telemetry initializers: 
-  Change operation id telemetry initializer to operation correlation telemetry initializer: Use parentcontext, rootOperationId and parentId
- Update SessionId telemetry initializer: Include IsFirst details
- Add AuthUser telemetry initializer
- Add AccountId telemetry initializer
- We have UserAgent telemetry initializer, DomainName Role instance initializer and componentversion telemetry initializer in addition

**Comment by cijothomas** [comment]
closing old issues.
