### ISSUE TITLE
UseApplicationInsightsExceptionTelemetry Not working

### ISSUE THREAD

**Issue by RisingStar1** [Microsoft/ApplicationInsights-aspnetcore#248]
Hi all,
I added this extension method, but its not catch any exception and therefore not writing any log.

why is that?
Thanks!

**Comment by SergeyKanzhelev** [comment]
See [here](https://blogs.msdn.microsoft.com/webdev/2015/05/19/application-insights-for-asp-net-5-youre-in-control/):

> Step 3. Enable the telemetry you choose. You can both write your own telemetry into your app, and use the standard middleware components to report basic metrics like number of requests per second or detailed information about a failed request. Middleware is configured in the Configure method of Startup.cs, and it forms a pipeline:
```
app.UseApplicationInsightsRequestTelemetry();
//Error handling middleware goes here…
app.UseApplicationInsightsExceptionTelemetry();
```

> Request tracking should always be the first item in the pipeline to give you the most accurate timing of the request. Typically exception reporting goes after any error handling middleware and before other middleware. Typical error handling middleware will handle exceptions and thus earlier middleware in the pipeline will never see it. Thus the Application Insights exception reporting middleware should go after the error handling middleware components unless you don’t want to report some exceptions to Application Insights. Again, you are in control of your telemetry and of course you can write your own middleware if you prefer.
