### ISSUE TITLE
Application Insights for ASP.NET Core doesn't support netcoreapp1.0

### ISSUE THREAD

**Issue by mclark1129** [Microsoft/ApplicationInsights-aspnetcore#249]
I am trying to add Application Insights to the basic ASP.NET Core web project. This project is configured to use netcoreapp1.0. When I try to add the AI package to my project I'm given a message that the restore fails:

Errors in C:\src\amwins\amlink-knowledge-navigator\AmWins.AmLink.KnowledgeNavigator.WebClient\AmWins.AmLink.KnowledgeNavigator.WebClient.xproj
Package Microsoft.ApplicationInsights.AspNetCore 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.ApplicationInsights.AspNetCore 1.0.0 supports:
- net451 (.NETFramework,Version=v4.5.1)
- netstandard1.6 (.NETStandard,Version=v1.6)
If I try to change the target framework of this project to netstandard1.6 then I am unable to load many of the other packages that come with the default web application. These packages only support netcoreapp1.0. Admittedly I'm still a little confused by the different frameworks/platforms in .NET Core, but I would expect a package designed for AspNetCore to work out of the box with the basic ASP.NET Core Web Application.

Is there something that I need to do differently in order to use AI with this project?

**Comment by mclark1129** [comment]
My frameworks section includes the imports specified in the README

```
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
```

**Comment by mclark1129** [comment]
I double-checked and upgraded my tooling for Visual Studio to the latest version, this resolved my issue.

**Comment by dnduffy** [comment]
I'm glad you got it figured out. :)

**Comment by dnduffy** [comment]
P.S. I've seen this error happen on a Linux setup that had an early release candidate of .NET Core installed which didn't uninstall cleanly.  A clean install of the latest bits works though.
