### ISSUE TITLE
Scoping bug with TelemetryClient (Middleware vs AddScoped)

### ISSUE THREAD

**Issue by cwe1ss** [Microsoft/ApplicationInsights-aspnetcore#251]
Hi,

I tried to add a context property to all telemetry calls following the [Configure wiki page](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure#add-application-level-context-properties) and noticed that only `requests` contained the property, but not `dependencies`!

After digging into this, I've seen that you have a scoping bug with `TelemetryClient`:

* In [ApplicationInsightsExtensions](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L82) you use `services.AddScoped<TelemetryClient>();`. This means that every request gets a new instance and that it should be resolved from `RequestServices` (which happens automatically when you inject it into e.g. a `Controller`).
* In [RequestTrackingMiddleware](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingMiddleware.cs#L23) and [ExceptionTrackingMiddleware](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/ExceptionTrackingMiddleware.cs#L18) you inject `TelemetryClient` into the constructor. Since middleware classes are reused for every request, `TelemetryClient` will be resolved **only once** from the global service provider (`ApplicationServices`). 
* Since the sample from the wiki also resolves the instance from `app.ApplicationServices`, the middleware incidentally shares the properties.
* I haven't found the location where the client is resolved for dependency events, but I guess that this resolves `TelemetryClient` from `RequestServices`, which does not contain the context-properties from the globally configured instance.

Resolving scoped services from a non-scoped provider is a code-flaw and should ideally throw on resolve (there's even some scope-validation work in progress for this in aspnet/DependencyInjection).

If you want `TelemetryClient` to be a singleton, you should change `AddScoped` into `AddSingleton`. This way, your sample would still work.

If you want to have it resolved once for each request, you have to add `TelemetryClient` as a parameter to the `Invoke` method in your middleware classes - this uses `RequestServices` instead of `ApplicationServices`. However, this way your sample no longer works and people would have to use a `ITelemetryInitializer` instead if I'm correct.

**Comment by dnduffy** [comment]
Sorry for the delay in responding, we are looking into it.

**Comment by cwe1ss** [comment]
No worries! thanks!

**Comment by kartang** [comment]
@cwe1ss  As you mentioned, there are 2 problems:

- **Transmitting properties to dependencies:** Currently, transmitting properties through telemetry client context to dependencies is not a supported feature. If the objective is to maintain a set of properties across all telemetry items, it is recommended to define a telemetry initializer that sets the respective properties for the telemetry. 

- **Scope of telemetry client:** Thank you for reporting this issue. We added this to the backlog, and we are planning to change to singleton. 

Please let me know if that makes sense. 

Thanks!

**Comment by kartang** [comment]
Closing this, and telemetry client is changed to singleton, and the fix is in https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/256.

**Comment by cwe1ss** [comment]
awesome - thanks!
