### ISSUE TITLE
startTrackEvent is not stubbed/queued

### ISSUE THREAD

**Issue by dfederm** [Microsoft/ApplicationInsights-aspnetcore#252]
It looks like in the JavaScriptSnippet, these events are stubbed out with an implementation that basically queues up the invocation until the real appInsights impl is on the page:
["Event","Exception","Metric","PageView","Trace","Ajax"]

However, this does not encompass all functions on the appInsights object. For example startTrackEvent.

This can cause lost instrumentation, as well as JS errors when the AI js fails to load (or is blocked by an adblocker in my case).

Here is an example of the JS error as well as an example of the "trackEvent" function being stubbed out which avoids the JS error (although still loses the instrumentation due to the adblocker):
![image](https://cloud.githubusercontent.com/assets/6445614/17939188/3c807f70-69de-11e6-8a8d-b9e732605369.png)

**Comment by SergeyKanzhelev** [comment]
Moved to JS repository. Thanks!

**Comment by dnduffy** [comment]
Currently the snippet also has to be maintained in this repo since we don't have a cross repo dependency.
