### ISSUE TITLE
Split package into two: with MVC reference and without

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#26]

**Comment by SergKanz** [comment]
I propose to postpone solving this problem till we have some customer feedback and customers who do not use Mvc in their applications. It will not be hard to split packages in future. Now it is quite difficult to implement nice interface of replacing the default behavior by replacing services as mentioned here [aspnet/DependencyInjection/issues/155](https://github.com/aspnet/DependencyInjection/issues/155).

**Comment by dnduffy** [comment]
The explicit MVC dependency was removed in 2.0.0.
