### ISSUE TITLE
SQL query command is not being recorded

### ISSUE THREAD

**Issue by jonaslundgren** [Microsoft/ApplicationInsights-aspnetcore#262]
I've followed the guide that used be to located at https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started, dead link? When using Microsoft.ApplicationInsights.AspNetCore version "1.0.0" on framework "net452" dependent SQL calls are being recorded but they lack the actual SQL query. I'm using Entityframework Core 1.0.0 and SqlServer.

![image](https://cloud.githubusercontent.com/assets/6916558/18381853/9eee1d00-767e-11e6-826e-87e8bc095236.png)

**Comment by abaranch** [comment]
If you host application in IIS you can install StatusMonitor in the box. StatusMonitor installs profiler and enables it for w3wp process. If you host it in a different process command text collection is not supported.

**Comment by jonaslundgren** [comment]
I tried to run my app in IIS on a machine that had StatusMonitor installed and it didn't help, get similar call traces as in the original screenshot. Do I have to active my AspCore site in some way? I tried to use the UI but got the following message: 
![image](https://cloud.githubusercontent.com/assets/6916558/18436465/c25b0cea-78f8-11e6-9529-e2b254d75e2f.png)

**Comment by abaranch** [comment]
This message means that your application will not be hosted in w3wp process (so currently this is not supported). Profiler is registered for w3wp.exe only (and you even do not need to configure anything in StatusMonitor, just have it on the box). So you have 2 options:
- either use full framework which would mean that your application will be hosted in w3wp and profiler will be loaded on start
- instrument your application manually using TrackDependency

**Comment by ctolkien** [comment]
I'm running an ASP.Net Core app against the full framework on Azure and having the same issues - SQL command text is not being captured?

Using `"Microsoft.ApplicationInsights.AspNetCore": "2.0.0"`

**Comment by dnduffy** [comment]
If you use the traditional .NET framework by itself then it is supported.
If you use .NET Core, with or without the traditional full .NET framework, then it is currently not supported.
We are working on adding SQL dependency tracking for .NET Core.

**Comment by ctolkien** [comment]
>If you use .NET Core, with or without the traditional full .NET framework

That.. doesn't make sense - you can't be using .NET Core and full framework. Are you referring to ASP.NET Core with full Framework?

**Comment by dnduffy** [comment]
Sorry to cause confusion, I'm referring to having a project.json which targets net451 for example, I guess that's not really .NET Core though.

For .NET 4.0, 4.5, 4.6, etc. = "full framework" on Windows only (& whatever Mono supports); this supports all the SQL dependencies functionality.

For .NET Core 1.0, 1.1, (soon 2.0) = new cross platform .NET framework; we currently do not have feature parity for dependency collection in .NET Core.
