### ISSUE TITLE
Dependency Track (SQL) doesn't work

### ISSUE THREAD

**Issue by fujiy** [Microsoft/ApplicationInsights-aspnetcore#266]
Dependency tracking is not working on ASP.NET Core?

**Comment by dnduffy** [comment]
Are you using the full .NET framework or just the new .NET Core cross platform framework?
Dependency tracking is only available in the full framework (not cross platform) at this time (see the [release notes](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases) for what is supported).
If you are using the full framework then see this [post](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/262) for possible reasons.

**Comment by fujiy** [comment]
.NET Core. Thanks

**Comment by fujiy** [comment]
I created a class to handle that: https://www.nuget.org/packages/Fujiy.ApplicationInsights.AspNetCore.SqlTrack/

https://github.com/fujiy/Fujiy.ApplicationInsights.AspNetCore.SqlTrack
