### ISSUE TITLE
Error after upgrade to core 1.0.1

### ISSUE THREAD

**Issue by bklooste** [Microsoft/ApplicationInsights-aspnetcore#268]
After upgrade to 1.0.1

An exception of type 'System.IO.FileLoadException' occurred in Fis.Configuration.WebAPI.exe but was not handled in user code Additional information: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=1.0.0.0,

**Comment by dnduffy** [comment]
We'll have an updated NuGet package for 1.0.1 within a day or two.

**Comment by dnduffy** [comment]
Try this package and let me know if that solves the problem.
[Release Notes](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v1.0.1)
[NuGet Package](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/1.0.1)
