### ISSUE TITLE
net452 framework doesn't work with ApplicationInsights package

### ISSUE THREAD

**Issue by kyschouv** [Microsoft/ApplicationInsights-aspnetcore#275]
There are some places in the code that specifically handle net451, but not net452 (or presumably net46*). These fail on startup in a net452 project using ApplicationInsights. For example, [ApplicationInsightsExtensions.cs](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/55224d6e3a77bede6d12624be4fdc7df839d02f5/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs).

**Comment by SergeyKanzhelev** [comment]
My understanding is that `net46` and `net452` will fall back to `net451`. Is it not the case? @kyschouv, do you have an example of such project where Application Insights will fail to initialize?

**Comment by SergeyKanzhelev** [comment]
@dnduffy - can you pls try to repro this before the next release?

**Comment by haseeb-ahmed-tkxel** [comment]
Is this fixed? I think this is still not fixed because I'm facing the same issue.

**Comment by dnduffy** [comment]
@haseeb-ahmed-tkxel No, I am sorry it is not, we prioritized it for the next version (2.2).

**Comment by haseeb-ahmed-tkxel** [comment]
@dnduffy Just wondering, whats the workaround than? How do I get it working for now?

**Comment by dnduffy** [comment]
@haseeb-ahmed-tkxel Can you upgrade to 4.6.1?

**Comment by tvenhaus** [comment]
We are using 4.6.1 and still running into this issue.  Is there a workaround other than waiting for 2.2?

**Comment by cijothomas** [comment]
Hi,
Any one who experienced this can share a repro for us to investigate? @kyschouv @haseeb-ahmed-tkxel @tvenhaus
