### ISSUE TITLE
Visual Studio "debug session" integration from first principles

### ISSUE THREAD

**Issue by kierenj** [Microsoft/ApplicationInsights-aspnetcore#276]
Hi - the tool is working great, and I've written a log provider too, so loads of telemetry going through the system and working very well.

I saw Scott's blog post on VS integration (latest post at http://www.hanselman.com/blog/), but when I use the VS2015 toolbar button and hook it to the "debug session" data source, I don't see anything.

I'm setting the instrumentation key via `ApplicationInsights:InstrumentationKey` and developer mode to `true` via `ApplicationInsights:TelemetryChannel:DeveloperMode`.  In the debug output in VS I see some app insights messages too.. but nothing in the extension's results window.

Is there something else that the VS tooling does when creating a new project "with app insights" for .NET Core, not covered here?

**Comment by SergeyKanzhelev** [comment]
@gardnerjr , @acearun can you pls take a look at this?

**Comment by gardnerjr** [comment]
@kierenj is this current asp.net core?  on VS2015?

when you debug, is the web project that has AI (and an appsettings.json file) the debug startup project?  When the debugger starts, i *believe* those are the 2 things we're looking for.

**Comment by kierenj** [comment]
I'm on `1.1.0-preview-*` - VS2015 Update 3.  I will check extensions and updates when I'm next at the machine (an hour or so!)

The web project is the startup project, but there's no appsettings.json... I configure in a different way entirely.  Combination of a couple of JSON files, an environment var and an in-memory provider!

I see debug output with AI JSON, am surprised that the extension wouldn't just look for that?

**Comment by gardnerjr** [comment]
we do look for that output, but only in cases where we expect to see it.  we don't want our extension watching for output in projects that don't have AI and possibly slow down the debugger in other situations.  

generally, having an applicationinsights.config or appsettings.json is where we'd expect to find ikeys and other things as well.  in the debugger case, we're not reading either file, just checking to see if it exists. you might be able to just add an empty one to the debugging project (doesn't even need to be copytooutupt or anything) and see if the debugger shows data?

**Comment by kierenj** [comment]
I have Developer Analytics Tools 7.9.1018.2 (no option to update).  I created blank files with those names but no luck there unfortunately.  And to confirm, VS 2015 Enterprise, 14.0.25431.01 Update 3.

I don't know if it's just the default set of "debugging" toolbars, but the Application Insights toolbar and button show when I start debugging (though not the window, I need to click to have that show).

**Comment by gardnerjr** [comment]
Yeah, the AI toolbar is by default only visible while debugging, but you can manually make it visible the rest of the time (which i think is what scott did in his post)

@avidhanju do we support aspnet core `1.1.0-preview-*` in the extension yet?

**Comment by avidhanju** [comment]
We haven't tested our tools against aspnet core 1.1.0-preview-*. If they have removed appsettins.json from the latest tooling, I can see how that will break us.

**Comment by gardnerjr** [comment]
@kierenj where/how do you have `1.1.0-preview` ? are you doing your own builds of aspnet?  the last release in there releases shows as 1.0.1 on https://github.com/aspnet/Home/releases

there might be other project/etc changes that also affect us as well.

**Comment by kierenj** [comment]
I'm on the nightly builds, in fact `1.1.0-alpha1-*` not preview.

**Comment by c1rus** [comment]
i had the same problem, my config file is config.json, adding appsetings.json to project helped. thanks

**Comment by kierenj** [comment]
(It didn't help for me - let me know if there's anything else I can try..)

**Comment by DamianEdwards** [comment]
@kierenj are still experiencing issues? I use the VS experience to see messages during debug without the instrumentation key being configured via appsettings.json and it works fine for me.

**Comment by user1568891** [comment]
I am also having this issue. Application Insights telemetry JSON appears in the Output - Debug window, and it shows up in Application Insights fine, but nothing appears in Application Insights Search - Data from Debug session telemetry. Using VS 2015 Update 3.

The [change note here](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-release-notes-vsix#version-43) sort of implied that the debug session telemetry only works when it can't connect to Application Insights, so I tried replacing my InstrumentationKey with all zeros, but no change in the debug session telemetry.

Anything else I should try?

**Comment by gardnerjr** [comment]
@user1568891 what version of .net core/etc.  this seemed to only be an issue for people using nightly builds/etc that the appinsights tools don't know anything about.  

when you debug the app, what does the application insights toolbar do?  does it say "Application Insights" with nothing after that?  or "Application Insights (?)"  the (?) indicates that the AI tools are watching for events but haven't seen any.  if the (?) isn't there, that means we don't think the project has AI configured, so we aren't watching for debug events at all.

**Comment by user1568891** [comment]
@gardnerjr thanks for the response. Running on .Net 4.6.2. The toolbar just says "Application Insights" with nothing after it. The telemetry still appears when searching application insights thought and in the debug output window.

**Comment by gardnerjr** [comment]
@user1568891 yes, but what version of core are you running?  asp.net core `1.0.x` ? or one of the 1.1 versions?  at this point anything experimental/alpha/preview probably won't work in VS2015, but should work in VS2017.

**Comment by user1568891** [comment]
Sorry I found this question via an internet search for help with this issue - I'm not using core, I'm using the full .Net Framework. Can you point me at the right place to go with this question?

**Comment by gardnerjr** [comment]
So you're doing a standard .net app, using AI?  but **not** an asp.net app and **not** an asp.net core app?

**Comment by user1568891** [comment]
Yes

**Comment by leftler** [comment]
@gardnerjr  I also am having a similar problem. I am running VS2017 15.2 and Application insights 2.4.0 installed in the project. This is with a Asp.net WebRole and is being launched locally via a Azure Cloud Service project. I see the output of the app inisghts in my console, and it shows up on my app insights account but the "Application Insights" button does not have a number after it and my Debug Session Telemetry has nothing in it.

**Comment by gardnerjr** [comment]
For standard asp.net (or even just regular .net non asp.net, non asp.net core), if your startup project *isn’t the project that has AI (or if your startup project is not an asp.net project)*, VS presumes that it shouldn’t waste time watching the output window.   The easiest way to force AI to watch for telemetry in any project is to do 2 things:

1)	Add an `applicationinsights.config` file  to the root of whatever the startup project is.  
Mark it as do not copy, it doesn’t need to show up in build output or anywhere else, we just look for its existence. in some of our solutions, the project is this content:

   <?xml version="1.0" encoding="utf-8"?>
      <ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
           
      </ApplicationInsights>

2)	Add an application insights resource id property to the *startup* project’s `.csproj` file (like 
`<ApplicationInsightsResourceId>[your resource id here]</ApplicationInsightsResourceId>`
The easiest way to get this one is to copy it form your other project, or find the resource id in azure.  If you do this, you can even right click this project and do search/trends/etc from that project.

If you do that, when you debug you should see the application insights toolbar turn on and start showing numbers while debugging.  (and the 2nd step should also make application insights submenus show up to let you search/etc from that node in solution explorer)

Let me know if that doesn’t work for you and I can help you debug further.

**Comment by leftler** [comment]
@gardnerjr My project was a .ccproj not a .csproj, it would not let me add through the GUI an existing item. However editing the .ccproj file with a text editor I was able to throw a `<None Include="ApplicationInsights.config" />` in to a Item Group and it picked up the App Insights debug data. Thanks!

**Comment by MHanafy** [comment]
Thanks @gardnerjr This was driving me crazy! I'm using VS 2019 and NetCore 2.2 with a console app; and application insights search screen doesn't show anything.
When I added the config file your mentioned it started working!
I VS should have an option to manually trigger this instead of having to place a config file that does nothing; perhaps the fact that you have "Application Insights Search" window open should make it start looking
