### ISSUE TITLE
Move to netstandard1.4 instead of dotnet5.4

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#277]
The `dotnet54` TFM is effectively deprecated. The package should instead be targeting the requisite .NET Standard version (`netstandard1.4`). Currently, applications targeting .NET Core (like ASP.NET Core apps on .NET Core) are required to specify imports in order to use Application Insights which isn't the desired experience.

**Comment by DamianEdwards** [comment]
Not sure why this was moved here, as this applies to the package built in https://github.com/Microsoft/ApplicationInsights-dotnet

Or I'm just confused :smile:

**Comment by SergeyKanzhelev** [comment]
@dnduffy please update it here: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/d3d4e3cef6e29d430f7865d6807132feb8676aac/src/Core/NuGet/Core/Package.nuspec#L31

**Comment by dnduffy** [comment]
Sorry, I thought you were referring to the imports in the .NET Core SDK in the project.json files.

**Comment by DamianEdwards** [comment]
This can be closed now as part of 2.0.0-beta1?
