### ISSUE TITLE
Microsoft.ApplicationInsights.AspNetCore 1.0.1 or 1.0.2 can't be installed on asp.net core 1.0.1 or 1.0.2

### ISSUE THREAD

**Issue by guybartal** [Microsoft/ApplicationInsights-aspnetcore#279]
after installing Microsoft.ApplicationInsights.AspNetCore 1.0.1 or 1.02 on asp.net core application i get this error on restoring nuget packages:

Package Microsoft.ApplicationInsights 2.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0)
![image](https://cloud.githubusercontent.com/assets/3179107/19743135/bd1c66a2-9bd0-11e6-9d84-582e6e036734.png)

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting and sorry for confusion. Here is the issue: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/335

Workaround would be to include import like this https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/project.json#L102-L104 to include `dotnet5.4` target

**Comment by DamianEdwards** [comment]
This should be resolved now in 2.2.0 and can be closed.

**Comment by dnduffy** [comment]
Version 2.0.0-beta1 of the AI SDK for .NET Core references 2.2.0 of the AI Base SDK which targets NetStandard1.5 now so you should not have a problem anymore if you use the latest version.
