### ISSUE TITLE
AspNetCore 1.0.2 is not compatible with AI 2.2-beta4

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/ApplicationInsights-aspnetcore#283]
I upgraded my ASP.NET Core app (target net 452) to AI 2.2-beta4 and got the error

Method not found: 'Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder Microsoft.ApplicationInsights.Extensibility.TelemetryProcessorChainBuilderExtensions.UseAdaptiveSampling(Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder)'.

The above method has been removed from AI 2.2-beta4. 

https://github.com/Microsoft/ApplicationInsights-dotnet/commit/30f33f698ff6c86d812189551208c11969bf3320

Here is the snippet of my project.json.

    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.ApplicationInsights": "2.2.0-beta4",
    "Microsoft.ApplicationInsights.Agent.Intercept": "2.0.5",
    "Microsoft.ApplicationInsights.DependencyCollector": "2.2.0-beta4",
    "Microsoft.ApplicationInsights.PerfCounterCollector": "2.2.0-beta4",
    "Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel":  "2.2.0-beta4"

**Comment by dnduffy** [comment]
We will be updating the AI SDK for ASP.NET Core very soon.
Please be advised that it may contain a couple minor breaking changes with how the library is initialized in Startup.cs.

**Comment by mcgear** [comment]
Anything new on this one?

**Comment by dnduffy** [comment]
Please try the [new version of the SDK](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0-beta1) and report here if you experience any issues.
As mention previously there may be some minor breaking changes with code in Startup.cs.
