### ISSUE TITLE
There is no "Asp.net Core" Application Type

### ISSUE THREAD

**Issue by runxc1** [Microsoft/ApplicationInsights-aspnetcore#284]
In the documentation found here
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started

It tells you that you have to select the application type of "Asp.net Core" when creating a new Application Insights account.   There are four options in the drop down with one of them being "ASP.Net web application"  it is not clear which option you should select as ASP.Net and Asp.Net Core are not the same

**Comment by DamianEdwards** [comment]
The docs have been updated to say:
Create a new Application Insights resource. (Click New -> Monitoring + management -> Application Insights). Select the ASP.NET application type.

**Comment by DamianEdwards** [comment]
@dnduffy might want to close this
