### ISSUE TITLE
No request tracking when using static file provider (only on 404)

### ISSUE THREAD

**Issue by Noer024** [Microsoft/ApplicationInsights-aspnetcore#285]
Hi,

Having issues tracking requests when using a static file provider in Asp.net Core using the core Application Insights package.

Generally files are served fine in the application but only 404s are registered against Application Insights. Is this normal behaviour? Currently I am having to register successful requests in code using TrackRequest ignoring 404 in the code I've added to prevent logging twice.

`app.UseStaticFiles(new StaticFileOptions              
{
FileProvider = FileSystemVirtualPathProvider.ConfigureMedia(fileSystem, authentication, httpContext, options, root),RequestPath = new PathString($"/{root}"),});`

**Comment by SergeyKanzhelev** [comment]
This may be middleware ordering issue. Have you registered Application Insights middleware before the static files one?

@pakrym will this be addressed with the new way tracking requests?

**Comment by pakrym** [comment]
Yes, new implementation should log all request correctly.

**Comment by SergeyKanzhelev** [comment]
@Noer024 please check the middleware ordering. We will be shipping the new version of SDK that does not use middleware to monitor request that should eliminate the need to order those correctly. Please check on updates

**Comment by Noer024** [comment]
@SergeyKanzhelev placing the static file provider after the declaration for the request telemetry seems to disable the provider.

Will wait for the updated telemetry to come out for now.

**Comment by dnduffy** [comment]
Glad you got it working.
Just FYI there is a [2.0.0-beta1](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0-beta1) package available now also.
