### ISSUE TITLE
Not able to update the file while deploying

### ISSUE THREAD

**Issue by lakshminarayanas** [microsoft/ApplicationInsights-aspnetcore#286]
I am getting the following error when trying to deploy the code.
Error Msg as follows:
Info: Updating file (demosite\Microsoft.AI.DependencyCollector.dll).
##[error]Failed to deploy website.
##[error]Error Code: ERROR_FILE_IN_USE
More Information: Web Deploy cannot modify the file 'Microsoft.AI.DependencyCollector.dll' 
on the destination because it is locked by an external process.  
In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, 
or use the AppOffline rule handler for .Net applications on your next publish attempt.  
Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.

I tried all the scenarios, even tried to delete the file through FTP(500 access denied- but I can delete other dlls).

**Comment by SergeyKanzhelev** [comment]
@Dmitry-matveev @dnduffy this needs to be triaged. Looks like a bug

**Comment by cijothomas** [comment]
Closing old issues. This does not appear to be an SDK issue as well.
