### ISSUE TITLE
Package Microsoft.ApplicationInsights.AspNetCore 1.0.0 is not compatible with netstandard1.5 

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/ApplicationInsights-aspnetcore#290]
This is what i get error for asp.net core app.

**Comment by henkmollema** [comment]
Try adding
```json
"imports": "dotnet5.6"
```
to the target framework in project.json

**Comment by Eilon** [comment]
I think you can also update the version of `Microsoft.ApplicationInsights` to 2.2.0, which supports netstandard:

```json
    "Microsoft.ApplicationInsights": "2.2.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
```

**Comment by dnduffy** [comment]
You can also try our newest beta release which references the AI 2.2.0 package.
https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0-beta1

**Comment by DamianEdwards** [comment]
The 2.0.0 package is now released. Can this be closed out>

**Comment by dnduffy** [comment]
Closing as Damian suggested since [2.0.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0) stable is available which is compatible.
