### ISSUE TITLE
Startup Tracing: No Events before IWebHostBuilder.Build() Logged when running in Azure

### ISSUE THREAD

**Issue by AaronRM** [Microsoft/ApplicationInsights-aspnetcore#293]
I have a simple ASP .NET Core site running in Azure App Service and have integrated Application Insights according to the [Getting Started guide](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started).

I wanted to add some Trace events in Startup.cs by calling TelemetryClient's TrackTrace method. These trace events come through in the Visual Studio Application Insights Search window when debugging locally. However, when I deploy the site to Azure App Service, I don't see any of the trace events prior to the call to IWebHostBuilder.Build().

Is this expected behavior? Is there a way we can get startup tracing via AppInsights, or should I resort to another logging mechanism for app startup?

**Comment by DamianEdwards** [comment]
How are you getting access to the `TelemetryClient` instance before the `ConfigureServices` method returns? In ASP.NET Core apps, it's expected you'll get the instance from the DI container, which doesn't exist until after `ConfigureServices` returns, so you won't be able to trace before then without creating a separate instance to log with. Note you'll have to configure that instance with the instrumentation key which is generally gotten from the configuration instance built in your `Startup` class's constructor, so you won't have access to that before calling `IWebHostBuilder.Build()` either.

In my application I'm tracking application start events via Application Insights but they won't get logged until the `WebHost` instance is fully configured and running (I do this via an `IStartupFilter`). If you really want to log events earlier than that to Application Insights in ASP.NET Core you'll need to create and configure a `TelemetryClient` instance independent of the one used elsewhere in the app (via DI).

Hope that helps.

**Comment by AaronRM** [comment]
Thank you, Damian. We were creating new instances of `TelemetryClient` directly (i.e. `new TelemetryClient()`). As you point out, doesn't work (#78) because the iKey isn't configured on the new instance. Thanks for the clarification.
