### ISSUE TITLE
Upgrade from 1.0.0 to 1.0.2 broke something in my Telemetry Initializers

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-aspnetcore#299]
Hi,
I've just updated my package from 1.0.0 to 1.0.2 and something broke in my code using HttpContextAccessor to get User and add some properties to the telemetry context properties. With version 1.0.2 it's like properties never clean up and they add up over time (i.e. something gets shared between requests). With 1.0.0 this didn't happen.
A bit of context. I have several telemetry initializes similar to:

```
public class AppTokenTelemetryInitializer : ITelemetryInitializer
{
	IHttpContextAccessor _httpContextAccessor;

	public AppTokenTelemetryInitializer(IHttpContextAccessor httpContextAccessor)
	{
		_httpContextAccessor = httpContextAccessor;
	}

	public void Initialize(ITelemetry telemetry)
	{
		if (_httpContextAccessor?.HttpContext?.User != null)
		{
			var user = _httpContextAccessor.HttpContext.User;

			if (user.HasAppId())
			{
				telemetry.Context.Properties["AppId"] = user.GetAppId().ToString();
			}

			if (user.HasClubId())
			{
				telemetry.Context.Properties["ClubId"] = user.GetClubId().ToString();
			}
		}
	}
}
```

"Has/GetAppId" and "Has/GetClubId" are extension methods for checking if a claim is present and getting its value.
Exactly similar to this I have other initializes adding "DeviceId" and some other properties.

With version 1.0.0, custom properties "AppId", "ClubId", "DeviceId" were set only if really present on the User. Switching to 1.0.0, I see that all my AI entries contain properties that should not be present (as an example, requests not containing tokens should not have any claim set).
It's like if my telemetry context is not instanced "per request" but shared between different requests, which didn't happen previously.

Initializers are added in my Startup.cs in this way:

```
var initializer = new AppTokenTelemetryInitializer(app.ApplicationServices.GetService<IHttpContextAccessor>());
var configuration = app.ApplicationServices.GetService<TelemetryConfiguration>();
configuration.TelemetryInitializers.Add(initializer);
```

I don't understand what's changed between versions and if there is something wrong in the way I use my initializers...

Thanks!

**Comment by dnduffy** [comment]
Could you try the new [2.0.0-beta1](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0-beta1) package and see if you still have the issue?

**Comment by MarcAir** [comment]
tried the new beta and di doesnt seem to like
```csharp
@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
`
HTML does not have applicationinsightsjavascript...

**Comment by dnduffy** [comment]
@MarcAir That has code changed to not have an MVC dependency and so that line needs to be replaced.
See the [release notes](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.0.0-beta1) for details of what code to replace it with.  It's a breaking change which is why we changed the major version number for the release.

**Comment by MarcAir** [comment]
thanks, @dnduffy it was more that I found it hard to find the details of the release notes since the call to action to upgrade came from within vs2017 and searching the error resulted with no help.
