### ISSUE TITLE
Issues with referencing existing 4.5.2 dll in Asp Dot Net Core project

### ISSUE THREAD

**Issue by AnithaLingam** [Microsoft/ApplicationInsights-aspnetcore#303]
I have already developed Logging application using ApplictaionInsights in Dot Net 4.5.2 and this application has some configuration settings in Web.Config and ApplictaionInsights.Config and now I am cretaing Logging application using Asp Dotnet core and referencing my existing 4.5.2 dll but it is throwing below error while calling some existing services,i think this issue the service that i am calling has some reading the configuration settings from web.config ..I think this causing the issue.Please provide solution.

Error:
'System.IO.FileNotFoundException
Could not load file or assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

**Comment by dnduffy** [comment]
System.Configuration is not available in .NET Core, the error message you received has nothing to do with ApplicationInsights but rather with the .NET Core framework itself, that namespace is not in .NET Core.
The ApplicationInsights SDK for .NET Core does not use XML based configuration like the traditional .NET AI SDK's do for this very reason, .NET Core has a new configuration system.
I realize this is inconvenient but you will have to do some additional work if you want your application to work with .NET Core CLI.  You can either write code to use the new configuration system provided in .NET Core or you can try including a third party library that attempts to expose a System.Configuration namespace to .NET Core but be aware that if you use the 3rd party library you may still have problems as that is not an officially supported scenario for .NET Core.  I think your best option would be to write code to use the new configuration system, and if need be, use some #ifdef statements in your library to build it to support both the old and new models.
Here are some links I found by searching online that might help you:
https://msdn.microsoft.com/en-us/magazine/mt632279.aspx
http://benfoster.io/blog/net-core-configuration-legacy-projects
https://github.com/dotnet/corefx/issues/1348
