### ISSUE TITLE
TelemetryInitializers not working on 2.0.0-beta1 beacause RequestTelemetry is created earlier than before

### ISSUE THREAD

**Issue by andrasg** [Microsoft/ApplicationInsights-aspnetcore#309]
Updated to 2.0.0-beta1 and noticed that requesttelemetry gets sent multiple times (4 in my case). Also custom TelemetryInitializers seem to be broken: altough they are exectued, added properties are not visible in VS Appinsights search or in the portal.

**Comment by andrasg** [comment]
My bad, removing `.UseApplicationInsights()` from the WebHostBuilder removed the redundant telemetries.
TelemetryInitializers still have an issue. They get called but their effect is not seen on telemetry going out.

**Comment by andrasg** [comment]
I have found some clue. It seems that the creation of RequestTelemetry is much sooner in the pipeline than my middleware could extract information from the request and store it in a request scoped object and pass it to the initializer.

**Comment by andrasg** [comment]
Ended up moving TelemetryInitilalizer code to a middleware and using `context.Features.Get<RequestTelemetry>()` to obtain and modify the requesttelemetry object.
Any better way to do this?

**Comment by pakrym** [comment]
@andrasg TelemetryInitializers are ran when telemetry gets posted to the TelemetryClient, in case of request telemetry this happens in the very end of request processing and after all midlware finished their execution.

Can you please share the code of you `ITelemetryInitializer` implementation or a simplified repro of this issue.

**Comment by andrasg** [comment]
@pakrym, you are right. I remembered wrong. Upon debugging it again, it turns out I have a DI problem.

I am using a middleware to get an instance of a custom object (IRequestContext) that is registered as scoped in DI. 

In the middleware:
```cs
IRequestContext requestContext = (IRequestContext)context.RequestServices.GetService(typeof(IRequestContext));
requestContext.CorrelationId = Guid.NewGuid();
```
I am successfully using the `IRequestContext` object instance throughout my code and retrieving the guid that's set in the middleware.
In my telemetry initializer though, I am not able to obtain a reference to the same `IRequestContext` object instance.
Here's the initialize method:
```c#
IHttpContextAccessor httpContextAccessor = _serviceProvider.GetService<IHttpContextAccessor>();
IRequestContext requestContext = httpContextAccessor?.HttpContext?.RequestServices?.GetService<IRequestContext>();
```
This will yield null for `requestContext` for `RequestTelemetry`, as `RequestServices` is `null`. For other types of telemetry (`DependencyTelemetry` or `TraceTelemetry`) this works correctly.

**Comment by pakrym** [comment]
@andrasg yeah, first part of issue is resolving scoped service from singleton (while you might not register ITelemetryInitializer as singleton it is still resolved only once - during application startup).
The other part of an issues is that when RequestTelemetry is logged HttpContext.RequestServices is already disposed.

I will think more about it, but for now putting IRequestContext  into HttpContext features is the easiest way to accomplish what you want.

**Comment by andrasg** [comment]
I am already registering my telemetryinitializers as singletons. So I was on the correct path using `HttpContext.RequestServices` to access a request scoped object from a singleton but wasn't aware that it is already disposed for `RequestTelemetry`.

Will move to using features. Closing the issue, thanks for the help!
