### ISSUE TITLE
ApplicationInsightsLoggerProvider should support setup via an IConfiguration instance with change tracking, like the ConsoleLoggerProvider

### ISSUE THREAD

**Issue by DamianEdwards** [microsoft/ApplicationInsights-aspnetcore#316]
The `ApplicationInsightsLoggerProvider` should support having its filter configured via an `IConfiguration` instance, including reacting to changes in the underlying config providers so that the filter can be altered easily while the app is running, e.g. by changing a settings JSON file. The `ConsoleLoggerProvider` [supports this already](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs#L96) and it's used in ASP.NET Core project templates in Visual Studio by default.

**Comment by cijothomas** [comment]
Closing as this is no longer relevant. Filtering is done by the logging infra itself, not application insights.
