### ISSUE TITLE
Update HttpContext.TraceIdenfier with Telemetry.Name generated in MvcDiagnosticsListener

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/ApplicationInsights-aspnetcore#321]
MvcDiagnosticsListener generates the operation name for request telemetry from IRouteData. 

Application Insights Profiler needs to correlate the profiling data with the request telemetry by operation name. 

Currently Application Insights Profiler subscribes to Microsoft.AspNetCore.Hosting diagnostic source through [DiagnosticSourceEventSource.cs](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs) but it only read the properties from HttpContext . 

To pass the operation name to Application Insights Profiler, MvcDiagnosticsListener can append the name to HttpContext.TraceIdenfier. eg, 

        [DiagnosticName("Microsoft.AspNetCore.Mvc.BeforeAction")]
        public void OnBeforeAction(HttpContext httpContext, IRouteData routeData)
        {
            var telemetry = httpContext.Features.Get<RequestTelemetry>();
            if (telemetry != null && string.IsNullOrEmpty(telemetry.Name))
            {
                string name = this.GetNameFromRouteContext(routeData);
                if (!string.IsNullOrEmpty(name))
                {
                    name = httpContext.Request.Method + " " + name;
                    telemetry.Name = name;
                    httpContext.TraceIdentifier += “|” + name
                }
            }
        }

**Comment by SergeyKanzhelev** [comment]
Would it be better to associate AI `RequestTelemetry` with the `TraceIdentifier`? So if you listen for all `RequestTelemetry` objects using rich event source you can associate trace identifier with the name

**Comment by northtyphoon** [comment]
The additional correlation events based on rich event source have the cost. First, we need to pipe the data to AI profiler process which is complicated in Antares. Second, to correlate the request and profiling trace, we need to keep the data in each profiling cycle for mapping.

In aspnetcore app, we both subscribe to the same aspnetcore diagnostic source and read the data from httpcontext in most cases. So we want to explorer a solution that can avoid the additional correlation event based on rich event source. 

We have a prototype that works based on the single diagnostics source as long as the name can be passed through HttpContext.TraceIdentifier.

@vancem @weng5e

**Comment by SergeyKanzhelev** [comment]
1. Our SDK is trying to be "least" invasive. Attaching the name to trace identifier will not be expected by other telemetry solutions.
2. We already misuse diagnostics source for http headers injection. We discussed it explicitly and agreed that it is not invasive.
3. Request `name` can be changed during the action execution. So this name may not be a final one.
4. There are other properties besides the `name` that can be used for correlation between SP and AI. So the approach of receiving of entire `RequestTelemetry` is better

**Comment by northtyphoon** [comment]
I admit it's not the ideal solution. We are investigating a long-term solution but it's pending on a few other dependencies. As currently there is no profiling solution for aspnetcore in AI, we want to propose it as a short-term solution to fill the gap.

Rich event source is not available on AI 2.2 netstandard1.5 version. Which project is it built from? PCL?

@SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
Yes, it is built from PCL today. It would be better to rebuild it for `netstandard1.5` for this support.

I don't think this solution will be good even as a short term. We just released a version of aspnetcore SDK and next release wouldn't be very soon. By this time it would be more beneficial figure out how to switch base library to be build against `netstandard1.5`

**Comment by northtyphoon** [comment]
I did some experiments on kusto to see if it's feasible to just use operation_id to correlate request and trace data. The performance was surprisingly good. I think we can build a short-term solution without passing the telemetry.name to service profiler. 

I'm closing current issue. I will open a new thread once we start the long-term solution work.

**Comment by SergeyKanzhelev** [comment]
Thank you! I appreciate your understanding and finding an alternative solution.
