### ISSUE TITLE
Create a centralized helper for setting SDK version prefix string.

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#323]
Instead of repeating code like the following we should centralize the version prefix construction in a helper:
``` C#
this.sdkVersion = SdkVersionUtils.VersionPrefix + SdkVersionUtils.GetAssemblyVersion();
...
telemetry.Context.GetInternalContext().SdkVersion = this.sdkVersion;
```
Currently this logic is repeated in ApplicationInsightsLogger, HostingDiagnosticListener, and ExceptionTrackingMiddleware.

**Comment by cijothomas** [comment]
Logger code is deprecated. The only place this repo is setting version is in the RequestTracking module. Closing as there is no action needed anymore.
