### ISSUE TITLE
AddApplicationInsightsTelemetry overload with explicit ApplicationInsightsServiceOptions should use reflection.

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#325]
Rather than requiring explicit property references for copying the configuration options it would be safer and more maintainable for future option additions if the copying was done with reflection.

**Comment by DamianEdwards** [comment]
I'm assuming you mean this overload: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/9287d7e9e900f6a398c5f2b65fb2982302fd48d1/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L98

@davidfowl @pakrym thoughts on this? That delegate only runs once, correct?

**Comment by dnduffy** [comment]
Yes, that is what I am referring to.  It's brittle now if someone adds a new parameter and doesn't know to update that method.  It only runs once so the perf overhead from reflection isn't a big deal in my opinion.

**Comment by davidfowl** [comment]
What's the purpose of that overload? Just for my knowledge...

**Comment by dnduffy** [comment]
User convenience and backwards compatibility with the old API.
I personally believe it is nicer to pass an "example" instance of the desired settings than to pass an anonymous delegate which returns them.

**Comment by cijothomas** [comment]
Closing old issues. Configuration improvements are tracked separately.
