### ISSUE TITLE
Telemetry does not include "ai.operation.parentId".

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#333]
Telemetry items sent from the .NET Core SDK do not have the "ai.operation.parentId" tag.

**Comment by pharring** [comment]
For a new incoming request, what should the operation.parentId be?
Perhaps you could implement a (Skip'd) functional test for it and I'll fix it with #343

**Comment by pharring** [comment]
I think I see what you mean. New top-level requests should not have parent IDs. However, other telemetry events (TrackException, TrackEvent, etc.) should set the parent Id.

**Comment by pharring** [comment]
In the ASP.NET codebase (_not_ aspnetcore) , the propagation of parent ID is done with ```OperationCorrelationTelemetryInitializer``` . It looks like we need that in core too. Agreed?

**Comment by SergeyKanzhelev** [comment]
Agree. Thanks
