### ISSUE TITLE
Getting started guide mentions UseApplicationInsightsExceptionTelemetry() which is obsolete

### ISSUE THREAD

**Issue by p-** [Microsoft/ApplicationInsights-aspnetcore#336]
Hi,
The [Getting Started with Application Insights for ASP.NET Core](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core) mentions `UseApplicationInsightsExceptionTelemetry()`, which is marked obsolete in `"Microsoft.ApplicationInsights.AspNetCore": "2.0.0"`.

**Comment by SergeyKanzhelev** [comment]
@dnduffy, where are we on docs update? 

@p- In most scenarios the only call needed to enable monitoring is `AddApplicationInsightsTelemetry` since we are using framework instrumentation instead of injecting middleware "manually".

I like your GH handle!

**Comment by dnduffy** [comment]
The documentation has gotten out of data, I've marked this as a bug to fix the documentation.
@p- In the mean time take a look at the release notes for [2.0.0](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.0.0) and [2.0.0-beta1](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.0.0-beta1) about the changes required from the old version.

**Comment by cijothomas** [comment]
Doc is updated.
