### ISSUE TITLE
What is ApplicationInsightsAnnotationResourceId?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/ApplicationInsights-aspnetcore#338]
What is `ApplicationInsightsAnnotationResourceId` and that is the difference with `ApplicationInsightsResourceId`?

**Comment by SergeyKanzhelev** [comment]
Where did you get it from? Annotations in a context of Application Insights are most probably means release annotations: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-annotations#create-custom-annotations-from-powershell

**Comment by xperiandri** [comment]
It is from xpoj file. Application Insights tools add them into it

**Comment by SergeyKanzhelev** [comment]
Oh, ok. @gardnerjr - can you please comment on this?

**Comment by gardnerjr** [comment]
`ApplicationInsightsResourceId` is the resource Id Visual Studio believes to be related to your project.  if you open the AI configure window, that resource is presumed to be the one you are sending data to, shown at the top of configure window.  It is also used as the default for showing data in CodeLens, or if you open live search or the Azure Portal or App Analytics portals for that project.  (in the configure window you can configure this separately (as the second resource picker) for example, if you want so send data to a debug resource while testing, but you always want CodeLens to show you production data)

`ApplicationInsightsAnnotationResourceId ` is the resource id Visual Studio uses to create release annotations when you publish a website from VS.  In the AI configure window, it would be the 3rd selectable resource.  if you're signed into vs when you publish, VS will automatically create a publish annotation for you.  You can change the resource (or turn this off) from the AI configure window.

docs for release annotations are here: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-annotations

**Comment by SergeyKanzhelev** [comment]
@gardnerjr thanks for explanation. @xperiandri I'm closing the issue for now. Feel free to reopen if you have more questions.

**Comment by QuantumHive** [comment]
@gardnerjr is it recommended that those values should be kept a secret from the public? E.g. what are the security risks if I would just push these settings to GitHub?

**Comment by gardnerjr** [comment]
When we did our security review, resource ids like that were *not* considered secrets, only unique ids.
in order to use it, you'd still need an auth token that goes along with that resource id.  the resource id does include the name of your app, etc, so that's up to you.

**Comment by BellaLi** [comment]
@gardnerjr  So the ApplicationInsightsResourceId and ApplicationInsightsAnnotationResourceId are used for local env only, majorly Visual Studio? For services deployed to multiple regions, hence will be configured with different ApplicationInsights accounts, these two settings don't matter, do they?

**Comment by gardnerjr** [comment]
yes.  those fields only apply inside visual studio, for the visual studio tools themselves.  they do not affect where your app sends data at actual runtime when deployed.  that's all from AppInsights.config or from whatever code/settings you are using at runtime.
