### ISSUE TITLE
Request-Dependency correlation is broken

### ISSUE THREAD

**Issue by kartang** [Microsoft/ApplicationInsights-aspnetcore#340]
Operation id of the request is not propagated to the child dependencies. Please find the following example:
![image](https://cloud.githubusercontent.com/assets/12818796/22480894/d752f5e0-e7a7-11e6-9ae3-a0d5e5de5a5e.png)

**Comment by pharring** [comment]
Sergey asked me to look into fixing this.

Am I right in thinking that we expect behavior for the dependency to look like this:
Operation Id: **80000032-0001-f000-b63f-84710c796bb**
Operation name: GET Benchmark/HttpDependencyParallelCalls
Dependency Id: qOwUmMlhB00=
DeveloperMode: true
?

Also, if the Request's Operation Id is blank, then should the dependency's Operation Id be taken from the "Request Id" instead?

**Comment by pharring** [comment]
I feel like this should be done with a TelemetryInitializer, much like ```OperationCorrelationTelemetryInitializer```. Agreed?

**Comment by SergeyKanzhelev** [comment]
yes, this would be great. The main issue with correlation is that `.Context.Operation.Id` should be shared across all items. `item.Id` should be unique. And `.Context.Operation.ParentId` should point to the parent. In the example @kartang posted dependency's `Operation.Context.Id` was used as a `ParentId`
