### ISSUE TITLE
Doesn't track startup errors

### ISSUE THREAD

**Issue by DamianEdwards** [Microsoft/ApplicationInsights-aspnetcore#341]
I don't think the SDK is currently tracking ASP.NET Core startup errors. These are exceptions that occur during the startup phase of the application before the server has started receiving requests, e.g. a line in the applications' `Startup.ctor` or `Startup.Configure` methods fail.

ASP.NET Core has configurable behavior to either catch startup errors and allow the server to start, then show a canned 500 error page, or not catch startup errors and let the exception propagate, usually to the applications `Program.Main` and thus causing it to exit with an error condition.

It would be useful to track these startup errors in AI for cases where the app is deployed, successfully configured to talk to AI, but fails elsewhere during startup. The timing may be problematic however, as typically the AI hookup doesn't happen in the application until the `Configure` phase (via an `IStartupFilter`) which would mean that any error occurring before this wouldn't get tracked without us rethinking this a bit. It might be possible to hook something up earlier exclusively for tracking startup errors and have this feature be controllable via a separate flag in the SDK.

**Comment by cijothomas** [comment]
Closing this as this is now mostly addressed with ILogger integration. AI can capture exceptions occurring from program.cs/startup.cs itself, (though with a minimal config).
