### ISSUE TITLE
[Docs / Guidance] RE: Custom ITelemetryProcessor

### ISSUE THREAD

**Issue by ctolkien** [Microsoft/ApplicationInsights-aspnetcore#344]
Just flagging that your own custom `ITelemetryProcessors` will be instantiated, but the `Process` method will  _never_ be called if your `IntrumentationKey` is left blank. 

For instance, in the scenario where you are developing locally and trying to get your own `ITelemetryProcessor` to work.

Yes, I just spent my morning trying to figure this one out...  🥇

**Comment by Dracs** [comment]
Oh, thank you for that. I was pulling my hair out over this. Adding in the `IntrumentationKey` value got my code being called.

**Comment by ohadschn** [comment]
Why would this be a documentation / guidance issue? 
In other words, why not call `Process` even when `IntrumentationKey` is blank?

**Comment by SergeyKanzhelev** [comment]
I think it may be addressed with the new multi-sink support work https://github.com/Microsoft/ApplicationInsights-dotnet/issues/559

**Comment by SergeyKanzhelev** [comment]
Addressed with #604.
