### ISSUE TITLE
Update from 1.0.0 to 2.0.0 breaks seemingly unrelated IActionContextAccessor dependency

### ISSUE THREAD

**Issue by senritsu** [Microsoft/ApplicationInsights-aspnetcore#347]
We have a custom `ActionFilter` that is instantiated by an `IFilterFactory` attribute.

After the update to 2.0.0 (which seems like it should be completely unrelated) the filter stopped working, due to a dependency resolution error.

> Cannot resolve parameter 'Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor actionContextAccessor' of constructor 'Void .ctor(Microsoft.AspNetCore.Mvc.Routing.IUrlHelperFactory, Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor)'."

The `IFilterFactory` itself does nothing but use its `CreateInstance(IServiceProvider serviceProvider)` method to return the filter instance via `IServiceProvider.GetService<T>`.

The only changes applied during the update were:
- removal of the obsolete `UseApplicationInsightsRequestTelemetry` middleware
- change of the old `Html.ApplicationInsightsJavaScript(telemetryConfig)` to the new `JavaScriptSnippet` and related injection into `_ViewImports.cshtml`
- package update from `1.0.0` to `2.0.0` in the startup project

Before these changes the filter works correctly, after the update it can't resolve `IActionContextAccessor` during filter creation.

We use Autofac as a dependency container.

Any clues as to why this might happen, or how those things could be even remotely related?

**Comment by pakrym** [comment]
Looks like Asp.Net Core packages version mismatch can you please post your `.csproj` file?

**Comment by dnduffy** [comment]
@senritsu If you are still experiencing the issue please reopen this GitHub issue and provide the example @pakrym requested.
