### ISSUE TITLE
Server with Disabled Telemetry Collection still visible on Azure Portal Live Stream 

### ISSUE THREAD

**Issue by matthieugd** [Microsoft/ApplicationInsights-aspnetcore#348]
We are using the kill switch (TelemetryConfiguration.Active.DisableTelemetry) to disable the collection on the developer machines.

But when we visit the Azure Live Stream blade we are still seeing those machines "online" with only the CPU and memory (see attached screenshot)
![livestream](https://cloud.githubusercontent.com/assets/143315/23028178/9f311374-f434-11e6-8284-e025bd98ad35.png)

Is that normal?

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting the issue. I moved it to a different repository: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/328 Please comment there if you have more feedback!
