### ISSUE TITLE
Allow to configure Server Telemetry Channel settings

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#353]
Reported by @yazici here: https://github.com/Microsoft/ApplicationInsights-Announcements/issues/1#issuecomment-283825739

>How do we disable this for AspNetCore for 2.0? There is no config file.

**Comment by oddbear** [comment]
Isn't this where we use the EnableAdaptiveSampling option?
```
services.AddApplicationInsightsTelemetry(configuration => {
    configuration.EnableAdaptiveSampling = false;
});
//or
services.AddApplicationInsightsTelemetry(new ApplicationInsightsServiceOptions ...
```
In my testing setting this to false, does not add the AdaptiveSamplingTelemetryProcessor.

**Comment by cijothomas** [comment]
@oddbear yes, thats the right way of turning off sampling.
