### ISSUE TITLE
Exception details not logged

### ISSUE THREAD

**Issue by svickers** [Microsoft/ApplicationInsights-aspnetcore#354]
After upgrading to 2.0.0 I noticed `app.UseApplicationInsightsExceptionTelemetry();` is marked as deprecated.  Now in the portal I see failed 500 requests but digging in doesn't show any exception details, I am pretty sure they were there before.
<img width="566" alt="screen shot 2017-03-03 at 10 43 23 am" src="https://cloud.githubusercontent.com/assets/105884/23564129/44a4e680-fffe-11e6-8a49-54276851076b.png">

Do we have to use a custom exception filter now to log the details?  Couldn't find anything in the docs or getting started guide mentioning this.

**Comment by dnduffy** [comment]
The deprecated method should be redundant to the listener that is automatically wired up internally now.
The code inside each handler function is identical.

It would be redundant to still have the old method that uses a middleware, and you would get two of each exception reported, but are you saying that with that obsolete method you are seeing details and without it you are not?  Or are you saying that with version 1.0.* you saw details and with version 2.0.0 you do not?
Just to confirm, if you downgrade to version 1.0.* of the SDK do you see more details?

**Comment by svickers** [comment]
Looks like when I go back to 1.0.0 the exception details are not logged either, I must've been mistaken with a non-core project that we use app insights on.  So what is the standard way to get exceptions logged?

**Comment by dnduffy** [comment]
Exceptions should be tracked automatically by default.
Can you see any in the search results or if you query through analytics?

**Comment by dnduffy** [comment]
I ran a simple .NET Core app with 2.0.0 of the AI SDK for .NET Core and I see the exceptions and requests in the portal.

**Comment by andrasg** [comment]
I have seen some similar issue with AI 2.0 and .net framework. As a tempfix I copied the  `OperationCorrelationTelemetryInitializer` that's in the works for 2.1 and is setting `OperationContext.ParentId` and `OperationContext.Id` to `requestTelemetry.Id`. Now exceptions show up on the request's blade properly.

**Comment by svickers** [comment]
@dnduffy Yes, I can see the individual exceptions and details but they aren't tied to the failed requests.  Sounds like @andrasg is on the right track for what the problem is.

**Comment by pharring** [comment]
We really need to get an update out for aspnetcore - even if it's pre-release. This has been fixed in develop for months now.

**Comment by dnduffy** [comment]
We plan to release a 2.1-beta1 soon to address getting the checked in fixes out for people to use.
