### ISSUE TITLE
Rename cross component dependency from "Application Insights" to "Http (tracked component)" 

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-aspnetcore#355]
See issue and corresponding .net sdk changes: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/323

**Comment by dnduffy** [comment]
@nizarq We have neither string in the AI SDK for .NET Core, does this issue (still) apply?

**Comment by nizarq** [comment]
Dependency collection for netcore, it turns out is not done in the aspnetcore repository but in the dotnet-server repository. I looked at the code, it seems to have been updated. Closing.
