### ISSUE TITLE
Microsoft.ApplicationInsights.NLogTarget not supported in .net core

### ISSUE THREAD

**Issue by steve-torchia** [Microsoft/ApplicationInsights-aspnetcore#356]
Not sure if this is the right repo to inquire about this - please point me in the right direction if not.

We are using NLog in our aspnet.core project.  We tried to add Microsoft.ApplicationInsights.NLogTarget package and noticed that it's not (yet) supported.  Is there a repo/project for this package where I could track anyprogress on this?

adding this
 `        <PackageReference Include="Microsoft.ApplicationInsights.NLogTarget" Version="2.0.0" />`

causes this: 
> Severity	Code	Description	Project	File	Line	Suppression State
Error		Package Microsoft.ApplicationInsights.NLogTarget 2.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.ApplicationInsights.NLogTarget 2.0.0 supports:  net40 (.NETFramework,Version=v4.0) , net45 (.NETFramework,Version=v4.5)			0

**Comment by dnduffy** [comment]
We plan to recompile that library to support netstandard and release an update.

**Comment by borlip** [comment]
The issue was closed a month ago. Are there any updates on the release date?

**Comment by snakefoot** [comment]
@borlip See https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/167 (Will be available with 2.6.0-beta3 of https://www.nuget.org/packages/Microsoft.ApplicationInsights.NLogTarget/

**Comment by borlip** [comment]
I got that, but my question was WHEN beta3 is going to be available?

**Comment by snakefoot** [comment]
Did you read the comments on the pull request that I linked to?


Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Microsoft.ApplicationInsights.NLogTarget ver. 2.6.0-beta3 has been released:

https://www.nuget.org/packages/Microsoft.ApplicationInsights.NLogTarget/2.6.0-beta3
