### ISSUE TITLE
How to override endpoint Url?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#357]
From @joyawad:

> I am using Application Insights in an ASP .NET 5 app.  Is redirecting the data to a different endpoint supported?
>This doc shows an example, but says it’s not supported. That’s confusing 😊 
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure#track-custom-traceeventmetric 

Wiki needs to be updated

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#configuration-based-approach-1 doc is updated
