### ISSUE TITLE
IIS Express Performance Counters Exception

### ISSUE THREAD

**Issue by avenger3pt0** [Microsoft/ApplicationInsights-aspnetcore#358]
I've successfully added App Insights to our application targeting net451 after following the [Starting Guide](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started).  However, when running locally through IIS Express, a System.InvalidOperationException exception is thrown soon after startup: 
`"Instance 'AppName' does not exist in the specified Category".  `
This also results in the following trace message : 
`"AI: Error collecting 3 of the configured performance counters. Please check the configuration."`

Through debugging and looking at [this page](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-cloudservices#performance-counters), I believe the counters are:
```
* \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests/Sec    
* \ASP.NET Applications(??APP_W3SVC_PROC??)\Request Execution Time
* \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests In Application Queue
```
I believe these counters created [on this line](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L140) in
`PerformanceCollectorModule.DefaultCounters`

I don't believe these counters cause issues when we deploy to Azure, as I haven't seen any issues pop up there.

How can I disable these counters when running in local development?

I tried conditionally calling `AddApplicationInsightsTelemetry`, but I then hit an exception when trying to inject `Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet`.

**Comment by dnduffy** [comment]
The three you list are added by default in the PerformanceCollectorModule.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/a50ba2ae3f4aab9da8b982b39ff471a9671fc035/Src/PerformanceCollector/Shared/PerformanceCollectorModule.cs#L158

You could try manually creating the list of counters you want to use the way the unit tests do it:
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/8c51d66c08c1baf0844613637fa5d3ccfc7590f9/Src/PerformanceCollector/Unit.Tests/PerformanceCollectorModuleTests.cs#L131
