### ISSUE TITLE
Update Getting Started page in Wiki for the 2.0 version of the library

### ISSUE THREAD

**Issue by follesoe** [Microsoft/ApplicationInsights-aspnetcore#359]
The Getting Started page says that you should call `services.AddApplicationInsightsTelemetry(Configuration);` in `ConfigureServices`, while the method is marked as obsolete. The change log states that you can simply remove the methods.

So; if I remove the call to `AddApplicationInsightsTelemetry`, and `builder.AddApplicationInsightsSettings(developerMode: true);` is wrapped in a `if (env.IsDevelopment())` check, is there really no need to do any registration in `Startup.cs`?

**Comment by dnduffy** [comment]
The methods that are obsolete and which should be removed are UseApplicationInsightsRequestTelemetry and UseApplicationInsightsExceptionTelemetry from the Configure method in Startup.cs.

You still need to call one of the services.AddApplicationInsightsTelemetry(***) overloads in the ConfigureServices method in Startup.cs.

**Comment by xperiandri** [comment]
Yes and the need of `.UseApplicationInsights()` in `Program.cs` is not clear.

**Comment by xperiandri** [comment]
Official Azure documentation redirects to wiki and wiki is outdated. Very bad!

**Comment by dnduffy** [comment]
I need to update the documentation, it is important, but unfortunately I haven't been able to get to it yet.

**Comment by cijothomas** [comment]
@xperiandri @follesoe 
I have put together a wiki for 2.0. Please let us if this helps!
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-ASP.NET-CORE2.0-WebApp

Sorry for not keeping documentation up-to-date. Will prioritize this for all further changes.
