### ISSUE TITLE
Cannot install Microsoft.ApplicationInsights.AspNetCore in VS2017 in new Asp.Net.Core Project

### ISSUE THREAD

**Issue by pkoecker** [Microsoft/ApplicationInsights-aspnetcore#361]
Install-Package : Package Microsoft.Extensions.DiagnosticAdapter 1.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Extensions.DiagnosticAdapter 1.0.0 supports: netstandard1.1 (.NETStandard,Version=v1.1)

Since the project.json is gone I cannot add the "dnxcore50" and "portable-net45+win8" to the imports list.

My csproj:
`  <PropertyGroup>    
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>MyApp</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>MyAppPackageId</PackageId>
    <RuntimeFrameworkVersion>1.1.0</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>
`

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-ASP.NET-CORE-2.0-WebApp
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-dotnetcore-quick-start
Please follow instructions above and re-open if you face issues.
