### ISSUE TITLE
Changing Success property is not reflected on Visual Studio 2017 AI debug session.

### ISSUE THREAD

**Issue by gongdo** [Microsoft/ApplicationInsights-aspnetcore#367]
I made a simple custom TelemetryInitializer like this:
```
public class NeverFailTelemetryInitializer : ITelemetryInitializer
{
    public void Initialize(ITelemetry telemetry)
    {
        if (telemetry is RequestTelemetry requestTelemetry)
        {
            requestTelemetry.Success = true;    // actual code has predicate function to evaluate it.
            requestTelemetry.Context.Properties["foo"] = "bar";
        }
    }
}
```
And added it to the `TelemetryConfiguration` in `Startup.cs`

It actually changes `Success` property for every RequestTelemetry, there's no problem after deploy to the Azure WebApp.
However in the Visual Studio 2017 AI debug session, the `Success` property is not changed. It's odd because it adds context properties successfully. It looks like that it only ignores `Success` property.

I think this issue is more proper for Visual Studio repository, since I tested it for the ASP.NET Core, I report it here. Please move this issue to more proper repository if it is actually an issue.

**Comment by cijothomas** [comment]
Please re-open if this is still an issue. VS has had many releases after this, so it might be already addressed.
