### ISSUE TITLE
Request duration reported to be less then it's dependency duration

### ISSUE THREAD

**Issue by pakrym** [Microsoft/ApplicationInsights-aspnetcore#370]
See https://github.com/aspnet/Home/issues/1955#issuecomment-289507366

**Comment by pharring** [comment]
Dupe of #350

**Comment by pharring** [comment]
@pakrym @jcsharp I believe this is now fixed. 2.1-Beta1 has just been released.

**Comment by jcsharp** [comment]
Yes, now the dependency traces are correlated to the requests and the duration times seem correct. Thank you.
