### ISSUE TITLE
ApplicationInsightsLogger requires IReadOnlyList when it updates a dictionary

### ISSUE THREAD

**Issue by Sentri** [microsoft/ApplicationInsights-aspnetcore#372]
The logger in [ApplicationInsightsLogger.Log](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs#L52) expects specifically a `IReadOnlyList` instead of a dictionary or a collection when adding extra properties to the trace telemetry. 

All it does with it is write values into a dictionary with a `foreach` so I suggest using a more abstract `IReadOnlyCollection`. This would give the advantage of passing in a `ReadOnlyDictionary<string, object>` directly without copying since that one implements `IReadOnlyCollection` but not `IReadOnlyList`.

**Comment by cijothomas** [comment]
closing here, as loggerproviders are completely rewritten into a separate repo.
