### ISSUE TITLE
Debug session not working when using Docker support on VS2017

### ISSUE THREAD

**Issue by fleed** [microsoft/ApplicationInsights-aspnetcore#379]
I have an application that's correctly registering ApplicationInsights events (local debug session) when running in debug mode under IIS Express.

Running the same application using the new `Docker support` functionality in `VS2017` doesn't collect local debug session data.

Is it not supported?

**Comment by SergeyKanzhelev** [comment]
@gardnerjr, do you know?

**Comment by gardnerjr** [comment]
all of the debug session stuff is powered by debug output.  when using the docker support, do you see application insights debug output in the output window?  the AI tools are also looking for specific supported debuggers, so it might be that the "docker debugger" is a new thing that hasn't been supported?  When you debug with docker support, what does the application insights toolbar button show?  does it just say "Application Insights" with nothing after that?  that would mean we saw the debugger start, but haven't seen any supported debugger engines start.  does it say "Application Insights (?)"  the question mark means "i'm watching for data but haven't seen anything yet"

**Comment by fleed** [comment]
@gardnerjr I can show you the actual output.

Project under `IIS Express`:

<img width="1229" alt="ai_iis" src="https://cloud.githubusercontent.com/assets/2131800/24825540/83fcea74-1c20-11e7-8a86-d74734d6f533.png">

Project under `docker`

<img width="1232" alt="ai_docker" src="https://cloud.githubusercontent.com/assets/2131800/24825544/8e896f12-1c20-11e7-904a-83aab36f824e.png">

**Comment by dnduffy** [comment]
Both views appear to be showing messages in the debug output (with no instrumentation key configured) so the SDK is collecting data (not sending it anywhere without an ikey of course).

**Comment by gardnerjr** [comment]
@fleed that's exactly what i was looking for.  This must then be a new thing with the docker support, they've possibly added a "debugger" that we'd never seen before, so the AI tools aren't watching for debug output.  Is this only in VS2017?  or are you doing this in VS2015?

I've created story 967317 on our side to track this.

**Comment by fleed** [comment]
@gardnerjr I'm using VS2017 only

**Comment by Lightning318** [comment]
I have also been running into this problem in VS2017. I had gotten used to the local application insights but it stopped working when I enabled docker support on my project just as above. Has there been any progress on this feature?

**Comment by gardnerjr** [comment]
Yes :) Hopefully this will make the VS2017 Update 3 in the next preview, but if not, it should make Update 3 by RTM.

**Comment by Vhab** [comment]
This appears to still be an issue. Any progress on this?

**Comment by devcfgc** [comment]
is still not working :'(

**Comment by mchristensen80** [comment]
It still doesnt appear to be working in VS 15.9.7 Any updates on when we can expect this to be resolved?

**Comment by cijothomas** [comment]
@gardnerjr to comment on VS release/support for this.

**Comment by cijothomas** [comment]
Closing older issues. This is not an SDK issue, but a Visual Studio question/enhancement.
