### ISSUE TITLE
Add ApplicationInsights to a statically rendered page

### ISSUE THREAD

**Issue by fleed** [Microsoft/ApplicationInsights-aspnetcore#381]
I have an Asp.net core middleware that's downloading html content from Azure storage and it is writing it to the output.
How can I inject ApplicationInsights into the output so that I can monitor performance for those *static* pages too?

**Comment by SergeyKanzhelev** [comment]
What version of Application Insights SDK are you using? 2.0 should capture all requests independently on which middleware is processing those requests.

cc: @pakrym

**Comment by fleed** [comment]
So does this include the rendering time?

<img width="980" alt="screenshot at apr 08 10-53-07" src="https://cloud.githubusercontent.com/assets/2131800/24827429/afdad254-1c49-11e7-8cb6-08a02e42414b.png">

**Comment by dnduffy** [comment]
@fleed Are you including the JavaScript SDK snippet for client side collection in this static files?

**Comment by dnduffy** [comment]
You can inject the JavaScript snippet and use our [JavaScript SDK](https://github.com/Microsoft/ApplicationInsights-js) to capture client side telemetry for those static pages.

**Comment by dnduffy** [comment]
@fleed If you have additional questions please feel free to reopen.
