### ISSUE TITLE
Shall we enable dependency collector by default?

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/ApplicationInsights-aspnetcore#384]
@dnduffy,
Like shows here in the tests, shall we enable DependencyCollector on by itself than asking user to add a line of code to enable it:
new DependencyTrackingTelemetryModule().Initialize(TelemetryConfiguration.Active);

Refer:
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Test/DependencyCollector/FunctionalTests/TestApps/AspxCore/Startup.cs

**Comment by dnduffy** [comment]
Yes, we will call it internally in something like ApplicationInsightsWebHostBuilderExtensions.UseApplicationInsights and expose configuration options in ApplicationInsightsServiceOptions.

**Comment by xiaomi7732** [comment]
Thanks for the confirm!

**Comment by radu-matei** [comment]
Is there a NuGet / MyGet package for the Dependency Collector on .NET Core?

Thanks!

**Comment by SergeyKanzhelev** [comment]
This [code](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/Samples/DataReduction/ApplicationInsightsDataROI/Demo1.cs#L21-L23) is essential:

```
// automatically collect dependency calls
var dependencies = new DependencyTrackingTelemetryModule();
dependencies.Initialize(configuration);
```

I think we will soon ship the version with it wired up

**Comment by dnduffy** [comment]
It is wired up automatically now and should be working in version [2.1.0-beta3](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.1.0-beta3).
