### ISSUE TITLE
Not all ApplicationInsightsServiceOptions are available from config

### ISSUE THREAD

**Issue by dfederm** [microsoft/ApplicationInsights-aspnetcore#388]
In `ApplicationInsightsExtensions.cs` the extension which takes an IConfiguration only reads and sets a subset of `ApplicationInsightsServiceOptions`

For example, this does not work:
```
  "ApplicationInsights": {
    "InstrumentationKey": "99fba640-790d-484f-83c4-3c97450d8698",
    "EnableAuthenticationTrackingJavaScript":  true
  },
```

**Comment by cijothomas** [comment]
#337 duplicated.
