### ISSUE TITLE
NuGet package metadata URLs should use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by Eilon** [Microsoft/ApplicationInsights-aspnetcore#390]
See here for the current URLs: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/5aa38ae65469aa649a50ad5433ae6d65d5b4e406/src/Microsoft.ApplicationInsights.AspNetCore/project.json#L9-L12

URLs affected: project URL, license URL, icon URL.

All of these URLs are available via HTTPS, which is of course a more secure protocol.

**Comment by nulltoken** [comment]
Shouldn't this be closed?

**Comment by Eilon** [comment]
Yeah I think this was done just recently...

**Comment by dnduffy** [comment]
Sorry, I thought I closed it, I must have only merged the PR.
