### ISSUE TITLE
Logging exceptions with ExceptionTelemetry

### ISSUE THREAD

**Issue by henkmollema** [Microsoft/ApplicationInsights-aspnetcore#393]
When you log an error with an exception through the `ILogger` interface like this:
```cs
logger.Log(LogLevel.Error, 0, state, exception, messageFormatter);
```
[it will use a `TraceTelemetry` instance](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/5aa38ae65469aa649a50ad5433ae6d65d5b4e406/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs#L44).

Is it possible to use an `ExceptionTelemetry` instance in the case where an exception is present? Exception telemetries provide a nicer experience in UI's such as Visual Studio and the Azure portal.

**Comment by andrasg** [comment]
This new behavior actually makes less sense if someone uses a global exception filter where all exceptions are tracked in a unified way.
With this new version, I get two exception telemetries (one at the `LogError` and one in my global exception filter. Of course, in the model I am using (using a global exception filter), I can change my `.TrackException()` into `.LogError()`...
I would have considered this as a bigger change than what makes into a .1 upgrade...
