### ISSUE TITLE
[Question] How can I filter requests for some specific URLs?

### ISSUE THREAD

**Issue by johnsonlu** [Microsoft/ApplicationInsights-aspnetcore#398]
I'm using Application Insights on my ASP.NET core project. The project contains a health check endpoint, e.g. api/health, which just return a string "OK". The health check endpoint is only for the load balancer. 

Is it possible to filter the request for health check URL in this package?

**Comment by SergeyKanzhelev** [comment]
You need to configure custom telemetry processor. See the [docs](https://docs.microsoft.com/azure/application-insights/app-insights-api-filtering-sampling) on what processor is and how to use it.

@dnduffy may suggest on the right way to register telemetry processor in the ASP.NET Core
