### ISSUE TITLE
CorrelationIdLookupHelper is not using ConcurrentDictionary

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/ApplicationInsights-aspnetcore#404]
To try to prevent creating tasks to fetch appId concurrently, we introduced a ConcurrencyDictionary of iKeyTaskIdMapping. But the code is not preventing multiple task creation from happening.
```chsarp
if (!this.iKeyTaskIdMapping.TryGetValue(iKeyLowered, out taskId))
{
...
}
```
We should use TryAdd instead.

**Comment by cijothomas** [comment]
Closing this as correlation lookup is not part of this repo any more.
