### ISSUE TITLE
Create new functional tests for AspNetCore 2.0

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-aspnetcore#408]
We should have 2 more applications: NET46 + AspNetCore 2.0 and netcoreapp2.0 +AspNetCore2.0.

Tests should ensure basic scenarios with AI could work with AspNetCore 2.0:
- registration and dependency injection
- request and dependencies collection

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/526
