### ISSUE TITLE
Remove the use of Platform Abstractions

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#410]
See https://github.com/aspnet/Announcements/issues/237

Remove the use of it. Here is the mention I found: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/801cf8a79ad34588611f133bde9c7c59a57dc783/src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetEventSource.cs#L31

**Comment by Dmitry-Matveev** [comment]
@Eilon, is it something you think needs to be fixed for light-up scenario?

Without this fix, in Core 2.0:
- in the best case, the app name will be "Undefined + exception message" in the AI tracing events.
- in the worst case, if this runtime exception is not caught by some reason (although, it should not be), it'll be an crash in event source constructor.

The current version of AI ASP.NET Core SDK on Nuget.org has this Platform Abstraction dependency and as far as I know your team has already referenced that version of AI ASP.NET Core SDK for your scenarios (which might involve Core 2.0).

**Comment by SergeyKanzhelev** [comment]
CC: @glennc @qubitron

**Comment by Eilon** [comment]
I think it's good to fix this no matter what because that package no longer provides any real value.

I'm not sure how it would block the light-up scenarios specifically, though, because ultimately it's "just a package, so in theory it would just work.
