### ISSUE TITLE
Make adding Application Insights services and logger idempotent

### ISSUE THREAD

**Issue by glennc** [Microsoft/ApplicationInsights-aspnetcore#414]
If we lightup AI we need to be able to compose with the application adding AI. 

@pakrym

**Comment by glennc** [comment]
@dnduffy can we add this to the current beta and @pakrym will do a PR? If we don't fix it we will likely end up duplicating messages.

**Comment by dnduffy** [comment]
@glennc 
I was sure we already had an issue for this but now I can't locate it...
I didn't have time to implement this before leaving but if @pakrym submits a PR and you mail chucknorris and get it approved (@Dmitry-Matveev) and merged on Monday then presumably Cijo can build a beta3.  Although do take care with the versioning and dependencies matrix from the private build for @lmolkova.

**Comment by DamianEdwards** [comment]
I think this is done now.

**Comment by dnduffy** [comment]
It is.
