### ISSUE TITLE
v2.1.0-beta2 breaks WindowsAzure.Storage CreateIfNotExistsAsync

### ISSUE THREAD

**Issue by melvin2907** [Microsoft/ApplicationInsights-aspnetcore#416]
Not sure if this is the correct repo to raise this issue however i reasonably certain that some code in the Application insights is the culprit. 

When upgrading from version 2.0.0 of package Microsoft.ApplicationInsights.AspNetCore to version v2.1.0-beta2 calls to the CreateIfNotExistsAsync method on the CloudQueue object in WindowsAzure.Storage. Start failing with the following error. 

Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by henkmollema** [comment]
I'm seeing the same behavior after updating the NuGet package to 2.1.0-beta2.

**Comment by michielpost** [comment]
Same issue here. I'm using `services.AddDataProtection().PersistKeysToAzureBlobStorage` from `Microsoft.AspNetCore.DataProtection.AzureStorage`, it throws the same StorageException when rendering a form with an AntiForgeryToken.

**Comment by SergeyKanzhelev** [comment]
Hm, it seems that `DependencyTrackingTelemetryModule` was not initialized correctly. Azure queue should be exempt from headers modifications. See https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/198

I haven't tried this workaround, but I think you can get `DependencyTrackingTelemetryModule` from the list of services as `ITelemetryModule` and configure excluded domains. Something like this:

```
var modules = serviceProvider.GetServices<ITelemetryModule>();
var dependencyModule = services.FirstOrDefault<ServiceDescriptor>(t => t.ImplementationType == typeof(DependencyTrackingTelemetryModule));

var domains = dependencyModule .ExcludeComponentCorrelationHttpHeadersOnDomains;
domains.Add("core.windows.net");
domains.Add("core.chinacloudapi.cn");
domains.Add("core.cloudapi.de");
domains.Add("core.usgovcloudapi.net");
```

**Comment by SergeyKanzhelev** [comment]
@yantang-msft @lmolkova can you please take a look and confirm that this is the case

**Comment by maganuk** [comment]
I have the same issue. Went back to beta 1 and it works fine

**Comment by DamianEdwards** [comment]
Just confirming I'm seeing this too trying to use 2.1.0-beta2 in https://github.com/aspnet/live.asp.net/ [here](https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Services/AzureStorageLiveShowDetailsService.cs#L72).

**Comment by DamianEdwards** [comment]
The following workaround indeed works (put this in your `Startup.Configure` method):
``` c#
var modules = app.ApplicationServices.GetServices<ITelemetryModule>();
var dependencyModule = modules.OfType<DependencyTrackingTelemetryModule>().FirstOrDefault();

if (dependencyModule != null)
{
    var domains = dependencyModule.ExcludeComponentCorrelationHttpHeadersOnDomains;
    domains.Add("core.windows.net");
    domains.Add("core.chinacloudapi.cn");
    domains.Add("core.cloudapi.de");
    domains.Add("core.usgovcloudapi.net");
}
```

**Comment by SergeyKanzhelev** [comment]
@DamianEdwards thanks for confirmation.

@cijothomas when can we ship the update? This bug is nasty!

**Comment by henkmollema** [comment]
@SergeyKanzhelev applying your workaround resolves the issue for me as well. Thanks.

**Comment by cijothomas** [comment]
Included this in the 2.1 Beta3 release to be released sometime today.

**Comment by joergjo** [comment]
Please reopen this issue--you're still missing `127.0.0.1` (i.e. [Azure Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/storage-use-emulator)) as exception. The workaround is the same as above:


```
var dependencyTrackingTelemetryModule = telemetryModules.OfType<DependencyTrackingTelemetryModule>().FirstOrDefault();
if (dependencyTrackingTelemetryModule != null)
{
    dependencyTrackingTelemetryModule.ExcludeComponentCorrelationHttpHeadersOnDomains.Add("127.0.0.1");
}
```

**Comment by yantang-msft** [comment]
I'm not sure if adding localhost to the exclusion list by default is a good idea. You can at least add you custom domains in client code to workaround this issue.

**Comment by joergjo** [comment]
You're right--I forgot about scenarios where a service may call another service on localhost and it  should be tracked by AI. It would still be nice though to have this interdependency documented explictly (unless I missed that), or maybe even exclude endpoints instead of domains.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/488 - for emulator
