### ISSUE TITLE
Support setting request operation name based on executing Razor Page

### ISSUE THREAD

**Issue by DamianEdwards** [Microsoft/ApplicationInsights-aspnetcore#430]
Currently, the request telemetry doesn't construct a friendly operation name for requests served by Razor Pages in ASP.NET Core 2.0. The [`MvcDiagnosticsListener`](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/MvcDiagnosticsListener.cs) should be updated to grab details of the current executing page (if indeed it's a page) and use that to construct the request operation name, e.g. /Pages/Index.cshtml

**Comment by pakrym** [comment]
Why do you want page file name instead of it's action descriptor display name? (`/Index` in your case)

**Comment by DamianEdwards** [comment]
Good question. What do you think folks would find more useful? That's what it really comes down to.

**Comment by pakrym** [comment]
In case of pages having file name is nice, but it's very inconsistent with what we do for views.

**Comment by DamianEdwards** [comment]
But I think that makes sense given the different way the route info is constructed, i.e. from the page file.

**Comment by dnduffy** [comment]
Personally I would expect to see the route that a user sees rather than the backing implementation details but I don't know if that view is representative of other users.

**Comment by pakrym** [comment]
With file name operation name would look like `GET /Pages/Index.cshtml` and it looks like user requested actual file vs `GET /Index` if we use route values.

I implemented the route values way to start with, mostly because it's simpler and more consistent.

**Comment by DamianEdwards** [comment]
Fair enough.
