### ISSUE TITLE
Sampling and metrics stream configuration unavailable

### ISSUE THREAD

**Issue by DustinVenegas** [Microsoft/ApplicationInsights-aspnetcore#431]
The wiki lists [sampling and metrics stream](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream) as available options for Application Insights in .NET Core. 

In the _Sampling_ and _Metrics Stream_ sections, there are code samples showing how to configure these options using the `services.AddApplicationInsightsTelemetry(Configuration, aiOptions);` method. This extension method does not exist in the v2.0.0 release of Microsoft.ApplicationInsights.AspNetCore. 

How should users configure sampling and setup the metrics stream in ASP.NET Core using version v2.0.0 of Microsoft.ApplicationInsights.AspNetCore?

**Comment by dnduffy** [comment]
That particular API overload does exist in v2.1.0 so you can update to the latest beta release of 2.1.0 to use it.  Alternatively, you can either use the overload which takes a callback and pass it a lambda which sets properties you want or give it a lambda like this directly on the services.Configure method (works out to the same thing in the end):
```
            services.Configure((ApplicationInsightsServiceOptions o) =>
            {
                o.EnableAdaptiveSampling = false;
                o.EnableQuickPulseMetricStream = false;
            });
```
By default both sampling and metrics stream will be enabled under full framework targets (net451 and up).
To turn them off you can set the properties in the ApplicationInsightsServiceOptions objects to false as done in my example.
