### ISSUE TITLE
Documentation: update debugging not seeing data for .NET Core apps.

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#435]
Update [this](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-troubleshoot-no-data) page for .NET Core apps.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core docs are updayed.
