### ISSUE TITLE
Documentation: update getting started documentation.

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#436]
Need to update documentation about changed API's, UseApplicationInsights() vs. AddApplicationInsightsTelemetry(...), new functionality, etc.

**Comment by dnduffy** [comment]
#476

**Comment by cijothomas** [comment]
docs are here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core
