### ISSUE TITLE
Seeing only some dependencies in ASP.net Core app on .NET Framework

### ISSUE THREAD

**Issue by htuomola** [Microsoft/ApplicationInsights-aspnetcore#437]
I have an ASP.net Core web application which runs on full .NET framework (4.6.1). The site is hosted on Azure App Services. The code is calling Azure DocumentDB, Azure Redis, PostgreSQL (via Entity Framework 6 & Npgsql) and Elasticsearch and out of these, only the Elasticsearch HTTP calls are logged as dependencies (and shown in application map). Do I have some issues with config? I understood from #298 that it should work better. 

I'm using Microsoft.ApplicationInsights.AspNetCore version 2.0.0. and it's registered with `services.AddApplicationInsights(Configuration);`, settings contain only the instrumentation key. FWIW, I'm using VS 2017 and the new csproj project format.

**Comment by dnduffy** [comment]
On full framework I would expect more dependency success but perhaps the [2.2.0 dependency collector](http://www.nuget.org/packages/Microsoft.ApplicationInsights.DependencyCollector/2.2.0) referenced in version 2.0.0 of the SDK for .NET Core didn't support as much as I thought.  I'll have to check but I don't recall if all of those types are supported yet or not.
We added support for dependency collection in pure .NET Core in version [2.1.0-beta2](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.1.0-beta2) and have updated the versions of referenced SDK libs as well so please try upgrading to the latest 2.1.0-beta release and see if things improve.  If you still don't get more data we can start further investigation and debugging.

**Comment by dnduffy** [comment]
@SergeyKanzhelev Do you recall which dependency types are supported and which are not for full framework?

**Comment by htuomola** [comment]
After upgrading to 2.1.0-beta4 I am now seeing DocumentDB dependencies. Still no Azure Redis or Postgres. Not sure if for Postgres ([EntityFramework6.Npgsql](https://www.nuget.org/packages/EntityFramework6.Npgsql/) package) it's even expected. Redis is used via Microsoft.Extensions.Caching.Redis, which uses StackExchange.Redis.StrongName internally.

**Comment by SergeyKanzhelev** [comment]
We only support http for both - .NET Core and Full FW and SQL for full FW. DocumentDB will only be collected when it's using an http communication
