### ISSUE TITLE
2.1.0-beta2 breaks Azure Blog Storage (403)

### ISSUE THREAD

**Issue by oscarwest** [Microsoft/ApplicationInsights-aspnetcore#438]
After upgrading to 2.1.0-beta2 from 2.0.0 we start getting 403 on calls to Blog Storage.
After downgrading from 2.1.0-beta2 to 2.0.0 it works again without any additional changes.

Info:
netcoreapp1.0
"WindowsAzure.Storage": "7.2.1",

Error:
Breaks on if statement line
Response code 403
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

`
CloudBlobContainer blobContainer = blobClient.GetContainerReference(containerName);
CloudBlockBlob a = blobContainer.GetBlockBlobReference(fileName);
            if (await a.ExistsAsync() == false)
            {
                throw new InvalidOperationException("Could not retrieve blob");
            }
`

**Comment by SergeyKanzhelev** [comment]
Dup for https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/416 See workaround and update information there
