### ISSUE TITLE
EntityFrameworkCode dependencies

### ISSUE THREAD

**Issue by johnkwaters** [microsoft/ApplicationInsights-aspnetcore#440]
I heard that some recent version supports showing rudimentary SQL telemetry from a .net core app using entity framework core. Am using 2.1.0 beta 3. Not seeing anything. What do I do?

**Comment by SergeyKanzhelev** [comment]
There is an example on how to do it sits in older PR and we track this feature request here: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/522.

Feel free to contribute.

CC: @TomMilos

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query 
Closing this. SQL collection was enabled quite sometime back.
