### ISSUE TITLE
A TelemetryProcessor that is also a TelemetryModule is not Initialized

### ISSUE THREAD

**Issue by pharring** [Microsoft/ApplicationInsights-aspnetcore#447]
#445 introduced a way to set up TelemetryProcessors via DI.
If a TelemetryProcessor _also_ implements ```ITelemetryModule``` the base SDK will call ```Initialize``` on it.
We should do the same in aspnetcore.

**Comment by pharring** [comment]
@karolz-ms FYI

**Comment by pharring** [comment]
As a general comment, trying to replicate all the behaviors of the base SDK in this repo is a losing proposition. Can we consider exposing some of the internals of the telemetry pipeline (particularly the configuration factory) from the Base SDK - either by making them public or adding an "InternalsVisibleTo" from the base SDK to this one?

**Comment by karolz-ms** [comment]
@pharring So do you think we should implement this behavior to unblock SnapshotCollector while using this issue to track the more comprehensive resolution?

**Comment by pharring** [comment]
@karolz-ms yes, I think so.
