### ISSUE TITLE
Add loggerfactory method without a IServiceProvider

### ISSUE THREAD

**Issue by bklooste** [microsoft/ApplicationInsights-aspnetcore#451]
One issue with the logger factory extention method is you cant get logs before startup is run which is ofetn when its most critical esp in MicroServices  .. you want them like the first 2 lines of Program.cs

So instead of  public static ILoggerFactory AddApplicationInsights(
            this ILoggerFactory factory,
            IServiceProvider serviceProvider,
            

adding a method that goes  public static ILoggerFactory AddApplicationInsights(
            this ILoggerFactory factory, Telemtry client)   

Note Action<IServiceCollection> servicesAction can be used before  Startup and then passed to the builder.

**Comment by cijothomas** [comment]
Closing as loggerfactory methods are obsolete, and new logging provider is shipped.
