### ISSUE TITLE
Question: v2.1-beta4 How can I restrict what HTTP requests App Insights tracks?

### ISSUE THREAD

**Issue by billpratt** [Microsoft/ApplicationInsights-aspnetcore#456]
I have an app that sends all logs to a remote log collector using HTTP. When I upgraded to v2.1-beta4 I noticed these requests are being tracked by application insights. Is there a way to restrict these http requests from being tracked to reduce bandwidth while not affecting the metrics I care about?

**Comment by yantang-msft** [comment]
See if this solve your problem
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/416

**Comment by dnduffy** [comment]
Reposting @DamianEdwards answer from #416:
Put this in your `Startup.Configure` method:
``` c#
var modules = app.ApplicationServices.GetServices<ITelemetryModule>();
var dependencyModule = modules.OfType<DependencyTrackingTelemetryModule>().FirstOrDefault();

if (dependencyModule != null)
{
    var domains = dependencyModule.ExcludeComponentCorrelationHttpHeadersOnDomains;
    domains.Add("core.windows.net");
    domains.Add("core.chinacloudapi.cn");
    domains.Add("core.cloudapi.de");
    domains.Add("core.usgovcloudapi.net");
}
```

**Comment by billpratt** [comment]
@dnduffy I cannot get that to work. I have tried adding the suggested into my application with no luck. I then created a new web project and added a simple HTTP GET to www.google.com. I see the dependency in Visual Studio's Application Insights logs both when I exclude *www.google.com* and include it.

Startup.cs

```
namespace WebApplication24
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry(Configuration);

            // Add framework services.
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            var modules = app.ApplicationServices.GetServices<ITelemetryModule>();
            var dependencyModule = modules.OfType<DependencyTrackingTelemetryModule>().FirstOrDefault();

            if (dependencyModule != null)
            {
                var domains = dependencyModule.ExcludeComponentCorrelationHttpHeadersOnDomains;
                domains.Add("www.google.com");
            }

            app.UseMvc();
        }
    }
}
```

ValuesController.cs

```
namespace WebApplication24.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public async Task<IEnumerable<string>> Get()
        {
            using (var client = new HttpClient())
            {
                await client.GetAsync(new Uri("http://www.google.com"));
            }
            

            return new string[] { "value1", "value2" };
        }
    }
}
```

Application Insights Logs
![screenshot at may 30 16-24-53](https://cloud.githubusercontent.com/assets/2847527/26603384/b401ba3a-4554-11e7-8bd7-a3fffbb3dd68.png)

**Comment by BorisWilhelms** [comment]
@billpratt : AFAIK this disables only the attaching of correlation id headers. If you want to disable DependecyTracking completely you have to use the following code in your ConfiureService Method

```
var module = services.FirstOrDefault(t => t.ImplementationFactory?.GetType() == typeof(Func<IServiceProvider, DependencyTrackingTelemetryModule>));
if (module != null)
{
    services.Remove(module);
}
```

This disables DependecyTracking **completly**.

**Comment by billpratt** [comment]
I dont want to disable dependency tracking completely. I would like to restrict what dependencies Application Insights tracks.

**Comment by BorisWilhelms** [comment]
This is afaik currently not possible?!

**Comment by billpratt** [comment]
@dnduffy @yantang-msft Any ideas?

**Comment by yantang-msft** [comment]
@billpratt Sorry for the confusion. Yes, ExcludeComponentCorrelationHttpHeadersOnDomains only disable injecting CorrelationId in http headers.
For your question, we hard coded to not track AI requests as dependency, but don't have an option for custom exclusion list yet.
@dnduffy @SergeyKanzhelev is this something we can think about in the next release?

**Comment by SergeyKanzhelev** [comment]
Use [telemetry processors](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#filtering-itelemetryprocessor) to filter out unwanted data.
