### ISSUE TITLE
Server-side sampling is broken with ASPNET Core SDK. 2.0+

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-aspnetcore#457]
ASP.NET Core SDK 2.0+ generates sequential operation IDs that result into non-uniform distribution when IDs are converted into server-side hash codes for sampling. Sampling algo that we are using requires that operation IDs are random, not just unique.

**Comment by dnduffy** [comment]
This has been resolved with the updated build of [DiagnosticSource](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Diagnostics.DiagnosticSource/4.4.0-preview2-25330-01).
The Id's from the diagnostic source are still not random but they are sequential in the middle of the {x:8}-{x:16} string (e.g. 4c25b178-5a48cd6132f9d68a22bc -> 4c25b179-5a48cd6132f9d68a22bc) and this causes the server side sampling hashing to perform as expected.
