### ISSUE TITLE
Need to enable adaptive sampling for pure .NET Core apps.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#458]
The functionality exists in the base SDK in the AdaptiveSamplingTelemetryProcessor and needs to be made available for pure .NET Core apps.

**Comment by SergeyKanzhelev** [comment]
This task requires port of the project containing this file: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/TelemetryChannels/ServerTelemetryChannel/Shared/AdaptiveSamplingTelemetryProcessor.cs
