### ISSUE TITLE
Resilient transmission support is needed for pure .NET Core apps

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#459]
The functionality exists in the base SDK in the ServerTelemetryChannel which needs to be ported or made generic enough to reuse in .NET Core without needing the "full" .NET framework.

**Comment by cijothomas** [comment]
@iusafaro is working on this

**Comment by cijothomas** [comment]
Completed with https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/530
