### ISSUE TITLE
Add additional dependency collection for Linux (beyond HTTP).

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#462]
I believe that currently we only support HTTP dependencies but it would be good to add additional support as available.

**Comment by cijothomas** [comment]
So far all dependencies are tracked same in Windows and Linux. Closing as there is no action needed.https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#i-run-my-application-in-linux-are-all-features-supported-in-linux-as-well
