### ISSUE TITLE
[Question] How should reverse proxy be handled in application insights

### ISSUE THREAD

**Issue by mkosieradzki** [Microsoft/ApplicationInsights-aspnetcore#463]
Let's consider following scenarios:
1. 
We have a public site: https://mydomain.com
It is handled locally by http://localhost:1234

Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware middleware is used to override Host, Port and Scheme.

Application Insights for ASP.NET Core are printing following events:
Microsoft.ApplicationInsights.Message, Microsoft.AspNetCore.Hosting.Internal.WebHost, http://localhost:1234, Connection id \"0HL552DLRQAR8\" completed keep alive response.

and then:
Microsoft.ApplicationInsights.Request, with url: https://mydomain.com

In case HttpMethodOverrideMiddleware would recover original values for scheme, host, port,  after calling next() - both places would show http://localhost:1234

Now my question is: is this behavior (url inconsistency) breaking some correlation stuff in analytics? Should this middleware be fixed to use original urls?

Or maybe Microsoft.ApplicationInsights.Request tracked separately and this is perfectly OK?

2. Let's assume we have handled above case in a manner that AI should display https://mydomain.com

Service Fabric is prepending services url paths with some guids to guarantee that service instances are NEVER mistaken. So going back to our example:
We have a public site: https://mydomain.com/mypath
It is handled locally by http://localhost:1234/{some guid}/{some guid}/mypath

Which url do we want to see in Microsoft.ApplicationInsights.Request? My guess would be that https://mydomain.com/mypath. Am I right?

If someone can confirm the intended behavior I will be creating a proper PR for the Service Fabric ASP.NET Core library to make this work properly.

**Comment by dnduffy** [comment]
1. It does not break correlation because the correlation is based on an Id (which is passed in a header so dependencies which are also instrumented can pick it up and set as their parent operation).

2. You will see the URL that was provided by the proxy, this might be the localhost URL, it depends on the proxy and what headers it sets and if the outside URL can be extracted from a header by later processing.

**Comment by mkosieradzki** [comment]
Thanks @dnduffy, we are already progressing with the second issue in Microsoft/ApplicationInsights-ServiceFabric#13.
