### ISSUE TITLE
How do you connect this package to the ASP.Net Core injected LoggingFactory?

### ISSUE THREAD

**Issue by timomta** [Microsoft/ApplicationInsights-aspnetcore#467]
Based on this: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core

How do you connect this package to the ASP.Net Core injected LoggingFactory?
My goal is for the Core provided ILogger to log to Application Insights.
I'm not clear on how to do that from the above link.

**Comment by dnduffy** [comment]
There are ILoggerFactory extension methods named AddApplicationInsights.
Calling one of these will add App Insights as a provider.

**Comment by timomta** [comment]
It would be extremely helpful if you documented your intended usage of this package for ASP.Net Core. There is extensive documentation for ASP.Net, but it doesn't seem like there is much for Core yet. A 'soup-to-nuts' sample (concrete/specific) for Core similar to what is shown here would really help folks get off the ground with this: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging

**Comment by dnduffy** [comment]
@timomta Agreed, see #436.

**Comment by timomta** [comment]
Thanks @dnduffy !
