### ISSUE TITLE
Where and how do you handle filtering in ASP.Net Core?

### ISSUE THREAD

**Issue by timomta** [Microsoft/ApplicationInsights-aspnetcore#468]
Based on this: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core
and this
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure

Where and how do you handle filtering in ASP.Net Core?
For example, it this package appears to push a large number of trace events up to Application Insights, which can cause performance issues under heavy load. Where does filtering go (assuming somewhere in appsettings.json, like the AI key) to trim some of this down?

**Comment by dnduffy** [comment]
You can add a telemetry processor to drop telemetry items you don't want.
You can use sampling to only collect a percentage of the possible data.
The .NET Core SDK does not configure much through config files but rather is configured programmatically, often through dependency injection.
Some simple settings are available by calling the AddApplicationInsightsTelemetry extension method.
If you want to reconfigure an existing processor you can get it through dependency injection.

**Comment by dnduffy** [comment]
https://docs.microsoft.com/azure/application-insights/app-insights-api-filtering-sampling

**Comment by timomta** [comment]
It would be extremely helpful if you documented your intended usage of this package for ASP.Net Core. There is extensive documentation for ASP.Net, but it doesn't seem like there is much for Core yet. A 'soup-to-nuts' sample (concrete/specific) for Core similar to what is shown here would really help folks get off the ground with this: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging
