### ISSUE TITLE
If TelemetryKey is not stored in root appSettings.json or appSettings.environment.json startup fails

### ISSUE THREAD

**Issue by pwiens** [microsoft/ApplicationInsights-aspnetcore#469]
The DI change between beta4 and beta5 causes application startup to fail because no instance of ApplicationInsightsInitializer is registered. To repro, move the instrumentation key to some other config file.

**Comment by dnduffy** [comment]
I cannot repro this with 2.1.0-beta5 nor with 2.0.0 stable.
What platform are you running on and what version of the .NET Core CLI are you running on?
Also, can you please provide a simple test app where this problem occurs?

You should see "unconfigured" telemetry messages like the following when there is no ikey present:
```Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message",...```
But it should not fail to startup.

**Comment by pwiens** [comment]
My bug description is incorrect. We're using StuctureMap for our DI container and that's what is causing the startup failure. Sample project is here: https://github.com/pwiens/ApplicationInsightInitError

Here's what ConfigureServices looks like in our case:
```C#
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry(this.Configuration);
    services.AddMvc();

    var container = new Container();
    container.Configure(c=>c.Populate(services));
    return container.GetInstance<IServiceProvider>();
}
```
This code works fine with beta4.

**Comment by pwiens** [comment]
Figured out the issue but am not sure what the best way to fix it is.

The core of the problem is that StructureMap will happily resolve concrete types if it thinks it can. So doing something like

```c#
var container = new Container();
var processorConstructors = container.GetAllInstances<Func<ITelemetryProcessor, ITelemetryProcessor>>();
```

will give you a list with one item. This is probably a bug in StructureMap but ApplicationInsights should probably have something a bit better than the current process for hooking up the processor pipeline.

**Comment by glennc** [comment]
@dnduffy Is this the same bug we pushed that fix in for the last update? Allowing the SDK to work with StructureMap better?

**Comment by pwiens** [comment]
@glennc please link to bug, I can confirm if it fixes my issue.

**Comment by cijothomas** [comment]
Closing old issue. Reopen is anyone facing this in newer version.
