### ISSUE TITLE
Add performance collector module for aspnet.core

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-aspnetcore#470]
At present, performance collector module exists only if run against full framework. (means there won't be any counters collected when running in linux/mac)

The proposal is to modify performance collector to run in pure .net core, collecting perf counters the usual way from windows environments, and implementing new way to collect counters from unix environments. The new way would be similar to how perf counters are collected from Azure Web Apps - instead of reading the special ENV variables exposed by Azure WebApps,  we can linux specific commands like netstat etc.

**Comment by dnduffy** [comment]
This is kind of the same as #460.

**Comment by dnduffy** [comment]
Note that there is no support for performance counters even on Windows in .NET Core.

**Comment by JonasSamuelsson** [comment]
Do you have an updated eta on this one, this really hinders us from migrating from aps.net to asp.net core as we loose a lot of insights in how our apis are behaving.
We are running on windows so for us getting this working there would be a great start.

And more generally, how is progress of this entire coming along, both beta1 & beta2 has passed their due dates...

**Comment by cijothomas** [comment]
@JonasSamuelsson Application Insights does not collect perf counters on asp.net core, because .net core does not have a concept of Performance Counters yet. Once .net core provides this feature, application insights will surely support it. There are several discussions on dotnet core Github repo about perf counters support ..like 
https://github.com/dotnet/corefx/issues/3906
https://github.com/aspnet/Home/issues/1319

**Comment by cijothomas** [comment]
@JonasSamuelsson Regarding releases of next version. Apologies for not updating the release dates, we (and other ApplicationInsights sdk which this depends on )faced certain infra issues that caused the delay.
Version 2.2.0-beta1 is undergoing final internal testing, and is going to be in nuget this week/next monday.
A lot of new features are added, as indicated here:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/CHANGELOG.md

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/ Need to look at this to see if we can support perf counters in netstandard.

**Comment by johnjbateman** [comment]
I would greatly appreciate this.  Running Linux containers and I cannot see perf counters because it is dotnet core.

**Comment by aligneddev** [comment]
Looks like it will be [released in 2.4.0](https://github.com/Microsoft/ApplicationInsights-aspnetcore/milestone/34)!

**Comment by cijothomas** [comment]
@aligneddev https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/CHANGELOG.md#version-240-beta1
What's part of 2.4.0 release is support for perf counters when application is running on Azure Web Apps.  If you are on Azure Web Apps, you will be able to see counters, but not in linux yet.

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/4.5.0 - Now that System.Diagnostics.PerformanceCounter stable is out, we may want to conside modifying ApplicationInsights to use this, and start supporting counters for asp.net core apps.

**Comment by nhart12** [comment]
I got this working in an ASP.net core 2 project as a quick workaround by forking ApplicationInsights-dotnet-server and adding a netstandard 2.0 target & having a conditional reference to the above nuget (https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/4.5.0) to the Perf project. The commit is here  https://github.com/nhart12/ApplicationInsights-dotnet-server/commit/123b97aa78185eca24b24b7b8c841f7581acf72d

**Comment by rh78** [comment]
@nhart12 will this then also work for Linux or is all of this pure Windows again?

**Comment by cijothomas** [comment]
@rh78 The above is windows only.

@nhart12 Would you like to contribute this to the official branch by submitting a PR ? We can help with any guidance required here.

**Comment by rh78** [comment]
@cijothomas OK is there an issue that is being tracked for Linux?

**Comment by cijothomas** [comment]
@rh78 This issue is for both linux/windows. 
Sorry what i meant in above comment was that the solution by @nhart12 using https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/4.5.0 is a windows only one.

**Comment by rh78** [comment]
@cijothomas OK cool thank you - is there an estimate on when we can expect tracking support for CPU/memory/etc. on Linux?

**Comment by cijothomas** [comment]
The team has work planned to collect process level counters for all platforms (linux+windows) by June/July 2019 time frame. We are working with the .net core team to align with their future plans for counters in general. Will share more info as we start working on this and this is only an estimated date now.

**Comment by rh78** [comment]
It's a tragedy. It renders AI useless for production use as a monitoring tool, because stats are only meaningful when being accompanied with low level stats as CPU and memory consumption. I am looking forward for a change - all the best!

**Comment by nhart12** [comment]
> @rh78 The above is windows only.
> 
> @nhart12 Would you like to contribute this to the official branch by submitting a PR ? We can help with any guidance required here.

I created PR over here. I'm sure there is more to be done to target netstandard 2.0 on some of the other projects, but this got it working for me.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/1148

**Comment by cijothomas** [comment]
@nhart12 's PR is merged and will be released as beta3

**Comment by twurm** [comment]
@cijothomas we've upgraded one of our web applications to beta3, we see CPU and RAM information for Kestrel hosted applications, but not when they are deployed to IIS.  Is this expected?  I was hoping we would get that information no matter how the web server.

**Comment by cijothomas** [comment]
@twurm No its no expected. Perf Counters should work irrespective of Web Server. Can you create a new issue to track this better? Please include as much details as you can share.

**Comment by nhart12** [comment]
@twurm make sure the user the app pool is running as has access to perf counters

**Comment by twurm** [comment]
@nhart12 that's probably the problem, we are running the app pools as: ApplicationPoolIdentity.  I'll take a look on Monday.

**Comment by cijothomas** [comment]
thanks @nhart12.
@twurm The #1 reason i've found related to perf counter not working is permission issue. I am wondering why SDK didnt sent a error trace to your ikey, stating "i am having trouble reading perf counter". Please respond back when you get time if permission issue fixed your case.

**Comment by cijothomas** [comment]
This is addressed for Windows in 2.7. Closing this.
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/875 This issue tracks the X-Platform performance counters work.
