### ISSUE TITLE
Add test infrastructure for running automated tests on .NET Core 2.0.0 in addition to 1.x

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#471]
Currently we run on a 1.x platform when we build and test, we need to run the tests on a 2.x platform also to catch breaking changes in newer builds of .NET Core.

**Comment by dnduffy** [comment]
#408

**Comment by dnduffy** [comment]
A couple options are:
- download different versions of .NET Core CLI and unzip them side by side and run the tests with each version.
- run functional tests in separate containers (e.g. Kubernetes) with different .NET Core CLI versions.

**Comment by cijothomas** [comment]
We have net 2.0 apps and runtime now. closing this issue.
