### ISSUE TITLE
Is there a global exception handler?

### ISSUE THREAD

**Issue by trailmax** [Microsoft/ApplicationInsights-aspnetcore#476]
I'm trying replace ELMAH with and log all exceptions in AppInsights. I've followed all the instructions and have `app.UseApplicationInsights()` in `Program` class of my aspnet core web application. 

Yet when I look on failures in Azure portal I get this suggestion: 
![2017-06-16 22_01_02-getting started - microsoft azure](https://user-images.githubusercontent.com/3606356/27244640-5706bab8-52df-11e7-9513-b1f4c0684d21.png)

Is default configuration not enough to see all exception details? Do I need to add additional middleware that does ` telemetryClient.TrackException(ex)` ? Is there such thing already written (and I'm just blind and can't see it)? Should I write one myself?

**Comment by dnduffy** [comment]
Exception tracking is built in, we do need to update more documentation.
Sorry for the confusion.

**Comment by trailmax** [comment]
OK, thanks for confirming. I've tried to add a `telemetryClient.TrackException(exception);` in a global middleware and nothing changed in the portal, so it was logging all it could already.

**Comment by dnduffy** [comment]
@trailmax If you do a test by throwing an unhandled exception from somewhere in your service or web app you should see it reported in the portal.

**Comment by trailmax** [comment]
Yes, it is reported, only I still get a suggestion from Azure portal to do `TrackException` - see the screenshot above. I guess this is Azure portal deceiving  me.

**Comment by dnduffy** [comment]
@trailmax Right, that is part of the documentation updates needed.

**Comment by Eneuman** [comment]
Also please document if `loggerFactory.AddApplicationInsights` is needed and if soo, what does it acually do/add to my code.

Also, if I just want to use AI local debug (not send to azure) but use AI in production, whats the best practice. And keep in mind that "Azure App Services AI Inject" does not work for us Service Fabric users ;)
