### ISSUE TITLE
Application Insights not using settings from appsettings.{env.EnvironmentName}.json

### ISSUE THREAD

**Issue by saluce65** [Microsoft/ApplicationInsights-aspnetcore#477]
In Visual Studio 2017 (15.2.26430.13), I am attempting to use different Application Insights resources for different environments, however, no matter what InstrumentationKey I put into any appsettings.*.json file, it will not read that key and will only use the key found in appsettings.json.

Steps to reproduce:
1.  Create a new ASP.NET Core Web Application (.NET Framework)
2.  Add Application Insights to project
3.  Move the InstrumentationKey from appsettings.json to appsettings.Development.json
4.  Build and run the application

Expected result:
    Trace log should should sending information using the Instrumentation Key.

Actual result:
    Trace log shows (unconfigured) for the instrumentation key.

**Comment by saluce65** [comment]
I've managed to work around it by adding `services.AddApplicationInsightsTelemetry(this.Configuration);` to Startup.cs, but I don't think I should have to do that to get differential InstrumentationKey to work out of the box.

**Comment by dnduffy** [comment]
Which version of the SDK are you using?
This is fixed in the latest beta (2.1.0-beta6).
