### ISSUE TITLE
Cannot add AppInsights to a web app targeting ASP.NET Core 2.0

### ISSUE THREAD

**Issue by moozzyk** [Microsoft/ApplicationInsights-aspnetcore#478]
![image](https://user-images.githubusercontent.com/1438884/27300144-7fda89a0-54e3-11e7-9835-cf45faecd0a8.png)

Note that this is out-of-the-box experience - Create a new web application targeting ASP.NET Core 2.0 and try to add app insights.

The problem is that VS is trying to add the Microsoft.ApplicationInsights.AspNet.Core.2.1.0-beta5 package but the application already has the Microsoft.ApplicationInsights.AspNet.Core.2.1.0-beta6 package pulled transitively: Microsoft.AspNetCore.All (2.0.0-preview2-final) ->Microsoft.AspNetCore.ApplicationInsights.HostingStartup (2.0.0-preview2-final) -> Microsoft.ApplicationInsights.AspNetCore (2.1.0-beta6)

VS: 26615.5.d15prerel

Note that despite the failure Output shows that Application Insights was added successfully to the project:

![image](https://user-images.githubusercontent.com/1438884/27300182-a9ce06c4-54e3-11e7-8fe3-351846d41f60.png)

and the project is, I think, in a kind of limbo state - the add application insights option is gone from menu, I have a few new files in my project but I don't think everything is setup correctly.

/cc: @pakrym @danroth27

**Comment by gardnerjr** [comment]
Where did this `Microsoft.ApplicationInsights.AspNet.Core.2.1.0-beta6` come from?  the newest one on nuget is beta5, the one the VS extension knows about.

FYI, if app insights *did* get added, then all of the menu items might have moved on you.  the VS client team made us move all of our context menu items to only appear if you right click on application insights inside the connected services folder of the project.  so try looking there and see if you see the standard "configure application insights" and other AI related items there?

Does your project still *work* in this state?  I was under the impression that a new ASP.NET core 2.0 project would *not* have application insights installed by default anymore.

**Comment by pakrym** [comment]
We got it from https://myget.org/feed/applicationinsights/package/nuget/Microsoft.ApplicationInsights.AspNetCore

**Comment by gardnerjr** [comment]
Prior releases of asp.net core 2.0 were *not* installing the application insights packages (even transitively) as part of project setup or build.  it was only getting included at "runtime" in the hosting startup stuff. did something change here, either in asp.net core or in the package management?

**Comment by moozzyk** [comment]
This is the feed we are using to verify 2.0.0-preview2 release which contains the beta6 package: https://dotnet.myget.org/gallery/dotnet-2-0-0-preview2-final/

I see - I can confirm that I can see "Add Application Insights" option when I right click on Application Insights in the Connected Services. On the other hand the Application Insights folder contains also "Gettting Started" item which does not have a backing file. 

The application runs but I don't see any App Insights related log entries in the Debug output.

**Comment by moozzyk** [comment]
I did not notice - Getting Started opens in browser...

**Comment by danroth27** [comment]
@glennc

**Comment by dnduffy** [comment]
My apologies, I was not expecting the beta6 build to get released like this.  @gardnerjr it is on nuget.org now but I was not aware that your team would need to pick it up if the .NET Core team bundled it into their preview.  My expectation was that you would still pick up the stable release at the end of the month as planned previously and not need anything else until then.

**Comment by gardnerjr** [comment]
What version of the Asp.net Core tools is this from?  preview 2 isn't up yet, is it?  how/where do i get this build?

**Comment by moozzyk** [comment]
@gardnerjr - https://github.com/aspnet/Release/issues/144

**Comment by gardnerjr** [comment]
@moozzyk i get a 404 for that link.  internal repo?

**Comment by moozzyk** [comment]
Oops, yes it's private. I will provide you details tomorrow morning.

**Comment by dnduffy** [comment]
This is being addressed offline in emails.

**Comment by vRITHNER** [comment]
I also can't add it to my solution with dotnet version 2.0.0-rtm-26343 | VS version 15.3.0 Preview 4.0

![2017-07-21_13h30_37](https://user-images.githubusercontent.com/238842/28462993-4ba256f0-6e1e-11e7-84dc-281f46396e4d.png)

**Comment by gardnerjr** [comment]
That message is saying specifically that package restore failed.  That would happen in nuget before it tries to install the AI package.  can you successfully build/restore before adding AI?  also, is there any install output either in a nuget output window or in a connected services output window?  that might have more details.

**Comment by joperezr** [comment]
I'm not sure if this comment might have to go to a new issue, but I just hit a similar problem when trying to install AI into a WebApi using VS Code's AI extension. Basically I get an error saying that AI isn't supported on my project.

**Comment by SergeyKanzhelev** [comment]
@gardnerjr worth re-opening this issue to investigate the VS Core behavior? Or it's a known behavior?

**Comment by gardnerjr** [comment]
the VS code extension and VS extension are completely unrelated to each other.  there's no "core" that the 2 platforms share.  the AI VS Code extension hasn't been updated to support asp.net core 2.0, so you'll have to manually add nuget packages/etc there.

**Comment by joperezr** [comment]
@gardnerjr is there a link somewhere of the manual steps I have to take? It's probably faster than installing full VS 😄

**Comment by gardnerjr** [comment]
not sure if this has been updated specifically for asp.net core 2.0, but all the standard instructions are here:
[https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started)

**Comment by danroth27** [comment]
@gardnerjr @glennc @Rick-Anderson Those instructions need to be updated for ASP.NET Core 2.0. In 2.0 we now "light up" App Insights support without you having to manually adding any NuGet packages or code. Also, the project.json based project system has gone the way of the Dodo. We should probably get rid of this wiki page and instead point people to the official ASP.NET Core 2.0 docs (as soon as they are available).

**Comment by gckeller-ps** [comment]
You all may find this issue interesting and informative: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/847
