### ISSUE TITLE
No default instance for type Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor when using 3rd party IoC/DI container.

### ISSUE THREAD

**Issue by f1xxxer** [Microsoft/ApplicationInsights-aspnetcore#482]
When App Insights package is added to project which is using 3rd party IoC/DI container (StructureMap in my case) it is falling with error `StructureMapConfigurationException: No default instance or named instance 'Default' for requested plugin type Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor`

Solution is to add your own custom dummy processor and then everything works, but i assume that shouldn't be the default behavior for the package?

My environment:

Microsoft Visual Studio Professional 2017 Preview (2)
Version 15.3.0 Preview 2.1

<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;dnxcore50;portable-net45+win8</PackageTargetFallback>
      .........
      .........
  </PropertyGroup>
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />

**Comment by paule96** [comment]
Hi Guys,

we have the same problem with our project. This is only a Problem in the newest Visual Studio preview.
If we use the console with dotnet run it will works fine. 

Maybe it's help to find the problem.

**Comment by DamianEdwards** [comment]
Interesting. Does this only happen when launching in VS under the debugger? Do you have a reference to the AppInsights SDK package in your project? Could you share your project's CSPROJ file here?

**Comment by kirkone** [comment]
Hi,

here is an example .csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0-preview2-final" />
    <PackageReference Include="StructureMap.Microsoft.DependencyInjection" Version="1.3.1" />
  </ItemGroup>

...

</Project>
```

I stripped out the "Microsoft.AspNetCore.All" package and added only the references to run our project.  
I can build in VS and with `dotnet build` with no errors.
When I run the project in VS (no matter with IIS or kestrel) I get this error:
```
No default instance or named instance 'Default' for requested plugin type Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
```
I testet run with debugging and without debugging, same result.

Running the project with `dotnet run` works fine.

I hope this will help a bit.

**Comment by f1xxxer** [comment]
For me it happens in VS2015 under debug as well.

I did some debugging and problem happens on initialization of TelemetryConfiguration in TelemetryConfigurationOptionsSetup class.

In fact, the error happens in referenced ApplicationInsights 2.4.0 package https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChainBuilder.cs in Build() method.

I will take more close a bit later when i have time.

**Comment by arishlabroo** [comment]
`Solution is to add your own custom dummy processor and then everything works, but i assume that shouldn't be the default behavior for the package?` 
How do you achieve this @f1xxxer ? I was not able to bind a dummy implementation of ```ITelemetryProcessor ```

**Comment by pharring** [comment]
@arishlabroo Can you upgrade to version 2.1.1 where this issue has been fixed?
