### ISSUE TITLE
Changing the minimum log level at runtime

### ISSUE THREAD

**Issue by fleed** [Microsoft/ApplicationInsights-aspnetcore#487]
Is there a way to change the minimum log level at runtime? I'd like to be able to set the current log level from an action in a Asp.net core controller, so that I can diagnose issues without redeploying the application (it is running under Azure Service Fabric).
Thank you

**Comment by SergeyKanzhelev** [comment]
You can implement it on multiple levels.

1. Wrap every TrackTrace call into your custom wrapper that can be controlled from outside. This wrapper will check severity and filter out unwanted traces.
2. Use log adaptors for Log4Net, SeriLog or whatever you like. Control how much trace they emit using their native APIs. In this case Application Insights will only receive traces you configured 
3. Create a [telemetry filter](https://docs.microsoft.com/azure/application-insights/app-insights-api-filtering-sampling#filtering-itelemetryprocessor) that will filter out traces based on severity. Control this processor in any way you'd like. 

First approach is simplest and most performant, but has very limited use.

Second approach allows to trace verbose log into file while Error logs are sent to Application Insights. You pay for conversion from traces to application Insights events for events that will be send to AI.

Third approach is heaviest as you always convert strings to AI events. The benefit is that you can place [Live Stream](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream) processor BEFORE this filter and get ALL traces while looking at telemetry "live". So you have more power troubleshooting ongoing issues.

**Comment by SergeyKanzhelev** [comment]
Please re-open if you need more details. Create a user voice suggestion if you have more sophisticated scenario on mind: http://aka.ms/aiuservoice

**Comment by leftside** [comment]
Would be nice if this could be configured via an app insights config file.

**Comment by SergeyKanzhelev** [comment]
You can do it via config, It will look like this:

``` xml
<TelemetryProcessors>
  <Add Type="ApmTips.SeverityLevelFilter, ApmTips.dll">
    <SeverityLevel>Warning</SeverityLevel>
  </Add>
  <!--OTHER PROCESSORS-->
  <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
  <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
  </Add>
<!--OTHER PROCESSORS-->
</TelemetryProcessors>
```

More on Application Insights config extensibility you can read [here](http://apmtips.com/blog/2015/02/06/more-on-applicationinsights-dot-config/)

**Comment by fleed** [comment]
Thank you for suggestions, @SergeyKanzhelev 
I think that both Serilog and telemetry filter are valid options. Especially the second one, I didn’t know about it until now.
I still think that especially in asp.net core this should be kind of “out of the box”, but I like and accept your detailed  answer.

**Comment by leftside** [comment]
Thanks for the suggestions. We're going to further investigate Serilog. It looks very promising.

**Comment by leftside** [comment]
Just an update: Serilog + ASP.NET Core + Application Insights works great.

**Comment by SergeyKanzhelev** [comment]
@leftside glad to hear that!
