### ISSUE TITLE
Add scopes support to AI logger

### ISSUE THREAD

**Issue by pakrym** [Microsoft/ApplicationInsights-aspnetcore#491]

**Comment by Tadimsky** [comment]
Any update on this issue? BeginScope clearly is not doing anything :)

    public IDisposable BeginScope<TState>(TState state)
    {
        return null;
    }

**Comment by davidfowl** [comment]
@SergeyKanzhelev can we get some movement on this? It means that you're missing a bunch of useful properties.

/cc @pakrym @glennc

**Comment by cijothomas** [comment]
@Dmitry-Matveev Lets triage and prioritize this issue in our next planning. There are a bunch of items in Logging area itself.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/labels/logging

**Comment by davidfowl** [comment]
Feel free to pull in anyone from the ASP.NET Core team about if there are questions about why this is important.

**Comment by Dmitry-Matveev** [comment]
@cijothomas, I'd add it to 2.3 due to high demand (apparently, half ASP.NET Core team up voted the issue :)). However, that would mean we've got only 9 days to take a look into this. So, I assume this can land in the beta we release in May instead. What's the amount of the work expected here?

**Comment by pharring** [comment]
For the uninitiated, can someone (@pakrym, @davidfowl ?) write up a brief description of this feature and what user-scenarios it enables?

**Comment by davidfowl** [comment]
Logging scopes allow users to attach extra properties (key value pairs) to all logs within that scope. So for example ASP.NET Core itself creates a request scope with a bunch of properties that get attached to every log within a request (request id, correlation id, http connection id). ASP.NET Core MVC creates another scope to attach properties that correlate to the current action. ASP.NET Core SignalR (in 2.1) creates a scope that attaches metadata bout the websocket connection. 

All of this to say, it's a way to add custom properties within an "async local scope". Today when you use this feature, AI doesn't get any of these extra properties resulting in a loss of rich logging information.

**Comment by cijothomas** [comment]
Tagging for 2.4 milestone, though not sure if we have man-hours available !

**Comment by ruimsft** [comment]
This is a very important feature to support ILogger<T>. To return null means we cannot use AppInsights for our logger.

**Comment by gursin87** [comment]
Is this available in the latest beta of 2.4?

**Comment by cijothomas** [comment]
@gursin87 Unfortunately this has not landed in 2.4.0 due to other commitments. Tagging for 2.5.0 release.

**Comment by profet23** [comment]
This is really important. Any updates?

**Comment by profet23** [comment]
Also curious what the implementation would look like for AppInsights.

I would expect that if you're sending an `IDictionary` it would simply append all key/value pairs as custom metrics to all telemetry in scope.

It might also be nice to have it create a new level to all telemetry below it by creating a new telemetry item with a new id and then giving telememtry in scope that as a operation_ParentId.

**Comment by zippy1981** [comment]
The Serilogger apender for ApplicationInsights handles scope by storing it in CustomDimensions. I'd like to move away from Serilog for my greenfield Asp.NET Core project work, because quite frankly your built in logging implementations are **finally** good enough, except for this one aspect.

Honestly, if you guys are unsure how to proceed (and I understand that some existing customers will see this change as breaking) with this, can you at least somehow expose scope to ITelemetryInitializer and let the users handle it?

However, being IncludeScope is a configurable boolean, I really doubt any customers will be affected in a truely bad way by this.

**Comment by profet23** [comment]
@cijothomas any reason this keeps getting pushed back? It would be amazing to have all my log scopes  actually send info to Application Insights.

**Comment by cijothomas** [comment]
@profet23 lack of bandwidth. Team is occupied with other deliverables :( Given the high demain, this item will be addressed as soon as I get some free cycles.

**Comment by 2xPower** [comment]
Glad to hear - looking forward to progress

**Comment by RSuter** [comment]
It's really a shame that this important feature is still not supported. As a workaround we use Serilog with an Application Insights sink... The advantage is that it will even log correctly/in the same way when you switch to another sink (e.g. Seq).

**Comment by RamjotSingh** [comment]
PR https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239 has been merged in which introduces the support for Scopes once the package is out you can use it to log Scopes as well.

**Comment by bkaidbb** [comment]
Beta version is available on MyGet: https://www.myget.org/feed/applicationinsights/package/nuget/Microsoft.Extensions.Logging.ApplicationInsights

**Comment by cijothomas** [comment]
Resolved via -> https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239
Closing this. 

Please post feedback/issues about Ilogger, use this repo: 
https://github.com/Microsoft/ApplicationInsights-dotnet-logging
