### ISSUE TITLE
Missing Type in ServiceCollection when upgrading Microsoft.ApplicationInsights.AspNetCore 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-aspnetcore#502]
Moved from https://github.com/Microsoft/ApplicationInsights-Home/issues/139

I have a unittest that tries to create all services in my service collection.

While populating the service collection I call 

`services.AddApplicationInsightsTelemetry( configuration );`

in 2.1.0 i could create all services application insights adds

in 2.1.1 i get 

```
System.InvalidOperationException : failed to create Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet

System.InvalidOperationException : Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
```

am i supposed to call another add stuff method or should this type be registered in `AddApplicationInsightsTelemetry`

**Comment by SergeyKanzhelev** [comment]
Yeah, it looks like something introduced recently to address potential security vulnerability. This class only registered by MVC. Something like this: https://github.com/aspnet/HtmlAbstractions/blob/c2690023d8f14f8deb64b9571212ad2da5ff6541/src/Microsoft.Extensions.WebEncoders/EncoderServiceCollectionExtensions.cs#L37

Try to register it as a workaround. In the next version we will need to have an override that do not depend on this class.

**Comment by JanEggers** [comment]
thx sergey

**Comment by cijothomas** [comment]
@SergeyKanzhelev 
Should we try to not throw if JavaScriptEncoder is not registered, and fall-back to the same logic we have prior to this? (https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/411/files#diff-f2533377302ae5764e5470a777b4ca1bL62)

Or should AI SDK try to add JavaScriptEncoder, if not already added?

**Comment by cijothomas** [comment]
Or check if JavaScriptEncoder is already injected, if not dont add AI JavascriptSnippet..? something like this..
`if(services.Any(service => service.ServiceType == typeof(JavaScriptEncoder)))
                {
                    services.AddSingleton<JavaScriptSnippet>();
                }`

**Comment by SergeyKanzhelev** [comment]
@cijothomas the point of this bug is make it not to throw. Implementation of this encoder is like 20 lines of code or so... So we can fall back to custom encoder

**Comment by cijothomas** [comment]
This bug exists, but not introduced in 2.2.0-betas. While this needs fixed, it should not block 2.2.0 stable release.
Will move this to the next immediate milestone.

**Comment by Yush0** [comment]
I also encounter this error in my Integration Tests. The only solution I found is to completly remove Application Insight from my Webapp. I would wather keep using it since its very helpfull to our team.
Has anyone got it working with a modified AddApplicationInsightsTelemetry function pointed out by @cijothomas? I don't get it working with manually adding the services in my Startup.

**Comment by dazinator** [comment]
I just came accross this here: https://github.com/aspnet/Mvc/issues/8340#issuecomment-416684751

The only solution I found was either to call `services.AddWebEncoders();` or to disable insights.

My case is non standard, but even so this was problematic.

**Comment by Yush0** [comment]
Only thing that got it working for me is injecting the following services manually while testing:
            services.AddScoped<TelemetryConfiguration>();
            services.AddScoped<JavaScriptSnippet>();

**Comment by cijothomas** [comment]
This is an issue with default webapi apps in asp.net core 3.0 preview builds. Tagging to fix for the next immediate release.
