### ISSUE TITLE
AutocollectedMetricsExtractor not added to AI processor chain

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-aspnetcore#503]
The default `ApplicationInsights.config` file includes the `Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor` telemetry processor in the `TelemetryProcessors` chain. 

As `UseApplicationInsights` is meant to replace `ApplicationInsights.config` (indeed, the latter is not even included in the ASP.NET Core VS template), I would expect `AutocollectedMetricsExtractor` to be added by  `ApplicationInsights-aspnetcore` somehow, but a [quick search](https://github.com/Microsoft/ApplicationInsights-aspnetcore/search?utf8=%E2%9C%93&q=AutocollectedMetricsExtractor&type=) suggests that is not the case.

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting! We will be enabling it when will turn on sampling for .NET Core target by default.
