### ISSUE TITLE
Access to operation id

### ISSUE THREAD

**Issue by rosieks** [Microsoft/ApplicationInsights-aspnetcore#504]
Please provide easy to use way to access Operation Id. I would like to create page or exception handler that will expose that ID to the user so he will be able to use it to contact the support.

**Comment by SergeyKanzhelev** [comment]
Something like this will give you ID of a currently running request: `httpContext.GetFeature<RequestTelemetry>().Context.Operation.Id`

**Comment by lmolkova** [comment]
If you are using SDK version 2.1+ you can also use `Activity.Current?.RootId`.

Showing Activity.Current.Id is the default behavior in ASP.NET Core 2.0 in VS 2017 (Preview 3) Razor page template.  https://github.com/dotnet/templating/pull/728

**Comment by rosieks** [comment]
Thanks, that what I needed.
