### ISSUE TITLE
Configuration story ironing/documenting

### ISSUE THREAD

**Issue by ohadschn** [microsoft/ApplicationInsights-aspnetcore#505]
@SergeyKanzhelev it looks like AI ASP.NET Core pulls configuration from multiple places:

1. `TelemetryConfiguration.Active` - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/ce6b4caade8566a451b3c98a10bc077d021f494f/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptions.cs#L21) (since 1.0.0-rc1-update4).
 1. `appsettings.json` - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/53ea997d23cef854bb05ccdf192199e818547dfe/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs#L31) (since 2.1.0-beta5).
 1. `AddApplicationInsightsTelemetry (ApplicationInsightsServiceOptions)` - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs) (since 2.0.0).
1.  Environment variables (`APPINSIGHTS_INSTRUMENTATIONKEY`, `APPINSIGHTS_DEVELOPER_MODE`, `APPINSIGHTS_ENDPOINTADDRESS`) - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L37) (mostly for Azure Web Apps).
 1. `IServiceCollection` manipulation (usually `UseApplicationInsights`) - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs).
1. (possibly in the future) `ApplicationInsights.config` - https://github.com/Microsoft/ApplicationInsights-dotnet/pull/536

It looks like 1-4 control simple properties like `InstrumentationKey` and `DeveloperMode` whereas 4-5 inject all the services. Also, as far as I can tell the `TelemetryClient` is [created with the default ctor](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L162), meaning the default configuration is used. In other words, `TelemetryConfiguration.Active` operations affect this client, both before and after its creation. This can have unexpected results, for example if you add some initializer/processor already added by ApplicationInsights-aspnetcore you will end up with two in the pipeline. The same if you change your channel or even instrumentation key. Modules are even more confusing, because they won't show up in `TelemetryModules.Instance` even though they were initialized (https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/506).

I think a clear hierarchy of where ApplicationInsights-aspnetcore takes what settings from and in what order (e.g. what overrides what) would be great. Also a specific explanation about how `TelemetryConfiguration.Active` comes into play would be very beneficial.

**Comment by cijothomas** [comment]
Immediate concerns are addressed in 2.3.0. Will revisit this again once we have sufficient feedback

**Comment by cijothomas** [comment]
Please refer to the new asp.net specific docs: 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core
This should answer most config related questions now. Please open new issues either in this repo or in the docs comment, and we'll get to it.

**Comment by ketaanhshah** [comment]
Thank you cijothomas and Sergey!

**Comment by cijothomas** [comment]
closing this as docs are now published which describes configuration story.
We will do more improvements in configuration area based on additional feedback.
