### ISSUE TITLE
Telemetry modules not added to TelemetryModules.Instance

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-aspnetcore#506]
At least two telemetry modules are added by [ApplicationInsights-aspnetcore](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L37) and yet when I check `TelemetryModules.Instance` (say, inside a controller handler method triggered by a REST request) I don't see them there. It looks like they are [initialized](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs#L83) so it's not really a bug in the sense that they won't work, but I think it would be more consistent (with `ApplicationInsights.config`), clear (to debuggers), and manageable (for example if I want to check the existing modules).

**Comment by cijothomas** [comment]
With the recent changes introduced in [2.3.0-beta1](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/CHANGELOG.md#version-230-beta1), all modules are injected to DI. Applications can retrieve them from DI if required. 
We are not planning to make it consistent with other sdk by populating the static instance `TelemetryModules.Instance`
