### ISSUE TITLE
Move logging provider to a separate package to make it usable outside of ASP.NET Core

### ISSUE THREAD

**Issue by cwe1ss** [Microsoft/ApplicationInsights-aspnetcore#507]
I want to use ApplicationInsights in a *non-web* application that uses `Microsoft.Extensions.Logging` for logging.

Unfortunately I have to copy the provider code right now, as this library depends on Microsoft.AspNetCore.* packages.

Could you extract the logging provider into something like a `Microsoft.Extensions.Logging.ApplicationInsights` package?

**Comment by SergeyKanzhelev** [comment]
@karolz-ms do you think you can help with this?

**Comment by karolz-ms** [comment]
@SergeyKanzhelev sorry, it looks like I have been already allocated 100% for the next month or so... :(

**Comment by cwe1ss** [comment]
Maybe I have time in the next days to come up with a PR. How would you want to name the package? 

* `Microsoft.Extensions.Logging.ApplicationInsights`
* `Microsoft.ApplicationInsights.Extensions.Logging`
* Something else??

/cc @davidfowl what's the latest viewpoint in this naming debate? :)

**Comment by cijothomas** [comment]
New package available: https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights
closing this.
