### ISSUE TITLE
Add Microsoft.ApplicationInsights.WindowsServer dependency for its initializers and modules

### ISSUE THREAD

**Issue by ohadschn** [microsoft/ApplicationInsights-aspnetcore#508]
The [Microsoft.ApplicationInsights.WindowsServer](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer/) package contains some useful telemetry initializers (like `AzureWebAppRoleEnvironmentTelemetryInitializer`) and modules (like `UnhandledExceptionTelemetryModule`). Why not include them in ApplicationInsights-aspnetcore by default?

**Comment by cijothomas** [comment]
This is fixed.
https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj#L68
