### ISSUE TITLE
Getting-Started Wiki  instructions need to be update for 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [Microsoft/ApplicationInsights-aspnetcore#509]
[Getting-Started Wiki](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started) instructions need to be update for 2.0

See https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/478
I can do an edit  pass when these are in PR

**Comment by cijothomas** [comment]
Made a starting point.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-ASP.NET-CORE2.0-WebApp

Not quite perfect, but a good starting doc.

**Comment by Rick-Anderson** [comment]
I made some minor edits.

**Comment by Rick-Anderson** [comment]
`<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.0-beta1" />`

@cijothomas  do you want the beta version?

**Comment by qrli** [comment]
It does not describe how to add the app insights logging provider.
