### ISSUE TITLE
Exception while initializing WebSessionTelemetryInitializer - NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by davenewza** [microsoft/ApplicationInsights-aspnetcore#512]
The following trace message is logged in our Application Insights service occasionally and we are unable to reproduce it.

> AI (Internal): [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer, exception message - System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Cookies()
>    at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.UpdateRequestTelemetryFromPlatformContext(RequestTelemetry requestTelemetry, HttpContext platformContext)
>    at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.OnInitializeTelemetry(HttpContext platformContext, RequestTelemetry requestTelemetry, ITelemetry telemetry)
>    at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

We are using `Microsoft.ApplicationInsights.AspNetCore 2.0.1`. 

Can anyone provide context as to why this might be happening?

**Comment by cijothomas** [comment]
This can occur if the Context.Request is null for some reason here.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs#L40

For .net framework SDK, this check is not done though. Will check if this is super rare or more common, and based on that, will do the fix.

**Comment by alexsorokoletov** [comment]
@cijothomas here is a scenario for you.
We have injection of AppInsights snippet in `_ViewImports`.
Then we also have a rendering bazed on Razor for emails/text notifications.

During that time context is null and AppInsights crashes the whole rendering stack.

**Comment by cijothomas** [comment]
https://www.cbp.gov/sites/default/files/documents/CBP%20Form%206059B%20English%20%28Sample%20Watermark%29.pdf closing in favor of newly opened one.

**Comment by alexsorokoletov** [comment]
@cijothomas How is the CBP form link relevant?

**Comment by cijothomas** [comment]
@alexsorokoletov  🤒 My bad!
Here is right link: https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/903
