### ISSUE TITLE
Track controller resolution

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-aspnetcore#514]
It could be useful to have automatic events tracked when controllers are resolved (perhaps via a module?) specifying the actual controller type that was resolved for each request.

**Comment by SergeyKanzhelev** [comment]
So you want every request has a property with the name of controller that processed the request? Or separate trace message? How do you want to use it?

**Comment by ohadschn** [comment]
Adding that property to the existing request event would be ideal (save traffic, easier queries), though I suspect request logging happens before you have that information. Postponing it to the point that information is available might be problematic if some error occurs after the request was received but before its controller has been resolved. In that case we would probably like to have the request telemetry sent without the controller resolution information (ideally with some clear error in that field such as "Exception occurred before controller resolution"). Failure to do so could hurt request/exception correlation. 

I don't have any specific usage in mind, other than an interesting data point I think would be good to have for diagnostics / debugging.

**Comment by SergeyKanzhelev** [comment]
@ohadschn without specific usage example I going to close the item. We are trying to increase ROI of collected data and only collect something widely useful.

Thanks for suggestion anyway, appreciate it!
