### ISSUE TITLE
Log the Referer HTTP Header By Default

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/ApplicationInsights-aspnetcore#516]
By default the HTTP Referer Header is not part of the telemetry data. It should be added default. [This](https://www.meziantou.net/2017/08/07/application-insights-track-http-referer) blog post shows how.

**Comment by SergeyKanzhelev** [comment]
@RehanSaeed why do you recommend to collect it by default? This nice blog post explains how to do it for people who needs a referrer information. From our experience it's not a majority of people so we do not want to impose this extra data collection (and price to pay for the ingested telemetry traffic) on them.

Please feel free to re-open if you think the issue needs more discussion

**Comment by SergeyKanzhelev** [comment]
Also mentioning user voice request here: https://feedback.azure.com/forums/357324-application-insights/suggestions/14129343-url-referral
