### ISSUE TITLE
ITelemetryInitializer unable to access HttpContext.RequestedServices - NullReferenceException

### ISSUE THREAD

**Issue by alohaninja** [Microsoft/ApplicationInsights-aspnetcore#519]
Receiving a .NET Exception when trying to retrieve a DI service using `HttpContext.RequestedServices`. This doesn't happen regularly - it's intermittent. I suspect it's a threading issue. 

`var myService = httpContext.RequestServices.GetRequiredService<IMyService>(); `

> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestServices()
   at MyTelemetry.Initialize(ITelemetry telemetry)

We added the telemetry initializer using middleware and inject the `HttpContext` in the `ITelemetryInitializer` constructor. Any ideas?

**Comment by alohaninja** [comment]
Since we didn't hear anything reported back here and this was sabotaging the stability of our app we had to disable the usage of application insights in our asp,net core apps. Hope to see this issue remedied in the future. We had lots of 500s in our middleware components that were too frequent when using application insights. Users were becoming intolerant of the unreliability. Hopefully others here can report and confirm this issue.

**Comment by cijothomas** [comment]
@alohaninja Apologies for slow response here.
Can you share a repro app where you see this?
I am not sure if I understand the issue correctly. Are you saying you tried to add a new TelemetryInitializer which threw exception?
