### ISSUE TITLE
Exception telemetry NOT logged

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/ApplicationInsights-aspnetcore#520]
In our [release for `2.0.0-beta1`](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.0.0-beta1), we said:
>UseApplicationInsightsExceptionTelemetry is obsolete, exception telemetry is handled automatically internally now. You should delete calls to this method from Startup.cs otherwise you will get duplicate exception telemetry reported.

However the AI dashboard for my web app is *not* automatically collecting it. Instead I'm seeing:
![image](https://user-images.githubusercontent.com/20270743/29745800-d95b650a-8a79-11e7-8971-138fb8d6734e.png)

So, how do I get exception telemetry handled if not via the `UseApplicationInsightsExceptionTelemetry` call?

**Comment by Eneuman** [comment]
The only way for me to get this working in Core 2.0, when im using a WebApi, was to add     `loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Warning);`
in
 `public void Configure(IApplicationBuilder app, IHostingEnvironment env)`

and add a seperate HttpGlobalExceptionFilter that acually does the logging like this

`logger.LogError(new EventId(context.Exception.HResult), context.Exception, context.Exception.Message);`

I have not yet  found another way :(

**Comment by cijothomas** [comment]
@brandonh-msft UseApplicationInsightsExceptionTelemetry() is marked obsolete as any unhandled exception is automatically reported.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs#L294

Can you share a small repro of this behavior where unhandled exception is NOT tracked automatically by application insights? 
I just tried throwing an exception from a controller, and it did get reported as ExceptionTelemetry.

        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            throw new Exception("cijo is here");
            return new string[] { "value1", "value2" };
        }

**Comment by cijothomas** [comment]
@Eneuman if possible, can you share repro for this issue?

**Comment by Ming-Sizung** [comment]
@cijothomas I think when you have a global exception handler for Mvc module, ApplicationInsights stops to log exceptions.

**Comment by brandonh-msft** [comment]
Sorry @cijothomas - 10wk after I filed you responded and I've no idea where a repro case for this might be anymore.
