### ISSUE TITLE
Compatibility with .NET Core 2.0

### ISSUE THREAD

**Issue by MBODM** [Microsoft/ApplicationInsights-aspnetcore#521]
This happens when we try to build a .NET Core 2.0 App (regardless if we use VS2017 15.3 Template or type "dotnet new mvc") on a fresh installed machine:

  Restoring packages for D:\TestProject\TestProject.csproj...
  Restore completed in 56,69 ms for D:\TestProject\TestProject.csproj.
D:\TestProject\TestProject.csproj : error NU1202: Package Microsoft.ApplicationInsights.AspNetCore 2.1.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.ApplicationInsights.AspNetCore 2.1.1 supports:
D:\TestProject\TestProject.csproj : error NU1202:   - net451 (.NETFramework,Version=v4.5.1)
D:\TestProject\TestProject.csproj : error NU1202:   - netstandard1.6 (.NETStandard,Version=v1.6)
D:\TestProject\TestProject.csproj : error NU1202: Package Microsoft.ApplicationInsights.DependencyCollector 2.4.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.ApplicationInsights.DependencyCollector 2.4.1 supports:
D:\TestProject\TestProject.csproj : error NU1202:   - net40 (.NETFramework,Version=v4.0)
D:\TestProject\TestProject.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5)
D:\TestProject\TestProject.csproj : error NU1202:   - netstandard1.6 (.NETStandard,Version=v1.6)
  Generating MSBuild file D:\TestProject\obj\TestProject.csproj.nuget.g.props.
  Generating MSBuild file D:\TestProject\obj\TestProject.csproj.nuget.g.targets.
  Restore failed in 2,78 sec for D:\TestProject\TestProject.csproj.

**Comment by cijothomas** [comment]
Can you confirm you have core 2.0 installed in the machine?

**Comment by MBODM** [comment]
Yes.

Fresh Windows 10 with Creators Update.
Fresh VS 2017 15.3.2 Community Install.
Fresh .Net Core 2.0 SDK 64 Bit Install.
Reboot.
File - New Project - .Net Core 2.0 - Web Application (MVC)
F5
This error.

Same thing with
- VS Professional
- "dotnet new mvc"
- On Virtual Machine

It seems the 2 Packages are only built against .Net Standard 1.6. Standard 2.0 should include this, but it seems for some reason this dont work here.

Strange thing is: In the .net 2.0 store (for the meta package system - c:\programfiles\dotnet\store) there are other packages with even standard 1.4 dependencies. But they are OK. I have no clue what is special with the 2 ApplicationInsights Packages above.

But its the same on 7 Computers in our Company. So...

**Comment by MBODM** [comment]
If that helps i can send screenshots. Or logs etc. 

I have also opened it here:

https://github.com/dotnet/core/issues/887

**Comment by MBODM** [comment]
Any news here ? I dont get that obviously nobody ever tested this. Just take a fresh Windows 10 Machine, Install latest VS 2017 (15.3.2), Install .net core 2.0 SDK (and maybe Runtime too). Now make some "dotnet new mvc" or use default template in VS and you get above error. Its really easy to reproduce.

Sorry, i am a .net dev since nearly 15 years. And for our company that behaviour just sucks. There are easier ways to force ppl to node.js or other technologies instead asp.net core. Even the Visual Studio Team, after using Feedback Button in VS, closed our Issue with a fucked up "Install .net core 2.0 sdk. Issue closed.". Thats hillarious. We described the problem exactly. I think they even didnt read it or even tested it.

Understand our frustration: We are in front of big descissions for the next 1-2 year projects. We WANT to use .net core 2.0. But we dont get even the default project compiled, because of above error. And it seems nobody cares. Thats very dissapointing.

**Comment by MBODM** [comment]
7h after my issue was closed (with a hillarious answer) by MS, they "magically" released 15.3.3. Which fixes that problem (Release Notes show a slightly another problem, but obviously it also do some fix with my problem).

MS just became a fucked up company.

Or in short: Now that they released 15.3.3 you can close this issue. Thx anyway.

**Comment by MBODM** [comment]
Bill Hiebert [MSFT] wrote on Visual Studio Developer Community:

"I apologize for this issue being closed without comments. Your issue sounds a lot like the one described here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/521
According to that post the issue was fixed in 15.3.3. Can you update to that version and confirm? 
Again, apologies for this being closed without confirmation that your issue has been fixed.
Thanks."

This is the Microsoft i know.

I wrote this here, to also inform in this issue here, that indeed the 15.3.3 VS Update solved the problem entirely. Directly after installing it, the error no longer existed. 

So you can safely close this issue.

**Comment by branko19** [comment]
fuck .net core dont work even on windows 
I installed new VS 2017 community edition on start I have 90 errors.
Is this way MS do it.
