### ISSUE TITLE
Add request-level properties for all telemetry items

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-aspnetcore#522]
Hi,
I've found an important difference between documentation and suggested code for creation of custom telemetry initializers which may lead to problems in accessing request http context using the suggested code.

Documentation [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure#add-request-level-properties-for-all-telemetry-items) is very straightforward in getting and accessing HTTP context.

But AI's own code internally uses a lock, as visible [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs#L36). As hinted in others discussions, it seems the lock is important.

I please need some clarifications:

1. Is there any problem in inheriting telemetry initializers from **TelemetryInitializerBase** and implementing **OnInitializeTelemetry** instead of using the interface as suggested in the docs?

2. Is this the new suggested way to create custom initializes until the problems with access to http context are sorted out?

Thanks!

**Comment by bragma** [comment]
I've just noticed TelemetryInitializerBase is internal. :(
Reformulating point 1, can it be used as a model for implementing a safe telemetry initializer accessing http context?

Thanks!

**Comment by pharring** [comment]
The lock is a fairly recent addition (see #492) in response to synchronization problems when accessing the Features dictionary (see #373). The documentation is out of date. However, as you can see from the discussion, we're still not sure this is the right fix and it may change again.

If we don't want to make TelemetryInitializerBase public (which is still reasonable), then we should provide a public helper (extension?) method for getting the current RequestTelemetry when implementing your own TelemetryInitializer.

**Comment by bragma** [comment]
Thanks @pharring, I understand the situation. I still need to use the initializers to set some telemetry request properties getting them from the http request user's claims. What do you suggest at the moment? As a temporary workaround, I can move the stuff to the controller constructor, but I still need to get the data from the request and set them on the telemetry of the request.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs TelemetryInitializerBase is made public in recent versions and can be used for now.
