### ISSUE TITLE
How can I remove ApplicationInsights from my app

### ISSUE THREAD

**Issue by kinglionsoft** [Microsoft/ApplicationInsights-aspnetcore#523]
When I start an Asp .Net Core 2.0 application, ApplicationInsights Logger will be auto added.
``` bash
Debug: Loaded hosting startup assembly Microsoft.AspNetCore.ApplicationInsights.HostingStartup
```

How can I remove it?

**Comment by vaindil** [comment]
I have this question as well. My output is full of useless entries that I'm not using like the one below, and they just hide what I'm really trying to see. I do not have AI installed, I don't even have the extension installed in VS, yet they're still being logged to my console.

    Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2017-10-24T18:24:35.3816064Z" ...

**Comment by cijothomas** [comment]
@vaindil To control the amount of logging Application Insights listens to and converts to ApplicationInsights Traces, you can modify appsettings.json to somelike this.. 

{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Trace"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "None"
      }
    }
  }
}

This will get rid of all Trace messages. (you can configure this in code also)
(ApplicationInsights will still collect/show Requests/Dependencies though).

I agree this may not be ideal, will provide a better answer on how to remove application insights completely soon.

**Comment by cijothomas** [comment]
Closing this issue here, as there an issue open in aspnet repo to prevent auto-opt-in for application insights.
https://github.com/aspnet/Home/issues/2051

**Comment by cijothomas** [comment]
Also - there are workarounds suggested in the above issue.
one of them being:
https://github.com/aspnet/Home/issues/2051#issuecomment-335641346

**Comment by joalcava** [comment]
Where can be tracked the progress on this? The issue @cijothomas references is also closed.

**Comment by cijothomas** [comment]
@joalcava https://github.com/aspnet/Home/issues/2051#issuecomment-363495498 This shows latest VS which include an option to not have application insights. Let me know if this helps you.
