### ISSUE TITLE
The schema URL is broken

### ISSUE THREAD

**Issue by jakemclelland** [microsoft/ApplicationInsights-aspnetcore#528]
I've added Application Insights to my project, which created the ApplicationInsights.config file. But the url to the schema namespace is invalid. at the top it shows 
`<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">`
but there are build output warnings saying it can't find the schema at that url. And if you browse to that url, you see a message that it has been moved.

Where is that schema now?

**Comment by cijothomas** [comment]
ai.config is not added for asp.net core.
