### ISSUE TITLE
Is profiler working with preview feature "Multi-role Application Map" enabled?

### ISSUE THREAD

**Issue by f1xxxer** [Microsoft/ApplicationInsights-aspnetcore#529]
My app has service oriented architecture so I've enabled Multi-role Application Map preview in my application insights to be able to see the map and requests.

All of my services (web apps) have the same app insights key and are pointing to same app insights instance. I can see http calls on the map and different dependencies, but i can't see any profiling information, i also can't see calls and requests to databases.

I have all the latests app insights packages installed on every web app (Microsoft.ApplicationInsights.AspNetCore 2.1.1).

Am i doing something wrong or it just doesn't work yet? #

**Comment by zakimaksyutov** [comment]
@f1xxxer, sorry for taking time to respond. What do you refer by "profiling information"? Is it Profiler Traces? Which DB your application uses?

**Comment by f1xxxer** [comment]
@zakimaksyutov sorry, for not telling it detailed enough.

My application is Angular 4 front-end and asp.net core 2.0 web api back-end.
I am using Azure Sql databases grouped in Sql Elastic Pool, ORM is entity framework core.

By profiling i mean all the metrics when you, for example, click "See server performance counters", like: "process cpu", "processor time", "commited memory", etc.

The main discomfort is that i can't see any database related operations.

If you need any more specific details, please, let me know.

**Comment by zakimaksyutov** [comment]
@f1xxxer, yes, there is a known issue that SQL dependencies are not collected in .NET Core compiled in Core mode. There is an active PR which should merged within a week which will get these dependencies back: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/607

Another option (not sure it is applicable) - compile .NET Core in Full mode and run it with Full framework. Then SQL dependencies should be collected as well.

**Comment by f1xxxer** [comment]
@zakimaksyutov thank you very much for the answer. Looking forward for the new release

**Comment by cijothomas** [comment]
@f1xxxer Will be relase 2.2.0-beta1 this week, which support SQL dependency collection for .NET Core Apps. Current SDK collects SQL dependencies only if targeting full .NET Framework.

Unfortunately, if the application is targetting .NET Core, then you will not see other performance counters like cpu, memory etc, as there is not way to retrieve performance counters in Asp.Net core. (this feature may come in future, but no commitments)
Please let us know if you have further questions.

**Comment by cijothomas** [comment]
Just to be clear - you can get performance counters, if targeting full .NET Framework.
