### ISSUE TITLE
netcore 2.0 SQL dependencies not being logged

### ISSUE THREAD

**Issue by oatsoda** [Microsoft/ApplicationInsights-aspnetcore#531]
I've got a few netcore 2.0 Azure App Services with App Insights enabled.  Everything seems to be tracked (Requests, Http Dependencies, Storage Dependencies) except for the SQL Dependencies which are not logged at all.

I've got the Instrumentation Key set in the appSettings.json and also have the `AddApplicationInsightsTelemetry` in my startup.  I am using NuGet package `Microsoft.ApplicationInsights.AspNetCore` v 2.1.1

I ran this query in the analytics to check what SDK version is logged against current dependencies:

`dependencies | summarize count() by cloud_RoleInstance, sdkVersion`

And it shows `rdddsc:2.4.1-1362`

I am using EF Core for DB operations.

Any ideas why I would not be seeing any SQL entries logged?  Anything I can check?

**Comment by cijothomas** [comment]
SQL will be collected if the app is compiled targeting full framework. IF the app is targetting NETCOREAPP.., then SQL wont be collected. Ability to collect SQL is being actively worked on and should be available for next version of sdk.

**Comment by oatsoda** [comment]
Thanks for confirming. I scoured the docs and issues to try and find this, but only found the issue for Entity Framework.

Do you have an item number for the SQL telemetry collection work so I can follow it?

**Comment by cijothomas** [comment]
This PR is the in-progress work. It's been resurrected now by EF team.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/607

**Comment by sandorfr** [comment]
@cijothomas the PR your are pointing to has been merge quite a while ago, has it been released ? I don't see SQL Dependencies either.

**Comment by sandorfr** [comment]
ah got it we have to use the latest beta client https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.2.0-beta3
