### ISSUE TITLE
 ASP.NET Core 2.0: enable AI in production only, disable in development build

### ISSUE THREAD

**Issue by Ziriax** [Microsoft/ApplicationInsights-aspnetcore#533]
I spent a couple of hours to disable Application Insights in our ASP.NET Core 2.0 conditionally in debug builds (so in development env AI should be disabled, but in production we want it enabled)

If we keep Application Insights, for some reason, when debugging, the kestrel web server starts using "localhost:true" instead of "localhost:5000".

Any hints on how to do this are welcome.

**Comment by cijothomas** [comment]
Can you share the code you used to enable/disable Application Insights? I cannot think of any reason why application insights affects the startup port. Would like to know more about this - please share a repro if possible.

**Comment by Ziriax** [comment]
I will try to make a minimal example. We already figured out it has nothing to do with Kestrel, but with VSCODE trying to figure out the port being used when it is launching the browser.

Intriguingly sometimes VSCODE launches the browser with "localhost:true", and sometimes with "localhost:Development" :-)

Removing the auto-url part in the launch json settings with a hardcoded localhost:5000 was an acceptable workaround for us.

**Comment by cijothomas** [comment]
ok.
As a general guide to how to enable Application Insights in Prod, but not in Dev - it should be fairly easy.
For your Production.appsettings.json, have application insights instrumentation key set,
and for Development.appsettings.json, do not set application insights instrumentation key. Without ikey, nothing from DEV env gets sent to ApplicationInsights, but Visual Studio 2017 still shows application insights telemetry locally.

"ApplicationInsights": {
    "InstrumentationKey": "ikeygoeshere"
  }

**Comment by cijothomas** [comment]
Closing this.
Please let us know if you have concerns/questions.
