### ISSUE TITLE
InstrumentationKey in source control

### ISSUE THREAD

**Issue by dalibor983** [Microsoft/ApplicationInsights-aspnetcore#535]
The method UseApplicationInsights load InstrumentationKey from application.json and applicaiotn.{EnvironmentName}.json and environment variables.

Is there any way to load InstrumentationKey from app secrets in development or it is safe to put instrumentation key in json file and commit in my source control that is public available.

**Comment by d3r3kk** [comment]
I would suggest that you do not check in your Instrumentation Key in a public repo, no. Instead, you can set variables into your deployment scripts, and have your automation system substitute those variables at deploy time.

One example of how others have done this is by our DevOps Rangers, you can [see how they did it for one of their OSS projects here.](https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/09/25/application-insights-tokenization-for-visual-studio-team-services-extensions/)

**Comment by dalibor983** [comment]
Is there any way to use user secrets to load InstrumentationKey with this code:
```
if (env.IsDevelopment())
{
    builder.AddUserSecrets<Startup>();
}
```

**Comment by cijothomas** [comment]
@dalibor983 This overload of UseApplicationInsights (string instrumentationKey) accepts instrumentation key as a parameter. You can store you key in Azure Key Fault, and read key from there, just like you would read any other secrets, and pass the instrumentation key to the UseApplicationInsights(key) method.

The following contains example of retrieving any secret from KeyVault.
https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?tabs=aspnetcore2x

Please let us know if this is what you are looking for. Closing this for now.

**Comment by jyarbro** [comment]
For future googlers like me, the actual answer (not Azure Key Vault) is here:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure

You can set environment variable "ApplicationInsights:InstrumentationKey" to your key.

The doc is written poorly, you need to make sure you remove the default .AddApplicationInsights() call from Program.cs and then add to your Startup.cs:

services.AddApplicationInsightsTelemetry(Configuration);

In azure make sure you add the application setting to the same key name I said above, not the default "APPINSIGHTS_INSTRUMENTATIONKEY" that gets added by Azure.
