### ISSUE TITLE
How to register ApplicationInsights ILoggingProvider in the ILoggingBuilder?

### ISSUE THREAD

**Issue by NicolasDorier** [Microsoft/ApplicationInsights-aspnetcore#536]
Navigating through outdated documentation, it seems that the latest way to configure logging on .net core is similar to that:

```
host = new WebHostBuilder()
	.UseKestrel()
	.UseIISIntegration()
	.UseContentRoot(Directory.GetCurrentDirectory())
	.UseConfiguration(conf)
	.UseApplicationInsights()
	.ConfigureLogging(builder =>
	{
		builder.AddFilter("Microsoft", LogLevel.Error);
		builder.AddProvider(new CustomConsoleLogProvider());
	})
	.UseStartup<Startup>()
	.Build();
```

However, it seems that this is not possible with ApplicationInsights which requires a `ILoggerFactory` instead of the `ILoggingBuilder`.

I then added 

```
loggerFactory.AddApplicationInsights(prov, LogLevel.Information);
```

In the Configure of my Startup.cs. This seems to work fine but is it not outdated ?

**Comment by Tadimsky** [comment]
I just migrated a project over to 2.0 and am having the same thing. It looks like there is no extension method on `ILoggingBuilder`. Would love to have it 😄

**Comment by mjrousos** [comment]
+1. All new ASP.NET Core documentation recommends registering logging providers via `ILoggingBuilder` in program.cs (as opposed to in startup.cs). It would be pretty straight-forward to work around not having an extension method except that ApplicationInsightsLoggingProvider is internal, so it can't be added directly.

**Comment by pauldalyii** [comment]
Hi @cijothomas, Does this still look like it'll make 2.6.0?

Looking forward to being able to send logging from ConfigureServices to App Insights.  I have been bit by some errant DI registrations lately and being able to send App Insights logs from ConfigureServices would be a big help.

Thanks!

**Comment by cijothomas** [comment]
Its less likely to land in 2.6.0.

**Comment by cijothomas** [comment]
This is going to addressed by the following PR in progress now..
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239

**Comment by cijothomas** [comment]
Closing this as this is solved by using https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights.

**Comment by timmkrause** [comment]
The extension method on `ILoggerFactory` had a min log level parameter which I was using but the extension method on `ILoggingBuilder` does not. Or to be more precise the `ApplicationInsightsLoggerOptions` do not have this option.

How to work around this?

**Comment by cijothomas** [comment]
LogLevel based filtering in part of logging infra itself. 

//configure LogLevel Trace or above is sent to ApplicationInsights for all categories.
loggingBuilder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Trace);
loggingBuilder.AddApplicationInsights("--YourAIKeyHere--"); 

See this doc: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/Readme.md

**Comment by timmkrause** [comment]
I saw this one coming.

So a feature has been removed with this "new design"...
I have different logging providers, why shouldn't I be able to granular control their behavior regarding for example their log level thresholds?

**Comment by cijothomas** [comment]
Ability to control/filter per logging provider is offered by the logging infra itself, not application insights.
