### ISSUE TITLE
TraceIdentifier in AI Logs

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/ApplicationInsights-aspnetcore#537]
I want to use the TraceIdentifier in ASP.NET Core as a Correlation Id between the client and service.
However, it seems like AI is not logging the Trace Identifier and instead is using its own Operation Id.

Is there a way that we can ensure that every AI log inside an HttpContext adds the TraceIdentifier as a property?

**Comment by zakimaksyutov** [comment]
+ @lmolkova

**Comment by SergeyKanzhelev** [comment]
You can implement [telemetry initializer](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer) to add TraceIdentifier to every telemetry item. Alternatively you can switch to Application Insights Operation Id. In fact it's not Application Insights specific and begin initialized by ASP.NET itself when it starts and stops an Activity.

**Comment by SergeyKanzhelev** [comment]
please re-open if you have more qq

**Comment by Tadimsky** [comment]
Thanks @SergeyKanzhelev - I found that and did end up using that - it worked well.
I'm having one problem that I wonder if you'd have some ideas about.

I've written some Middleware that can allow the client to specify a correlation id. This will then overwrite the TraceIdentifier on the HttpContext with the new value supplied by the client in a Header. The point of this is to easily trace S2S calls through our services.
This works great and the Telemetry Initializer picks up the changed value, except for the very first log which is the Request Starting done in `OnHttpRequestInStart`. This function runs before all the Middleware starts and so it hasn't gone through my Correlation Id code (which makes sense).
Do you have any ideas how to set it up so `OnHttpRequestInStart` runs after the CorrelationId middleware? I can't think of anything other than doing my own version of `OnHttpRequestInStart` which handles the rewriting of the Correlation Id.

**Comment by lmolkova** [comment]
@Tadimsky 
I believe the `Request Starting` log is written by AspNetCore Hosting layer and not by AppInsights `OnHttpRequestInStart` method.

`OnHttpRequestInStart` is  callback for event that happens in AspNetCore Hosting layer. 
Hosting layer happens before any middleware and there is no way to change their order.

If you want to stamp your id on this log, you may implement telemetry initializer that accesses HttpContext and parses request with the header containing your id.

This way your initializer would be called on the TraceTelemetry containing this log and you'd be able to stamp it with your correlation id.
