### ISSUE TITLE
Leverage Microsoft.AspNetCore.Mvc.Testing for functional tests

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-aspnetcore#539]
See https://github.com/aspnet/Announcements/issues/275 for details.

**Comment by cijothomas** [comment]
Will visit this after next release.

**Comment by cijothomas** [comment]
https://blogs.msdn.microsoft.com/webdev/2018/03/05/asp-net-core-2-1-0-preview1-functional-testing-of-mvc-applications/

**Comment by cijothomas** [comment]
We are making this change in the context of adding asp.net core 3.0 support. Will start with 3.0 for now, leaving older tests as such. Will migrate all tests to this new method later.
