### ISSUE TITLE
Make unit tests discoverable in Visual Studio

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-aspnetcore#547]
Since the test project targets both netstandard and net46, Visual Studio only shows tests from the 1st target. This make it difficult to debug unit tests from visual studio.
Solution would be to create separate projects (.csproj) for netstandard and net46 targets, with each of them containing link references to actual source code in a shared proj.
This ensures all tests are discovered and run inside Visual Studio 2017

**Comment by d3r3kk** [comment]
I believe this is how we do it in the base SDK right now, is that correct? If so, I +1 this idea!

**Comment by cijothomas** [comment]
@d3r3kk yes, i meant to make it like base sdk!

**Comment by cijothomas** [comment]
De-prioritizing due to new VS improvements.
