### ISSUE TITLE
Application Insights not using settings from appsettings.{Environment.MachineName}.json

### ISSUE THREAD

**Issue by VSDekar** [Microsoft/ApplicationInsights-aspnetcore#548]
We use App Insights 2.1.1 with latest VS 2017

This is the same issue like https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/477 , but we have appsettings per machine and not only per environment.

It works with the same workaround like in the linked issue. It would be nice if you could make a generic solution which reads the settings from the `Configuration` object

**Comment by cijothomas** [comment]
Thanks @VSDekar for reporting!
Will address this here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/605
