### ISSUE TITLE
fixed rate samling

### ISSUE THREAD

**Issue by etombi** [Microsoft/ApplicationInsights-aspnetcore#549]
Hi all,
as i see theres no method .UseSampling() under TelemetryConfiguration.Active.TelemetryProcessorChainBuilder in .net core package there's only  .Use()
that can recieve the processor. Any suggestion how to use the fixed rate sampling processor class (SamplingTelemetryProcessor) from asp.net package?

**Comment by cijothomas** [comment]
@etombi Have you tried the latest beta version? ServerTelemetryChannel is entirely ported to .NET Core and TelemetryProcessorChainBuilder should now have UseSampling() and UseAdaptiveSampling() methods.

https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.2.0-beta1

Note: This beta version has a bug and wont work on Linux. This is being fixed for beta2.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/551
