### ISSUE TITLE
.Net Core 2 Console App and Application Insights

### ISSUE THREAD

**Issue by ranouf** [Microsoft/ApplicationInsights-aspnetcore#554]
Hi,

I developed a .Net Core 2.0 App Console with Dependency Injection.
I wanted to add App Insight, I can see in debug that the Applicationkey is taken from the appSettings but there is no trace or exception added (when a exeption is throw) in the Appplication Insights in Debug or on Azure.
My code is available here:
https://github.com/ranouf/AzureWebJob/tree/MakeAAzureWebJob

It could be me who had made a mistake in my code (probably), but it could be an Issue too.

Is there someone who have an Idea?

Thank you

**Comment by ranouf** [comment]
So I created a new .net core console  project then i copy paste the following getting from : https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-.NET-Core-console-application
```
using System;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;

namespace Microsoft.ApplicaitonInsights.Examples.NetCoreConsole
{
    public class Program
    {
        public static void Main(string[] args)
        {
            TelemetryConfiguration.Active.InstrumentationKey = 
                "11111111-2222-3333-4444-555555555555";
            TelemetryClient client = new TelemetryClient();
            client.TrackTrace("Demo application starting up.");

            for (int i = 0; i < 10; i++)
            {
                client.TrackEvent("Testing " + i);
            }

            client.TrackException(new Exception("Demo exception."));
            client.TrackTrace("Demo application exiting.");
            client.Flush();
        }
    }
}
```
I executed the app, and nothing was added in ApplicationInsights Visual studio.

So maybe, there is something missing in my project, in this case, it could be interesting to add it in the Wiki for the next person like me who wants to use Application Insight in a .Net core Console App.
Or, there is an Issue with Telemetry Client.

**Comment by cijothomas** [comment]
The above snippet is all you need to start sending data to application insights. And it should be working. (I just tried the same code now - using my ikey).

![image](https://user-images.githubusercontent.com/5232798/32911629-90706060-cac1-11e7-8b38-d6346fb8e62e.png)

**Comment by cijothomas** [comment]
nothing was added in ApplicationInsights Visual studio. - can you clarify this a bit more? Where are you looking for Application Insights events?

**Comment by cijothomas** [comment]
client.Flush();
            Thread.Sleep(5000);
            Console.ReadLine();

I did add some sleep after flush though...

**Comment by ranouf** [comment]
Hi,

Thank you for your help.

I m looking there (see image bellow, top left)
![image](https://user-images.githubusercontent.com/1764519/32915672-aa67c046-cae7-11e7-97b5-5809f6b3df56.png)

I can see calls in the output.

if I try with "11111111-2222-3333-4444-555555555555", i m supposed to see new ApplicationInsight in Local.

Just to be sure, I tried with a key from my azure Account, nothing appears on the Azure Account or In local.

**Comment by cijothomas** [comment]
Thanks for clarifying. Yes I understood the Visual Studio part- I don't see it either. @SergeyKanzhelev do you know what's missing for Visual Studio integration?

If you are using an actual ikey, the data should be in Application Insights portal. Do a sleep(10sec) after Flush(). (Breakpoint will pause all threads including sender threads i believe)

**Comment by ranouf** [comment]
Yes, the sleep helped, I can see them on the Azure Instance.

It could be nice to have them in local too.

I will follow the conversation to know what will happen.

Thanks @cijothomas

**Comment by ranouf** [comment]
I m curious, why is it necessary to make a sleep after the Flush?
What I guess, the telemetry Client is launch in the current thread, when we do a flush, it need time to send data to Azure, but as the thread is closed by the ending of the app, the tracking is not sent?
Am I right?

**Comment by cijothomas** [comment]
yes. (items are kept in buffer and sent periodically. Flush() triggers sending of items, but takes time)

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#flushing-data

**Comment by ranouf** [comment]
In this case, could it be possible to have a FlushAsync method? So no need to use thread.sleep anymore after that.

**Comment by cijothomas** [comment]
Yes, tracking here. https://github.com/Microsoft/ApplicationInsights-dotnet/issues/482

**Comment by pandianrb** [comment]
Hi @cijothomas ,

do we need manual code for tracking the exception for application insights ?

client.TrackException(new Exception("Demo exception."));
            client.TrackTrace("Demo application exiting.");

do we have any configuration to track the exception across the console application ?

**Comment by cijothomas** [comment]
@pandianrb If you are using a Console .NET Core Application, there is no automatic exception tracking. You need explicitly call TrackException().
Please let us know if you have more questions. Closing this item for now.

**Comment by AsValeO** [comment]
@cijothomas, Is self-hosted ASP.NET Core 2.0 Web App counts as console application in this case? Application insights catches only exceptions of type `System.Net.Http.WinHttpException` automatically in my case. Why this happens?

**Comment by cijothomas** [comment]
@AsValeO self-hosted ASP.NET Core 2.0 Web App are not really counted as console apps. How did you onboard Application Insights SDK to your project?
Please open a separate issue if this is not related to a consoleapp,.
