### ISSUE TITLE
JavascriptSnippet : Add nullable check for HttpContext

### ISSUE THREAD

**Issue by tmakin** [Microsoft/ApplicationInsights-aspnetcore#556]
I just ran into an obscure problem with the `JavascriptSnippet` class when rendering razor templates to string. It works fine when it is part of an HTTP request but I'm getting an exception from `JavascriptSnippet` when the rendering is done from a custom scope. For example, a self test at application startup where there is no `HttpContext` available.

I've tracked the problem down to the call to `httpContextAccessor` here:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/12cb0cd96c83115eeb16d7b2711c5ddb73c9e69c/src/Microsoft.ApplicationInsights.AspNetCore/ApplicationInsightsJavaScript.cs#L62

I propose the following minor change to make `JavascriptSnippet` tolerant of the use case above:

    //Before
    IIdentity identity = httpContextAccessor?.HttpContext.User?.Identity;

    //After (with nullable check on HttpContext)
    IIdentity identity = httpContextAccessor?.HttpContext?.User?.Identity;

**Comment by cijothomas** [comment]
@tmakin Thanks for reporting the issue! I have submitted a fix for the same. PR #618
