### ISSUE TITLE
Tracking processes within webjobs

### ISSUE THREAD

**Issue by wayne-thomson-cxa** [Microsoft/ApplicationInsights-aspnetcore#557]
Hi there,

I managed to build a .NET core console app deployed as a web app which logs traces and metrics to application insights. I used the method outlined [Getting-Started-for-a-.NET-Core-console-application](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-.NET-Core-console-application). 

How is sampling configured in this .NET Core library? Particularly for a console application.

Thanks,

Wayne.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling

If you are using .net core console app to call Track() methods yourselves, then no sampling is configured automatically. Please follow the above link to know how to configure sampling programatically.

Note that for asp.net core web applications, adaptive sampling is ON by default.

Let us know if you have more questions.
