### ISSUE TITLE
Redirect traffic to the different endpoint

### ISSUE THREAD

**Issue by dhayhak** [Microsoft/ApplicationInsights-aspnetcore#559]
I saw https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure#redirect-traffic-to-the-different-endpoint that application insight has support to redirect traffic to different endpoint.

Can I redirect traffic to any custom url?
Is this feature already available or it will be available in the future?
Could you please give us more details about it?

**Comment by cijothomas** [comment]
You can redirect traffic to any urls by changing the channel endpoint.
```
TelemetryConfiguration.Active.TelemetryChannel.EndpointAddress
```
But i am not clear on why you would want to do it. If data is not sent to application insights, it wont show up in application insights.
If your use case is to do filter/something before data reaches application insights using a proxy, then yes you can do it. Ofcourse that proxy has to eventually send data to application insights.
