### ISSUE TITLE
Can I disable/enable App Insight by configuration in asp.core?

### ISSUE THREAD

**Issue by dhayhak** [Microsoft/ApplicationInsights-aspnetcore#561]
Hi,

I would like to be able to enable & disable AI by configuration at Runtime.
My scenario is I want to send trace data to AI only when it's enabled by configuration.
Does AI support log level like the the console provider in ASP Core?

I know I can use `TelemetryConfiguration.Active.DisableTelemetry = true;` but this means that on every request I check the config and set the `DisableTelemetry` accordingly. I'm just wondering if there is a better way.

**Comment by cijothomas** [comment]
You can modify appsettings.json to control the logging done by ApplicationInsights. Something like the following in appsettings.json ensure Applicationinsights only sends traces for logs with severity >= Warning.
```
"ApplicationInsights": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
```
And you can have different appsettings.json per environment, and control the behaviour.
Use ```none``` if you do not want any loggins via application insights.

Let me know if this helps.

**Comment by cijothomas** [comment]
More specifically to your questions -  application insights supports log level, just like other logging providers like console.

**Comment by dhayhak** [comment]
I just tested your example with `default:"none"`. I was expecting that this will dismiss all tracing done by AI, but it didn't. AI still sending data to Azure. Am I missing something?

This is how I initialize AI:
`services.AddApplicationInsightsTelemetry(configuration);`

**Comment by cijothomas** [comment]
@dhayhak sorry my bad. I did not paste the whole json. The setting is meant to be insie Logging section.
```
{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Trace"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  }
}

```

This shows full appsettings file. Please try this.

**Comment by dhayhak** [comment]
Yeap, that worked! Thanks @cijothomas 
Quick note though:
I've been playing with AI LogLevel settings, I noticed that ` "Default": "None"` is still sending data to App Inisights. It is minimal (Initial request and dependency) but I was expecting it will just dismiss every tracking.

Thanks!

**Comment by cijothomas** [comment]
The above setting only controls the Trace telemetry items sent to application insights. This does not have impact on Request/Dependency or other telemetry.

**Comment by luismanez** [comment]
Is this still valid in asp.net core 2.1?
I'm calling this in the ConfigureServices
```c#
services.AddApplicationInsightsTelemetry(Configuration);
```
and
```c#
public void Configure(IApplicationBuilder app, 
            IHostingEnvironment env, 
            ILoggerFactory loggerFactory)
        {
            loggerFactory.AddApplicationInsights(app.ApplicationServices);
```
here is my appsettings file:

```js
{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Trace"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      }
    }
  },
  "ApplicationInsights": {
    "InstrumentationKey": "9b4459ea-aeed-4b1b-a29e-6cc1b9a21834"
  },
  "AllowedHosts": "*"
}
````
However, seems is only logging Warning messages or higher (default config instead of my settings)

```c#
_logger.LogInformation("Welcome");
_logger.LogWarning("warning message");
```
Only the warning message is being logged.

Am I missing something?

Thanks!

**Comment by kevin-meyer** [comment]
@luismanez I'm experiencing the same with Microsoft.ApplicationInsights.AspNetCore 2.4.1.
