### ISSUE TITLE
Accessing HttpContextAccessor in custom initializer

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/ApplicationInsights-aspnetcore#562]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create Custom Initializer  that references IHttpContextAccessor
2. Register Initializer in Middleware 

##  Actual Behavior
Custom Initializer Hit and logs Telemetry

## Expected Behavior
Custom Initializer Not Being Hit

## Version Info 
SDK Version : 2.1.1
.NET Version :	Dot Net Core  	1.1					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Visual Studio
Hosting Info (IIS/Azure WebApps/ etc) : Azure App Service

I added a custom Initializer to Add the Request Body of Post/Put messages to AI Tracks, here is the initializer

````
  public class RequestBodyInitializer : ITelemetryInitializer
  {
    IHttpContextAccessor httpContextAccessor;

    public RequestBodyInitializer(IHttpContextAccessor httpContextAccessor)
    {
      this.httpContextAccessor = httpContextAccessor;
    }

    public void Initialize(ITelemetry telemetry)
    {
      var requestTelemetry = telemetry as RequestTelemetry;
      if (requestTelemetry != null && (httpContextAccessor.HttpContext.Request.Method == HttpMethods.Post.ToString() || httpContextAccessor.HttpContext.Request.Method == HttpMethods.Put.ToString()))
      {
        using (var reader = new StreamReader(httpContextAccessor.HttpContext.Request.Body))
        {
          string requestBody = reader.ReadToEnd();
          requestTelemetry.Properties.Add("body", requestBody);
        }
      }
    }
  }
````
I registered the initializer in Startup, but breakpoints in this class are not being hit. I imagine there is a step that I am missing.

**Comment by cijothomas** [comment]
@isaac2004 How did you register initializer? It need to be added to the list of TelemetryInitializers.

Add this to Configure() method in startup.cs.
var configuration = app.ApplicationServices.GetService<TelemetryConfiguration>();
            configuration.TelemetryInitializers.Add(new RequestBodyInitializer());

**Comment by cijothomas** [comment]
or
```
TelemetryConfiguration.Active.TelemetryInitializers.Add(new RequestBodyInitializer())
```

**Comment by isaac2004** [comment]
@cijothomas Issue here is that I can't use parameterless constructor. Do I need to get an instance of IHttpContextAccessor from Services and inject that?

**Comment by henkmollema** [comment]
You should be able to register the telemetry initializer using just DI in `ConfigureServices`:
```cs
services.AddSingleton<ITelemetryInitializer, RequestBodyInitializer>();
```

**Comment by isaac2004** [comment]
@henkmollema well it seems to fire up the DI, it looks like thee is a problem with reading the request body before MVC gets it. I have tried EnabledRewind(), but no matter what I do, any action like this has an empty body

````
  [HttpPut("{id}")]
        public void Put(int id, [FromBody]UserDto value) //value is null, but body is logged by Initializer
        {
            _repository.Update(value);
        }

````

**Comment by henkmollema** [comment]
Telemetry initializers are invoked for every telemetry object being sent to Application Insights. It can indeed be invoked multiple times per request. You could try to determine whether the current telemetry instance is invoked for request logging by casting it to a `RequestTelemetry` instance. For example:

```cs
public void Initialize(ITelemetry telemetry)
{
  if (telemetry is RequestTelemetry)
  {
    // Process telemetry data...
  }
}```

I suggest that you also determine whether `httpContextAccessor.HttpContext` is not `null` and that you are able to read the request body (you could check `Request.Body.CanRead` for example).

**Comment by isaac2004** [comment]
CanRead is true in this case. I ended up swallowing a DisposeException, which is super hacky but can't think of another way to do it.

**Comment by henkmollema** [comment]
You should only have one telemetry instance where `telemetry is RequestTelemetry` equals to `true` per request. Is that not the case?

**Comment by isaac2004** [comment]
This Initializer fires twice, first time works and logs as expected, 2nd throws Dispose Expception at the ReadToEndLine

````
    public void Initialize(ITelemetry telemetry)
    {
      if (telemetry != null && telemetry is RequestTelemetry)
      {
        var requestTelemetry = telemetry as RequestTelemetry;
        if ((httpContextAccessor.HttpContext.Request.Method == HttpMethods.Post.ToString() || httpContextAccessor.HttpContext.Request.Method == HttpMethods.Put.ToString()) && httpContextAccessor.HttpContext.Request.Body.CanRead)
        {
          httpContextAccessor.HttpContext.Request.EnableRewind();

          string bodyContent = new StreamReader(httpContextAccessor.HttpContext.Request.Body).ReadToEnd();
          httpContextAccessor.HttpContext.Request.Body.Position = 0;
          requestTelemetry.Properties.Add("body", bodyContent);

        }
      }
    }
````

**Comment by isaac2004** [comment]
@henkmollema can you help me out with this issue I am having. When I use MVC login sample, my Initialize is firing twice, the second time it throws DisposeException. Is there something wrong I am doing with the Rewind()? If I catch DisposeException, the app works as expected and the request is sent. Seems like swallowing an exception is bad practice in this case

**Comment by isaac2004** [comment]
After chatting with some folks, it seems this is expected behavior with TelemetryInitializers. Best approach is to properly handle ObjectDisposed in code

**Comment by johnkwaters** [comment]
I ended up needing this too. Rather than handle Disposed, I checked if the call had already happened once by seeing if the telemetry already had the added property:

    public class RequestBodyInitializer : ITelemetryInitializer
    {
        readonly IHttpContextAccessor _httpContextAccessor;

        public RequestBodyInitializer(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public void Initialize(ITelemetry telemetry)
        {
            if (telemetry is RequestTelemetry requestTelemetry)
            {
                if ((_httpContextAccessor.HttpContext.Request.Method == HttpMethods.Post || 
                     _httpContextAccessor.HttpContext.Request.Method == HttpMethods.Put) && 
                     _httpContextAccessor.HttpContext.Request.Body.CanRead)
                {
                    const string body = "JsonBody";

                    if (requestTelemetry.Properties.ContainsKey(body))
                    {
                        return;
                    }
                    _httpContextAccessor.HttpContext.Request.EnableRewind();
                    var sr = new StreamReader(_httpContextAccessor.HttpContext.Request.Body);                   
                    var bodyContent = sr.ReadToEnd();
                    _httpContextAccessor.HttpContext.Request.Body.Position = 0;
                    requestTelemetry.Properties.Add(body, bodyContent);                   
                }
            }
        }
    }

**Comment by johnkwaters** [comment]
I also added this check, I dont want user's passwords in my telemetry!

                 if (bodyContent.Contains("password"))
                    {
                        // don't log passwords!
                        bodyContent = "contains sensitive information, hidden";
                    }

**Comment by isaac2004** [comment]
@johnkwaters I like this idea, but sadly the use case is pretty broad right? For instance what if the field name is 'pw' also things like email/ssn/dob could all be captured using that Initializer. Thinking about this, I imagine this Initializer probably would be a problem with GDPR.. hmmmmm
