### ISSUE TITLE
How to use Initializers

### ISSUE THREAD

**Issue by ddobric** [Microsoft/ApplicationInsights-aspnetcore#565]
Looking for a sample or documentation, which demonstrates how to use initializers.
For example, to log session identifiers, I guess WebSessionTelemetryInitializer should be used.
However all initializers are internal classes.
What is the proper way to use them?

Thank

**Comment by cijothomas** [comment]
WebSessionTelemetryInitializer is added by default to asp.net core app when you use .UseApplicationInsights() or AddApplicationInsightsTelemetry() option to onboard.

If you are talking about your own custom initializers, you can add it to the list of TelemetryInitializers like shown below.

Do this in Configure() method of your startup class.
```
var tc = TelemetryConfiguration.Active;
            tc.TelemetryInitializers.Add(new MyInitializer());
```

**Comment by cijothomas** [comment]
This has overall documentation.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling
