### ISSUE TITLE
How to handle network failure with the SDK?

### ISSUE THREAD

**Issue by dhayhak** [Microsoft/ApplicationInsights-aspnetcore#566]
Hi,

I'm wondering how to handle network failure when we send telemetry with the aspnetCore SDK.
Let's say the SDK failed to send the telemetry to AI. How can I handle that? Can I listen to the failure and log that locally?

Thanks

**Comment by SergeyKanzhelev** [comment]
Channel implementation will make the best effort to send the telemetry. Make sure you are using latest versions of SDK so ServerTelemetryChannel will be initialized. Implementation of server telemetry channel is here: https://github.com/Microsoft/ApplicationInsights-dotnet

If you need to definitely make sure that item is delivered - you'd need to implement your own channel like this http://apmtips.com/blog/2016/11/10/sync-channel/ as Application Insights SDK do not guarantee delivery - it's designed to make a best effort in delivering.

**Comment by dhayhak** [comment]
Thanks for the quick reply. I tested the example of the sync-channel. It worked good for .NET framework (4.6.1) but not for dotnetCore 2.0. The `Transmission SendAsync() and Wait()` does not throw an exception. Should I open a bug?

**Comment by SergeyKanzhelev** [comment]
Yes, please open a bug. Transmission class is not very extensive so you can just re-implement it yourself. And add any error handling you need.
