### ISSUE TITLE
Support EventId in ApplicationInsightsLogger

### ISSUE THREAD

**Issue by duracellko** [Microsoft/ApplicationInsights-aspnetcore#569]
It would be nice, if `ApplicationInsightsLogger` would include `EventId.Id` and `EventId.Name` in telemetry properties ad EventId and EventName.

**Comment by older** [comment]
What is official way to enable EventId today? I used documentation from [https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging](here), but it is now deprecated and recommended replacement `Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerOptions` does not even have `IncludeEventId` property.

**Comment by cijothomas** [comment]
@older In the new provider Microsoft.Extensions.Logging.ApplicationInsightsLoggingProvider, EventID and EventName are always included. You dont need to do anything extra to enable it.

Please give it a try, and if EventId/Name are not captured, let us know.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger
