### ISSUE TITLE
HttpClient dependencies in ASP.NET Core app showing out of sync

### ISSUE THREAD

**Issue by bgever** [Microsoft/ApplicationInsights-aspnetcore#582]
The telemetry in the Application Insights dashboard reports the dependencies for requests incorrectly. It sometimes misses the dependency, or attaches the dependency to the wrong request within the same timeframe. This happens when the requests and dependency calls are executed asynchronously with `async`/`await`.

## Repro Steps
You'll need an ASP.NET Core MVC app that calls repeatedly async a Web API.
Our example (reduced to essential bits) is retrieving images:

```.cs
[Route("assets/thumbnails/{type}/{id}")]
public async Task<ActionResult> Thumbnails(string type, string id)
{
    var thumbnail = await RetrieveThumbnail(type, id);
    return File(thumbnail.Image, thumbnail.MediaType);
}

private async Task<Thumbnail> RetrieveThumbnail(type, id)
{
    var request = new HttpRequestMessage(HttpMethod.Get, $"{baseUri}/thumbnails/{type}/{id}");
    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
    var response = await _httpClient.SendAsync(request);
    return new Thumbnail(
        image: await response.Content.ReadAsByteArrayAsync(),
        mediaType: response.Content.Headers.ContentType.MediaType);
}
```

##  Actual Behavior
Dependency calls get randomly attached to requests within the same time period. Refreshing the Application Insights dashboard will render different results.

*No dependencies:*
![image](https://user-images.githubusercontent.com/1618765/34369436-91c0d86e-eaf6-11e7-8777-6b696e4b7ed4.png)

*Wrong dependency from previous request attached:*
![image](https://user-images.githubusercontent.com/1618765/34369381-3b85065a-eaf6-11e7-91e7-4bebd47db1ab.png)

## Expected Behavior
`HttpClient` dependency calls are linked to the request that triggered them.

## Version Info 
SDK Version: `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" />`
.NET Version:
`<TargetFramework>net461</TargetFramework>`
`<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />`
SDK loaded manually during app startup with:
`host.UseApplicationInsights(instrumentationKey); // WebHostBuilder`
Running on Azure App Service.

**Comment by bgever** [comment]
Is https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/65 related? Do we need to target `net462`?

**Comment by cijothomas** [comment]
@bgever Can you try the latest SDK (2.2.1) and see if this helps? Also I am not sure whether this is/was a bug in UI. (you can run analytics queries and verify yourself)

if you are still having issues, please share a repro project and we'll investigate deeper.

**Comment by bgever** [comment]
Sorry, I no longer have access to the codebase.

@thomasmktong could you have a look?

**Comment by thomasmktong** [comment]
Sorry for late reply. I think the dependency calls are attached correctly now, thanks!

**Comment by cijothomas** [comment]
Thanks for confirming. Closing this

**Comment by bgever** [comment]
Thanks for checking @thomasmktong 😄
