### ISSUE TITLE
How can I disable Adaptive Sampling?

### ISSUE THREAD

**Issue by fujiy** [Microsoft/ApplicationInsights-aspnetcore#585]
I followed the instruction here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream#sampling

But, when I use the first one:

```
var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
aiOptions.EnableAdaptiveSampling = false;

services.AddApplicationInsightsTelemetry(Configuration, aiOptions);
```

(and comment UseApplicationInsights in Program.cs)

The client-side script doesn't show up.

So I tried the second option, adding the code in ConfigureServices method:

```
var builder = telemetryConfiguration.TelemetryProcessorChainBuilder;
 
// Using fixed rate sampling   
builder.UseSampling(100);

builder.Build();

```
But it has no effect.

**Comment by cijothomas** [comment]
Here's my ConfigureServices method.
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            var tc = TelemetryConfiguration.Active;
            var channel = tc.TelemetryChannel;

            var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
            aiOptions.EnableAdaptiveSampling = false;
            aiOptions.InstrumentationKey = "myikey";

            services.AddApplicationInsightsTelemetry(aiOptions);                        
        }
```

This is worked as expected. (i.e SamplingProcessor is not added to list of TelemetryProcessors). You can verify this by obtaining the active configuration inside Configure() method.
```
var tc = TelemetryConfiguration.Active;
```
This tc should show that SamplingTelemetryProcessor is not present.

In your case - how did you conclude that sampling was disabled?

**Comment by fujiy** [comment]
I verified the itemCount property, it is greater than 1. So, sampling is enabled.

The problem with AddApplicationInsightsTelemetry is that @Html.Raw(JavaScriptSnippet.FullScript) doesn't work. So, I'm afraid of using it, it seems an old API that doesn't work well.

**Comment by cijothomas** [comment]
Got it. 

The 2nd approach using ```builder.UseSampling(100).build()``` does not work as AdaptiveSamplingProcessor is already in the list. (The documentation is not up-to-date - apologies for the confusion)

The right way to control sampling is to use use the approach in my example. So the real issue here is you are not getting JavaScriptSnippet with this approach. 

From the code it looks like JSSnippet is injected with AddApplicationInsightsTelemetry.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L178

Can you share an easy repro where you don't get JavaScriptSnippet?

**Comment by fujiy** [comment]
It was a customer code.  I'm not there anymore, I'll  try to reproduce in my machine

Felipe Pessoto
________________________________

**Comment by cijothomas** [comment]
Ok.

**Comment by fujiy** [comment]
@cijothomas I'm sending a sample to you by e-mail. By it's simple to reproduce, I created a new project, added AI, commented UseApplicationInsights in Program.cs and added services.AddApplicationInsightsTelemetry() in ConfigureServices.

**Comment by fujiy** [comment]
It seems AddApplicationInsightsTelemetry doesn't read the Instrumentation Key  from appSettings. If I pass as parameter of AddApplicationInsightsTelemetry, it works:

`services.AddApplicationInsightsTelemetry();`

or

```
var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
aiOptions.EnableAdaptiveSampling = false;
aiOptions.InstrumentationKey = "11111111-2222-3333-4444-555555555555";
services.AddApplicationInsightsTelemetry(aiOptions);
```

**Comment by cijothomas** [comment]
@fujiy I am working on fixing the documentation and also we are working to formalize the configuration story for .net core applications in general.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/505

I got your email with repro. Will investigate it .

**Comment by cijothomas** [comment]
@fujiy The documentation here is updated to correctly reflect how to disable adaptive sampling.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream#sampling

I have also verified that javascript snippet is available in both UseApplicationInsights() and AddApplicationInsightsTelemetry() method. If using the latter ikey should be passed as argument as it wont read ikey from appsettings. (https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/605)

Apart from the issue https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/605, do you have any other issues in this topic?

**Comment by fujiy** [comment]
No, that's all. Thanks

**Comment by cijothomas** [comment]
Ok. closing this.

**Comment by mcsdodo** [comment]
in the example here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream should be clearly stated, that you need to explicitly set instrumentation key to the ``ApplicationInsightsServiceOptions``. Once this approach is used the ``IWebHostBuilder.UseApplicationInsights(YOUR_KEY)`` method has no effect.
