### ISSUE TITLE
GetUri does not respect PathBase

### ISSUE THREAD

**Issue by ChristianSauer** [Microsoft/ApplicationInsights-aspnetcore#590]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
0. Setup a simple sample project
1.  Set a Pathbase in Startup.cs,  e.g.  app.UsePathBase("/mybase");
2. Observe difference in Index()
            var a = HttpContext.Request.GetUri();
            var b = HttpContext.Request.GetDisplayUrl();
            var c = HttpContext.Request.GetEncodedUrl();
2.  Visit your localhost:<port>:/mybase/

##  Actual Behavior
GetUri does not respect the path base, both others do.
a = http://localhost:8099/
b = http://localhost:8099/mybase/
c = http://localhost:8099/mybase/
## Expected Behavior
GetUri should include the Path Base

## Version Info 
SDK Version :  2.1.4
.NET Version :	 	2.05					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel

**Comment by cijothomas** [comment]
@ChristianSauer This does not seem related to applicationinsights sdk, but rather a general question about Asp.Net Core. Please file in https://github.com/aspnet/Home
