### ISSUE TITLE
AI not reporting ILogger logs when run outside of Visual Studio

### ISSUE THREAD

**Issue by dhayhak** [Microsoft/ApplicationInsights-aspnetcore#591]
I'm not sure if this a bug, but for sure a weird behavior.

- Given this config file:
```
  "Logging": {
    "LogLevel": {
      "Default": "Trace"
    }
  },
"ApplicationInsights": {
    "InstrumentationKey": Key"
  }
```
- AI Initializing step
calling `services.AddApplicationInsightsTelemetry(configuration);` in `ConfigureServices`

## Repro Steps
1.  Create  logger from the loggerFactory`  _logger = loggerFactory.CreateLogger("category here");
`
2. log something `_logger.LogInformation("this should appear in AI");`
3. publish the app using `dotnet publish`
4. run the app using `dotnet` or directly from the `exe` . The log is not shown in AI dashboard

##  Actual Behavior
The log is not shown in AI dashboard

## Expected Behavior
The log should be shown in AI dashboard

This is not happening when I run the app from Visual studio.
If I wanted to get it working outside of VS I need to add to the `configure` method in startup:
`loggerFactory.AddApplicationInsights(serviceProvider, LogLevel.Trace);`

**How is this possible? And why it is working from VS and not from outside?**

## Version Info 
SDK Version :2.2.0-beta1
.NET Version :	 netcoreapp2.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel

**Comment by dhayhak** [comment]
OK so I checked the source code of AI and I found the potential issue:
```
if (options.Value.EnableDebugLogger && string.IsNullOrEmpty(options.Value.InstrumentationKey))
            {
                // Do not use extension method here or it will disable debug logger we currently adding
                var enableDebugLogger = true;
                loggerFactory.AddApplicationInsights(serviceProvider, (s, level) => enableDebugLogger && Debugger.IsAttached, () => enableDebugLogger = false);
            }
```

Why you guys are calling `loggerFactory.AddApplicationInsights` only when there is a debugger attached?
Also, it seems like the `EnableDebugLogger` is always true (from the default options).

So, you are enabling AI's logging only when there is no _instrumentation key_? How is that helpful?

After this discovery, I don't understand how this could have happened based on the Repro Steps I described above.
This is so confusing..

My take away on this is you should not call `AddApplicationInsights` based on the debugger. It should be based on the config or enabled in the application code. It should be consistent.

**Comment by cijothomas** [comment]
@dhayhak Inorder for applicationinsights to collect traces logged via ILogger, you need to enable/configure your application manually. (While running from Visual Studio, it enables log capture automatically).
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging
I have put together some basic documentation on how to do this.

Can you follow the documentation and let us know if there is something missing still?

**Comment by Dmitry-Matveev** [comment]
@dhayhak , did you have change to follow the docs @cijothomas provided?

**Comment by dhayhak** [comment]
Yes, it worked. It is clear now that when running from Visual Studio, AI collects ILogger logs automatically by default. Thanks.
