### ISSUE TITLE
application_Version is always 1.0.0.0

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/ApplicationInsights-aspnetcore#596]
All of my logs show application_Version as being 1.0.0.0 instead of the Assembly version that the DLLs are stamped with. 
Is there some other way that this needs to be set?

## Version Info 
SDK Version : dotnet:2.4.0-32153
.NET Version : .Net Core 2.0	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :VS
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Azure App Service

**Comment by Tadimsky** [comment]
Here is the DLL version information:
![image](https://user-images.githubusercontent.com/1149244/35990309-73e74cae-0cb8-11e8-8f68-db343d9cf869.png)

**Comment by fadamsen** [comment]
The version you see in the the DLL's properties is actually the `AssemblyFileVersion`, while Application Insights reports the `AssemblyVersion`.

You can get the `AssemblyVersion` using PowerShell if you want to see for yourself:

```posh
[Reflection.AssemblyName]::GetAssemblyName((Get-Item $dll).FullName).Version
```

**Comment by Tadimsky** [comment]
@fadamsen aha, you are right! I was using the `GitVersioning` plugin to version my DLLs and it was not setting the `AssemblyVersion` attribute. I've configured that and now I have the correct version showing up.

Shouldn't App Insights rather be using `AssemblyFileVersion`? Since `AssemblyVersion` is used mostly for referencing a DLL with a strongly-named reference? Whereas `AssemblyFileVersion` is to identify a particular assembly?

**Comment by fadamsen** [comment]
@Tadimsky I think using `AssemblyFileVersion` would make more sense, yeah, but at the same time I imagine there might be backwards-compatibility concerns preventing a change.

It is also possible to set the application version yourself using a telemetry initializer, then you can get things just the way you want.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsServiceOptions.cs#L20 shows what gets reported as ApplicationVersion.
As @fadamsen mentioned, you can use own telemetry initializer to change this behavior.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration - this contains information on how to configure a custom TelemetryInitializer.

Please let us know if further questions.
