### ISSUE TITLE
Infrastructure EventCounters collection

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-aspnetcore#601]
Allow to configure collection of ASP.NET Core infrastructure event counters. See the following for the initial list:

• aspnet/Caching#357
• aspnet/DependencyInjection#605
• aspnet/HttpSysServer#411
• aspnet/IISIntegration#468
• aspnet/KestrelHttpServer#2145
• aspnet/Mvc#7018
• aspnet/Razor#1749
• aspnet/ResponseCaching#141
• aspnet/Security#1518
• aspnet/SignalR#349

The right place for this code may be PerformanceCounters collection module or EventSource module in logging repo. Need to decide what's the best place is.

**Comment by cijothomas** [comment]
Closing in favor of https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1222 in the actual repo.
