### ISSUE TITLE
[Question] Preventing default columns from being sent to AppInsights

### ISSUE THREAD

**Issue by ravarnamsft** [Microsoft/ApplicationInsights-aspnetcore#626]
I see a few fields in our traces and requests such as client_type, client_ip, client_stateOrProvince etc which we don't care about as we have separate custom dimensions for them. I am looking at avoiding sending them to reduce our data consumption. How do I go about doing it. I looked at the TelemetryContext but i couldn't find anything other than LocationContext (where in the IP is logged). We are sending the logs from a lot of machines and this affects our data limits (even after aggressive sampling)
I have cleared the TelemetryInitializers list in the Configure method of the Asp.Net core project, that doesn't seem to help though.  

TelemetryConfiguration configuration = app.ApplicationServices.GetService<TelemetryConfiguration>();
configuration.TelemetryInitializers.Clear();

**Comment by SergeyKanzhelev** [comment]
You don't pay for auto-populated types you listed. Only for JSON that was sent to Application Insights.

You can remove client IP from LocationContext if needed using Telemetry Processor.
