### ISSUE TITLE
Consolidate telemetry modules shared with Web SDK

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ApplicationInsights-aspnetcore#629]
Now that the Web SDK contains modules that are .NET Full Framework *and* .NET Standard compatible, we can share the code.

Specifically, these modules can be removed from AspNetCore and supplanted with the modules in the Web SDK:
AzureWebAppRoleEnvironmentTelemetryInitializer
DomainNameRoleInstanceTelemetryInitializer

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/624 Duplicated
