### ISSUE TITLE
Dependency error false positives

### ISSUE THREAD

**Issue by dmcweeney** [Microsoft/ApplicationInsights-aspnetcore#635]
Hi,

this is kind of the opposite of Issue #625, where 404 errors from Cosmos Db and Graph API GET user photo are getting registered as dependency failures, but they are not "failures" - it is expected in certain circumstances.

So are the solutions listed in Issue #625 the same for filtering out these false positives?

Thanks, 

Donal

**Comment by cijothomas** [comment]
Yes. Please re-open if you have more questions about the approach.
