### ISSUE TITLE
Insights not working when using .Net Core 2.0 default builder

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#638]
Moved from https://github.com/Microsoft/ApplicationInsights-Home/issues/165
Originally posted by @i02coroj

>Sorry if this topic has been already discussed. I haven't found any related issue.

>I've realized that no telemetry is registered in a .Net Core 2.0 applications using the default builder.
According to this link (https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#rely-on-application-insights-light-up-features) the `.UseApplicationInsights()` instruction can be removed, but if I do it stops working.

>Is that a known topic?
>Maybe an error in the documentation of the mentioned link?

**Comment by cijothomas** [comment]
@i02coroj Did you debug the application via Visual Studio Debugger? if yes, you should see telemetry even if UseApplicationInsights() is removed.
If you are running it outside visual studio, then UseApplicationInsights() is required to configure and enable application insights.
The instructions are here:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core
