### ISSUE TITLE
How to set Cloud_RoleName (in telemetry) and server name (in live stream)?

### ISSUE THREAD

**Issue by Ming-Sizung** [Microsoft/ApplicationInsights-aspnetcore#640]
Hello,

Thanks again for this amazing tool for us to monitor our app in real time.

However, I did not find a way to set the Cloud_RoleName and the Server Name (which will be included in the Live Metrics Stream under Servers section). Being able to set those two names will certainly help monitoring (and differentiating the sender in) a micro-service based system where every service report to the same ApplicationInsights resource. 

Please let me know if there is a way to set those two names or is this feature still under development?

Thanks in advance.

**Comment by Ming-Sizung** [comment]
@SergeyKanzhelev Thanks for the link. However, I did not find a way to set the Server Name in the live stream (currently it is the container id).

**Comment by SergeyKanzhelev** [comment]
@cijothomas can you please take a look?

**Comment by cijothomas** [comment]
I can help figure out this. But its faster if @netgh0st can help as he knows best about where Livemetrics pick the value from.

**Comment by cijothomas** [comment]
`.Context.Cloud.RoleInstance` Please try to set this field via TelemetryInitializer. I believe this is whats gets picked by livemetrics, as per this code
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/PerformanceCollector/Perf.Shared/QuickPulseTelemetryModule.cs#L394

**Comment by Ming-Sizung** [comment]
Thanks for the help guys. I will definitely try it out.

**Comment by Ming-Sizung** [comment]
@cijothomas I tried to set the `telemetry.Context.Cloud.RoleInstance` but it seems that it still picks up the machine name (which is the container id for containerized apps) and report to ApplicationInsights. Both the Server Name in live stream and the actual `RoleInstance` in telemetry details shows the container id instead of the value set in the telemetry initializer.

**Comment by cijothomas** [comment]
Seems like TelemetryInitializer is not configured correctly. Can you tell us how did you configure telemetry initializers? 
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#adding-new-telemetryinitializer

**Comment by Ming-Sizung** [comment]
@cijothomas Sure. I set the `RoleInstance` along with `RoleName`, however, only the `RoleName` changed.

```csharp
    public class CloudRoleNameInitializer : ITelemetryInitializer
    {
        private readonly string roleName;

        public CloudRoleNameInitializer(string roleName)
        {
            this.roleName = roleName ?? throw new ArgumentNullException(nameof(roleName));
        }

        public void Initialize(ITelemetry telemetry)
        {
            telemetry.Context.Cloud.RoleName = this.roleName;
            telemetry.Context.Cloud.RoleInstance = this.roleName;
        }
    }
```

In `Startup.cs` file:
```csharp
            services.AddSingleton<ITelemetryInitializer>(new CloudRoleNameInitializer(this.aiOptions["CloudRoleName"]));
            services.AddApplicationInsightsTelemetry(
                options => options.InstrumentationKey = this.aiOptions["InstrumentationKey"]);
```

**Comment by cijothomas** [comment]
The above should work. I was able to successfully modify Server Name in livemetrics by using the code from your comment. But I did not do it inside a container.

Are you using ApplicationInsights SDK for service fabric? OR just the AI asp.net code sdk ?
https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/master/src/ApplicationInsights.ServiceFabric/Shared/FabricTelemetryInitializer.cs#L80

I'll try out in a container as well now.

**Comment by Ming-Sizung** [comment]
@cijothomas Thanks for your help. I am using just the ApplicationInsights-aspnetcore sdk.

I did a quick search, it says here that setting the `RoleInstance` should work.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/0ec3fac9273308cff56dc5654adc07ca3dec86d0/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializer.cs#L39

But in reality, it always picks up the machine name.

I will try setting up a repro soon.

**Comment by cijothomas** [comment]
Ok.

**Comment by dushes-ag** [comment]
Hi! 
Is there any way to set Cloud Role name for .net core console app? I'm adding ApplicationInsights to logging and also enable heartbeat with AzureWebAppRoleEnvironmentTelemetryInitializer set up.
All heartbeats go with Role name property, but logger log records don't. Any suggestions?

**Comment by cijothomas** [comment]
@dushes-ag can you share your repro/share more details for us to investigate? Its not clear what your full setup is - what exactly is the 'logger log'? Are you using Ilogger?

**Comment by dushes-ag** [comment]
here is the extension method I use to configure AppInsights for console app:
`public static class ConfigurationExtensions
    {
        public static IHostBuilder AddApplicationInsights(this IHostBuilder hostBuilder)
        {
            hostBuilder.ConfigureServices((config, services) =>
            {
                TelemetryModules.Instance.Modules.Add(new AzureInstanceMetadataTelemetryModule());
                var configuration = TelemetryConfiguration.Active;
                var key = config.Configuration["ApplicationInsights:InstrumentationKey"];
                if (!string.IsNullOrEmpty(key))
                {
                    configuration.InstrumentationKey = key;
                }
                configuration.TelemetryInitializers.Add(new OperationCorrelationTelemetryInitializer());
                configuration.TelemetryInitializers.Add(new HttpDependenciesParsingTelemetryInitializer());
                configuration.TelemetryInitializers.Add(new AzureWebAppRoleEnvironmentTelemetryInitializer());

                foreach (var module in TelemetryModules.Instance.Modules)
                {
                    if (module is IHeartbeatPropertyManager hbeatManager)
                    {
                        hbeatManager.IsHeartbeatEnabled = false;
                        hbeatManager.HeartbeatInterval = TimeSpan.FromSeconds(5);
                        hbeatManager.IsHeartbeatEnabled = true;
                    }
                }

                services.AddSingleton<ITelemetryInitializer, CloudRoleNameInitializer>();
                services.AddSingleton(new TelemetryClient(configuration));
            });

            return hostBuilder;
        }
    }

    public class CloudRoleNameInitializer : ITelemetryInitializer
    {
        private const string WebAppNameEnvironmentVariable = "WEBSITE_SITE_NAME";
        private const string WebAppHostNameEnvironmentVariable = "WEBSITE_HOSTNAME";

        public void Initialize(ITelemetry telemetry)
        {
            if (string.IsNullOrEmpty(telemetry.Context.Cloud.RoleName))
            {
                telemetry.Context.Cloud.RoleName = GetRoleName();
            }

            if (string.IsNullOrEmpty(telemetry.Context.Cloud.RoleInstance))
            {
                telemetry.Context.Cloud.RoleInstance = GetRoleInstanceName();
            }

            var internalContext = telemetry.Context.GetInternalContext();
            if (string.IsNullOrEmpty(internalContext.NodeName))
            {
                internalContext.NodeName = GetRoleInstanceName();
            }
        }

        private string GetRoleName()
        {
            return Environment.GetEnvironmentVariable(WebAppNameEnvironmentVariable) ?? string.Empty;
        }

        private string GetRoleInstanceName()
        {
            return Environment.GetEnvironmentVariable(WebAppHostNameEnvironmentVariable) ?? string.Empty;
        }
    }`
Then in Program.cs I build a host and configure logging this way:
`private static IHostBuilder CreateDefaultBuilder(string[] commandLineArgs)
        {
            return new HostBuilder()
               .ConfigureHostConfiguration(configHost =>
               {
                   //...
               })
               .ConfigureAppConfiguration((context, config) =>
               {
                   //...
               })
               .AddApplicationInsights()
               .ConfigureLogging((hostContext, configLogging) =>
               {
                   configLogging.AddConfiguration(hostContext.Configuration.GetSection("Logging"));
                   configLogging.AddConsole();
                   configLogging.AddDebug();

                   configLogging.AddApplicationInsights();

                   var configLevel = hostContext.Configuration["Logging:ApplicationInsights:Default"];

                   if (!string.IsNullOrEmpty(configLevel) && Enum.TryParse(configLevel, out LogLevel minLevel))
                   {
                       configLogging.AddFilter<ApplicationInsightsLoggerProvider>("", minLevel);
                   }
               })
               .UseConsoleLifetime();
        }`
So heartbeat records have those cloud role props set, but custom records from loggers don't

**Comment by dushes-ag** [comment]
and yes, I use ILogger<CLASS_NAME> to log messages. This works well when I do the same in the web context (IWebHost extension method to add AppInsights) log records written by ILogger do have cloud role names set.

**Comment by cijothomas** [comment]
I think you are making config changes to TC.Active and it maynot be picked up. Please follow this and let me know if it helps.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/FAQs#2-accessing-telemetryconfiguration-via-telemetryconfigurationactive-vs-using-di

**Comment by dushes-ag** [comment]
Not sure how it is possible for .net core Console app during the configuration. The suggested code snippet seems to be related to Web app with it's Startup file:
`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory)
{
    var configuration= app.ApplicationServices.GetService<TelemetryConfiguration>();
}`
which is not appliable for Console app

**Comment by cijothomas** [comment]
Ok missed that part about console app. Let me read again.

**Comment by cijothomas** [comment]
This shows the right docs about using Ilogger and adding custom initializers etc. https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/Readme.md 

Did you follow this already >?

**Comment by dushes-ag** [comment]
Thanks a lot, setting up TC via DI helped to get Role name metric in logger messages as well. But I still had to use TC.Active to configure it for the heartbeat, as long as the heartbeat module seems to be configured this way. So now I configure it twice: for logger via DI and via TC.Acitve for Heartbeat.
Here is the code:
`public static IHostBuilder AddApplicationInsights(this IHostBuilder hostBuilder)
        {
            hostBuilder.ConfigureServices((config, services) =>
            {
                services.Configure<TelemetryConfiguration>(SetupTelemetryConfiguration);

                TelemetryModules.Instance.Modules.Add(new AzureInstanceMetadataTelemetryModule());//add before init
                SetupTelemetryConfiguration(TelemetryConfiguration.Active);

                foreach (var module in TelemetryModules.Instance.Modules)
                {
                    if (module is IHeartbeatPropertyManager hbeatManager)
                    {
                        hbeatManager.IsHeartbeatEnabled = false;
                        hbeatManager.HeartbeatInterval = TimeSpan.FromSeconds(30);
                        hbeatManager.IsHeartbeatEnabled = true;
                    }
                }

                void SetupTelemetryConfiguration(TelemetryConfiguration tc)
                {
                    var key = config.Configuration["ApplicationInsights:InstrumentationKey"];
                    if (!string.IsNullOrEmpty(key))
                    {
                        tc.InstrumentationKey = key;
                    }
                    tc.TelemetryInitializers.Add(new OperationCorrelationTelemetryInitializer());
                    tc.TelemetryInitializers.Add(new HttpDependenciesParsingTelemetryInitializer());
                    tc.TelemetryInitializers.Add(new AzureWebAppRoleEnvironmentTelemetryInitializer());

                }

                services.AddSingleton<TelemetryClient>();
            });`

**Comment by cijothomas** [comment]
Use the following to configure heartbeat interval:
```
            var configuration = serviceProvider.GetService<IOptions<TelemetryConfiguration>>();
            DiagnosticsTelemetryModule diag = new DiagnosticsTelemetryModule();
            var hbManager = diag as IHeartbeatPropertyManager;
            hbManager.HeartbeatInterval = TimeSpan.FromSeconds(10);
            diag.Initialize(configuration.Value);
```

**Comment by cijothomas** [comment]
This is my full program code.
```
class Program
    {
        static void Main(string[] args)
        {            
            // Create DI container.
            IServiceCollection services = new ServiceCollection();

            services.Configure<TelemetryConfiguration>(
                (config) =>
                {                    
                    config.TelemetryInitializers.Add(new MyTelemetryInitalizer());                    
                }
            );

            // Add the logging pipelines to use. We are using Application Insights only here.
            services.AddLogging(loggingBuilder =>
            {
                // Optional: Apply filters to configure LogLevel Trace or above is sent to ApplicationInsights for all
                // categories.
                loggingBuilder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Trace);
                loggingBuilder.AddApplicationInsights("mykey");
            });
            

            // Build ServiceProvider.
            IServiceProvider serviceProvider = services.BuildServiceProvider();
            ILogger<Program> logger = serviceProvider.GetRequiredService<ILogger<Program>>();

            // Setup Heartbeat
            var configuration = serviceProvider.GetService<IOptions<TelemetryConfiguration>>();
            DiagnosticsTelemetryModule diag = new DiagnosticsTelemetryModule();
            var hbManager = diag as IHeartbeatPropertyManager;
            hbManager.HeartbeatInterval = TimeSpan.FromSeconds(10);
            diag.Initialize(configuration.Value);
            

            // Begin a new scope. This is optional. Especially in case of AspNetCore request info is already
            // present in scope.
            using (logger.BeginScope(new Dictionary<string, object> { { "Method", nameof(Main) } }))
            {
                logger.LogInformation("Logger is working"); // this will be captured by Application Insights.
            }

            Thread.Sleep(30000);
        }
    }
```
