### ISSUE TITLE
Dependency tracking for DNX apps

### ISSUE THREAD

**Issue by bojanrajkovic** [Microsoft/ApplicationInsights-aspnetcore#65]
This package provides request telemetry and exception telemetry. It would be good to also have a way to enable dependency telemetry via this package for projects targeting DNX, even if it's only for the full framework (`dnx451`) and not CoreCLR (`dnxcore50`).

**Comment by SergKanz** [comment]
@bojanrajkovic, thanks for the interest to Application Insights SDK. Monitoring of dependencies and performance counters is not a supported scenario today. However for ```dnx451``` I just tried it and it seems to be working. 

This is how I made it work:

1. Import packages into ```project.json```. You should only import it for dnx451 target
```
"dnx451": {
  "dependencies": {
        "Microsoft.ApplicationInsights.PerfCounterCollector": "0.16.1-build01613",
        "Microsoft.ApplicationInsights.DependencyCollector": "0.16.1-build01613" 
  }
}
```
2. In ```Configure``` method you'll need to get ```TelemetryConfiguration``` object from the services and initialize corresponding telemetry module:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory, TelemetryConfiguration configuration)
        {
#if dnx451
            TelemetryConfiguration.Active.InstrumentationKey = configuration.InstrumentationKey;
            TelemetryConfiguration.Active.TelemetryChannel = configuration.TelemetryChannel;

            PerformanceCollectorModule module = new PerformanceCollectorModule();
            module.Initialize(configuration);
            configuration.TelemetryModules.Add(module);

            RemoteDependencyModule dependencyModule = new RemoteDependencyModule();
            dependencyModule.Initialize(configuration);
            configuration.TelemetryModules.Add(dependencyModule);
#endif
```
I was also needed to initialize ```TelemetryConfiguraiton.Active``` due to some issues in how these modules are implemented.

Dependencies monitoring will use EventSource-based monitoring, not profiling API-based so no additional configuration as mentioned [here](http://apmtips.com/blog/2015/01/05/track-dependencies-in-console-application/) required

Please let us know how it is working for you and we will be happy to hear feedback on request/exceptions monitoring.

**Comment by bojanrajkovic** [comment]
Cool, will test this out and let you know. Thanks @SergKanz!

**Comment by hfjallemark** [comment]
@SergKanz when I delete the application insights extension for the Azure Web App -- SQL dependency tracking stops working. Can you confirm if it is needed or not?

**Comment by SergKanz** [comment]
@hfjallemark , sorry missed your comment. For the full framework we are using the same mechanism of collecting dependencies as for the regular ASP.NET applications. If you have framework 4.6 installed you'll see dependencies collected in development experience. No additional configuration required. We are using EventSource events reported by SQL code. For Azure WebSites you will not have 4.6 installed so you'll need to install azure WebSite extension. I've explained some basics on how we are doing it here: [apmtips.com](http://apmtips.com/blog/2015/01/05/track-dependencies-in-console-application/)

**Comment by hfjallemark** [comment]
@SergKanz I added the extension but dependencies are not being collected. If I add the code you suggested above, it does work. When will dependency tracking be supported out of the box for both full framework and CoreCLR (preferrably through an extension method)?

**Comment by pherbel** [comment]
Update about dependency support in aspnet5?

**Comment by SergeyKanzhelev** [comment]
@pherbel do you run aspnet5 on full framework or core framework?

**Comment by SergeyKanzhelev** [comment]
cc: @kartang

**Comment by gongdo** [comment]
I'm using ASP.NET5 RC1 with dnx4.5.1.
`TelemetryConfiguration` doesn't have `TelemetryModules` interface anymore(AI 2.0.0-beta4). How can I add `DependencyCollector` module? Any updates about this?

**Comment by SergeyKanzhelev** [comment]
@kartang is working on enabling this functionality out of the box. For telemetry modules - you don't need to store them into configuration, just construct the module and call `Initialize`

**Comment by gongdo** [comment]
@SergeyKanzhelev, you mean DependencyCollector is not working with AI(2.0.0-beta4) currently, right?

I've tried with new ASP.NET 5 application. Microsoft.ApplicationInsights.AspNet itself is working fine. When I add Microsoft.ApplicationInsights.DependencyCollector as dnx451 dependency, a `TypeLoadException` is occurred on this line:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry(Configuration);
//...
```
> Could not load type 'Microsoft.ApplicationInsights.Extensibility.IContextInitializer' from assembly 'Microsoft.ApplicationInsights, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by SergeyKanzhelev** [comment]
@kartang just updated it to use `beta4` https://github.com/Microsoft/ApplicationInsights-aspnet5/commit/4bee4894485d2fd9f59d538743074e6538354094 You can find a package at https://www.myget.org/F/applicationinsights-sdk-labs/api/v3/index.json It will be compatible with the latest DependencyCollector.

Also @kartang plans to turn on dependency collector by default for Full Framework applications

**Comment by abaranch** [comment]
Dependency collection and performance counters collection was enabled by default for full framework
