### ISSUE TITLE
Concurrent tests using ApplicationInsights fail with concurrent modification exceptions

### ISSUE THREAD

**Issue by TyOverby** [Microsoft/ApplicationInsights-aspnetcore#651]
## Repro Steps
1. In Parallel
1. Create multiple `TestServer`s and use `ConfigureServices` to add `AddApplicationInsightsTelemetry`.
2. Dispose the TestServer

##  Actual Behavior

```
      <Output>
        <ErrorInfo>
          <Message>System.InvalidOperationException : Collection was modified; enumeration operation may not execute.</Message>
          <StackTrace>   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsInitializer.Dispose(Boolean disposing)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at MLS.Orchestrator.Tests.WebRequest_specs.&lt;When_request_provides_a_RequestId_Then_it_is_echoed_in_the_response&gt;d__0.MoveNext() in /home/tyoverby/workspace/trydotnet/orchestrator/MLS.Orchestrator.Tests/WebRequest_specs.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</StackTrace>
        </ErrorInfo>
      </Output>
```

## Expected Behavior
Should behave just like it would in a singlethreaded world.

## Version Info 
```
dotnet --version
2.1.300-preview1-008174
```

```
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0-beta1" />
    <PackageReference Include="microsoft.applicationinsights" Version="2.6.0-beta3" />
```

SDK VersiSDK Version : I don't know how to find this
.NET Version : I don't know how to find this	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : I don't know what this is.
OS : Linux
Hosting Info (IIS/Azure WebApps/ etc) :on : This is happening locally

**Comment by lmolkova** [comment]
Indeed, we can fail here https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/f696dd44f55055fad1774154219acf6c1e32c99b/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsInitializer.cs#L82 if the host is disposed immediately after started.

We miss synchronization between OnNext and Dispose.

**Comment by cijothomas** [comment]
Closed via https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/652
