### ISSUE TITLE
Duplicate telemetry via DiagnosticSourceTelemetryModule as TelemetryConfigurationOptions initializes it twice

### ISSUE THREAD

**Issue by rggammon** [Microsoft/ApplicationInsights-aspnetcore#653]
## Repro Steps
1.  Add DiagnosticSourceTelemetryModule - 
   I do this with 
     - services.ConfigureTelemetryModule<DiagnosticSourceTelemetryModule>
     - services.AddSingleton<ITelemetryModule, DiagnosticSourceTelemetryModule>();

##  Actual Behavior
I get two AI Trace messages with the same data for each DiagnosticsSource event

## Expected Behavior
One trace message per DiagnosticSource event

I think this is due to some code in TelemetryConfigurationOptions.cs where we apply two configs:
- TelemetryConfiguration.CreateDefault()
- TelemetryConfiguration.Active

via Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptionsSetup.Configure, which ends up calling DiagnosticSourceTelemetryModule.Initialize twice, which creates two subscription on DiagnosticListener.AllListeners, resulting in duplicate messages.

## Version Info 
SDK Version : 2.3.0-beta1
.NET Version :	core 2.0
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : added connected service
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by lmolkova** [comment]
`DiagnosticSourceTelemetryModule` is added by default, so you don't need to add it again.
Is there any particular reason you are adding it manually?

> I think this is due to some code in TelemetryConfigurationOptions.cs where we apply two configs:

> TelemetryConfiguration.CreateDefault()
> TelemetryConfiguration.Active

this is close, but not exactly correct, we are tracking this issue in the #621.

**Comment by rggammon** [comment]
I am adding it manually because it is not getting added by default for me - if you have a pointer to how this should be getting added, I could see what is going wrong here. I do not have multiple webhost's in the same process FWIW :)

**Comment by lmolkova** [comment]
We configure it here (inside `UseApplicationInsights` or `AddApplicaitonInsightsTelemetry` extension methods): 
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L151

What is the issue you observe? Why do you think you are not getting it by default?

Having multiple web hosts and configuring multiple `DiagnosticSourceTelemetryModule` leads to the same issue: multiple dependency tracking.

**Comment by rggammon** [comment]
This particular module is in https://github.com/Microsoft/ApplicationInsights-dotnet-logging and so is outside of the core set of ITelemetryModule's that get registered by Microsoft.ApplicationInsights.AspNetCore. 

As another example, https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-monitoring-aspnet shows adding ServiceRemotingDependencyTrackingTelemetryModule this way, which is another example of a registering a telemetry module that is not part of core appinsights. 

As for what I observe, if I don't call services.AddSingleton<ITelemetryModule, DiagnosticSourceTelemetryModule>(); then the delegate passed into ConfigureTelemetryModule<DiagnosticSourceTelemetryModule> does not get called, and no traces are reported, and DiagnosticSourceTelemetryModule is not injected into TelemetryConfigurationOptionsSetup's list of IEnumerable<ITelemetryModule> modules.

If I do call services.AddSingleton<ITelemetryModule, DiagnosticSourceTelemetryModule>(); then I see one instance of DiagnosticSourceTelemetryModule in the list injected into TelemetryConfigurationOptionsSetup, and DiagnosticSourceTelemetryModule.Initialize gets called twice as TelemetryConfigurationOptionsSetup.Configure gets called twice (for default and active configurations). The ConfigureTelemetryModule delegate also gets called twice on the same DiagnosticSourceTelemetryModule

**Comment by lmolkova** [comment]
@SergeyKanzhelev 
Do we expect all modules have protection from double-initialization? I'm reopening the issue assuming the answer is 'no', feel free to close it again.

**Comment by SergeyKanzhelev** [comment]
I doubt we will be able to prevent double-initialization. So modules should be agnostic for it. One problem that we can avoid is that today one can initialize module with different `TelemetryConfiguration` objects and behavior - where to send telemetry to is undefined after that. One of proposal from before was to make module implement some `IObesrvable` interface to reverse the control.

This issue is about this specific module. Perhaps - create another one if you want to track this work item.
