### ISSUE TITLE
Slowdown and time-out when using Microsoft.ApplicationInsights.AspNetCore 2.2.1 with a ASP.NET 

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/ApplicationInsights-aspnetcore#676]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Enable ApplicationInsights (use AI.AspNetCore 2.2.1) using the HostingStartup mechanism (call builder.UserApplicationInsights() from your custom IHostingStartup implementation)
2. Set "LogLevel": { "Default":"Debug"}
3. Deploy the application in Azure AppService. and notice the slow down & possible time-outs

##  Actual Behavior
All requests are slow & possibly time-out

I have collected profiler traces from Kudu: [profile_5506ae_dotnet_40196.zip](https://github.com/Microsoft/ApplicationInsights-aspnetcore/files/1984756/profile_5506ae_dotnet_40196.zip)
## Expected Behavior

If I user AI.AspNetCore 2.3.0-beta2 with the same configuration the slow-down disappears.

## Version Info 
SDK Version : 2.2.1
.NET Version :	 netcore 2.1-preview2						
How Application was onboarde

d with SDK(VisualStudio/StatusMonitor/Azure Extension) :  Azure App Service site extension that enables AI dynamically through HostingStartup (contact me for further details)
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by Dmitry-Matveev** [comment]
@clguimanMSFT, upon quick review of the sessions, I can see AI on the stack taking milliseconds for QuickPulse purposes (were Live Metrics enabled for this Resource at a time?) but nothing immediately concerning. Was there anything else that may help narrow down the issue?

It's great it does not repro with 2.3, we may be able to release 2.3 stable soon.

**Comment by clguimanMSFT** [comment]
That's all the information I have. I'll close the issue because version 2.3 seems to have fixed it.
