### ISSUE TITLE
Logging Debug level messages.

### ISSUE THREAD

**Issue by blindjustis** [Microsoft/ApplicationInsights-aspnetcore#688]
## Repro Steps
1. Create a default Asp.net core 2.0 WebApi project
2. Add Application Insights
3. **Edit Config files to make sure that the logging behaviour is the same in every environment**
4. Add the following in the Configure method of the Startup class: `loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Debug);`
5. Add logging to the parameters for constructor of the ValuesController
6. Add a debug and an error level log message in the GET Action
7. Deploy the application as an app service
7. In the Azure Portal navigate to the Application insights Live Metrics Stream for the Application Insights Endpoint
7. Open the Application Insights Endpoint query in visual studio or  analytics.applicationinsights.io
8. In the settings add the key `ASPNETCORE_ENVIRONMENT` with the value `production`
9. Call the GET method from something (browser, postman, fiddler etc.) (you may need to pump a couple of GET requests through before the live stream is available)
10. In the settings change the value  to `development` for the key  `ASPNETCORE_ENVIRONMENT` 
10. Call the GET method from something (if you restart the webserver after making the settings change you may need to pump a couple of GET requests through before the live stream is available)
12. wait for a bit
13. repeat the switches between production and development a few times

##  Actual Behavior
For ASPNETCORE_ENVIRONMENT == production, only the error level message appears, and appears in both the live stream and the chosen query tool.

For ASPNETCORE_ENVIRONMENT == development all the error messages appear in the live stream, none of them are available in the query tool

## Expected Behavior
`loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Debug);` would emit debug messages in any environment with severity 0

Some documentation about the non persistence of the development logging or how to control that  would be good.

## Version Info 
SDK Version : aspnet5c:2.2.1
.NET Version :	core 2.0 
with Microsoft.ApplicationInsights.AspNetCore Version="2.2.1" 					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : 
published from visual studio 2017 15.7.1, the application insights endpoint and app service were pre-created in the portal before publishing.
OS : windows web app
Hosting Info (IIS/Azure WebApps/ etc) : see above

**Comment by cijothomas** [comment]
@blindjustis The behavior of ApplicationInsights logger is not expected to be dependent on the envrionment variable ASPNETCORE_ENVIRONMENT.
Lets try to understand why you are experiencing this behavior. (I am not able to repro this)
1. Can you share your appsettings.json file for all environments? We need to double ensure that appsettings.json is same as it can control logger behavior.
2. Have you faced the same issue when trying locally? (i.e NOT on webapps)
  If you are using Visual Studio 2017, it may affect AI logger behavior, so please run the application from command line using dotnet myapp.dll
3. Have you installed ApplicationInsights extension in your WebApps?

**Comment by blindjustis** [comment]
@cijothomas 

So today, after changing `ASPNETCORE_ENVIRONMENT` to `development` again and restarting the app service (again), the trace messages are now appearing in `analytics.applicationinsights.io` with no other changes on our part.

In the test app we only had the one appsettings.config with no environment ones to keep all the environments the same HOWEVER the app had been used before for other tests, and the publish had not been configured to delete any extra files on the site , so there was an old appsettings.development.json.

The content was 

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  }
}
```

And I'm guessing that its the the entry for `LogLevel:Default` that made the difference?
(**can you confirm the interaction between specifying a log level in the AddApplicationInsights API and the config file Logging key please ?**)

The debug messages appear in production with the "LogLevel" key and values added to out app config.
