### ISSUE TITLE
InstrumentationKey is not readed from user secrets after update from asp.net core 2.0->2.1 

### ISSUE THREAD

**Issue by m-demydiuk** [microsoft/ApplicationInsights-aspnetcore#695]
Hi. After I updated asp net core to 2.1, seems InstrumentationKey is not readed from user secrets anymore.

If I set `InstrumentationKey` in the user secrets but not in `appsettings.json`, web app do not connects to the Azure portal dashboard. But if I set `InstrumentationKey` in the `appsettings.json`, then web app connects to Azure portal and I see my custom events.

## Repro Steps
1. Update version of asp.net core 2.0 -> 2.1 according to https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1
2. Launch the project

##  Actual Behavior
The web app does not connect to the Azure portal dashboard nor debug console and custom events do not appear.

## Expected Behavior
Web app connects to the Azure portal dashboard or visual studio debug console and custom events appear

## Version Info 
SDK Version : 2.1
.NET Version :	2.1 						
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : IIS express or visual studio

**Comment by cijothomas** [comment]
@m-demydiuk I am not sure how ikey was read from user secrets previously..Don't see any code doing that.
Can you point me to instructions which you used to onboard an application with application insights?

**Comment by mrfrankbell** [comment]
Secrets working for me on Asp.Net Core 2.1 after finding https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/535#issuecomment-358362345 :

> ... you need to make sure you remove the default .AddApplicationInsights() call from Program.cs and then add to your Startup.cs:
> services.AddApplicationInsightsTelemetry(Configuration);

**Comment by sidecus** [comment]
[This wiki](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-ASP.NET-CORE-2.0-WebApp) is suggesting that *IWebHostBuilder.UseApplicationInsights* in the preferred new way, instead of from within ConfigServices.

Not good that the preferred new way doesn't honor user secrets.

**Comment by Porges** [comment]
I'm seeing the same behaviour and I can't figure out why: `IConfiguration` definitely has `ApplicationInsights:InstrumentationKey` set from user secrets, but it remains unconfigured. It only works if the setting is in one of the `appsettings.json` files.

**Comment by cijothomas** [comment]
Closing this .
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core doc explains how SDK reads ikeys.

Please reopen or file a new issue for new questions.
