### ISSUE TITLE
Plans for automatic exception tracking middleware?

### ISSUE THREAD

**Issue by anblanco** [Microsoft/ApplicationInsights-aspnetcore#698]
I’m curious if there are any plans for UseApplicationInsights() to automatically add an exception tracking middleware in ASP.NET core.

I can write one up myself for my project, but I was curious if there was an intentional design decision not to include one (or if you’ll accept a PR for it)

**Comment by cijothomas** [comment]
The existing ExceptionTracking middleware was made obsolete, in favor of DiagnosticSource based request monitoring which tracks exception as well. 
Can you describe the scenario where this is not sufficient ? 

(And yes we always welcome PRs. But for this particular issue, lets discuss further the exact requirements)

**Comment by anblanco** [comment]
Oh cool, I did not realize that the DiagnosticSource already tracked it. 

In ASP.NET Classic I had to write my own filters and exception handlers for MVC / Web API, but it looks like this is all automatically handled for me in ASP.NET Core.

Thanks for the clarification!

**Comment by cijothomas** [comment]
@anblanco We only track those exceptions which propagate all the way back through the request pipeline. If you have some exception filter added to handle exceptions then exception won't be propagated all the way up, and hence you may still need to call `TrackException(ex)` in those cases.
