### ISSUE TITLE
question: adaptive sampling

### ISSUE THREAD

**Issue by funkycoding** [Microsoft/ApplicationInsights-aspnetcore#703]
In the code i see this construct, i can't really figure out what i means, can someone explain this?

```
configuration.TelemetryProcessorChainBuilder.UseAdaptiveSampling(5, excludedTypes: "Event");
configuration.TelemetryProcessorChainBuilder.UseAdaptiveSampling(5, includedTypes: "Event");
```

Regards,
Mark

**Comment by SergeyKanzhelev** [comment]
it means that SDK will try to send not more than 5 `Events` per second and not more than 5 other types per second. So if you have a high thopughput app that serves hundreds of requests - you will collect information about subset of requests. If only handful of collected requests result in "Check out" event - those events will not be lost. Makes sense?

**Comment by SergeyKanzhelev** [comment]
Basically sampling of diagnostics telemetry will not affect sampling of business telemetry

**Comment by funkycoding** [comment]
Makes sense, thanks!
