### ISSUE TITLE
ASP.NET Core 2.1 apps do not have the ApplicationInsightsLogger registered in the logging configuration

### ISSUE THREAD

**Issue by asosMikeGore** [Microsoft/ApplicationInsights-aspnetcore#706]
Since upgrading an API to ASP.NET Core 2.1 I have noticed that only request telemetry is being captured.  Is this an intentional design decision?  If so what should we be doing to register Application Insights as a logger on the logging builder?

When targeting ASP.NET Core 2.0 I get trace telemetry sent without any changes to code.

## Repro Steps
1. Create a new ASP.NET Core 2.1 application
2. Add Application Insights support
3. Run the application and inspect the telemetry being captured by Application Insights

##  Actual Behavior
1. Only request telemetry is being sent to Application Insights.

## Expected Behavior
1. Request telemetry is sent to Application Insights.
2. Trace telemetry is sent to Application Insights as the ApplicationInsightsLogger has been registered and therefore calls to ILogger are sent to AI as trace telemetry.

## Version Info 
SDK Version : 2.1.1
.NET Version : .NET Core 2.1	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel

**Comment by cijothomas** [comment]
Prior to 2.1, how did you enable logging? Did you explicitly add logging like below ?
` loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Warning); `
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging

You'll need to explicitly do the above step to enable AI capturing ILogger traces.

**Comment by cijothomas** [comment]
Oh actually - If you were running the app from VS (F5) itself, then VS automatically enabled logging capture. But this won't work in 2.1.

**Comment by asosMikeGore** [comment]
I'm just doing what the getting started docs say here:
[https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started)

```csharp
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .UseStartup<Startup>()
                .Build();
```
What I hadn't realised is that the logger in the 2.0 app was added due to debug mode.  Adding it via the logger factory sorted the problem out.  Thanks for your help with this.

**Comment by cijothomas** [comment]
Glad to see your issue is solved! Please reopen if more help needed.

**Comment by derth** [comment]
@cijothomas 
This page says that you can log Ilogger traces in application-insights as long as you create them inside visual studio: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging

This is not true for aspnet v2.1 as you say in the comment above.

You should change it because it's confusing for people trying to test application-insights from inside VS.
