### ISSUE TITLE
Logging Request Response on 400 error

### ISSUE THREAD

**Issue by johnkwaters** [Microsoft/ApplicationInsights-aspnetcore#712]
I am adding some custom telemetry, and wanted to add the provision that when you get a 400 Bad Request back in my dotnetcore 2.1.1 ApiController, I want to attach the response body to the telemetry. However, I can't seem to find a way to read the response body. Any ideas? Code is below:

`    public class JsonTelemetryInitializer : ITelemetryInitializer
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="accessor">For accessing the http context</param>
        public JsonTelemetryInitializer(IHttpContextAccessor accessor)
        {
            _httpContextAccessor = accessor;
        }

        /// <summary>
        /// Initialize the custom telemetry initializer
        /// </summary>
        /// <param name="telemetry">Telemetry</param>
        public void Initialize(ITelemetry telemetry)
        {
            if (_httpContextAccessor.HttpContext == null)
            {
                return;
            }

            if (_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                const string tenantId = "northstar_tenantid";
                if (!telemetry.Context.Properties.ContainsKey(tenantId))
                {
                    var user = _httpContextAccessor.HttpContext.User;
                    telemetry.Context.Properties[tenantId] =
                        ClaimsHelper.GetClaim<int>(user, TokenNames.TenantId).ToString();
                    telemetry.Context.Properties["northstar_userid"] =
                        ClaimsHelper.GetClaim<int>(user, TokenNames.UserId).ToString();
                }
            }

            if (telemetry is RequestTelemetry requestTelemetry)
            {
                var ctxt = _httpContextAccessor.HttpContext;
                if ((ctxt.Request.Method == HttpMethods.Post || ctxt.Request.Method == HttpMethods.Put) &&
                    ctxt.Request.Body.CanRead)
                {
                    const string requestBody = "JsonRequestBody";

                    // this method is called once before the request, once after, so only log the 
                    // properties once (on the before)
                    if (!requestTelemetry.Properties.ContainsKey(requestBody))
                    {
                        ctxt.Request.EnableRewind();
                        var sr = new StreamReader(ctxt.Request.Body);
                        var bodyContent = sr.ReadToEnd();
                        if (bodyContent.Contains("password"))
                        {
                            // don't log passwords!
                            bodyContent = "contains sensitive information, hidden";
                        }

                        ctxt.Request.Body.Position = 0;
                        requestTelemetry.Properties.Add(requestBody, bodyContent);
                    }
                }

                if (requestTelemetry.ResponseCode == "400")
                {
                }
            }
        }
    }
}`

**Comment by lmolkova** [comment]
You have to use `EnableRewind` carefully see: https://github.com/aspnet/Mvc/issues/4962. 

ApplicationInsights SDK does not read request/response bodies and never logs them, i.e. there is no 'standard' way to achieve it. 

Depending on your code you may just call TelemetryClient.TrackTrace(body) from your controller where you actually read request stream so you don't have to read it twice.

I'm closing this issue for now. Feel free to reopen as needed.
If you have questions about `EnableRewind` usage, [AspNet team](https://github.com/aspnet/Home) has much more expertise on it!

**Comment by johnkwaters** [comment]
Thanks - but I don’t think there is an enablerewind on the response - just the request ?

**Comment by ThiruKM** [comment]
I resolved using the following approach
https://thirum.wordpress.com/2019/08/19/logging-the-http-response-body-in-application-insights/

**Comment by ThiruKM** [comment]
> @johnkwaters I am having same issue as yours (Logging request response in Initializer); have you found any solution?

I resolved it using the following approach

https://thirum.wordpress.com/2019/08/19/logging-the-http-response-body-in-application-insights/
