### ISSUE TITLE
Http Request Rate not showing up asp.net core (even backed by full .net)

### ISSUE THREAD

**Issue by sadjadbp** [Microsoft/ApplicationInsights-aspnetcore#713]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Setup AppInsights for asp.net core project backed by .net full

##  Actual Behavior
Http Request Rate shows nothing 

## Expected Behavior
Http Request rate should show up via performance counters

## Version Info 
SDK Version : 2.3.0
.NET Version : .Net Core 2.1.1	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : WinServer 2018
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by cijothomas** [comment]
I don't think asp.net counters are populated when using a asp.net core app (even if targeting .net framework)
Do you see values to these counters when using tools like perfmon?

**Comment by cijothomas** [comment]
Closing this. Please reopen if you think this is a bug.
(If the counters are populated, and SDK does not collect them, we can investigate more, but I don't think asp.net core apps get any of the counters like those in classic asp.net. (irrespective of the target framework)
