### ISSUE TITLE
ASPNET CORE AI Custom Logger

### ISSUE THREAD

**Issue by joshidp** [Microsoft/ApplicationInsights-aspnetcore#715]
Hi AI team,

I am using ASPNET CORE 2.1 and a custom AppIndight logger class. I need to set up the following things

- Correlation ID generation with Http Header setup.
- Custom TelemetryInitializer but I am not sure how to initialize ITelemetryInitializer, will it be per request or not?
- If I use custom logger do I still need to call  services.AddApplicationInsights?
- If I use custom logger will it track the request/dependencies by itself?

Please suggest the ideal way of doing this.

Thanks

**Comment by cijothomas** [comment]
Closing.
 please re-open if you need more help here.
