### ISSUE TITLE
Update Microsoft.Extensions.DiagnosticAdapter version to 2.1.0

### ISSUE THREAD

**Issue by eduherminio** [Microsoft/ApplicationInsights-aspnetcore#721]
`Microsoft.ApplicationInsights.AspNetCore` newest versions reference `Microsoft.Extensions.DiagnosticAdapter` v1.x, which has [this bug](https://github.com/aspnet/Hosting/issues/1312); that seems to appear again when ApplicationInsights package is used.

(See https://github.com/aspnet/Hosting/issues/1312#issuecomment-404007570).

Would it be possible to update the version of that dependency?

**Comment by lmolkova** [comment]
it's a bit more complicated than simple version update because version 2.1.0 does not target netstandard1.6 which ApplicaitonInsights SDK targets. We'll need to retarget the AI SDK to netstandard2.0

@SergeyKanzhelev @cijothomas what do you think?

**Comment by SergeyKanzhelev** [comment]
oh, I thought we already have separate target for `netstandard2.0`. @davidfowl I remember you tweeted that this is the best practice?

**Comment by lmolkova** [comment]
This is what we target: 
```xml
    <TargetFrameworks>net451;net46;netstandard1.6</TargetFrameworks>
```

**Comment by SergeyKanzhelev** [comment]
ok. thanks. Maybe split to netstandard2.0 separately... perhaps it can be done after the stable we about to ship to avoid unintended problems

**Comment by cijothomas** [comment]
I'll check if this can be done for the upcoming stable 2.5.0 release.
