### ISSUE TITLE
How to vary Insutrmenttion Key based on Envrionment?

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/ApplicationInsights-aspnetcore#726]
I'd like to use different instrumentation key based on environment (local, dev, test, prod). What is supported/recommended way to achieve this? Where in ASP.NET Core configuration/startup pipeline I plug it in? Can I use dependency injection (I have a class that would provide me current environment or the key based on it)?

## Version Info 
SDK Version : 2.3.0
.NET Version : .NET Core 2.1

**Comment by cijothomas** [comment]
Instrumentation key can be supplied via Environment variable or Appsettings.json file, apart from code. You could have different settings.json file/ENV variable for each environment to vary ikeys.

https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#configuration-based-approach
