### ISSUE TITLE
loggerFactory.AddApplicationInsights should read LogLevel from configuration

### ISSUE THREAD

**Issue by briandunnington** [Microsoft/ApplicationInsights-aspnetcore#731]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
Used the AddApplicationInsights() extension method

##  Actual Behavior
Using the `AddApplicationInsights()` extension method requires passing in a specific LogLevel (or it defaults to LogLevel.Warning if not passed)

## Expected Behavior
It would be nice if the default behavior was to read the LogLevel from the Configuration so that this could be controlled without having to make a code change.

## Version Info 
SDK Version : 2.3.0

Source code: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/725a7bd3239438415fa82eb1445442cce7f999cf/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs

**Comment by briandunnington** [comment]
I tried the following as suggested by @cijothomas in another issue, but it does not work. Specifically I am interested in controlling the telemetry (trace) default log level.

"Logging": {
    "IncludeScopes": false,
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "None"
      }
    },
    "LogLevel": {
      "Default": "Warning"
    }
  }

**Comment by cijothomas** [comment]
@briandunnington 
I just tried this and works without issues.

Here's what I did:
1. Enabled logging with this call `loggerFactory.AddApplicationInsights(app.ApplicationServices);`. Note: I did not pass logging level here.
2. Modified a controller to emit logs of all Levels as shown below:
```
        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            _logger.LogTrace("My Trace Log");
            _logger.LogDebug("My Debug Log");
            _logger.LogInformation("My Information Log");
            _logger.LogWarning("My Warning Log");
            _logger.LogError("My Error Log");
            _logger.LogCritical("My Critical Log");

            return new string[] { "value1", "value2" };
        }
```
3. Added following in appsettings.json
```
"Logging": { 
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "None"
      }
    }
```

Ran the app - I see no logs capture by AI.
Changed loglevel in appsettings.json to Warning, and then ran the app. AI now captures logs above Warning level.

Can you make sure that appsettings.json is copied to the published location?

**Comment by tamirdresher** [comment]
@cijothomas 
You can clearly see in the code [file ](https://github.com/Microsoft/ApplicationInsights-aspnetcore/tree/develop/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs) that `LogLevel.Warning` is used if you're not passing the LogLevel yourself
       
 ```
public static ILoggerFactory AddApplicationInsights(this ILoggerFactory factory, IServiceProvider serviceProvider)
{
       return factory.AddApplicationInsights(serviceProvider, LogLevel.Warning);
}
```

I'm not sure why your example worked

**Comment by cijothomas** [comment]
"Logging": { 
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "None"
      }
    }

This overrides the log level.

**Comment by FarronV1** [comment]
This works if the LogLevel in appsettings is set to None, Critical, Error or Warning. If it's set to a lower level such as information it won't actually send unless AddApplicationInsights has a LogLevel of that level or lower.

Is this the expected behavior? It seems like there's two layers of checks and the app setting and the value passed in both need to be of the log level or lower for it to work.

To get the functionality I want of getting my own logs to appear and controlling this in config rather than code I use this in startup:

`loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Trace);`

And then in my settings something like this
`"Logging": { 
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Debug",
        "Microsoft": "Warning"
      }
    }`

This logs all my own debug or higher but suppresses anything with a Microsoft prefix unless it's warning or higher.
