### ISSUE TITLE
Collecting CPU, memory and performance metrics is not supported in .net Core SDK

### ISSUE THREAD

**Issue by hiraldesai** [Microsoft/ApplicationInsights-aspnetcore#732]
Is this a temporary limitation or a permanent one? Is there a workaround?

![image](https://user-images.githubusercontent.com/1005174/43742333-66868fe2-9986-11e8-88bf-8c6993d5d56d.png)

## Version Info 
SDK Version : 2.3.0
.NET Version : dotnet core 2.1 (SDK 2.1.300)	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Azure Extension + NuGet in code
Hosting Info (IIS/Azure WebApps/ etc) : Azure Web App

**Comment by cijothomas** [comment]
Likely permanent - There is not API in .net core to collect perf counters yet.

Since you are on Azure WebApp, you'll get some perf counter support if you update to 2.4.0-beta1 or higher. 2.4 stable is coming this week.

**Comment by hiraldesai** [comment]
Thank you - I will start using the new release as it releases.

**Comment by cijothomas** [comment]
@hiraldesai https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.4.0 This is released to nuget now.

**Comment by hiraldesai** [comment]
I upgraded our project and committed memory and CPU is showing up even for a dotnet core app.
