### ISSUE TITLE
EVENT Statistics stopped collecting events at page level after .net core 2.1 update

### ISSUE THREAD

**Issue by sasind** [Microsoft/ApplicationInsights-aspnetcore#739]
## Repro Steps
Update project to .NET core 2.1

##  Actual Behavior
Event statistics not capturing page level events 

![image](https://user-images.githubusercontent.com/42284141/43984423-5d8f69fe-9cb5-11e8-950a-231f6030c0a4.png)

## Expected Behavior
Event statistics should capture page level events

![image](https://user-images.githubusercontent.com/42284141/43984418-53bef8e0-9cb5-11e8-9205-72cf1d387b37.png)

## Version Info 
SDK Version : 2.1
.NET Version :	 						

IIS

**Comment by cijothomas** [comment]
@sasind Please describe the issue bit more with repro steps.
