### ISSUE TITLE
How to set Role Name from config directly with out modifying the code like Instrumentation Key. ?

### ISSUE THREAD

**Issue by bodhisatta1984** [Microsoft/ApplicationInsights-aspnetcore#740]
There needs to be property exposed to configuration setting where we can set Role Name like Instrumentation Key.

**Comment by cijothomas** [comment]
You can write a telemetry initializer which can read the role name from config/other place, and populate it accordingly. SDK does not allow an option to set role name.

**Comment by cijothomas** [comment]
Closing this. Please reopen if you require further help with this.
