### ISSUE TITLE
webHostBuilder.UseApplicationInsights conflicts with custom log provider

### ISSUE THREAD

**Issue by v-caxian** [Microsoft/ApplicationInsights-aspnetcore#745]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create a web application
2. Add the code `.UseApplicationInsights()` in Program.cs
3. Add the code   ```
"ApplicationInsights": {
    "InstrumentationKey": "InstrumentationKey-A"
  } ``` in appsettings.json
4. Add the code `services.AddApplicationInsightsTelemetry("InstrumentationKey-B")` or ``` services.AddSingleton(new TelemetryClient()
            {
                InstrumentationKey = "InstrumentationKey-B"
            }) ``` in Startup.cs.
5. Add the code in a controller 
```
 [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly TelemetryClient _telemetryClient;

        public ValuesController(TelemetryClient telemetryClient)
        {
            _telemetryClient = telemetryClient;
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            var message = $"value-{id}";
            _telemetryClient.TrackTrace(message);

            return message;
        }
    }
```
##  Actual Behavior
Assume the InstrumentationKey-A is associated with ApplicationInsight-A and the InstrumentationKey-B is associated with ApplicationInsight-B.

Whenever I visit my web service, I always see a lot of logs in "ApplicationInsight-B" that should be logged in "ApplicationInsight-A" that makes me confused.

## Expected Behavior
`UseApplicationInsights` can be used with custom log provider. And the logs should be stored in different ApplicationInsights.

## Version Info 
SDK Version : 2.4.1
.NET Version : NET Core 2.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Microsoft Windows Server 2016 Datacenter - 14393
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by cijothomas** [comment]
Do not use both `UseApplicationInsights()` and `AddApplicationInsigtsTelemetry()`. The ikey supplied in appsettings.json will be picked up by the default configuration and hence by the default TelemetryClient which gets Constructor injected.

If your use case if to use a separate ikey for all the custom logs you track via explicit `Track...()` methods, then you can modify ikey on that telemetry client. (which gets reflected in any controllers which has TelemetryClient injected, but not on the auto-collection modules which collects Requests, Dependencies etc)

```
[Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly TelemetryClient _telemetryClient;

        public ValuesController(TelemetryClient telemetryClient)
        {
            _telemetryClient = telemetryClient;
                       _telemetryClient.InstrumentationKey = "ikeyForCustomEvents";
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            var message = $"value-{id}";
            _telemetryClient.TrackTrace(message);

            return message;
        }
    }
```

**Comment by v-caxian** [comment]
Thanks @cijothomas, 
Our log provider implements the `Microsoft.Extensions.Logging.ILogger<out TCategoryName>` interface and uses the TelemetryClient internally. Do you have any way to avoid the class received any request from the automation module? I have tried the solution you mentioned above but it doesn't work. The code part as below.
```
public static IServiceCollection AddApplicationInsights(this IServiceCollection services, Action<AppInsightsOptions> options)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));
            if (options == null) throw new ArgumentNullException(nameof(options));

            services.AddTransient(typeof(ILogger<>), typeof(ApplicationInsightsLogger<>));
            services.Configure(options);

            return services;
        }

 public class ApplicationInsightsLogger<T> : ILogger<T>
    {
        private readonly TelemetryClient _telemetryClient;
        private readonly AppInsightsOptions _options;

        public ApplicationInsightsLogger(IOptions<AppInsightsOptions> options)
        {
            _options = options.Value ?? throw new ArgumentNullException(nameof(options));
            _telemetryClient = new TelemetryClient()
            {
                InstrumentationKey = _options.InstrumentationKey
            };
        }

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception,
            Func<TState, Exception, string> formatter)
        {
            if (!IsEnabled(logLevel)) return;
            var logEntry = state as LogEntry;
            if (exception == null && formatter == null)
            {
                LogTrace(logLevel, eventId, logEntry);
            }
            else
            {
                LogException(logLevel, state, exception, formatter);
            }
        }
    }
```

**Comment by 961951000** [comment]
Fixed using  ApplicationInsightsLoggerFactoryExtensions
