### ISSUE TITLE
Improve how exception looks like for dnxcore

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-aspnetcore#75]
PCL collects stack as exception.StackTrace string. We may want to improve this in Core.

**Comment by djob195** [comment]
Hi, I have the following questions:

1) In what aspects do you want the exeption to improve?
2) Is there the issues, which can help me?

Thank you, I await your response...

**Comment by gzepeda** [comment]
Hello, 

Any specifics on how can this be improved?

**Comment by SergeyKanzhelev** [comment]
@gzepeda this was fixed by https://github.com/Microsoft/ApplicationInsights-dotnet/pull/521 Thanks for asking!
