### ISSUE TITLE
ApplicationInsightsLoggingProvider not injected

### ISSUE THREAD

**Issue by reerden** [Microsoft/ApplicationInsights-aspnetcore#750]
## Repro Steps
Program.cs:
```
public static IWebHost BuildWebHost(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration(config =>
        {
            config.SetBasePath(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));
        })
        .ConfigureLogging(factory =>
        {
            factory.AddConsole();
            factory.AddDebug();
            factory.AddAzureWebAppDiagnostics();
        })
        .UseStartup<Startup>()
        .Build();
}
```
Startup.cs:
```
public Startup(IConfiguration configuration, IHostingEnvironment environment)
{
    Configuration = configuration;
    HostingEnvironment = environment;
}

public IConfiguration Configuration { get; }

public IHostingEnvironment HostingEnvironment { get; }

public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry(Configuration);
    services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Information);
    app.UseMvc();
}
```
appsettings.json:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information"
    }
  }
}
```
appsettings.dev.json
```
  "ApplicationInsights": {
    "InstrumentationKey": "......."
  }
````

TestController.cs -> **WebApi project** (Injects DebugLoggerProvider, ConsoleLoggerProvider and **ApplicationInsightsLoggerProvider** into logger)
```
private readonly Microsoft.Extensions.Logging.ILogger<TestController> _logger;

public TestController(ILogger<TestController> logger)
{
    _logger = logger; // Contains DebugLoggerProvider, ConsoleLoggerProvider and ApplicationInsightsLoggerProvider 
}
```
TestRepository.cs -> **DataAccess project** (Injects only **DebugLoggerProvider, ConsoleLoggerProvider** into logger)
```
private readonly Microsoft.Extensions.Logging.ILogger<TestRepository> _logger;

public TestRepository(ILogger<TestRepository> logger)
{
    _logger = logger; // Contains DebugLoggerProvider, ConsoleLoggerProvider
}
```

##  Actual Behavior
In the startup WebApi project, **three** logger providers are injected:

- DebugLoggerProvider
- ConsoleLoggerProvider
- ApplicationInsightsLoggerProvider 

In the referenced DataAccess project, **two** logger providers are injected:

- DebugLoggerProvider
- ConsoleLoggerProvider

## Expected Behavior
I expect the ApplicationInsightsLoggerProvider to be injected in the Microsoft.Extensions.Logging.ILogger instance in all referenced projects.

## Version Info 
SDK Version : 2.1.401
.NET Version :  .NET Core 2.1	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Azure

**Comment by Quass1m** [comment]
Having the same problem. If I don't provide any values to AddApplicationInsightsTelemetry() method then the logger is being injected but has no instrumentation key.

**Comment by reerden** [comment]
@Quass1m That's not working for me. Still no ApplicationInsightsLoggerProvider injected.

**Comment by varadhan3n90** [comment]
It is working with .Net Core 2.0 but does not work with .Net core 2.1

**Comment by RamjotSingh** [comment]
I think this should be fixed with the new separate logging package. https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights/2.9.0-beta3


```cs
.ConfigureLogging(loggingBuilder =>
        {
            loggingBuilder.AddApplicationInsights();
        })
```

**Comment by cijothomas** [comment]
@reerden  The referenced DataAccess project - how have you enabled ApplicationInsights in that project? It does not look like you enabled application insights logger in that project. Debug and Console is available there because those are added by default if you are using standard project templates.

**Comment by cijothomas** [comment]
@varadhan3n90 When you say it works in .net 2.0  but not in .net core 2.1, do you mean that when you run the app from visual studio, you can see Ilogger logs captured automatically? If yes, its because visual studio auto injects and enables SDK in .net core 2.0. This feature is no longer supported in net core 2.1 onwards. You need to explicitly add/enable application inssights.

**Comment by cijothomas** [comment]
@RamjotSingh I don't see how using new package would help here? can you help understand it?

**Comment by RamjotSingh** [comment]
The new package should add the LoggerProvider. My guess is the problem here is that the LoggerProvider is not getting registered properly due to ILoggerBuilder being used which is something newer package added support for.

**Comment by reerden** [comment]
@cijothomas We didn't enable ApplicationInsights for the referenced projects. That's something we typically don't want to do for every project in the solution (startup project only).

After updating to the new package (like @RamjotSingh mentiones) , it's working as expected! Thanks.
