### ISSUE TITLE
Unable to use the ApplicationInsights.AspNetCore with Microsoft.Extensions.Logging of version higher than 1.1.2

### ISSUE THREAD

**Issue by snowpardx** [Microsoft/ApplicationInsights-aspnetcore#756]
Hello,
I attempting to use Microsoft.ApplicationInsights.AspNetCore package with up-to-date Microsoft.Extensions.Logging package. Unfortunately when Microsoft.Extensions.Logging of version higher than 1.1.2(e.g. 2.1.1) in use there is runtimer error caused by old version of Microsoft.Extensions.Configuration which Microsoft.ApplicationInsights.AspNetCore want.

## Repro Steps
I created small sample which demonstrates the behaviour above. https://github.com/snowpardx/app-insights-failure/tree/master

And if try to run, we get the following exception
![image](https://user-images.githubusercontent.com/3825438/45905988-55b65180-bda7-11e8-8653-6b47386f295f.png)

If switch to https://github.com/snowpardx/app-insights-failure/tree/no-error-if-using-old-package
Where only difference is 
![image](https://user-images.githubusercontent.com/3825438/45906074-a3cb5500-bda7-11e8-9f8e-f2c3998b5981.png)

The runtime error gone.

Could you please check it out and provide the guidance how to use the package with recent versions of Microsoft.Extensions.Logging?

**Comment by cijothomas** [comment]
We are planning to add NETSTANDARD2.0 target to the SDK and update the logging packages to 2.XX version along with that. Its tagged for the upcoming stable release, so ~1-2 month ETA.
Thanks for your patience!

**Comment by RamjotSingh** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights/2.9.0-beta3 should help with this error I think.

**Comment by snowpardx** [comment]
@RamjotSingh thanks for the link, having the ILogger implementation (https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239 ) in main AppInsights repo is awesome. By the way it still doesn't allow use Microsoft.ApplicationInsights.AspNetCore package with Microsoft.Extensions.Logging v 2.* some reason to use this package are metrics additionally collected and rich customization possibilities (e.g. we can inject TelemetryClient here).

**Comment by cijothomas** [comment]
WIP https://github.com/Microsoft/ApplicationInsights-aspnetcore/compare/develop...cithomas/net20target
Started on this. Planning to complete this before next week :)
