### ISSUE TITLE
Question: Server Telemetry Channel behavior

### ISSUE THREAD

**Issue by zauggm** [Microsoft/ApplicationInsights-aspnetcore#757]
I have a question about the expected behavior of the Server Telemetry Channel when internet connection is lost.  I am working on an application that may periodically lose connection to the internet. The application is deployed local so it can still be used by consumers but the service would not always be able to send telemetry data right away.  

My understanding is that Server Telemetry handles this scenario by persisting telemetry until connection is reestablished. I've been testing this situation and have found that when the internet connection is lost, network still connected but not connected to internet, telemetry is not persisted and is lost forever.  The only way I've been able to get data to persist is by physically disconnecting the test machine from the network.

Is my understanding of how Server Telemetry Channel handles offline scenarios correct?  If so, am I missing some form of configuration that enables the feature?

## Version Info 
SDK Version : 2.4.1
.NET Version :	2.2.100-preview2-009404 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10 Pro 64-bit
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by cijothomas** [comment]
There is bug which affects when there is network, but not internet. Tracking here.
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/796
