### ISSUE TITLE
Add TrackAvailability method

### ISSUE THREAD

**Issue by Orekhov** [Microsoft/ApplicationInsights-aspnetcore#758]
[TrackAvailability](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient.trackavailability?view=azure-dotnet) method is very useful in cases when availability tests feature can't be used. It is available in the .NET package, but is missing in .net core.

As more and more projects are being created with .net core, this method is very valuable to have.

**Comment by cijothomas** [comment]
@Orekhov `TrackAvailability`  and all other methods in `TelemetryClient` is available in both .NET Framework and .NET Core. 
All public methods in TelemetryClient is compiled against netstandard as well - Please let us know if you are having issues using this with .net core apps.
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/TelemetryClient.cs
