### ISSUE TITLE
Question: correct way of adding telemetry initializer to Azure Functions host

### ISSUE THREAD

**Issue by hiraldesai** [Microsoft/ApplicationInsights-aspnetcore#759]
The telemetry initializer I created in #725 works fine for a dotnet core 2.1 API. I want to also use the same initializer in Azure Functions V2 app. What is the correct way of bootstrapping this in the Azure Functions host?

**Comment by lmolkova** [comment]
@brettsam 
we've discussed that Functions will allow to access to host dependency injection container and configure things. Is it something that has been recently added or planned?

I believe so far the answer is: there is no way of doing this.

**Comment by cijothomas** [comment]
Closing this - as of now Azure functions does not allow configuring new TelemetryInitializers, but this may change in future.

**Comment by brettsam** [comment]
Sorry for the delay -- we do support this in v2. You can register an `IWebJobsStartup` which we'll call during initialization and it gives you a place to plug in your own services. Since we pull all of our ITelemetryInitializers from DI, this should work. I just did a really quick example in a new app in VS and I saw my initializer get called.

We don't have docs on any of this DI extensibility (yet), but here's what I did. I set a breakpoint in the Intialize() method and it got hit once I hit F5 and the host started running:

```
using FunctionApp35;
using Microsoft.ApplicationInsights.Channel;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;
using Microsoft.Extensions.DependencyInjection;

[assembly: WebJobsStartup(typeof(MyStartup))]

namespace FunctionApp35
{
    internal class MyTelemetryInitializer : ITelemetryInitializer
    {
        public void Initialize(ITelemetry telemetry)
        {
        }
    }

    public class MyStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.Services.AddSingleton<ITelemetryInitializer, MyTelemetryInitializer>();
        }
    }
}
```

**Comment by hiraldesai** [comment]
I had tried this already before raising but couldn't get the initializer to hit a break point. Let me do some more tests. The only difference in my function is that I have 

```
builder.AddExtension<InjectConfiguration>();
```

And `InjectConfiguration : IExtensionConfigProvider` is a bootstrapper that initializes our own `ServiceCollection`, adds Azure KeyVault configuration, AppInsights, and a lot of other service registrations using `Autofac`. We inject these things as `[Inject] IServiceName` into all our functions.

**Comment by brettsam** [comment]
If you're creating your own ServiceCollection, then the host doesn't know about it, which is why you're not seeing it get used. Services need to be registered with the host's service collection, which is exposed via `IWebJobsBuilder.Services`.

FYI -- `[Inject]` isn't an official binding, but we'll have proper DI injection support coming very soon (a lot of the code is already merged; just not shipped). Some of the pieces are already released -- like the ability to inject services that we'll use internally, which is why this specific example of `ITelemetryInitializer` works.

**Comment by hiraldesai** [comment]
Yes - I thought so too. I suppose we will wait till the feature is available and do a full revision of our IoC. [Inject] was just added because there was no DI when we first started with Functions V2 preview but we wanted some way of doing DI.

Q1: How long before full DI support will be available - will it support external containers like how dotnet core apps do?
Q2: Is there some sort of workaround in its current state that can work for us (using ServiceCollection + AutoFac hybrid)? Some of our injections are complex and not supported by default ServiceCollection.

**Comment by brettsam** [comment]
@hiraldesai -- Do you want to throw your questions over on the "core" DI issue we've got? That'll let us track and answer them better: https://github.com/Azure/azure-functions-host/issues/1579

For Q2 -- can you give some examples of the complex injections you're doing with AutoFac? That'll give us some good customer scenarios.

**Comment by hiraldesai** [comment]
I've posted Q1 there.

For Q2 - one of the examples I have is named instances support that Autofac provides but ServiceCollection doesn't. Something like this:

```
public static void AddBlobStorages(this ContainerBuilder builder, IConfiguration config)
{
	var connectionString = config["StorageConnectionString"];

	var containers = new List<(string ContainerName, string InstanceName)>
			 {
				( "EmailTemplates", "EmailTemplatesBlob"),
				( "Artifacts", "ArtifactsBlob"),
				( "Workflows", "WorkflowsBlob")
			 };

	foreach (var pair in containers)
		builder.RegisterInstance(new AzureBlobStorage(connectionString, config[pair.ContainerName])).Named<IBlobStorage>(pair.InstanceName);
}


public static void AddService(this ContainerBuilder builder)
{
	builder.RegisterType<MyService>()
				   .As<IService>()
				   .WithParameter
				   (
					   (pi, ctx) => pi.ParameterType == typeof(IBlobStorage) &&
									string.Equals(pi.Name, "ArtifactsBlob", StringComparison.InvariantCultureIgnoreCase),
					   (pi, ctx) => ctx.ResolveNamed<IBlobStorage>("ArtifactsBlob")
				   )
				   .WithParameter
				   (
					   (pi, ctx) => pi.ParameterType == typeof(IBlobStorage) &&
									string.Equals(pi.Name, "EmailTemplatesBlob", StringComparison.InvariantCultureIgnoreCase),
					   (pi, ctx) => ctx.ResolveNamed<IBlobStorage>("EmailTemplatesBlob")
				   );
}

public class MyService : IService 
{
	public MyService(ISomeService someService, ISomeOtherService someOtherService, IBlobContainer artifactsBlob, IBlobContainer emailTemplatesBlob)
	{
		
	}
}
```

**Comment by brettsam** [comment]
Note that I've updated my code above with the following disclaimer:

_Disclaimer -- I want to be clear that while adding additional `ITelemetryInitializer`s in this way will be supported going forward, it is no guarantee that the replacement or composition of other internal services will be supported forever. We are currently working on official guidance on what will be supported (and how) for Functions dependency injection. This guidance will include a list of supported services and their lifetime scopes. Any other internal service registrations may fail in future releases._

**Comment by ins4n333** [comment]
Hi @brettsam.
I tried to use https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/759#issuecomment-426687852 for adding custom TelemetryInitializers. 
But it still doest not work for me. Debugger also doesnt reach Initialize method. It looks as telemetryconfiguration with all telemetryInitializers are configured before my custom Configure(IWebJobsBuilder builder).
In my func project I use next packages:
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.5.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.6.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.23" />

May be there is another way to add TelemetryInitializers?

**Comment by mayoatbm** [comment]
@brettsam 

It looks like the unofficial (your disclaimer is noted) usage you posted above doesn't  appear to be working in the latest version of the sdk. We had used it successfully for at least three months.

Is that expected?

**Comment by lmolkova** [comment]
@mayoatbm this is a known issue https://github.com/Azure/azure-functions-host/issues/3731. Functions team is going to address it in the current sprint.
