### ISSUE TITLE
Access request telemetry from controller

### ISSUE THREAD

**Issue by breyed** [Microsoft/ApplicationInsights-aspnetcore#763]
As I understand it, the current guidance for customizing telemetry (e.g. adding a user identifier) is to:

1. Create an `ITelemetryInitializer` and set the desired properties (e.g. `AuthenticatedUserId`). The sets up the request telemetry.
2. Create a new `TelemetryClient` object. On this object also, set the desired properties (e.g. `AuthenticatedUserId`). This gives you an object for custom telemetry (e.g. `TrackEvent`).

It seems redundant to have to set up two separate telemetry instances. It seems that it would be better if you could get access the existing request telemetry instance for sending custom telemetry.

**Comment by pharring** [comment]
For ASP.NET Core, you're better off using dependency injection to access the existing `TelemetryClient` by adding a parameter of type `TelemetryClient` to your controller's constructor and saving it in a (private readonly) field. It's certainly more efficient that creating a new TelemetryClient.
Add your `ITelemetryInitializer` via dependency injection too (in your startup code).

**Comment by breyed** [comment]
That sounds great. It sounds like the [API docs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#get-a-telemetryclient-instance) could use some improvement. I'll create an issue accordingly.
