### ISSUE TITLE
Is HostBuilder supported?

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-aspnetcore#765]
Hi, is the new HostBuilder supported by AppInsights SDK? How to use it?

On a simple try out, there is an issue that IHostingEnvironemnt is not in the DI tree but is required by AspNetCoreEnvironemntTelemetryInitialzer:
**https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/e5019227c204dcd891785782cdee7d9970fac185/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs#L19**

And thus fail the DI:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/17cc5de23ba58872650f7f2c4eaf0f0f2e47a823/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L147

Here my code trying to piece things up:
```csharp
static void Main(string[] args)
        {
            IHost host = new HostBuilder().ConfigureHostConfiguration(configHost =>
                {
                    configHost.SetBasePath(Directory.GetCurrentDirectory());
                    configHost.AddJsonFile("hostsettings.json", optional: true);
                    configHost.AddEnvironmentVariables();
                }).ConfigureServices((hostContext, services) =>
                {
                    services.AddApplicationInsightsTelemetry(options =>{
                        options.InstrumentationKey="put into appsettings.json later ...";
                        // options.
                    });
                    // Enable Application Insights with iKey configured in the environemnt variable
                    services.AddSingleton<IHostedService, PrintHelloService>();
                    // Enable Application Insights for Kubernetes when running inside Kubernetes.
                    services.EnableKubernetes();
                })
                .UseConsoleLifetime()
                .Build();

            host.Run();
        }
```
**Exception:**
```
Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'Microsoft.AspNetCore.Hosting.DefaultApplicationInsightsServiceConfigureOptions'.
```

References for HostBulider:
* [How to use HostBuilder](https://www.stevejgordon.co.uk/using-generic-host-in-dotnet-core-console-based-microservices)
* [MS Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)

**Comment by lmolkova** [comment]
hey @xiaomi7732 

no, unfortunately, we don't support it: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/708

For now, the best option is to take pieces that you need from AspNetCore AI SDK configuration

**Comment by davidfowl** [comment]
@xiaomi7732 Are you looking for logging support or something else?

**Comment by bklooste** [comment]
@davidfowl  also have this issue and yes we send all logging traces  to insights .

**Comment by davidfowl** [comment]
We now have an AI logger provider that will work for logs but there's no other extensibility enabled.

**Comment by jsprpalm** [comment]
@davidfowl Can you set Cloud.RoleName via an ITelemetryInitializer when using the provider for logs in a HostedService?

**Comment by cijothomas** [comment]
You can write a TelemetryInitializer for setting Cloud.RoleName or any other properties and wire it up with the folowing snippet.
```
 services.Configure<TelemetryConfiguration>(
        (config) =>
        {                            
            config.TelemetryInitializers.Add(new MyTelemetryInitalizer());
        }
    );

    // Add the logging pipelines to use. We are adding ApplicationInsights only.
    services.AddLogging(loggingBuilder =>
    {
        loggingBuilder.AddApplicationInsights();
    });
```

**Comment by cijothomas** [comment]
Closing in favor of #708
