### ISSUE TITLE
Application Insights data is not showing up when run as Linux service

### ISSUE THREAD

**Issue by OlafHaalstra** [microsoft/ApplicationInsights-aspnetcore#767]
I have built a .NET Core application that simply makes some API calls and post the data into a database. We want to track its performance to with application insights. However the application doesn't seem to reach AI under certain circumstances.

## Repro Steps
1. Run the systemd service `sudo -i service dataservice start` with the following parameters:
```
[Unit]
Description=DataService
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/dotnet run bin/Application/netcoreapp2.1/DataService.dll -c Release
WorkingDirectory=/srv/http/Application/DataService
User=username
Group=username
Restart=on-failure
SyslogIdentifier=dataservice
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

2. The `telemetryClient` is simply created within the class where I try to log from:
```
this.telemetryClient = new TelemetryClient
{
    InstrumentationKey = configuration.GetSection("InstrumentationKey").Get<string>()
};
```

3. The journalctl logging inidicates that the following code is executed properly:
```
telemetryClient.TrackMetric($"{building.Key}: {meterId}", value);
logger.LogInformation($"Send | {building.Key}: {meterId} | to telemetry with key {telemetryClient.InstrumentationKey}, {telemetryClient.Context.InstrumentationKey}");
```

In the log I can see the InstrumentationKey independently from how the program is started as explained below.

##  Actual Behavior & Expected Behaviour

This way no data shows up in application insights, this is weird because if I run the program myself by invoking `/usr/bin/dotnet run bin/Application/netcoreapp2.1/DataService.dll -c Release` as the same user as in the configuration the data is showing in application insights. I think this means that it cannot be a firewall issue as is widely suggested by the troubleshooting documentation of AI.

Is there anyone who could help me progress with this issue, because I found no similar issues anywhere.

## Version Info 
.NET Version : 2.1.401						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension): VisualStudio
OS : Ubuntu 18.04.1 LTS
Hosting Info (IIS/Azure WebApps/ etc): Azure

**Comment by cijothomas** [comment]
Can you try adding a flush after the Track() call ? (This is required if you app dies soon after, but not really if it is running as a service)
If AI had some trouble internally, it tried to send a Diagnostic Trace to your ikey.. Since you are not seeing that, its likely an ikey issue.. Can you try to set ikey differently? (hard code in code, or set ENV variable etc) .
I am not sure whats causing it yet, hence the ask to try out several options

**Comment by OlafHaalstra** [comment]
I tried that, it didn't work though. It even stops the Task completely. I scheduled to run the tracking every minute with: 
```timer = new Timer(DoWork, null, TimeSpan.Zero, TimeSpan.FromMinutes(1));```
The tracking is executed in a `foreach` loop, the first `logger.logInformation` is observed but after that nothing is done until one minute later when the loop is executed again (this is possible since its asynchronous I suppose). I'm not sure what this implies, the it fails to `Flush()` this might give some information?


How do you propose to send a Diagnostic Trace to my ikey? I tried to set the ikey different but I'm pretty sure that's not the issue since it simply shows up in the log (on my local machine windows machine it does work, remotely on linux it doesn't).

**Comment by cijothomas** [comment]
Closing old issues. Please re-open if you still have issues. (I agree we haven't investigated this, but asking to reopen if still an issue)

**Comment by OlafHaalstra** [comment]
The issue persisted, was never able to figure it out unfortunately. Eventually moved to a different solution.

**Comment by cijothomas** [comment]
thanks for reporting back. sorry we couldn't help in time.
