### ISSUE TITLE
Is it possible to Include SQL query parameter values in Application Insights?

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-aspnetcore#775]
I have the following sql query in my project:
"select location from test where name = @name", and then I can see this query is logged in the application insights.

But I wonder if it's possible to record the value of the parameter "@name" in the query in application insights? like if the "@name"'s value is "jack", then in the application insights, it's logged this query as "select location from test where name = jack".

**Comment by Dmitry-Matveev** [comment]
@imeya, Application Insights SDK does not collect SQL parameters by default (as per my understanding, it's done to decrease chances of collecting PII in the telemetry by default).

If you have a way to retrieve the values you'd like to put into Dependency Telemetry on your own - then you can set them in [Telemetry Initializer](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer) on the outgoing telemetry item.

**Comment by imeya** [comment]
thank you.
