### ISSUE TITLE
SQL Dependency has wrong parrentId

### ISSUE THREAD

**Issue by stefrostik** [microsoft/ApplicationInsights-aspnetcore#778]
## Repro Steps
1. AddApplicationInsightsTelemetry to youe service
2. Add call to some API, SQL Server

##  Actual Behavior
Requests logged correctly, API call is child, 
SQL Server call is NOT a child of root request. It is on the same level with request
![image](https://user-images.githubusercontent.com/20971368/47514908-27d29a00-d88a-11e8-9d88-793b2a4a4a51.png)
![image](https://user-images.githubusercontent.com/20971368/47514984-55b7de80-d88a-11e8-8cac-e7c8d09e4740.png)
## Expected Behavior
SQL Server dependency should have request as parrent
![image](https://user-images.githubusercontent.com/20971368/47515080-9283d580-d88a-11e8-9f7a-317a2118a9d6.png)

NOTE: workaround is to  store RequestId in Activity when request starts, and set parrentId in sql dependency in custom telemetryProccessor
## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore Version=2.3.0 - 2.5.1
.NET Version :	 netcoreapp2.1

**Comment by lmolkova** [comment]
thanks for reporting this. 
Would you mind sharing the following info?

1.  > Microsoft.ApplicationInsights.AspNetCore Version=2.3.0 - 2.5.1

You've upgraded the SDK to 2.5.1?
Did it repro on 2.3.0?

2. Incoming request in your case, is it ServiceBus message processing?
3. SQL dependency - it is tracked automatically or manually?
4. Please share request telemetry and dependency telemetries operation id, parent id and Id.

**Comment by stefrostik** [comment]
1. Issue exists on all versions from 2.3.0 to 2.5.1 (havent checked older versions)
2. Yes, it is service bus request
3. It is tracked automatically
4. Do you need real opertion Ids? not sure if I can share them due to security policy

**Comment by lmolkova** [comment]
> Do you need real opertion Ids? not sure if I can share them due to security policy

They are random and do not have any personal or sensitive information. If your policies do not allow to share them publically, could you consider sending them over email to me? (my email is in the profile).

you may run query that returns only Ids and won't reveal any information to me
e.g. 
```
union requests | union dependencies| union traces
| where operation_Id == "your operation id"
| project operation_Id, id, operation_ParentId, name
```

Another option could be a small repro app.

Also, where do you make db call? Is it during message processing within a processing handler?

**Comment by ThiemeNL** [comment]
I think I have the same issue, see my stackoverflow question: https://stackoverflow.com/questions/53322973/disable-ef-core-migration-verification-query
The operation_id gets sticky once I enable the SQL dependecy tracking.

**Comment by cijothomas** [comment]
Closing as this is fixed in linked PR
