### ISSUE TITLE
Sampling and custom processors with JSON configuration.

### ISSUE THREAD

**Issue by asimsir** [Microsoft/ApplicationInsights-aspnetcore#779]
Hi there,

I am trying to setup fixed-sampling and custom processors through appsettings.json, by trying to adapt what's documented for the .config file here : https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config

So something that would look like this :

```
"ApplicationInsights": {
    "InstrumentationKey": "my-instrumentation-key",
    "TelemetryProcessors" : {
          "Type": "Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.SamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel"
          "SamplingPercentage" : 50
     }
  }
```

I've failed to find such examples in this documentation : https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration

Is it available or should I stick to a code based approach ?
Any guides or documentation I missed ?

Thanks

**Comment by pharring** [comment]
It's not available for .NET core. You need to write code. For ASP.NET Core, this is usually done in the ConfigureServices code in startup. Telemetry processors need to be added via `ITelemetryProcessorFactory`.

**Comment by asimsir** [comment]
Ah well. Thank you for the quick answer, i'll stick to the code base approach then. :)
