### ISSUE TITLE
creating new TelemetryClient creates a client instance that doesn't send telemetry and silently fails

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#78]
Reported by @AlexBulankou 

This is the right way to create TelemetryClient instance:
``` c#
TelemetryClient telemetryClient = (TelemetryClient)this.Resolver.GetService(typeof(TelemetryClient));
```
This is NOT the right way

``` c#
TelemetryClient telemetryClient = new TelemetryClient().
```

but user has no idea :)

What can we do to improve this experience (other than documentation)

**Comment by olegsych** [comment]
Well, some might say that Service Locator is an [anti-pattern](http://blog.ploeh.dk/2014/05/15/service-locator-violates-solid/) in application code and the "right" way to get a TelemetryClient instance is to get in injected in the constructor.

```
public class HomeController: Controller
{
    private readonly TelemetryClient client;
    public HomeController(TelemetryClient client)  {
        this.client = client;
    }
}

But, you're right. We've designed the API for classic .NET frameworks and this is confusing. Ooh... I have an idea, let's create or own API for ASP.NET 5! :grin:

**Comment by SergeyKanzhelev** [comment]
This issue was reported again. Here are the options we have to resolve it:

What experience would you prefer (or expect):

1. **Make constructor fail**. This is not how our SDK is designed today and we try to minimize number of cases any call to SDK will fail. So it is dangerous path...

2. **Code works if you’ve called UseApplicationTelemetry at least once for the current application**. This behavior creates confusion as you configure Application Insights non-globally, when using it globally.

3. **Track method will trace error** to output saying that it wasn't configured. This one sounds reasonable, but wouldn't be easy to catch unless looking into output window.

**Comment by petehauge** [comment]
I think from a user perspective (I ran into this, was really painful that it failed silently), we should either make it work or alert the user that it would fail.  I don't think a trace error would be enough (I'd probably miss it), but how about a green squiggle & message to the user (like code lens?  or smart tag? etc)
![sqiggle](https://cloud.githubusercontent.com/assets/12090616/9122850/b18ab3ac-3c59-11e5-88e2-95c6327b72bc.png)

**Comment by olegsych** [comment]
That's an interesting idea. This would be possible in Visual Studio 2015 with diagnostics analyzers.
 
![image](https://cloud.githubusercontent.com/assets/8355091/9123160/a762c674-3c42-11e5-8bcd-6b37be8def9d.png). 

Do we know if or when ASP.NET 5 projects will support this feature?

**Comment by SergeyKanzhelev** [comment]
@Eilon, do you know anything about diagnostics analyzers for ASP.NET 5 applications support?

What will be your recommendation on how to show this API misuse for customers?

**Comment by Eilon** [comment]
@troydai has been working on enabling Roslyn analyzers in DNX projects.

**Comment by vladzaharia** [comment]
I agree, as a user, it was *incredibly* painful that it was failing silently and I only realized when I went into debug and saw that there was no iKey loaded in that something was wrong with the configuration. It's especially painful since I had copied some code I knew was working in ASP.net 4 to 5 when I hit it, so I had expected it to work completely out of the box.

**Comment by olegsych** [comment]
I wonder if we can make `TelemetryClient`

**Comment by SergeyKanzhelev** [comment]
@troydai, can you please comment on this? Are Roslyn analyzers can be used in DNX projects?

**Comment by troydai** [comment]
DNX project doesn't support analyzer now.

Good news is that we're prototyping the analyzer in DNX (https://github.com/aspnet/dnx/commit/1b02955ff0f24b64628f0a50c693eb97610e0649) and it fits in a broader change to introduce "build time" dependencies.

**Comment by kartang** [comment]
Fixed as a part of: https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/143

However, we are further enhancing the experience: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/156
