### ISSUE TITLE
Visual Studio Application Insights Search local session and .net core 2 console app

### ISSUE THREAD

**Issue by darthkurak** [Microsoft/ApplicationInsights-aspnetcore#780]
## Repro Steps
1. Creating example like: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-.NET-Core-console-application

##  Actual Behavior
I can see telemetry in Output window, but don't have anything in Application Insights Search in Visual Studio for local session, regardless if i provide InstrumentationKey or not.

## Expected Behavior
I should see telemetry in both, Output window, and local session of VS Application Insights Search

## Version Info 
SDK Version : Microsoft.ApplicationInsights (2.8.1)
.NET Version :	 .net core 2.1						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Nuget
OS : Windows 10
Console App

**Comment by cijothomas** [comment]
@darthkurak This must be something specific to visual studio installation. Do you have application insights 

tools for visual studio installed? Report back if you have it installed and still see issue. Will get VS integration team to get help.
