### ISSUE TITLE
Sampling and AutoCollectedMetricExtractor

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-aspnetcore#784]
Hi,
I am trying to configure adaptive sampling and followed instructions found here:

https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream

but this caused the following error to appear:

> AI: A Metric Extractor detected a telemetry item with SamplingPercentage < 100. Metrics Extractors should be used before Sampling Processors or any other Telemetry Processors that might filter out Telemetry Items. Otherwise, extracted metrics may be incorrect.

I've tried to fix it in the following way, is it correct?

In "ConfigureServices(...)":

```
	var aiOptions = new ApplicationInsightsServiceOptions
	{
		EnableAdaptiveSampling = false,
		AddAutoCollectedMetricExtractor = false, // NOTICE THIS <---
		InstrumentationKey = aiInstrumentationKey,
		DeveloperMode = _env.IsDevelopment()
	};
	services.AddApplicationInsightsTelemetry(aiOptions);
```

And in "Configure(IApplicationBuilder app, IHostingEnvironment env)":

```
	var configuration = app.ApplicationServices.GetService<TelemetryConfiguration>();
	// Using adaptive sampling
	configuration.TelemetryProcessorChainBuilder
		.Use(next => new AutocollectedMetricsExtractor(next)) // NOTICE THIS <---
		.UseAdaptiveSampling(new SamplingPercentageEstimatorSettings
	{
		InitialSamplingPercentage = 20,
		MaxSamplingPercentage = 20
	}, null, excludedTypes: "Trace;Exception", includedTypes: "Request;Dependency").Build();
```

If this is the correct way to fix the warning, docs should be updated.

Thanks for any guidance!

**Comment by cijothomas** [comment]
@bragma Thanks for reporting the issue.
What is the SDK version you are using?
If version is 2.5.0-beta2 and above,  use the following line to get the builder.
var builder = configuration.DefaultTelemetrySink.TelemetryProcessorChainBuilder;

(I have updated the wiki as well) 
Let me know if this helps.

**Comment by bragma** [comment]
@cijothomas 
I was using 2.5.1, I'll get the builder in the new way and let you know. Thanks
