### ISSUE TITLE
Telemetry added in Middleware not sent to App Insights

### ISSUE THREAD

**Issue by johnkwaters** [Microsoft/ApplicationInsights-aspnetcore#786]
I have a middleware, that upon failure adds the Json body to the request telemetry:

`    internal class LogJsonMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly SystemOptions _systemOptions;

        public LogJsonMiddleware(RequestDelegate next, IOptions<SystemOptions> systemOptions)
        {
            _next = next;
            _systemOptions = systemOptions.Value;
        }

        private static bool IsSuccessStatusCode(int statusCode) => statusCode < 400 || statusCode==409;

        private static bool IsRequestWithBody(HttpRequest r) => r.Method == HttpMethods.Post || r.Method == HttpMethods.Put;

        public async Task InvokeAsync(HttpContext context)
        {
            await _next.Invoke(context);
            if (_systemOptions.LogJsonBody && !IsSuccessStatusCode(context.Response.StatusCode))
            {
                try
                {
                    var request = context.Request;
                    if (!IsRequestWithBody(request))
                    {
                        return;
                    }

                    if (request.HasFormContentType)
                    {
                        return;
                    }

                    var telemetry = context.Features.Get<RequestTelemetry>();
                    if (telemetry == null)
                    {
                        return;
                    }

                    request.EnableRewind();
                    request.Body.Position = 0;
                    var sr = new StreamReader(request.Body);
                    var bodyContent = sr.ReadToEnd();
                    var len = bodyContent.Length;

                    const string requestBodyKey = "JsonRequestBody";

                    if (bodyContent.Contains("password", StringComparison.CurrentCultureIgnoreCase))
                    {
                        // don't log passwords!
                        bodyContent = "contains sensitive information, hidden";
                    }
                    else
                    {
                        // don't want huge amounts of AI data - it costs money!
                        if (len > _systemOptions.LogJsonMaxSize)
                        {
                            bodyContent = bodyContent.Substring(0, _systemOptions.LogJsonMaxSize);
                        }
                    }                  
                    telemetry.Context.GlobalProperties["northstar_requestpayloadsize"] = len.ToString();
                    telemetry.Context.GlobalProperties[requestBodyKey] = bodyContent;
                }
                catch (Exception)
                {
                }
            }
        }
    }`

But I dont see these fields in Azure Portal App Insights. 

I also have a TelemetryInitalizer that adds some fields for all requests:

`    public class JsonTelemetryInitializer : ITelemetryInitializer
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="accessor">For accessing the http context</param>
        public JsonTelemetryInitializer(IHttpContextAccessor accessor)
        {
            _httpContextAccessor = accessor;
        }

        /// <inheritdoc />
        /// <summary>
        /// Initialize the custom telemetry initializer
        /// </summary>
        /// <param name="telemetry">Telemetry</param>
        public void Initialize(ITelemetry telemetry)
        {
            const string tenantId = "northstar_tenantid";

            if (!(telemetry is RequestTelemetry rt) || 
                _httpContextAccessor.HttpContext == null ||               
                !_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated ||
                rt.Properties.ContainsKey(tenantId))
            {
                return;
            }

            // need the user (claims principal) to get the claims to log
            var user = _httpContextAccessor.HttpContext.User;

            rt.Properties[tenantId] =
                ClaimsHelper.GetClaim<int>(user, TokenNames.TenantId).ToString();

            var userId = ClaimsHelper.GetClaim<int>(user, TokenNames.UserId).ToString();
            telemetry.Context.User.Id = userId;
            rt.Properties["northstar_userid"] = userId;

            var deviceId = ClaimsHelper.GetClaim<string>(user, TokenNames.DeviceId);
            if (deviceId != null)
            {
                rt.Properties["northstar_deviceid"] = deviceId;
            }

            var sessionId = ClaimsHelper.GetClaim<string>(user, TokenNames.SessionId);
            if (!string.IsNullOrEmpty(sessionId)) {
                telemetry.Context.Session.Id = sessionId;
            }
        }
    }
`
I do see these in the portal.
The idea with the middleware is to only log Json on failure, after the request is processed.

Is there a better way to do this? Am I doing it wrong?

**Comment by cijothomas** [comment]
Looks correct. 
Are you seeing the RequestTelemetry in the portal for failed requests, but its is missing the additional properties (response body) ? Or are you NOT seeing the failred RequestTelemetry at all ?

**Comment by johnkwaters** [comment]
Mystery solved. The custom properties are here, but as you can see, not the JSON body:

![image](https://user-images.githubusercontent.com/3422637/49235883-e153ec00-f3af-11e8-8ad5-baa31c2128ba.png)

However... they ARE in this subnode!

![image](https://user-images.githubusercontent.com/3422637/49235934-fdf02400-f3af-11e8-89d4-445fc9666d58.png)

Why are the in a separate area of App Insights?

**Comment by cijothomas** [comment]
Its a UI issue (if at all its an issue) Closing this for now. If this requires further followup, please comment, and will get help from UI friends.
