### ISSUE TITLE
Cannot see SQL statements under SQL Dependency in AI (ASP.NET Core 2.2 doc changes)

### ISSUE THREAD

**Issue by k290** [Microsoft/ApplicationInsights-aspnetcore#822]
Since ASP.NET Core 2.2 was released in December 2018 the docs were updated to state that Applicaiton Insights now fully supports SQL Dependencies. See "Application Insights SDK Comparison" section here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

Additionally on the same page under troubleshooting for "SQL query not shown in full" it says all that is necessary is " upgrade your application to .NET framework 4.6 or later and install the Application Insights SDK in your app." which I have done.

![image](https://user-images.githubusercontent.com/5611876/50910312-3ca8dd80-1436-11e9-834d-eb9822d995bc.png)

I am aware that previously you needed status monitor installed as indicated here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/705

However, I would expect that now with ASP.NET core 2.2 this is no longer necessary, based on the explanations in the docs and the above screenshot. Is that correct? 

Please see set up below:

## Version Info 
SDK Version: rddf:2.8.1-19196 (Microsoft.ApplicationInsights.AspNetCore Version 2.5.1)
ASP.NET Core Version: 2.2
.NET Version :	.NET Framework 4.6.1					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows Server 2016
Hosting Info: ASP.NET Core running in Kestrel with IIS Server

**Comment by k290** [comment]
Thanks. I understand. Then in theory it should work for the setup indicated:

SDK Version: rddf:2.8.1-19196 (Microsoft.ApplicationInsights.AspNetCore Version 2.5.1)
ASP.NET Core Version: 2.2
.NET Version :	.NET Framework 4.6.1
Entity Framework: EF Core 2.2.0
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows Server 2016
Hosting Info: ASP.NET Core running in Kestrel with IIS Server

But it does not work

**Comment by cijothomas** [comment]
@k290 Is your application a asp.net core app, but its targeting the full .NET Framework?

**Comment by k290** [comment]
@cijothomas That is correct

**Comment by Johnsonxd4** [comment]
Hello,
This solution of using Status Monitor works only for applications hosted on IIS, or should it work for applications using a .net framework self hosted using httpsys?
