### ISSUE TITLE
Application Insights Rejecting Exceptions with empty Message

### ISSUE THREAD

**Issue by joshbratt** [Microsoft/ApplicationInsights-aspnetcore#823]
When sending exception telemetry through to Application Insights, the request gets rejected with a 400, stating that "Field 'message' on type 'ExceptionDetails' is required but missing or empty."

## Repro Steps
1. Perform a call to TelemetryClient.TrackException() with an exception with an empty message.

##  Actual Behavior
The message is rejected by Application Insights with a 400, requiring the message property to be populated.

## Expected Behavior
The message property should not be a required property, or the rejection of the telemetry should be communicated.

![image](https://user-images.githubusercontent.com/8520900/51157240-d283b300-18e3-11e9-831f-69417e8a13c1.png)

![image](https://user-images.githubusercontent.com/8520900/51157242-d57ea380-18e3-11e9-8e54-7e13c451dd42.png)

## Version Info 
SDK Version : 2.5.1
.NET Version : .NET Core 2.1
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10 Enterprise 17134.472

**Comment by cijothomas** [comment]
```
var ex = new Exception();
tc.TrackException(ex);
```

Is the above a repro code for this? Or can you share the snippet to repro.

**Comment by cijothomas** [comment]
Thanks! 
Opening in the correct repo. Will close this one.
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/1066
