### ISSUE TITLE
Cannot filter PII from PageView events

### ISSUE THREAD

**Issue by YoniSmolin** [Microsoft/ApplicationInsights-aspnetcore#824]
I am experiencing an issue identical to [#173 in the ApplicatoinInsights-JS repository](https://github.com/Microsoft/ApplicationInsights-JS/issues/173).

I have an ASP.Net Core application which launches a React based SPA (both have Application Insights instrumentation enabled) that may redirect to an authorization page whose URL contains sensitive PII (an access token).

My problem is twofold:
- The authorization PageView event logs sensitive data to Application Insights.
![image](https://user-images.githubusercontent.com/11846732/51195457-c7d21980-18f5-11e9-8594-056c28cf7186.png)
- A UrlTooLong warning message is displayed in console, also containing the full URL with sensitive data.
![image](https://user-images.githubusercontent.com/11846732/51195488-d4567200-18f5-11e9-8720-87b9866074fa.png)

I tried adding an [ITelemetryInitializer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.itelemetryinitializer?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer);k(SolutionItemsProject);k(SolutionItemsProject);k(SolutionItemsProject);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=azure-dotnet) and an [ITelemetryProcessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.itelemetryprocessor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor);k(SolutionItemsProject);k(SolutionItemsProject);k(SolutionItemsProject);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet) to filter out the PII, but they don't seem to intercept the PageView events for some reason.

I'm posting the issue here and not on [ApplicatoinInsights-JS](https://github.com/Microsoft/ApplicationInsights-JS/issues) because it persists even when I remove all Application Insights code bits from the React SPA.

I'm using Microsoft.ApplicationInsights.AspNetCore version 2.5.1, and .Net core 2.0 framework.

Any help dealing with or working around this issue will be very appreciated!

**Comment by cijothomas** [comment]
Microsoft.ApplicationInsights.AspNetCore SDK does not track page views - they are tracked by javascript sdk only. (The former has a way of injecting the js sdk snippet only)
Where have you added TelemetryInitialier/Processor to filter the item? Was it on server side code or on client side ? Since server side (i.e aspnetcore sdk) does not track pageviews, it wont intercept Pageviews. So make sure to add it to the client side code.

Also can you clarify a bit more on this " because it persists even when I remove all Application Insights code bits from the React SPA." -- IF there is no application insights, are you still seeing telemetry tracked somehow ?

**Comment by YoniSmolin** [comment]
Thank you for the response, @cijothomas.

When posting my question, I wasn't aware that the AspNetCore SDK secretly injects a JS snippet. I think this may be the source of my trouble: I'm loading the JS SDK manually (I do this manually, and not through `Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet`, because I'm using [applicationinsights-web](https://www.npmjs.com/package/@microsoft/applicationinsights-web) instead of [applicationinsights-js](https://github.com/Microsoft/ApplicationInsights-JS) - the former provides Ajax tracking, which I rely on). I'm suspecting there may be some cross-talk between the snippet and my manual code.

Is there a way to tell the AspNetCore SDK **not** to automatically inject a JS snippet?

To answer your questions:

> Where have you added TelemetryInitialier/Processor to filter the item? Was it on server side code or on client side ?

I tried both and none seemed to catch the page view events.

> IF there is no application insights, are you still seeing telemetry tracked somehow ?

No, but I am seeing it as soon as I enable the AspNetCore SDK, and this can be explained by the auto-injected snippet you mentioned.

**Comment by cijothomas** [comment]
Whether AspNetCore SDK injects SDK or not depends on how you onboard to the SDK- can you describe how have you onboarded to this SDK?

**Comment by YoniSmolin** [comment]
I've added the following in the `Program.cs` file of the ASP.Net Core app:

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights(AppInsightsKey)
                ...;

**Comment by cijothomas** [comment]
If you have added a nuget Microsoft.ApplicationInsights.AspNetCore. and added             `.UseApplicationInsights(AppInsightsKey)` into program, this alone should not inject javascript snippet.

Have you done the following as well to cause js snippet be inserted?
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#page-view-load-time

**Comment by YoniSmolin** [comment]
Thank you for the response, @cijothomas.

To answer you question: I had manually removed all instances of `@inject JavaScriptSnippet snippet` from my code, prior to creating this issue, so it cannot be what is instantiating the snippet.

There simply remains nothing but the `.UseApplicationInsights(AppInsightsKey)` bit that could cause the snippet injection.

To prove my point, I've forked a [sample React JS app hosted in ASP.Net core](https://github.com/AnkitSharma-007/CRUD.ASPCore.Reactjs.WebAPI.EF) (has nothing to do with Application Insights) and added just the Application Insights Nuget package reference and the `.UseApplicationInsights(AppInsightsKey)` line. Find my changes [here](https://github.com/YoniSmolin/CRUD.ASPCore.Reactjs.WebAPI.EF/commits/appInsightsUndesiredSnippetInjection).

Said changes caused `index.html` to go from this

![image](https://user-images.githubusercontent.com/11846732/51686798-bfff2d00-1ff9-11e9-84a7-050d8e53b03b.png)

to this (note the highlighted JS snippet)

![image](https://user-images.githubusercontent.com/11846732/51686869-f177f880-1ff9-11e9-9ac5-88ea1873f4b5.png)

As I mentioned previously, the injected snippet causes me trouble - I'd rather manually instantiate Application Insights in my JS code, as I'm not using the default library (I'm using [applicationinsights-web](https://www.npmjs.com/package/@microsoft/applicationinsights-web) instead).

Is this a bug? Can you suggest a workaround? I'd like to use Application Insights instrumentation in the server, but don't want the auto-injected JS snippet...

**Comment by cijothomas** [comment]
I can't comment about the React app you shared - But for a New Web App created from Visual Studio, If you just add the nuget Microsoft.ApplicationInsights.AspNetCore, and modify program.cs to have .UseApplicationInsights("ikey") , - This does NOT inject js snippet.

**Comment by YoniSmolin** [comment]
Thanks, @cijothomas! Your last point is indeed the root cause of the issue. I checked to verify and indeed there is no code snippet injected in the deployed version of the app.

**Comment by cijothomas** [comment]
Okay. I understand several people (including myself) were confusing when launch from VS altered behavior.
You can fix it in latest VS from the menu below:
Check "Disable local Application Insights for Asp.Net Core web projects"
![image](https://user-images.githubusercontent.com/5232798/51695678-7d693080-1fb8-11e9-8745-20d6c72672a6.png)
