### ISSUE TITLE
AppInsights logging level not respected in Production environment

### ISSUE THREAD

**Issue by armanik11** [Microsoft/ApplicationInsights-aspnetcore#825]
If you are reporting bug/issue, please provide detailed Repro instructions.

Questions:

1) What are the expectations here based on below?
2) I need some help in understanding the different between ILogger loglevel and appinsights severityLevel

## Repro Steps
We have 2 stateless services (asp.net core) running in service fabric and sending data to appinsights. I recently added the following piece of code at the Configure method in StartUp.cs

   logger.AddApplicationInsights(app.ApplicationServices, (category, level) =>
            {
                return category.StartsWith("Servicename.") && level > LogLevel.Trace;
            });

##  Actual Behavior
We have some logger.LogInformation and Logger.LogDebug lines that I would expect to see in the AppInsights portal. But for some reasons, I see only below and it's different for both services which is strange.

For the front end service - I only see traces with Severity level 2
For the backend service - I only see traces with Severity level 4

I am looking at the "traces" in Logs (Analytics)

## Expected Behavior

I would expect to see all statements from logger.LogInformation also captured. I do see them captured while debugging locally in Development environment (test instance of appinsights) but don't see them in PROD environment.

Appsettings.json looks like this.

Service 1:

  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }   
  },
  "ApplicationInsights": {
    "InstrumentationKey": "***"
  }
}

Service 2:

{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  }
}

## Version Info 
SDK Version :
.NET Version :	 .net core 2.0 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) :

**Comment by cijothomas** [comment]
Investigated this offline. We suspect that the logs are missing because they happened too early in startup phase before app insights is even configured. Also sampling can cause it. Please turn off sampling and try logging something from a regualr controller to rule out the above.

**Comment by RamjotSingh** [comment]
If you want to logs to be available too early in the pipeline, try using https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights/2.9.0-beta3 package and setup logging using logging builder in the WebHostBuilder. Additionally specify the InstrumentationKey during the logging builder registration. This should solve the issue of not having logs during application startup.

**Comment by armanik11** [comment]
Have your tried this and does this work? Last I heard from Cijo, I heard it doesn't capture startup logging.

**Comment by cijothomas** [comment]
@armanik11 
Install this nuget and use the example below . https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights/2.9.0-beta3

```
public class Program
    {
        public static void Main(string[] args)
        {
            var host = BuildWebHost(args);
            var logger = host.Services.GetRequiredService<ILogger<Program>>();
            logger.LogInformation("From Program. Running the host now.."); // This will be picked up up by AI
            host.Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging(logging =>
                {
                    logging.AddApplicationInsights("ikey");
                    // optional - filter Microsoft logs only above warning
                    logging.AddFilter<ApplicationInsightsLoggerProvider>("Microsoft", LogLevel.Warning);
                })
                .Build();
    }
```
And startup.cs
```
public class Startup
    {
        private readonly ILogger _logger;

        public Startup(IConfiguration configuration, ILogger<Startup> logger)
        {
            Configuration = configuration;
            _logger = logger;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
                      _logger.LogInformation("From ConfigureServices. Services.AddMVC invoked"); // This will be picked up up by AI
        }
}
```

**Comment by ben-burton** [comment]
I'm also experiencing the same issue with logging in Startup. 

I can see traces in Application Insights from controllers but not from Startup.cs. I've tried restarting my App Service from the Azure portal and monitoring the logs for a while afterwards, but the messages don't show. Interestingly, the logs do appear when I run the app locally and check the Output window in Visual Studio - but not in App Insights. I am using version 2.9.1 of Microsoft.Extensions.Logging.ApplicationInsights

My code is slightly different to the above example in that I'm calling AddLogging from the ConfigureServices method in Startup as opposed to Program. Should this make a difference? My logging appears further down in Startup after the logging is configured. As I mentioned, the logging appears in the Output window locally, so it does appear to work like this. Any ideas?

**Comment by cijothomas** [comment]
Can you see if modifying the code to enabling logging in Program.cs help ? Share the code you have to know more.

When you are running locally - you are running from VS right? VS somewhat alters behavior, so can you try without Visual Studio, or with ASPNETCORE_PREVENTHOSTINGSTARTUP = true.?

**Comment by RamjotSingh** [comment]
@ben-burton The only way to get logs from Startup.cs is if you configure the logging at WebHostBuilder level. Configuring them in Startup.cs will mean you will not get logs for Startup.cs.

**Comment by cijothomas** [comment]
Closing as all questions seems to be answered.Please reopen if there are new questions.!
