### ISSUE TITLE
StartupBootstrapper exception logged on startup

### ISSUE THREAD

**Issue by emilssonn** [Microsoft/ApplicationInsights-aspnetcore#826]
## Repro Steps
1. Create a new Asp.Net Core API Project in VS2017 with .Net Core 2.2.
2. Add Microsoft.ApplicationInsights.AspNetCore 2.5.1, add "UseApplicationInsights" in program.cs.
3. Enable logging, https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging
4. Create API App in Azure
5. Create Application Insights resource in Azure.
6. Deploy Code
7. Link AI to webapp using the "Application Insights" menu item on the webapp. Enable all options.

##  Actual Behavior
On startup in Azure the following exception is logged (everything seems to work, it is just logged):
Hosting startup assembly exception Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

## Expected Behavior
No exception should be logged.

## Version Info 
SDK Version : 
.NET Version : 2.2	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Nuget + azure
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApp

**Comment by cijothomas** [comment]
Thanks for reporting!
For azure webapps, enabling application insights is not supported yet for .net 2.2. (and hence the exception about bootstrapper)
Support for 2.2 is planned for February 2019, but I am working to get the fact that 2.2 is not supported in the ApplicationInsights menu item itself to avoid confusion.

**Comment by emilssonn** [comment]
As far as I can see the exception is logged only when logging is enabled in AI. Everything seems to work.

- What is it that is not supported? 
- What does enabling (when it works) it in Azure do compared to the nuget? Profiler and?

**Comment by cijothomas** [comment]
Application Insights menu item in App Service - is an easy mechanism to inject & enable App insights monitoring for those apps which did not already enable application insights in code (via nuget). For apps already having AI via nuget, adding extension does not anything App Insights specific, but it opens up SnapShotcolector, profiler etc.

Not supported is - inject & enable from Web Apps for apps targeting .net core 2.2. Infact only .net core 2.0 and 2.1 is supported now. For those unsuported targets, recommendation is to onboard via nuget itself.

let me know if this clarifies bit more.

**Comment by emilssonn** [comment]
Ok, thanks for your clarification.

The documentation should really say all of this.
- What I need to get all features of AI (profiler, snapshotcollector etc).
- When I need to install the extension (or parts of it, appsettings) or when nuget provides all features etc.
- And more

**Comment by cijothomas** [comment]
@emilssonn Doc fixes are coming soon here! Thanks for your patience.
