### ISSUE TITLE
InvalidCastException when logging Exception.Data

### ISSUE THREAD

**Issue by tomazv** [Microsoft/ApplicationInsights-aspnetcore#831]
## Repro Steps
Log an Exception which contains entries in Exception.Data and Data is a generic dictionary. An example of such exception is [PostgresException](https://github.com/npgsql/npgsql/blob/9260da14d6a58b3b2e2f315489aaf2e1088a118c/src/Npgsql/PostgresException.cs#L292) from the npgsql library.

This issue appeared when we upgraded from version 2.4 to 2.5. I think the issue is [ApplicationInsightsLogger line 72](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/de1af6235a4cc365d64cbc78db9bdd2d579a37ee/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs#L72), where exception.Data can contain KeyValuePair entries.

##  Actual Behavior
ApplicationInsightsLogger throws the following exception:

```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.KeyValuePair`2[System.Object,System.Object]' to type 'System.Collections.DictionaryEntry'.
  at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
  at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at Microsoft.ApplicationInsights.AspNetCore.Logging.ApplicationInsightsLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

## Expected Behavior
Exception is logged without InvalidCastException being thrown.

## Version Info 
SDK Version : .NET Core SDK 2.2.103
.NET Version : .Net Core 2.2.1				
OS : linux docker image
Hosting Info (IIS/Azure WebApps/ etc) : Azure AKS

**Comment by cijothomas** [comment]
Thanks @tomazv for reporting. While this is definitely a bug, we recommend users to try the new ILogger provider, as the ILogger in this repo is being deprecated in favor of the new ones. 

https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights/2.9.0-beta3

Interestingly the new implementation does not read exception.Data, so you wont be hit with this exception, but at the same time Data is not populated to telemetry. Will open an issue to track it in logging repo.

**Comment by tomazv** [comment]
Thanks for the info. I will try the new provider.
