### ISSUE TITLE
No telemetry when running in Docker container

### ISSUE THREAD

**Issue by mbekron** [Microsoft/ApplicationInsights-aspnetcore#836]
## Repro Steps
1. Create AspNetCore Web Application, API, via visual studio
2. Add Application Insights via visual studio
3. Build and Publish the project
4. Build Docker image using below docker file from published output
5. Start Docker container (exposing ports as required)
6. Execute a few calls against the api
7. Check for telemetry on Azure

##  Actual Behavior
Telemetry is collected when debugging via visual studio (IIS or Runnig dll directly)
No telemetry is collected when running inside docker container.

## Expected Behavior
Telemetry should be collected when running inside docker container.

## Version Info 
SDK Version : 2.6.0
.NET Version : 2.2
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Docker for Windows Container

## Docker File
FROM microsoft/dotnet:2.2.0-aspnetcore-runtime
WORKDIR /app
COPY . .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "AppInsightsCore.dll"]

**Comment by cijothomas** [comment]
@mbekron How is ikey configured? Can you check by passing ikey directly in code in the UseApplicationINsights("ikey") method?

**Comment by mbekron** [comment]
@cijothomas Thanks for the response. I seems the issue I was having, was due to the docker nat , which was forwarding traffic through my network connection with the lowest metric. In my case this was my ethernet port. At a suggestion I found in another issue, I updated my Wifi's metric to be lower than my ethernet and all seems to be working now. Thanks again.
