### ISSUE TITLE
Log Metrics with ILogger

### ISSUE THREAD

**Issue by ranouf** [Microsoft/ApplicationInsights-aspnetcore#840]
> .Net Core 2.2
> Azure Webjob v3
> 

Hi,

I m using an Azure Webjob. I would like to log metrics in Application Insight using Ilogger. Is there a way to do it? Or do I need to create a custom ILogger?

My purpose is to get something like:
new  information "Get Cars from API" with values
- "Count", 15
- "Duration", 1500 (ms)

Then I can see on the azure portal a graph with 2 lines:
- one for the number of Cars return from the API
- one for the duration

Is it something possible with Application Insight? 
I looked on many websites, but I didnt find a documentation explaining how to do something like this, Do you have one to recommend?

Thanks

**Comment by cijothomas** [comment]
You can use the application insights ILogger provider.
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/Readme.md

**Comment by ranouf** [comment]
Thanks, this is what I already use, but I didnt find a way to add Metric with the ILogger, or did I miss something?
I can log trace, information, error, ... but I always log only a string message without any properties.

**Comment by cijothomas** [comment]
Using scopes, you can attach any customer key,value pairs the telemetry. But equivalent of 'TrackMetric() API is not available.
@RamjotSingh - Do you know if this can be done?

**Comment by RamjotSingh** [comment]
ILogger at the moment does not support metrics (atleast not the way you want them). So TrackMetric is your best bet for now. If .Net adds support for common Metric logging interface we will work on building support for it.
