### ISSUE TITLE
Missing logging for request too size cases

### ISSUE THREAD

**Issue by BertanAygun** [Microsoft/ApplicationInsights-aspnetcore#844]
There seems to be a gap in requests/exceptions events when clients make a request that is too large and gets 404 in response from asp.net

## Repro Steps
1.  Have a controller that accepts a PUT request
2.  Send a PUT request that exceeds the max request size

##  Actual Behavior
Client gets 404 response, no telemetry is generated in requests or exceptions tables

## Expected Behavior
Client gets 404 response but telemetry visible in requests and possibly exceptions as well

## Version Info 
SDK Version : 2.1.503
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS using AI.AspNetCore package
Hosting Info (IIS/Azure WebApps/ etc) : Azure webapps and AI extension

**Comment by Dmitry-Matveev** [comment]
If there was no indication in .NET pipeline that this request ended abruptly, AI could not have a chance to learn about this request being abandoned. As a workaround, you may submit `RequestTelemetry` with any status code manually via `TrackRequest()` API on `TelemetryClient`.

However, in this particular case you may need an additional simple tracking system for the requests that started but have not finished in X amount of seconds (some sort of hash map) and only use TrackRequest manually for those requests that overstayed in that hash map..

**Comment by cijothomas** [comment]
@BertanAygun Please try to use the latest beta SDK, and see if it helps - we now capture exceptions from ILogger by default, so quite likely you'd see atleast an exception.  
Please reopen if you have more question on this.
