### ISSUE TITLE
Logger.LogTrace() does not write message to application insights

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-aspnetcore#845]
I have a .net core(2.1) mvc project, and I want to use ILogger to log messages to application insights.

In the Startup.cs -> Configure() method, I have added:
`loggerFactory.AddApplicationInsights(app.ApplicationServices,LogLevel.Trace);`

Then in the HomeController.cs, my code like below:
```
public class HomeController : Controller
    {
        ILogger<HomeController> Logger { get; set; }
        TelemetryClient client = new TelemetryClient();
        public HomeController(ILogger<HomeController> logger)
        {
            this.Logger = logger;
        }

        public IActionResult Index()
        {
            Logger.LogTrace("ILogger: xxxxxxxxxxxxxxxxxxxxxxxxx");
            Logger.LogDebug("ILogger: debug from index page aa111");
            Logger.LogInformation("ILogger: infor from index page aa111");
            Logger.LogWarning("ILogger: warning from index page aa111");
            Logger.Log(LogLevel.Error, "ILogger: error from index page aa111");
            return View();
        }
//other code
}
```

after run the project, all other messages like debug/information/warning/error are all logged into app insights, but the LogTrace() does not send messages to app insights.

I used the latest packages for the project:

![netcore2 1](https://user-images.githubusercontent.com/25738099/53226881-86344b80-36b7-11e9-8e0f-80aa87b70473.JPG)

And I also tried change log level to Trace in appsettings.json, but still have no effect:
```
"Logging": {
    "LogLevel": {
      "Default": "Trace"
    }
  },
```

**Comment by cijothomas** [comment]
Though you have the new Microsoft.Extensions.Logging.ApplicationInsights package, you are still using old loggig provider (which is being deprecator).

Follow this doc to correctly enable logging:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger

```
public class Program
{
    public static void Main(string[] args)
    {
        var host = BuildWebHost(args);
        host.Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()                
        .ConfigureLogging(logging =>
        {                
        logging.AddApplicationInsights("ikeyhere");
//The following line is to ensure only Trace or above is sent to application insihgts.        
logging.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Trace);
        })
        .Build();
}
```

**Comment by imeya** [comment]
@cijothomas , thank you Thomas. It works :)
