### ISSUE TITLE
No data from the asp.net core app that is shosted on IIS

### ISSUE THREAD

**Issue by pustun** [Microsoft/ApplicationInsights-aspnetcore#846]
We have an asp.net core app and it works and sends some metrics when we run it localy.

Now it deployed to IIS and we get telemetry only from the client side, from the page that is served from this app, but no info from the app itself.

The only differnce comparing to the local machine is that is hosted on the iis

p.s. we have already checked firewall

## Version Info 
SDK Version : 2.5.1
.NET Version :	.net core 2.2					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows server 
Hosting Info (IIS/Azure WebApps/ etc) : IIS (out of process)

**Comment by cijothomas** [comment]
How is SDK added to the project and how is application insights enabled?

**Comment by pustun** [comment]
As nuget package.

here is the appsettings.json

```
"ApplicationInsights": {
  "Enabled": true,
  "InstrumentationKey": "00000000-0000-0000-0000-000000000000"
}
```
and of cause we use something more meaningfull as a key

In the Startup.cs we call

```
if (appInsightsSettings.Enabled)
{
        services.AddSingleton<ITelemetryInitializer>(new MyTelemetryInitializer());
        services.AddApplicationInsightsTelemetry();
}
```
this is MyTelemetryInitializer

```
public class MyTelemetryInitializer: ITelemetryInitializer
{
    public void Initialize(ITelemetry telemetry)
    {
        telemetry.Context.GlobalProperties["machineName"] = Dns.GetHostName();
    }
}
```

**Comment by cijothomas** [comment]
@pustun 
Can you try hardcoding the ikey to         services.AddApplicationInsightsTelemetry("key");? If this works, then can you verify that appsettings.json is indeed copied to output folder?

**Comment by pustun** [comment]
@cijothomas config is definetely there, otherwise other services that relay on this config would be broken.

**Comment by cijothomas** [comment]
Did you try with ikey hardcoded? (I am trying to confirm if this is a pure ikey issue or not) So this really helps us narrow down..

**Comment by pustun** [comment]
I will give a try when we have the next release. I will let you know if it helps.

**Comment by atljoseph** [comment]
@cijothomas 
Having VERY similar issue. 
App is hosted both in Azure AppService and locally on my machine in IIS. 
Insights work fine locally in Visual Studio when ran with IIS profile (NOT IIS Express profile - have not tried that, but assuming it works fine), however the Application Insights Status Monitor says that Insights are not enabled in the code. 
This is simply not true (the ARE enabled), even after hard-coding the instrumentation key. 
BUT interesting to note is that AFTER hard-coding instrumentation key, while the Status Monitor still reported Not Enabled, Insights suddenly started appearing in Azure.

Very dissappointed in Micorsoft for the following points:
(1) Not having decent documentation on the WHATSOEVER
(2) Not having tested this feature adequately with the ApplicationInsightsStatusMonitor
(3) Not reading the instrumentation key from the Configuration object 
(4) Claiming the benefits of dotnet core when there really are none yet, mostly because of lacking documentation on how to use the product.

PREVIEW (dotnetcore 3) = Put your best foot forward, and NOT half of your worst foot.

**Comment by atljoseph** [comment]
Furthermore, after hard-coding the instrumentation key, not all the telemetry was available in the Azure Portal:

![image](https://user-images.githubusercontent.com/25017621/53653244-e3c91a80-3c18-11e9-8350-ae0453e0313c.png)

I just pounded the server with 3200 users using Jmeter, but graphs for Availability and Unique Users show NO DATA ... Aren't these telemetries right out of the box?

**Comment by cijothomas** [comment]
Application Insights Status Monitor - does not support asp.net core apps. 
 I'd be happy to correct the docs anywhere, if any docs states Status Monitor supports Asp.Net Core.

IKey is ready from code or config or env variable as documented here - if you observe otherwise, we'll investigate.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core#3-add-the-instrumentation-key

**Comment by cijothomas** [comment]
> Furthermore, after hard-coding the instrumentation key, not all the telemetry was available in the Azure Portal:
> 
> ![image](https://user-images.githubusercontent.com/25017621/53653244-e3c91a80-3c18-11e9-8350-ae0453e0313c.png)
> 
> I just pounded the server with 3200 users using Jmeter, but graphs for Availability and Unique Users show NO DATA ... Aren't these telemetries right out of the box?

If you follow the instructions, it talks about how to enable Client Side monitoring, Availability monitoring.  (These are not done by server side SDK)

**Comment by atljoseph** [comment]
I would like to know where the docs actually ARE LOCATED. Because everything I am finding has to do with 2.0, not 3.0. Make it easy to find

**Comment by atljoseph** [comment]
HARD CODING the instrumentation key was the only way data was sent to Azure. 
DID NOT WORK until that step.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core - Official docs page.
There is nothing on .net core 3.0.  Will be added as 3.0 is released and application insights sdk

**Comment by cijothomas** [comment]
> HARD CODING the instrumentation key was the only way data was sent to Azure.
> DID NOT WORK until that step.

Give specific repro steps, and we'll investigate.

**Comment by atljoseph** [comment]
Nuget:
    Install Microsoft.ApplicationInsights.AspNetCore 2.6.1

Right-click solution and choose to add App Insights Telemetry. Subsequently, sign in and register the resource.

Program:

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    // was also able to add hardcoded inst key here with .UseApplicationInsights("key")
                });

Startup:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc()
                .AddNewtonsoftJson();

            // PRODUCED DATA IN AZURE:
            services.AddApplicationInsightsTelemetry("instrumentation key that is ALREADY in appsettings, and which also appears in the Configuration object");

            // DID NOT PRODUCE DATA IN AZURE:
            //services.AddApplicationInsightsTelemetry(Configuration); 
        }

**Comment by atljoseph** [comment]
Given

**Comment by cijothomas** [comment]
After adding ApplicationInsights using Visual Studio, can you confirm the SDK version being used? (You can either tell from .csproj or there is SDK version field in collected telemetry also)

**Comment by cijothomas** [comment]
My configure servicesmethod:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddApplicationInsightsTelemetry();
        }

appsettings.json

{
  "ApplicationInsights": {
    "InstrumentationKey": "ikey"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*"
}

Make sure appsettings.json was copied to output folder
![image](https://user-images.githubusercontent.com/5232798/53673345-b477d500-3c3b-11e9-8947-2d2b15ff8f8d.png)

I ran the application  - ikey is loaded from appsettings.json

**Comment by atljoseph** [comment]
Thank you. Will try this with comparability and passing no params into the
addappsightstelemetry method in configureservices method.

Also, what does your web.config look like for the iOS aspnetcore handler?

**Comment by cijothomas** [comment]
web.config (i didnt modify it, just the default one created by VisualStudio upon publish)
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\AspNetCore22OnIISTest.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess" />
    </system.webServer>
  </location>
</configuration>

**Comment by cijothomas** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\AspNetCore22OnIISTest.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess" />
    </system.webServer>
  </location>
</configuration>
```

**Comment by atljoseph** [comment]
Ok. I had trouble getting core 3 to deploy to azure app service with modules=“...V2”. Had to take V2 off for it to work. Even after installing 3.0 extension. Also tried self-contained publish instead of framework-dependent. But that is not an app insights issue. Literally would not work with V2 on end with InProcesses in azure. Had to make a transform especially for the azure environment with only this change. 

Thanks

**Comment by atljoseph** [comment]
Thanks for the example. It works now, but still have to remove "V2" from
the modules value in the aspNetCore handler of the web.config when deployed
to Azure
.

**Comment by cijothomas** [comment]
Glad you got it working. I haven't done any testing with 3.0 yet - if you face any issues please report it here.

**Comment by cijothomas** [comment]
Please reopen if there are any further questions/comments, or maybe create a new issue.

**Comment by pustun** [comment]
Hi, we managed to make it work. I checked code and turned out to be that if you just call services.AddApplicationInsightsTelemetry(); without arguments then it builds an instance of IConfiguration that relies on appsettings.json and appsettings.environment.json. In our case we have more than 2 files and AI knows nothing about them.

However thanks for the help and for the hint what might be wrong.
