### ISSUE TITLE
Consider also enabling ILogger provider in non-debug scenarios

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/ApplicationInsights-aspnetcore#850]
Currently, when using `ApplicationInsightsWebHostBuilderExtensions.UseApplicationInsights()` or `ApplicationInsightsExtensions.AddApplicationInsightsTelemetry()` the AppInsights ILogger implementation is enabled, but only for debug scenarios.

The recomendation seems to be to add the `Microsoft.Extensions.Logging.ApplicationInsights` package and configure it in the `ConfigureLogging()` method of `CreateWebHostBuilder()`. It seems weird to me to have to configure AppInsights at 2 different points for my ASP.NET Core application. It would seem more logical to me to make `UseApplicationInsights()` and `AddApplicationInsightsTelemetry()` also configure the ILogger provider, since it is such a big part of ASP.NET Core.

**Comment by cijothomas** [comment]
This is in line with the way other ApplicationInsights logger providers are enabled (eg:log4net etc). But given ILogger's tight integration, we may consider taking a dependency on Microsoft.Extensions.Logging.ApplicationInsights, and enable it when enabling applicationinsights.

Other than ease of use - do you have other reasons to need this support?

**Comment by cijothomas** [comment]
@nphmuller I just re-read the title again - the existing ILogger implementation inside this repo is not just for debug scenarios - its valid for all use cases. But its being deprecated infavor of the new separate package.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging

**Comment by nphmuller** [comment]
No, it's only for ease of use. It wasn't clear for me in the [ASP.NET Core docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core) that the ILogger provider wasn't configured. Especially since it _is_ configured in debug mode.

So if the docs were more explicit to note that ILogger traces weren't logged in production scenarios by default, it would have saved me a bit of time.

**Comment by cijothomas** [comment]
Got it - when you say debug mode - do you mean when running from Visual Studio? VS injects some SDK behavior. 

We'll update the https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core to advice on the usage of ilogger -> applicationinsihgts provider.

**Comment by cijothomas** [comment]
https://github.com/MicrosoftDocs/azure-docs/issues/26565

**Comment by nphmuller** [comment]
Yeah, that's what I meant.

It seems [this](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/4d21b40dab37d41b3b3dc38e5cea99bffa46334e/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsDebugLogger.cs) class registers the ILogger provider when EnableDebugLogger is set to true. 

Not sure if Visual Studio sets it or something else, but the result is that the ILogger provider is registered when debugging from Visual Studio.

**Comment by cijothomas** [comment]
The ApplicationInsightsDebugLogger is enabled for local debugging **only**- it is [not enabled](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/4d21b40dab37d41b3b3dc38e5cea99bffa46334e/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsDebugLogger.cs#L23) if ikey is setup. I guess these are remnants from the days when applicationinsights was always enabled (and was part of the .All metapackage), when debugging from visual studio. This was the case with asp.net core 2.0 apps.

Now the recommendation is to enable `Microsoft.Extensions.Logging.ApplicationInsights` package explicitly. We are actively looking at the possibility of doing this by default when application insights monitoring is enabled with AddAppliationInsights() call.

**Comment by cijothomas** [comment]
This is now fixed. ApplicationInsightsLoggingProvier is enabled by default 2.7.0-beta3 onwards.

**Comment by nphmuller** [comment]
Awesome! Basically every project I’ve checked out at my workplace forgot to enable the logging provider manually, and I’ve also read on Twitter that multiple users ran into this. So this will help a lot!

**Comment by cijothomas** [comment]
@nphmuller Thanks!.
We have re-written entire docs for ILogger and ApplicationInsights and is published here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger

Please let us know additional feedback on the new feature and docs as well.!

**Comment by nphmuller** [comment]
@cijothomas Looks much clearer now. Would solve and confusion I had before!
