### ISSUE TITLE
Enable ApplicationInsightsLoggerProvider by default

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-aspnetcore#854]
Currently enabling ApplicationInsightsLoggerProvider is an additional step on top on enabling ApplicationInsights. 
i.e users have to 
1. Install Additional Nuget Package - Microsoft.Extensions.Logging.ApplicationInsights.
2. Enable ApplicationInsightsLoggerProvider by calling AddApplicationInsights() extension method on LoggingBuilder.

Proposing to change this behaviour, to automatically enable ApplicationInsightsLoggerProvider, when ApplicationInsights collection is enabled with either services.AddApplicationInsightsTelemetry() or IWebHostBuilder.UseApplicationInsights() methods.

With this change, users no longer have to add additional nuget or do any change to enable ILogger provider for ApplicationInsights.

Notes:
1. By default, only "Warning" or above LogLevel logs are sent to ApplicationInsightsProvider for all categories. But this can be easily configured by user either in code or using appsettings.json.

For eg:
```
 // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddLogging((logging) =>
            {
                // For categories beginning with Microsoft, sent only Error or above
                // logging.AddFilter<ApplicationInsightsLoggerProvider>("Microsoft", LogLevel.Error);
                // For every other categories, sent only Warning or above
                //logging.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Warning);
            });            
        }
```
or in appsettings.json
```
{
  "Logging": {
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Warning",
        "Microsoft" : "Error" 
      }
    },    
    "LogLevel": {
      "Default": "Debug"
    }
  }
```

2. This new feature will be available only for NETSTANDARD2.0 or above, as the dependent package Microsoft.Extensions.Logging.ApplicationInsights is only from NETSTANDARD2.0 or above.
If you need to send ILogger logs to applications from an older apps, please use the `AddApplicationInsights` extension method on ILoggerFactory as shown [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging). Please note that this is now a deprecated way.

If old provider was enabled with now obsolete extension method `AddApplicationInsights` of `ILoggerFactory`, please remove it - otherwise it'll result in double logging.

**Comment by DaEkstrim** [comment]
This changed caused me so much headache, I ended wasting a whole day to find out that this change was the culprit, and was causing a circular dependency in my code after I updated ApplicationInsights nuger package to the latest version.

Here's the scenario:

One of my `ITelemetryInitializers` requires an app state object (through injection) whose constructor requires the injection of `ILogger` for internal operations.

This has lead to the following circle of doom:

`ApplicationInsightsLoggingProvider` > `CustomTelemetryInitializer` > `StateObject` > `ILogger` > `ILoggerFactory` > `ILoggerProviders[]` > `ApplicationInsightsLoggingProvider`

In my opinion, this was a very opinionated change. Is there a way to remove the `ApplicationInsightsLoggingProvider `without having to call the `ILoggingBuilder.ClearProviders()` after the `IServiceCollection.AddApplicationInsightsTelemetry(key)`?

**Comment by cijothomas** [comment]
@DaEkstrim Thanks for reporting this! its unfortunate that this change caused you a lot of trouble. I realize this can potentially affect other users as well. 
As of now there is no option to NOT add ApplicationInsightsLoggingProvider when calling AddApplicationInsightsTelemetry. We'll need to provide a overload which provides this option. Will open a new item to track.
