### ISSUE TITLE
Update Microsoft.Extensions.DiagnosticAdapter version to 2.1.0 (when targeting the full .NET framework)

### ISSUE THREAD

**Issue by drauch** [microsoft/ApplicationInsights-aspnetcore#868]
We face the same issue as described in https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/721, however, we don't target .NET Core, we're still targeting the full .NET framework (4.7.2).

We reference `Microsoft.ApplicationInsights/2.9.1` and `Microsoft.ApplicationInsights.AspNetCore/2.6.1` (both seem to be the newest versions). If you look at the latter in `project.assets.json` it still references `"Microsoft.Extensions.DiagnosticAdapter": "1.1.0"`.

Could you fix this problem when targeting the full .NET framework as well?

**Comment by cijothomas** [comment]
@drauch Thanks for reporting. The project has a target for net46, so we can modify it also to use updated Microsoft.Extensions.DiagnosticAdapter.

**Comment by lmolkova** [comment]
Fixed: dependency is removed in #852
