### ISSUE TITLE
AppInsights ILogger: Not flushing in time

### ISSUE THREAD

**Issue by TheReaLee** [microsoft/ApplicationInsights-aspnetcore#870]
In the Program.cs of our application we are utilizing the AddApplicationInsights method.
In the Startup.cs we have subscribed to the AppDomain.CurrentDomain.UnhandledException to capture early exceptions, specifically within Startup.cs until the Exception middleware is initialized. The issue is that from all the LoggingProviders, only AppInsights is not logging.
Logging Providers used:

- Serilog
- Console
- ApplicationInsights

`

        private readonly ILogger _logger;

        void _unhandledExceptionHandler(object sender, UnhandledExceptionEventArgs args)
        {

            Exception ex = (Exception)args.ExceptionObject;

            _logger.LogError(ex, $"An unhandled exception on startup has occured: {ex.Flatten()}");

            //Thread.Sleep(5000) - Giving the application some time before shutting down works;
            //Ideally something like _logger.Flush() or _logger.Dispose() to flush any pending //telemetry
        }
`

## Version Info 
SDK Version : Microsoft.Extensions.Logging.ApplicationInsights (2.9.1)
.NET Version : .NET Core 2.2	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by cijothomas** [comment]
@TheReaLee Thanks for reporting the issue.
Please share how have you configured application insights logger provider. If its too early in the pipeline, then instrumentation key may not be setup , so the log will not be captured/sent.  Have you tried the instructions from the below link to configure application insights earlier with an ikey?
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#capturing-ilogger-logs-from-startupcs-programcs-in-aspnet-core-applications

**Comment by TheReaLee** [comment]
@cijothomas The instrumentation key is properly setup as per my comment above 'Thread.Sleep(5000)' it works. Furthermore as per your request kindly find the Program.cs below:

`

    internal static class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>

            WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
                logging.AddApplicationInsights("InstrumentationKey")
            )
            .UseApplicationInsights();
    }
`

Startup.cs:
`

        private readonly ILogger _logger;
        public IConfiguration Configuration { get; }

        public Startup(IConfiguration configuration, ILogger<Startup> logger)
        {
            Configuration = configuration;
            _logger = logger;

            //catch app domain's unhandled exceptions
            AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(_unhandledExceptionHandler); 
        }
        
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            //Code hidden
        }

        void _unhandledExceptionHandler(object sender, UnhandledExceptionEventArgs args)
        {
            //Application will terminate after this method
            Exception ex = (Exception)args.ExceptionObject;
            _logger.LogError(ex, $"An unhandled exception on startup has occured: {ex.Flatten()}");
            //Need to Flush loggers as app insights is not getting logged.
            //Using Thread.Sleep(5000) or more successfully logs to app insights
        }
        
        public void ConfigureServices(IServiceCollection services)
        {
            //To be captured by _unhandledExceptionHandler
            throw new Exception("Test");
            //Code hidden
        }
    
`

**Comment by cijothomas** [comment]
@TheReaLee Understood. Telemetry is not sent instantly - its is batched and sent once every 30 sec or when 500 items are buffered. So if your application is about to die, and you just called log.LogError, then it wont get sent. 
You need to modify Startup constructor to take IOptions<TelemetryConfiguration> options in constructor, save it to _telConfig, and call this._telConfig.TelemetryChannel.Flush(), followed by sleep. in your unhandled exception handler.

**Comment by TheReaLee** [comment]
@cijothomas I am trying to avoid sleep in my unhandled exception handler and am trying to use it as a last resort. Can you suggest other alternatives i.e. How to track early exceptions to insights?

**Comment by cijothomas** [comment]
@TheReaLee Tracking early exception - you already solved this issue.
The issue we need to solve now is to flush the channel so that the telemetry is pushed to the application insights service. The best way is to use InMemoryChannel, and do a Flush on it explicitly. For InMemoryChannel flush is sync, so you wont need sleep.
Are you looking for an example on how to do this?

**Comment by TheReaLee** [comment]
No need for examples but thanks. In regards to your previous comment, re

> You need to modify Startup constructor to take IOptions options in constructor, save it to _telConfig, and call this._telConfig.TelemetryChannel.Flush(), followed by sleep. in your unhandled exception handler.

How much would you suggest to sleep for? 

Furthermore in regards to the original question, do you think it makes sense to implement Flush (Sync and Async) or Dispose functions in ILogger? As we would prefer to use the ILogger infrastructure rather than maintaining other telemetry objects as well.

**Comment by cijothomas** [comment]
@pharring Thanks for the tip. Will do it.

**Comment by cijothomas** [comment]
@TheReaLee If the channel is InMemoryChannel, then Flush() is sync, so you just need to do flush. I'd assume this early in the pipeline, AI is not fully setup - so channel would be InMemoryChannel.

For ServerTelemetryChannel, there is a need to do sleep, but i can't say for sure how much :(  5sec should suffice. We are addressing this issue in channel, where channel is going to provide sync/async version of Flush allowing user more control there.

**Comment by TheReaLee** [comment]
@cijothomas  When are you planning to release these changes?

**Comment by TheReaLee** [comment]
@cijothomas I think we are deviating from the original question. The issue I'm having is with the ILogger infrastructure not with the channels per se... Point being that I cannot define what memory channel the ApplicationInsights Logger is using.

**Comment by cijothomas** [comment]
@TheReaLee issue is you are losing events because its not sent out before app is shutdown. The only way to fix this now from your side is to do explicit Flush. You can define the channel used by ApplicationInsightsLogger provider.

We'll fix the applicationinsightsprovider to do the flush automatically, but i dont have timeline when this will land :(

**Comment by TheReaLee** [comment]
Thanks @cijothomas. We're in the early stages of development and prefer to wait for the next release. 
Where can I subscribe to get information regarding new releases?

**Comment by cijothomas** [comment]
@TheReaLee Please watch this repo as that's where logging implementations reside.
https://github.com/microsoft/ApplicationInsights-dotnet-logging/labels/ilogger

**Comment by TheReaLee** [comment]
@cijothomas Can you change this issue from Question to Bug?

**Comment by cijothomas** [comment]
CLosing this in favor of https://github.com/microsoft/ApplicationInsights-dotnet-logging/issues/284

@TheReaLee Will track it as an enhancement here. I will give this high priority and try to get to it in the next beta itself.
