### ISSUE TITLE
Remove system.net.http reference in net45 target

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-aspnetcore#874]
https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj#L105

This is not required, and indirectly brings other packages which has security vulnerabilities.

**Comment by lmolkova** [comment]
Fixed by #879

**Comment by cijothomas** [comment]
Addressed in 2.7.0
