### ISSUE TITLE
cloud_roleName Telemetry intializer declarative method not working as documented

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-aspnetcore#877]
I have been following this article for adding cloud_RoleName to my web-app (https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-monitor/app/app-map.md#net), I just tried this with a very simple ASP.net web-app. I created a class library for telemetry and referenced it with my Web-App and made sure Instrumentation Key is used. Now when I initialize the custom TELEMETRY class programmatically i.e. (Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.TelemetryInitializers.Add(new ExtendedIDTelemetryInitializer())) .. It works very well and no issues at all. Telemetry gets sent to my Azure App Insights Resource with my custom CLOUD_ROLENAME but samething if I try to add it declaratively i.e. adding the INITIALIZE code to ApplicationInsights.config file, it DOESNT WORK :( nothing is reported with my CUSTOM cloud_RoleName to Azure App insights, any help with this? I want to go the DECLARATIVE route instead of programmatic as I need to send this code to a third party product and they cant make changes to the STARTUP event to add it. Not sure why DECLRATIVE is Not working any help? my ApplicationInsights.config file looks like this . Any help? tried searching but doesn't help

**Comment by SergeyKanzhelev** [comment]
I think it's mentioned in here: https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/505 Closing as it is a duplicate feature request for this repo

**Comment by cijothomas** [comment]
@ketaanhshah Using ApplicationInsights.config is not supported for Asp.net Core applications.
This shows the right instructions: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#adding-telemetryinitializers

I modified the app-map instructions to also call out asp.net core specific instructions. it should be live in docs in a day.
