### ISSUE TITLE
incorrect link on front page of repository

### ISSUE THREAD

**Issue by morgangrobin** [microsoft/ApplicationInsights-aspnetcore#878]
docs bug:

On the [home page of this repository](https://github.com/Microsoft/ApplicationInsights-aspnetcore), the line "The configure guide demonstrates the most common tasks you may want to do." links to the [Github wiki](https://github.com/microsoft/ApplicationInsights-aspnetcore/wiki), which is no longer up to date. It should link to [The official docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core)

**Comment by cijothomas** [comment]
Thanks @morgangrobin for reporting. This is addressed via  #892
