### ISSUE TITLE
startup filter gobbles up all exceptions from all pipeline configuration

### ISSUE THREAD

**Issue by wpbrown** [microsoft/ApplicationInsights-aspnetcore#897]
Title covers the problem. This filter should not be catching exceptions from downstream appbuilders. It was very confusing to debug this.

## Repro Steps
1. Throw an exception in your Startup class Configure method with App Insights 2.7.0 installed.

##  Actual Behavior
No exception reaches WebHostBuilder logic

## Expected Behavior
Exception propogates out of pipeline configuration

## Version Info 
Bug was introduced in this commit:
https://github.com/microsoft/ApplicationInsights-aspnetcore/commit/2def166fefd7a785737790026638ab5407d8208a#diff-f48f778899a1b501f8f8c45b35ada34b

**Comment by cijothomas** [comment]
@wpbrown thanks for reporting this issue and providing the root cause as well! 
Agree the startup filter should not catch ex from downstream builders. Will make a fix soon. Tagging for the  nearest next release.

**Comment by cijothomas** [comment]
@Dmitry-Matveev Considering this is a regression, i think we should do a hotfix release. Please share your thoughts.

**Comment by cijothomas** [comment]
We'll releasing this fix as 2.7.1 hotfix release.

**Comment by cijothomas** [comment]
Released hotfix to address https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.7.1
