### ISSUE TITLE
GlobalProperties not showing custom properties on App Insight

### ISSUE THREAD

**Issue by shalinparmar** [microsoft/ApplicationInsights-aspnetcore#902]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Use TelemetryClient client.Context.GlobalProperties["customPropertyKey" = "CustomPropertyValue"
2. The custom properties can't be seen in application insight.

##  Actual Behavior
Custom properties are showing default and not the custom one added like above in the Request.

## Expected Behavior
It should show up under Custom Properties section in the Request

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : 2.7.0
.NET Core Version (TargetFramework in your .csproj file) : 2.2	 						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : Nuget
OS :
Hosting Info (IIS/Azure Web Ap
![AppInsight_CustomProperties](https://user-images.githubusercontent.com/13654332/59391008-0dbcdc00-8dc7-11e9-977e-42854fbff733.png)
ps/Running From Visual Studio etc) :IIS v8.5, Windows Server 2012, Windows 8.1, VS 2017

**Comment by cijothomas** [comment]
@shalinparmar How are you setting GlobalProperties? I assume you are setting it on a telemetryclient - only those telemetry tracked by that particular telemetryclient will have those properties added.

To modify autocollected telemetry, add TelemetryInitializer to add GlobalProperty

**Comment by shalinparmar** [comment]
Yes I am setting it on a telemetry client via middleware. However, the same logic does the magic for Exception tracking but doesn't work for normal requests where we are trying to log some response body for bad requests (400s).

**Comment by cijothomas** [comment]
How are you tracking exceptions? if you use same TelemetryClient to track exceptions, it will work for them. But RequestTracking module creates own telemetryclient.

**Comment by shalinparmar** [comment]
Ok. So, the solution would be to have CustomTelemetryInitializer for custom parameters in requests?

**Comment by cijothomas** [comment]
yes.https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#adding-telemetryinitializers

**Comment by cijothomas** [comment]
or you can directly add custom properties like below from your middleware/controller where you have HttpContext injected.

var telemetry = this.httpContext?.Features.Get<RequestTelemetry>();
 if (telemetry != null)
 {
  telemetry.Properties["key"] = "value"; 
}

**Comment by shalinparmar** [comment]
Although this sounds very peculiar it works! Can I request a new feature so that the whole TelemetryClient is consistent behind an interface and has proper customization contracts and we don't have to work with TelemetryClient and RequestTelemetry and TelemetryInitializers for getting telemetry from different behaviors?

**Comment by cijothomas** [comment]
Built-in modules creates own TelemetryClient, and not really shared for customizing. TelemetryConfiguration is shared by all - adding TelemetryInitializer to the shared config is the right approach.

If there is a specific enhancement request, feel free to open/re-open an issue.

**Comment by shalinparmar** [comment]
> 
> 
> or you can directly add custom properties like below from your middleware/controller where you have HttpContext injected.
> 
> ```
> var telemetry = this.httpContext?.Features.Get<RequestTelemetry>();
>  if (telemetry != null)
>  {
>   telemetry.Properties["key"] = "value"; 
> }
> ```

I was able to get it working on local dev box, but when I publish this app to the server then it is again not sending the custom telemetry. Is there anyway to see what is being sent from server to the App Insight?

**Comment by cijothomas** [comment]
If you can use fiddler to look at the json payload being sent, you can see it.

I am not yet sure why this doesn't work in your server.

**Comment by shalinparmar** [comment]
I had to move the IHttpContextAccessor from my middleware and instead pass the HttpCotext from middleware to get it to work properly.
