### ISSUE TITLE
Logging to application insights when using HostBuilder requires specific registration of instrumentation key

### ISSUE THREAD

**Issue by arabelaa** [microsoft/ApplicationInsights-aspnetcore#905]
Inside a console app .NET Core 2.2 and using HostBuilder I need to explicitly pass InstrumentationKey (even if the key is present inside appsetting.json)  when logging to application insights. 
```
{
  "ApplicationInsights": {
    "InstrumentationKey": "somevalue"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Debug",
        "Microsoft": "Error"
      }
    }
  }
}
```

##  Actual Behavior
When using HostBuilder and adding
   ```
 services.AddLogging(loggingBuilder =>
            {
               loggingBuilder.AddApplicationInsights();
            });
```
 logs are not sent to ApplicationInsights.

 I noticed that when i pass the explicit instrumentationkey it works 
`   loggingBuilder.AddApplicationInsights(config.GetValue<string>("ApplicationInsights:InstrumentationKey"));`

## Expected Behavior
To not be required to pass the InstrumentationKey.

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) :
.NET Core Version (TargetFramework in your .csproj file) :	 						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : 2.2
OS :
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) :

**Comment by cijothomas** [comment]
Using the standalone logging package in console app dont yet support reading ikey from anywhere other than code.
https://github.com/microsoft/ApplicationInsights-dotnet-logging/issues/272
