### ISSUE TITLE
Add preview package for asp.net core 3.0

### ISSUE THREAD

**Issue by niemyjski** [microsoft/ApplicationInsights-aspnetcore#906]
The current package doesn't work for asp.net core 3.0. The IWebHostBuilder was replaced by the IHostBuilder interface for generic hosting.

**Comment by cijothomas** [comment]
Thanks for reporting.
We'll be releasing new SDK before 3.0 GA to support 3.0 with generic host.
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/708

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/932 Please refer to this post to know workarounds for now.
