### ISSUE TITLE
catch block hides exceptions in the startup pipeline

### ISSUE THREAD

**Issue by thtp** [microsoft/ApplicationInsights-aspnetcore#908]
https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/61cb4498f4f8722829e9c8192a6776e327bdd82f/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsStartupFilter.cs#L26

Any exceptions in next(...) delegate will be swallowed by the catch block. It results in the application started in inconsistent and absolutely unpredictable state. It is rather hard to debug. I believe, startup pipeline should not be executed successfully in case of any exceptions.

My suggestion is to rethrow an exception after it has been logged (catch (Exception ex) where (LogException(ex)) or something like this), or to move call of the next() delegate outside the try..catch block.

**Comment by cijothomas** [comment]
@thtp Thanks for reporting. This was already reported and fixed, to be available in next beta.
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/897

Considering the severity, I am thinking to do a .1 release to address this. Please stay tuned for an update soon.

**Comment by cijothomas** [comment]
Discussion in original post. closing this as duplicate.
