### ISSUE TITLE
Deprecate extension methods on WebHostBuilder

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-aspnetcore#919]
Proposing to deprecate UseApplicationInsights() extension methods on IWebHostBuilder, https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsWebHostBuilderExtensions.cs#L18

The alternate option is to use the AddApplicationInsightsTelemetry() extensions methods on IServiceCollection.
https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L65

Reasons:
Former did not allow overrides to customize behavior, so all public docs were already recommending the latter approach.
Visual Studio AI Tools used the Former approach, and this has created customer confusion about which one to use.
With Asp.Net Core 3.0, default templates use IHostBuilder, as opposed to IWebHostBuilder - this already means customers have to use extension methods on IServiceCollection. As of preview 7, the Visual Studio integrated enablement is broken due to this reason. Users should follow non-VS doc to workaround(https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio)

If there are no concerns, will ask VS Team to modify "Add Application Insights" experience to use extension methods on IServiceCollection.

**Comment by cijothomas** [comment]
@lmolkova @Dmitry-Matveev @MS-TimothyMothra please share any concerns.

**Comment by Dmitry-Matveev** [comment]
If the approach is switched in VS - will VS extension assume that the exising projects instrumented in the old way are not instrumented and will try to add `AddApplicationInsightsTelemetry()` in addition to `UseApplicationInsights()`?

Other than that, deprecation should not be an issue - I guess you are suggesting to obsolete in 2.* and drop in 3.*?

**Comment by cijothomas** [comment]
I'll check how VS Extension detects sdk presence. While adding both methods are not harmful (i.e there wont be double addition as methods internally check if already added), we surely don't want to have that confusing experience.

Yes to Obsolete in 2.*, and Drop in 3.*, following standard deprecation processes.
