### ISSUE TITLE
How set telemetry field name as a textbox.txt name,

### ISSUE THREAD

**Issue by nainesh72** [microsoft/ApplicationInsights-aspnetcore#926]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. 
2. 

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) :
.NET Core Version (TargetFramework in your .csproj file) :	 						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) :
OS :
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) :

**Comment by nainesh72** [comment]
Hi I use textbox.txt  value as a telemetry field name how can i do please guide me

**Comment by cijothomas** [comment]
Please describe what you are trying to achieve. Its not clear to me.

**Comment by nainesh72** [comment]
OK currently my code is like 
 var telemetryDataPoint = new
                    {      m1tt = currentTemperature1,
                       m1pt = currentPressure1,
                        m1ft = currentFlow1,
                        m1sdp = currentStainerdp1,
                        m1status = currentmeter1state
   }
Now i want give my textbox text value in place of m1tt

**Comment by cijothomas** [comment]
This does not seem related to application insights.
