### ISSUE TITLE
.NET Core 3.0 and Application Insights SDK

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-aspnetcore#932]
Application Insights SDK for Asp.Net Core version 2.8.0 will be fully supporting .NET Core 3.0, and will be released 1 week after .NET Core 3.0 release (Sept 23 2019). The following guide contains known issues and workarounds when using .NET Core 3.0 preview version with currently available versions of Application Insights SDK.

1. Visual Studio experience will not work with .NET Core 3.0 projects. This is because Visual Studio experience relied on IWebHostBuilder extension methods, and IWebHostBuilder is replaced with IHostBuilder in .NET Core 3.0 projects.

Workaround: Use the non visual studio based documentation:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio

A future update to Visual Studio will fix this experience.

2. Current stable version of the SDK 2.7.1 has a bug and causes .NET Core 3.0 Apps to fail to start. This is because SDK assumed presence of WebEncoders in the DI Container, which is not always the case especially in Web API Projects. (note that this issue and workaround may be present in some .NET Core 2.1/2.2 projects as well)

Workaround:
Add `services.AddWebEncoders();` in `ConfigureServices()` method of your `Startup.cs` class, before `services.AddApplicationInsightsTelemetry();`

2.8.0-beta2 already has a fix for this issue. (https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.8.0-beta2)

3. MVC Routing parameters changes in preview 8 which caused an issue with application insights. This is fixed in 2.8.0-beta2
(https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.8.0-beta2)

4. Worker Role projects are not fully supported.
The services.AddApplicationInsightsTelemetry() which enables entire Application Insights monitoring experience will not work in Worker Role Projects of .Net Core 3.0 (https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/708)
This is because the entire ApplicationInsights SDK is assuming HttpContext injection which is not available in Worker Roles.

Workaround: 
1. Users can manually Track telemetry
2. Use the Microsoft.Extensions.Logging.ApplicationInsights package to automatically collect ILogger logs from Worker projects.

2.8.0 release will contain support for Worker role projects. This will most likely be a new nuget. (Please share comments here https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/708)

**Comment by RyanWng** [comment]
>Worker Role projects are not fully supported.
The services.AddApplicationInsightsTelemetry() which enables entire Application Insights monitoring experience will not work in Worker Role Projects of .Net Core 3.0 (#708)
This is because the entire ApplicationInsights SDK is assuming HttpContext injection which is not available in Worker Roles.

Does this also mean in worker role, AppInsights cannot automatically track dependencies like other services HTTP call and host server's CPU/Memory statistics? If so, would you mind giving advice on how to track CPU/Memory for worker role please?

**Comment by cijothomas** [comment]
@RyanWng Its definitely possible to track dependencies and cpu/memory etc, if you manually setup respective telemetry modules. There is no single lines like AddApplicationInsightsTelemetry() yet. We plan to ship a new nuget with extension method to enable entire monitoring for worker templates. This will be available before Sep 23.

**Comment by andtii** [comment]
@cijothomas It has been more then one week since the release of .net core 3. When will you do the release?

**Comment by cijothomas** [comment]
SDKs were released same time as .NET Core 3.0 was released.

**Comment by andtii** [comment]
Aha sweet :)
