### ISSUE TITLE
Remove support for old x-ms headers based correlation.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-aspnetcore#939]
AspNetCore SDK 2.1.0 version onwards, x-ms ids are not used. It was replaced with request-id based correlation. However, x-ms headers were still parsed from incoming headers to support with very old systems.

Proposing to completely remove x-ms headers based correlation. This would have small performance gain, as we don't need to search for x-ms headers anymore in the incoming request, and also would keep code base less complicated.

**Comment by lmolkova** [comment]
I'm fine with this approach. In reality, AppInsights SDKs do not inject x-ms headers by default starting with 2.7.0-beta1 (dependency collector, shipped more than a year ago) and the way to enable injection is not documented. And we didn't get any requests about it.

Another reason why it is safe to remove them is that x-ms headers were stopped being default correlation mechanism from AppInsights SDKs 2.4, shipped ~2 years ago. In AppInsights 2.3 correlation was not really working well inside the process. And headers were only injected with rddp.

So chances are that for users of old SDKs correlation does not work anyway and removing old headers from newer SDKs will not make it worse.
