### ISSUE TITLE
ITelemetryInitializer.Initialize got triggered only once for a single HTTP request in version 2.7.1

### ISSUE THREAD

**Issue by LiangZugeng** [microsoft/ApplicationInsights-aspnetcore#940]
Previously we were using version 2.6.1, and we retrieved request.body from IHttpContextAccessor.HttpContext.Request properties in the first trigger of ITelemetryInitializer.Initialize method and it worked fine. In 2.6.1 ITelemetryInitializer.Initialize got triggered twice for a single request (one at the beginning of the request and another one at the end of the request).

Recently we upgraded to version 2.7.1 and found ITelemetryInitializer.Initialize was triggered only once at the end of the request (not at the beginning of the request), thus the previous code cannot access the request body (object disposal exception).

Was there a behavior change being made? If yes what's the workaround or new tricks to handle HTTP request beginning event in ITelemetryInitializer?

## Repro Steps
1. Create a ASP.Net Core WebAPI app and Reference 2.6.1 of Microsoft.ApplicationInsights.AspNetCore
2. Create a class inheriting ITelemetryInitializer and add `services.AddSingleton<ITelemetryInitializer, RequestTelemetryInitializer>();` in Startup.cs
3. Add a breakpoint to the ITelemetryInitializer.Initialize method, start debugging and issue a request to the webapi
4. Verify there are two triggers for Initialize method (one at the beginning and once at the end)
5. Modify the Web.csproj and change the reference of Microsoft.ApplicationInsights.AspNetCore to 2.7.1
6. Repeat the debugging and http request
7. Initialize is triggered only once (at the end of the request)

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : 2.7.1
.NET Core Version (TargetFramework in your .csproj file) : netcoreapp2.2

How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : Installed Nugets
OS : Windows 10 Professional 1809
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) : Debugging from Visual Studio Code

**Comment by cijothomas** [comment]
@LiangZugeng There is only one guarantee from the SDK - that telemetry initializers will be called at least once. In the past, it may have been invoked more than once, but those are internal implementation details, and you had a dependency on the internal implementation detail. In recent versions, SDK has been optimized for performance, and as part of this initializers are called only once, at the end of request processing. This is still done in the context of incoming request, so you should get access to HttpContext as before. (like Headers, etc.)
I will check back what is the best way to get request body again. 

You can get the RequestTelemetry inside any controllers using this line (after accessing httpcontext):
`RequestTelemetry reqTelemetry = httpContext?.Features.Get<RequestTelemetry>();`, and then add request body to telemetry.Properties.Add("body","body contents"). At this stagem you are in controller, and body is not disposed.

This is also an internal implementation detail, but i'll find out the recommendation here.

Thank you for investigating and posting this.

**Comment by LiangZugeng** [comment]
@cijothomas thanks for the clarification.

The reason we used a TelemetryInitializer to capture request body was that we want to do this in a central place instead of adding code to every actions in controllers returning 400 status code.

Another way we previously wanted to explore was to add a middleware but we decided to go with TelemetryInitializer as it seemed a better and official way, without the ability to retrieve request body in TelemetryInitializer we will have to visit the middleware solution again.

If you find any way to get request body in TelemetryInitializer please do let me know, we will wait for several days before learning to write a middleware (which we've never done before).

**Comment by Ro3A** [comment]
@LiangZugeng

Middleware is a decent solution for this. I have middleware to add response body to the request telemetry and have a bit of heartburn that request body is handled one way, and response body another. 

I'll likely move my code to middleware until it becomes a native feature in AI

**Comment by LiangZugeng** [comment]
@Ro3A I agree with you, and we will soon start writing a middleware for that.

@cijothomas I close this issue for now as we will go with the middleware solution, but please do post here if you find a way to get the request body in TelemetryInitializer.Initialize, once it's resolved we will likely to move back to use TelemetryInitializer.
