### ISSUE TITLE
Cannot log additional keyvalue pairs using params object[] args in, say, logger.LogInformation()

### ISSUE THREAD

**Issue by s-tuli** [microsoft/ApplicationInsights-aspnetcore#942]
**Using Microsoft.ApplicationInsghts.AspNetCore 2.7.1**
## Repro Steps
1. Trying to log the following using ILogger
_logger.LogInformation("myDescription", new Dictionary<string, string>() {
                    { "scenario.Description", "MyScenario" },                    
                    { "ScenarioResult", "MyScenarioResult" }
                  });

##  Actual Behavior
I don't see logs for the keyvalue pairs above viz. scenario.Description etc.

## Expected Behavior
I would expect to see logs under customDimensions for each of the key value pair above.
I am querying traces:
//My analytics query
traces
| where message  contains "myDescription"
| order by timestamp desc

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : 2.7.1
.NET Core Version (TargetFramework in your .csproj file) :	 2.2						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : NuGet: Using Microsoft.ApplicationInsghts.AspNetCore 2.7.1
OS : Windows
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) : Running with VS

**Comment by cijothomas** [comment]
This can be achieved with scopes, as shown below.

using (_logger.BeginScope<IReadOnlyCollection<KeyValuePair<string, object>>>(new Dictionary<string, object> { { "scenario.Description", "MyScenario" } }))
                {
// do actual logging inside the scope. All logs inside this will have the properties from the Dictionary used in begin scope.
                    _logger.LogInformation("myDescription");
                    
                }

**Comment by s-tuli** [comment]
Thanks @cijothomas. This resolved the issue. Do you have documentation? Perhaps others may benefit from this.
