### ISSUE TITLE
Unable to read body content: 'Cannot access a disposed object. Object name: 'FileBufferingReadStream'.'

### ISSUE THREAD

**Issue by Ro3A** [microsoft/ApplicationInsights-aspnetcore#948]
We use a custom telemetry initializer to collect the body contents and add to custom property on request telemetry.

## Repro Steps
1. Create a telemetry Initializer that reads the request body using version 2.7.0-beta3 or lower
2. Post a request with a body
3. Change version to 2.7.0-beta4 or higher
2. Repeat step 2

##  Actual Behavior
Cannot read from disposed exception

## Expected Behavior
Read body content and reset to original position

## Version Info 
The problem begins in 2.7.0-beta4. Beta 3 works fine.

OS :
Running locally via VS 2019 / .Net Core 2.2

**Comment by cijothomas** [comment]
same as being discussed here: https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/940

**Comment by Ro3A** [comment]
You're right. I saw that thread but didn't read it close enough apparently. I thought my issue was similar, but slightly different as it appeared my initializer was being called multiple times.
