### ISSUE TITLE
Internal calls are not tracked

### ISSUE THREAD

**Issue by narasimmanr64** [microsoft/ApplicationInsights-aspnetcore#949]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create a web API 
2.  Within the Get() method call some internal methods.
3. Check if the internal methods are tracked

##  Actual Behavior

In the application map, only http requests are tracked.  It is not tracking the internal calls.
## Expected Behavior
In the application map, the internal calls need to be shown.

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) :
.NET Core Version (TargetFramework in your .csproj file) :	 						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) :
OS :
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) :

**Comment by cijothomas** [comment]
Application Insights only tracks outbound dependency calls and incoming http requests. Internal methods are application specific and won't be automatically tracked. You can manually track anything additional using the apis exposed by the sdk.https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking
