### ISSUE TITLE
Cannot see SQL statements under SQL Dependency in AI using HttpSys

### ISSUE THREAD

**Issue by Johnsonxd4** [microsoft/ApplicationInsights-aspnetcore#951]
Hello,
I'm configuring azure app insights on applications .net core with targeting .net framework, and my SQL query dependency not shown in full.
I saw this issue (https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/822) advicing to install status monitor, 
but i think my scenario is a little bit different.
Does this solution of using Status Monitor works only for applications hosted on IIS, or should it work for applications using a .net framework self hosted using httpsys?

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query

StatusMonitor works only in IIS. There are no documented way to get it working on non-iis scenarios, but people have made it work in non-IIS scenarios as well. I will check if I can find that workaround. Its not a official workaround though.

**Comment by cijothomas** [comment]
Closing as this is not officially supported.
