### ISSUE TITLE
Timestamp for Event Telemetry in Application Insights Azure Portal get overridden by ingestion time

### ISSUE THREAD

**Issue by DeviZ9** [microsoft/ApplicationInsights-aspnetcore#953]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. For EventTelemetry, if we set the Timestamp 
var eventTelemetry = new EventTelemetry(eventName) 
{ 
Timestamp = DateTime.Now.AddHours(-10) 
};

2.          EventTelemetry eventTelemetry = ConvertLogEntryToEventTelemetry(entry, eventName);
            Client.TrackEvent(eventTelemetry.Name, eventTelemetry.Properties);

##  Actual Behavior
On the Azure portal, the Timestamp for that event log gets overridden with the ingestion time.

## Expected Behavior
We expect to see the actual time that we set for the Timestamp on the EventTelemetry object.

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) :
.NET Core Version (TargetFramework in your .csproj file) :	 .NET 2.1						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : Installed Nuget package
OS :
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) :
Running From Visual Studio
Deployed to OpenShift Container Platform

**Comment by DeviZ9** [comment]
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : 2.7.1
.NET Core Version (TargetFramework in your .csproj file) :	.NET 2.1
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : Installed Nuget package
OS : Windows
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) :
Running From Visual Studio
Deployed to OpenShift Container Platform

**Comment by cijothomas** [comment]
`
tc.TrackTrace("cijo tracing");

            var evt = new EventTelemetry("myevent");
            evt.Timestamp = DateTimeOffset.Now.AddHours(-10);

            tc.TrackEvent(evt);
`

I just tried the above 2 telemetry. Event showed up as 10 hour earlier than Trace.
![image](https://user-images.githubusercontent.com/5232798/63112506-3edf9700-bf45-11e9-80bb-4f417c0bc33a.png)


Can you double check if you are seeing this behavior? 
Can you also check with Fiddler/VisualStudio if the generated output(json) is having correct timestamp?
And please share a working repro.

**Comment by cijothomas** [comment]
var evt = new EventTelemetry("myevent") { Timestamp = DateTimeOffset.Now.AddHours(-9)};
also tried this.
