### ISSUE TITLE
How to disable SQL logging for Azure Functions?

### ISSUE THREAD

**Issue by pzbyszynski** [microsoft/ApplicationInsights-aspnetcore#968]
## Repro Steps
1. Azure Function is connected to Application Insights using `APPINSIGHTS_INSTRUMENTATIONKEY` setting
2. I have also following settings set:
```
[
  {
    "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "ApplicationInsightsAgent_EXTENSION_VERSION",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "DiagnosticServices_EXTENSION_VERSION",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "InstrumentationEngine_EXTENSION_VERSION",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "SnapshotDebugger_EXTENSION_VERSION",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "XDT_MicrosoftApplicationInsights_BaseExtensions",
    "value": "disabled",
    "slotSetting": false
  },
  {
    "name": "XDT_MicrosoftApplicationInsights_Mode",
    "value": "default",
    "slotSetting": false
  }
]
```

##  Actual Behavior
In end to end transaction details I can see SQL statement

## Expected Behavior
SQL statement should not be logged

## Version Info 
SDK Version: `2.7.1` 
.NET Core Version: `2.2`	 						
How Application was onboarded with SDK: `nuget`
OS : `WIN`
Hosting Info: `Azure`

**Comment by cijothomas** [comment]
For .net core, if dependency module is enabled, it will collect sql query, currently there is no option to disable it, other than turning off dependency tracking completely.
