### ISSUE TITLE
Can I delete Application Insights from project file properties and Connected Services folder?

### ISSUE THREAD

**Issue by EdiWang** [microsoft/ApplicationInsights-aspnetcore#969]
## Repro Steps
1. Add or Link an application insights resources to an ASP.NET Core website in VS2019 (16.2)
2. Observe the project file and folder

##  Actual Behavior
Following lines are added into <project>.csproj file

```xml
<ApplicationInsightsResourceId>/subscriptions/****/resourcegroups/****/providers/microsoft.insights/components/****</ApplicationInsightsResourceId>
<ApplicationInsightsAnnotationResourceId>/subscriptions/****/resourcegroups/****/providers/microsoft.insights/components/****</ApplicationInsightsAnnotationResourceId>
```

Following Folders and files are added to the project

"\Connected Services\Application Insights\ConnectedService.json"

## Expected Behavior

I don't understand what's the purpose of ApplicationInsightsResourceId and ApplicationInsightsAnnotationResourceId. And **I don't want my Azure information exposed in an open-source project**. Can I delete Application Insights code from the project file? Same question for Connected Services folder.

I tried delete and recreate an application insight resource on Azure with a different name and did not update the project file for a .NET Core 2.2 app, it seems azure and my application works just fine. 

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : 2.8.0-beta2
.NET Core Version (TargetFramework in your .csproj file) : 3.0 preview 8

**Comment by cijothomas** [comment]
You can absolutely remove the connected services section. If you onboard with instructions from here (https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio), you'll not have these added automatically. All functionality remain same, except your ability to go directly to the portal from visual studio.

**Comment by EdiWang** [comment]
@cijothomas Thanks for the helpful document.
