### ISSUE TITLE
Question: Is it possible to emit CustomEvent from the ILogger? (by using EventId)

### ISSUE THREAD

**Issue by johnib** [microsoft/ApplicationInsights-aspnetcore#972]
Hello,

Application Insights has the notion of `customEvents`, which is very useful -- only caveat is that I need to modify my code to use the `TelemetryClient` directly whenever I want to emit custom events, which is less desired -- as I would like my aspnet core apps to use `ILogger` solely.

One possible implementation would use `ILogger.Log` method that accepts an `EventId` object, which can be used to emit custom events instead of traces.

Hopefully you can consider that, thank you! :-)

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet-logging/issues/254 duplicate,
