### ISSUE TITLE
Proposal: Skip version to be in sync with BaseSDK

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-aspnetcore#979]
Can we skip ahead to catch up with the Base SDK?
- Base 2.11 = AspNetCore 2.8
- Base 2.12 = AspNetCore 2.12

Alternatively, we could skip everything ahead to indicate that we intend to merge all repos during this milestone.
- Base 2.20 = AspNetCore 2.20

**Comment by Dmitry-Matveev** [comment]
Go ahead, there is no counter-argument.
