### ISSUE TITLE
System.ObjectDisposedException when trying to read request.Body

### ISSUE THREAD

**Issue by mcsdodo** [microsoft/ApplicationInsights-aspnetcore#985]
From package version [2.7.0-beta4](https://github.com/microsoft/ApplicationInsights-aspnetcore/releases/tag/2.7.0-beta4) in our netcoreapp2.2 we started having System.ObjectDisposedException when reading request.Body for logging purposes in a custom [ITelemetryInitializer implementation](https://gist.github.com/mcsdodo/ccb6d5ad5c9e0e8393e1d5c70a862910).

I've gone through the changelog but I can't find any relevant changes to the code.

We initialize application insights using `IWebHostBuilder.UseApplicationInsights(string instrumentationKey)` extension method and we call `services.AddApplicationInsightsTelemetry` with options object to disable adaptive sampling. Application is a stateless service fabric web api service.

## Version Info 
SDK Version : 2.7.0-beta4
.NET Core Version (TargetFramework in your .csproj file) : netcoreapp2.2					
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) :
Microsoft.ApplicationInsights.AspNetCore
OS : Windows
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) : Service fabric

**Comment by cijothomas** [comment]
Please check this: https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/940#issuecomment-513297006  Let us know if it helps.

**Comment by mcsdodo** [comment]
Thanks, I've implemented a middleware as suggested in that thread.
